#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUNDLE_DIR="${METALSHARP_BUNDLE_DIR:-$PROJECT_ROOT/app/bundles}"
OUT_DIR="${METALSHARP_BUNDLE_OUT_DIR:-$PROJECT_ROOT/dist/bundles}"
RELEASE_TAG="${METALSHARP_BUNDLE_TAG:-bundles}"
REPO="${METALSHARP_BUNDLE_REPO:-aaf2tbz/metalsharp}"
MANIFEST="$PROJECT_ROOT/tools/bundles/asset-manifest.tsv"
REMOTE_MANIFEST="$OUT_DIR/source-metalsharp-bundle-manifest.tsv"
REPAIR_BUNDLES="${METALSHARP_REPAIR_BUNDLES:-1}"
REPAIR_GRAPHICS="${METALSHARP_REPAIR_GRAPHICS_BUNDLE:-$REPAIR_BUNDLES}"
REPAIR_ASSETS="${METALSHARP_REPAIR_ASSETS_BUNDLE:-$REPAIR_BUNDLES}"
REPAIR_RUNTIME="${METALSHARP_REPAIR_RUNTIME_BUNDLE:-$REPAIR_BUNDLES}"
SKIP_DEVELOPER_SDK="${METALSHARP_SKIP_DEVELOPER_SDK_BUNDLE:-0}"

mkdir -p "$BUNDLE_DIR" "$OUT_DIR"

echo "Downloading bundle manifest from release: $RELEASE_TAG"
curl -fL --retry 3 -o "$REMOTE_MANIFEST" \
  "https://github.com/$REPO/releases/download/$RELEASE_TAG/metalsharp-bundle-manifest.tsv"

download_asset() {
  local asset="$1"
  local dest="$2"
  if [ -s "$dest" ]; then
    if "$PROJECT_ROOT/tools/bundles/verify-bundles.sh" --bundle-dir "$BUNDLE_DIR" "$asset" >/dev/null 2>&1; then
      if python3 "$PROJECT_ROOT/tools/bundles/verify-bundle-manifest.py" \
        --bundle-dir "$BUNDLE_DIR" --manifest "$REMOTE_MANIFEST" "$asset" >/dev/null 2>&1; then
        echo "SKIP bundle: $asset"
        return 0
      fi
    fi
    echo "Refreshing stale or unlocked bundle: $asset"
    rm -f "$dest"
  fi
  echo "Downloading bundle: $asset"
  curl -fL --retry 3 -o "$dest" "https://github.com/$REPO/releases/download/$RELEASE_TAG/$asset"
  python3 "$PROJECT_ROOT/tools/bundles/verify-bundle-manifest.py" \
    --bundle-dir "$BUNDLE_DIR" --manifest "$REMOTE_MANIFEST" "$asset"
}

repair_graphics_m12_bundle() {
  local archive="$BUNDLE_DIR/metalsharp-graphics-dll.tar.zst"
  local m12_root="${METALSHARP_DXMT_M12_ROOT:-$HOME/.metalsharp/runtime/wine/lib/dxmt_m12}"
  if [ ! -s "$archive" ] || [ ! -d "$m12_root/x86_64-windows" ] || [ ! -d "$m12_root/x86_64-unix" ]; then
    return 0
  fi

  local tmp root
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/metalsharp-graphics-m12.XXXXXX")"
  root="$tmp/root"
  mkdir -p "$root"
  tar --use-compress-program=unzstd -xf "$archive" -C "$root"
  mkdir -p "$root/Graphics/dll/dxmt-m12/x86_64-unix" "$root/Graphics/dll/dxmt-m12/x86_64-windows"
  cp -R -p "$m12_root/x86_64-unix/." "$root/Graphics/dll/dxmt-m12/x86_64-unix/"
  cp -R -p "$m12_root/x86_64-windows/." "$root/Graphics/dll/dxmt-m12/x86_64-windows/"
  (
    cd "$root"
    tar -cf "$tmp/metalsharp-graphics-dll.tar" Graphics
  )
  zstd -q -19 -T0 -f "$tmp/metalsharp-graphics-dll.tar" -o "$archive"
  chmod 0644 "$archive"
  rm -rf "$tmp"
  echo "repaired graphics M12 payload: $archive from $m12_root"
}

repair_assets_fnalibs_bundle() {
  local assets_archive="$BUNDLE_DIR/metalsharp-assets.tar.zst"
  local fnalibs_archive="$BUNDLE_DIR/fnalibs.tar.zst"
  if [ ! -s "$assets_archive" ] || [ ! -s "$fnalibs_archive" ]; then
    return 0
  fi

  local tmp assets_root fnalibs_root
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/metalsharp-assets-fnalibs.XXXXXX")"
  assets_root="$tmp/assets"
  fnalibs_root="$tmp/fnalibs"
  mkdir -p "$assets_root" "$fnalibs_root"

  tar --use-compress-program=unzstd -xf "$assets_archive" -C "$assets_root"
  tar --use-compress-program=unzstd -xf "$fnalibs_archive" -C "$fnalibs_root"

  if [ ! -d "$assets_root/assets" ] || [ ! -d "$fnalibs_root/fnalibs" ]; then
    echo "Unable to repair assets fnalibs payload: unexpected bundle layout" >&2
    rm -rf "$tmp"
    return 1
  fi

  rm -rf "$assets_root/assets/fnalibs"
  rm -rf "$assets_root/assets/eac-toggle"
  mkdir -p "$assets_root/assets"
  cp -R -p "$fnalibs_root/fnalibs" "$assets_root/assets/fnalibs"
  mkdir -p "$assets_root/assets/fna-kickstart/osx"
  for dylib in libFNA3D.0.dylib libSDL2-2.0.0.dylib libFAudio.0.dylib libtheorafile.dylib; do
    cp -p "$fnalibs_root/fnalibs/$dylib" "$assets_root/assets/fna-kickstart/osx/$dylib"
  done

  (
    cd "$assets_root"
    tar -cf "$tmp/metalsharp-assets.tar" assets
  )
  zstd -q -19 -T0 -f "$tmp/metalsharp-assets.tar" -o "$assets_archive"
  chmod 0644 "$assets_archive"
  rm -rf "$tmp"
  echo "repaired assets payload: $assets_archive (fnalibs refreshed, eac-toggle removed)"
}

while IFS=$'\t' read -r asset _root _platforms _notes; do
  case "$asset" in
    ""|\#*) continue ;;
  esac
  if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
    echo "SKIP bundle: $asset (will be generated by CI)"
    continue
  fi
  download_asset "$asset" "$BUNDLE_DIR/$asset"
done < "$MANIFEST"

if [ "$REPAIR_GRAPHICS" = "1" ]; then
  repair_graphics_m12_bundle
fi
if [ "$REPAIR_ASSETS" = "1" ]; then
  repair_assets_fnalibs_bundle
fi
if [ "$REPAIR_RUNTIME" = "1" ]; then
  "$PROJECT_ROOT/tools/dmg/repair-runtime-bundle.py" \
    --archive "$BUNDLE_DIR/metalsharp-runtime.tar.zst" \
    --host-dir "$PROJECT_ROOT/app/native/host" \
    --backend "$PROJECT_ROOT/app/build/c-backend/metalsharp-backend"
fi
if [ "$REPAIR_GRAPHICS" != "1" ] && [ "$REPAIR_ASSETS" != "1" ] && [ "$REPAIR_RUNTIME" != "1" ]; then
  echo "bundle repair disabled; using verified release bundles as downloaded"
fi

VERIFY_ARGS=(--bundle-dir "$BUNDLE_DIR" --require mac)
if [ "$SKIP_DEVELOPER_SDK" = "1" ]; then
  while IFS=$'\t' read -r asset _root _platforms _notes; do
    case "$asset" in
      ""|\#*|metalsharp-d3d12-developer-sdk.tar.zst) continue ;;
    esac
    VERIFY_ARGS+=("$asset")
  done < "$MANIFEST"
fi
"$PROJECT_ROOT/tools/bundles/verify-bundles.sh" "${VERIFY_ARGS[@]}"

rm -f "$OUT_DIR"/metalsharp-*.tar.zst
while IFS=$'\t' read -r asset _root _platforms _notes; do
  case "$asset" in
    ""|\#*) continue ;;
  esac
  if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
    continue
  fi
  cp "$BUNDLE_DIR/$asset" "$OUT_DIR/$asset"
done < "$MANIFEST"

{
  printf 'asset\troot\tsha256\tsize\tnotes\n'
  while IFS=$'\t' read -r asset root _platforms notes; do
    case "$asset" in
      ""|\#*) continue ;;
    esac
    if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
      continue
    fi
    archive="$BUNDLE_DIR/$asset"
    hash="$(shasum -a 256 "$archive" | awk '{print $1}')"
    size="$(wc -c < "$archive" | tr -d ' ')"
    printf '%s\t%s\t%s\t%s\t%s\n' "$asset" "$root" "$hash" "$size" "$notes"
  done < "$MANIFEST"
} > "$OUT_DIR/metalsharp-bundle-manifest.tsv"

OUTPUT_ASSETS=()
while IFS=$'\t' read -r asset _root _platforms _notes; do
  case "$asset" in
    ""|\#*) continue ;;
  esac
  if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
    continue
  fi
  OUTPUT_ASSETS+=("$asset")
done < "$MANIFEST"
python3 "$PROJECT_ROOT/tools/bundles/verify-bundle-manifest.py" \
  --bundle-dir "$OUT_DIR" --manifest "$OUT_DIR/metalsharp-bundle-manifest.tsv" "${OUTPUT_ASSETS[@]}"

echo ""
echo "=== Split Bundle Summary ==="
ls -lh "$BUNDLE_DIR"/metalsharp-*.tar.zst
