#include <string.h>
#include <stdlib.h>

static char g_empty[1] = {0};

int FMOD_System_Create(void **system) {
    if (system) *system = malloc(1);
    return 0;
}
long FMOD_Channel_GetChannelGroup() { return 0; }
long FMOD_Channel_GetCurrentSound() { return 0; }
long FMOD_Channel_GetFrequency() { return 0; }
long FMOD_Channel_GetIndex() { return 0; }
long FMOD_Channel_GetLoopCount() { return 0; }
long FMOD_Channel_GetLoopPoints() { return 0; }
long FMOD_Channel_GetMode() { return 0; }
long FMOD_Channel_GetPosition() { return 0; }
long FMOD_Channel_GetPriority() { return 0; }
long FMOD_Channel_GetUserData() { return 0; }
long FMOD_Channel_IsVirtual() { return 0; }
long FMOD_Channel_SetChannelGroup() { return 0; }
long FMOD_Channel_SetFrequency() { return 0; }
long FMOD_Channel_SetLoopCount() { return 0; }
long FMOD_Channel_SetLoopPoints() { return 0; }
long FMOD_Channel_SetMode() { return 0; }
long FMOD_Channel_SetPosition() { return 0; }
long FMOD_Channel_SetPriority() { return 0; }
long FMOD_Channel_SetUserData() { return 0; }
long FMOD_ChannelGroup_AddDSP() { return 0; }
long FMOD_ChannelGroup_AddFadePoint() { return 0; }
long FMOD_ChannelGroup_AddGroup() { return 0; }
long FMOD_ChannelGroup_Get3DAttributes() { return 0; }
long FMOD_ChannelGroup_Get3DConeOrientation() { return 0; }
long FMOD_ChannelGroup_Get3DConeSettings() { return 0; }
long FMOD_ChannelGroup_Get3DCustomRolloff() { return 0; }
long FMOD_ChannelGroup_Get3DDistanceFilter() { return 0; }
long FMOD_ChannelGroup_Get3DDopplerLevel() { return 0; }
long FMOD_ChannelGroup_Get3DLevel() { return 0; }
long FMOD_ChannelGroup_Get3DMinMaxDistance() { return 0; }
long FMOD_ChannelGroup_Get3DOcclusion() { return 0; }
long FMOD_ChannelGroup_Get3DSpread() { return 0; }
long FMOD_ChannelGroup_GetAudibility() { return 0; }
long FMOD_ChannelGroup_GetChannel() { return 0; }
long FMOD_ChannelGroup_GetDelay() { return 0; }
long FMOD_ChannelGroup_GetDSP() { return 0; }
long FMOD_ChannelGroup_GetDSPClock() { return 0; }
long FMOD_ChannelGroup_GetDSPIndex() { return 0; }
long FMOD_ChannelGroup_GetFadePoints() { return 0; }
long FMOD_ChannelGroup_GetGroup() { return 0; }
long FMOD_ChannelGroup_GetLowPassGain() { return 0; }
long FMOD_ChannelGroup_GetMixMatrix() { return 0; }
long FMOD_ChannelGroup_GetMode() { return 0; }
long FMOD_ChannelGroup_GetMute() { return 0; }
long FMOD_ChannelGroup_GetName() { return 0; }
long FMOD_ChannelGroup_GetNumChannels() { return 0; }
long FMOD_ChannelGroup_GetNumDSPs() { return 0; }
long FMOD_ChannelGroup_GetNumGroups() { return 0; }
long FMOD_ChannelGroup_GetParentGroup() { return 0; }
long FMOD_ChannelGroup_GetPaused() { return 0; }
long FMOD_ChannelGroup_GetPitch() { return 0; }
long FMOD_ChannelGroup_GetReverbProperties() { return 0; }
long FMOD_ChannelGroup_GetSystemObject() { return 0; }
long FMOD_ChannelGroup_GetUserData() { return 0; }
long FMOD_ChannelGroup_GetVolume() { return 0; }
long FMOD_ChannelGroup_GetVolumeRamp() { return 0; }
long FMOD_ChannelGroup_IsPlaying() { return 0; }
long FMOD_ChannelGroup_Release() { return 0; }
long FMOD_ChannelGroup_RemoveDSP() { return 0; }
long FMOD_ChannelGroup_RemoveFadePoints() { return 0; }
long FMOD_ChannelGroup_Set3DAttributes() { return 0; }
long FMOD_ChannelGroup_Set3DConeOrientation() { return 0; }
long FMOD_ChannelGroup_Set3DConeSettings() { return 0; }
long FMOD_ChannelGroup_Set3DCustomRolloff() { return 0; }
long FMOD_ChannelGroup_Set3DDistanceFilter() { return 0; }
long FMOD_ChannelGroup_Set3DDopplerLevel() { return 0; }
long FMOD_ChannelGroup_Set3DLevel() { return 0; }
long FMOD_ChannelGroup_Set3DMinMaxDistance() { return 0; }
long FMOD_ChannelGroup_Set3DOcclusion() { return 0; }
long FMOD_ChannelGroup_Set3DSpread() { return 0; }
long FMOD_ChannelGroup_SetCallback() { return 0; }
long FMOD_ChannelGroup_SetDelay() { return 0; }
long FMOD_ChannelGroup_SetDSPIndex() { return 0; }
long FMOD_ChannelGroup_SetFadePointRamp() { return 0; }
long FMOD_ChannelGroup_SetLowPassGain() { return 0; }
long FMOD_ChannelGroup_SetMixLevelsInput() { return 0; }
long FMOD_ChannelGroup_SetMixLevelsOutput() { return 0; }
long FMOD_ChannelGroup_SetMixMatrix() { return 0; }
long FMOD_ChannelGroup_SetMode() { return 0; }
long FMOD_ChannelGroup_SetMute() { return 0; }
long FMOD_ChannelGroup_SetPan() { return 0; }
long FMOD_ChannelGroup_SetPaused() { return 0; }
long FMOD_ChannelGroup_SetPitch() { return 0; }
long FMOD_ChannelGroup_SetReverbProperties() { return 0; }
long FMOD_ChannelGroup_SetUserData() { return 0; }
long FMOD_ChannelGroup_SetVolume() { return 0; }
long FMOD_ChannelGroup_SetVolumeRamp() { return 0; }
long FMOD_ChannelGroup_Stop() { return 0; }
long FMOD_Debug_Initialize() { return 0; }
long FMOD_DSP_AddInput() { return 0; }
long FMOD_DSP_DisconnectAll() { return 0; }
long FMOD_DSP_DisconnectFrom() { return 0; }
long FMOD_DSP_GetActive() { return 0; }
long FMOD_DSP_GetBypass() { return 0; }
long FMOD_DSP_GetChannelFormat() { return 0; }
long FMOD_DSP_GetCPUUsage() { return 0; }
long FMOD_DSP_GetDataParameterIndex() { return 0; }
long FMOD_DSP_GetIdle() { return 0; }
long FMOD_DSP_GetInfo() { return 0; }
long FMOD_DSP_GetInput() { return 0; }
long FMOD_DSP_GetMeteringEnabled() { return 0; }
long FMOD_DSP_GetMeteringInfo() { return 0; }
long FMOD_DSP_GetNumInputs() { return 0; }
long FMOD_DSP_GetNumOutputs() { return 0; }
long FMOD_DSP_GetNumParameters() { return 0; }
long FMOD_DSP_GetOutput() { return 0; }
long FMOD_DSP_GetOutputChannelFormat() { return 0; }
long FMOD_DSP_GetParameterBool() { return 0; }
long FMOD_DSP_GetParameterData() { return 0; }
long FMOD_DSP_GetParameterFloat() { return 0; }
long FMOD_DSP_GetParameterInfo() { return 0; }
long FMOD_DSP_GetParameterInt() { return 0; }
long FMOD_DSP_GetSystemObject() { return 0; }
long FMOD_DSP_GetType() { return 0; }
long FMOD_DSP_GetUserData() { return 0; }
long FMOD_DSP_GetWetDryMix() { return 0; }
long FMOD_DSP_Release() { return 0; }
long FMOD_DSP_Reset() { return 0; }
long FMOD_DSP_SetActive() { return 0; }
long FMOD_DSP_SetBypass() { return 0; }
long FMOD_DSP_SetChannelFormat() { return 0; }
long FMOD_DSP_SetMeteringEnabled() { return 0; }
long FMOD_DSP_SetParameterBool() { return 0; }
long FMOD_DSP_SetParameterData() { return 0; }
long FMOD_DSP_SetParameterFloat() { return 0; }
long FMOD_DSP_SetParameterInt() { return 0; }
long FMOD_DSP_SetUserData() { return 0; }
long FMOD_DSP_SetWetDryMix() { return 0; }
long FMOD_DSP_ShowConfigDialog() { return 0; }
long FMOD_DSPConnection_GetInput() { return 0; }
long FMOD_DSPConnection_GetMix() { return 0; }
long FMOD_DSPConnection_GetMixMatrix() { return 0; }
long FMOD_DSPConnection_GetOutput() { return 0; }
long FMOD_DSPConnection_GetType() { return 0; }
long FMOD_DSPConnection_GetUserData() { return 0; }
long FMOD_DSPConnection_SetMix() { return 0; }
long FMOD_DSPConnection_SetMixMatrix() { return 0; }
long FMOD_DSPConnection_SetUserData() { return 0; }
long FMOD_Geometry_AddPolygon() { return 0; }
long FMOD_Geometry_GetActive() { return 0; }
long FMOD_Geometry_GetMaxPolygons() { return 0; }
long FMOD_Geometry_GetNumPolygons() { return 0; }
long FMOD_Geometry_GetPolygonAttributes() { return 0; }
long FMOD_Geometry_GetPolygonNumVertices() { return 0; }
long FMOD_Geometry_GetPolygonVertex() { return 0; }
long FMOD_Geometry_GetPosition() { return 0; }
long FMOD_Geometry_GetRotation() { return 0; }
long FMOD_Geometry_GetScale() { return 0; }
long FMOD_Geometry_GetUserData() { return 0; }
long FMOD_Geometry_Release() { return 0; }
long FMOD_Geometry_Save() { return 0; }
long FMOD_Geometry_SetActive() { return 0; }
long FMOD_Geometry_SetPolygonAttributes() { return 0; }
long FMOD_Geometry_SetPolygonVertex() { return 0; }
long FMOD_Geometry_SetPosition() { return 0; }
long FMOD_Geometry_SetRotation() { return 0; }
long FMOD_Geometry_SetScale() { return 0; }
long FMOD_Geometry_SetUserData() { return 0; }
long FMOD_Memory_GetStats() { return 0; }
long FMOD_Memory_Initialize() { return 0; }
long FMOD_Reverb3D_Get3DAttributes() { return 0; }
long FMOD_Reverb3D_GetActive() { return 0; }
long FMOD_Reverb3D_GetProperties() { return 0; }
long FMOD_Reverb3D_GetUserData() { return 0; }
long FMOD_Reverb3D_Release() { return 0; }
long FMOD_Reverb3D_Set3DAttributes() { return 0; }
long FMOD_Reverb3D_SetActive() { return 0; }
long FMOD_Reverb3D_SetProperties() { return 0; }
long FMOD_Reverb3D_SetUserData() { return 0; }
long FMOD_Sound_AddSyncPoint() { return 0; }
long FMOD_Sound_DeleteSyncPoint() { return 0; }
long FMOD_Sound_Get3DConeSettings() { return 0; }
long FMOD_Sound_Get3DCustomRolloff() { return 0; }
long FMOD_Sound_Get3DMinMaxDistance() { return 0; }
long FMOD_Sound_GetDefaults() { return 0; }
long FMOD_Sound_GetFormat() { return 0; }
long FMOD_Sound_GetLength() { return 0; }
long FMOD_Sound_GetLoopCount() { return 0; }
long FMOD_Sound_GetLoopPoints() { return 0; }
long FMOD_Sound_GetMode() { return 0; }
long FMOD_Sound_GetMusicChannelVolume() { return 0; }
long FMOD_Sound_GetMusicNumChannels() { return 0; }
long FMOD_Sound_GetMusicSpeed() { return 0; }
long FMOD_Sound_GetName() { return 0; }
long FMOD_Sound_GetNumSubSounds() { return 0; }
long FMOD_Sound_GetNumSyncPoints() { return 0; }
long FMOD_Sound_GetNumTags() { return 0; }
long FMOD_Sound_GetOpenState() { return 0; }
long FMOD_Sound_GetSoundGroup() { return 0; }
long FMOD_Sound_GetSubSound() { return 0; }
long FMOD_Sound_GetSubSoundParent() { return 0; }
long FMOD_Sound_GetSyncPoint() { return 0; }
long FMOD_Sound_GetSyncPointInfo() { return 0; }
long FMOD_Sound_GetSystemObject() { return 0; }
long FMOD_Sound_GetTag() { return 0; }
long FMOD_Sound_GetUserData() { return 0; }
long FMOD_Sound_Lock() { return 0; }
long FMOD_Sound_ReadData() { return 0; }
long FMOD_Sound_Release() { return 0; }
long FMOD_Sound_SeekData() { return 0; }
long FMOD_Sound_Set3DConeSettings() { return 0; }
long FMOD_Sound_Set3DCustomRolloff() { return 0; }
long FMOD_Sound_Set3DMinMaxDistance() { return 0; }
long FMOD_Sound_SetDefaults() { return 0; }
long FMOD_Sound_SetLoopCount() { return 0; }
long FMOD_Sound_SetLoopPoints() { return 0; }
long FMOD_Sound_SetMode() { return 0; }
long FMOD_Sound_SetMusicChannelVolume() { return 0; }
long FMOD_Sound_SetMusicSpeed() { return 0; }
long FMOD_Sound_SetSoundGroup() { return 0; }
long FMOD_Sound_SetUserData() { return 0; }
long FMOD_Sound_Unlock() { return 0; }
long FMOD_SoundGroup_GetMaxAudible() { return 0; }
long FMOD_SoundGroup_GetMaxAudibleBehavior() { return 0; }
long FMOD_SoundGroup_GetMuteFadeSpeed() { return 0; }
long FMOD_SoundGroup_GetName() { return 0; }
long FMOD_SoundGroup_GetNumPlaying() { return 0; }
long FMOD_SoundGroup_GetNumSounds() { return 0; }
long FMOD_SoundGroup_GetSound() { return 0; }
long FMOD_SoundGroup_GetSystemObject() { return 0; }
long FMOD_SoundGroup_GetUserData() { return 0; }
long FMOD_SoundGroup_GetVolume() { return 0; }
long FMOD_SoundGroup_Release() { return 0; }
long FMOD_SoundGroup_SetMaxAudible() { return 0; }
long FMOD_SoundGroup_SetMaxAudibleBehavior() { return 0; }
long FMOD_SoundGroup_SetMuteFadeSpeed() { return 0; }
long FMOD_SoundGroup_SetUserData() { return 0; }
long FMOD_SoundGroup_SetVolume() { return 0; }
long FMOD_SoundGroup_Stop() { return 0; }
long FMOD_System_AttachChannelGroupToPort() { return 0; }
long FMOD_System_AttachFileSystem() { return 0; }
long FMOD_System_Close() { return 0; }
long FMOD_System_CreateChannelGroup() { return 0; }
long FMOD_System_CreateDSP() { return 0; }
long FMOD_System_CreateDSPByPlugin() { return 0; }
long FMOD_System_CreateDSPByType() { return 0; }
long FMOD_System_CreateGeometry() { return 0; }
long FMOD_System_CreateReverb3D() { return 0; }
long FMOD_System_CreateSound() { return 0; }
long FMOD_System_CreateSoundGroup() { return 0; }
long FMOD_System_CreateStream() { return 0; }
long FMOD_System_DetachChannelGroupFromPort() { return 0; }
long FMOD_System_Get3DListenerAttributes() { return 0; }
long FMOD_System_Get3DNumListeners() { return 0; }
long FMOD_System_Get3DSettings() { return 0; }
long FMOD_System_GetAdvancedSettings() { return 0; }
long FMOD_System_GetChannel() { return 0; }
long FMOD_System_GetChannelsPlaying() { return 0; }
long FMOD_System_GetCPUUsage() { return 0; }
long FMOD_System_GetDefaultMixMatrix() { return 0; }
long FMOD_System_GetDriver() { return 0; }
long FMOD_System_GetDriverInfo() { return 0; }
long FMOD_System_GetDSPBufferSize() { return 0; }
long FMOD_System_GetDSPInfoByPlugin() { return 0; }
long FMOD_System_GetFileUsage() { return 0; }
long FMOD_System_GetGeometryOcclusion() { return 0; }
long FMOD_System_GetGeometrySettings() { return 0; }
long FMOD_System_GetMasterChannelGroup() { return 0; }
long FMOD_System_GetMasterSoundGroup() { return 0; }
long FMOD_System_GetNestedPlugin() { return 0; }
long FMOD_System_GetNetworkProxy() { return 0; }
long FMOD_System_GetNetworkTimeout() { return 0; }
long FMOD_System_GetNumDrivers() { return 0; }
long FMOD_System_GetNumNestedPlugins() { return 0; }
long FMOD_System_GetNumPlugins() { return 0; }
long FMOD_System_GetOutput() { return 0; }
long FMOD_System_GetOutputByPlugin() { return 0; }
long FMOD_System_GetOutputHandle() { return 0; }
long FMOD_System_GetPluginHandle() { return 0; }
long FMOD_System_GetPluginInfo() { return 0; }
long FMOD_System_GetRecordDriverInfo() { return 0; }
long FMOD_System_GetRecordNumDrivers() { return 0; }
long FMOD_System_GetRecordPosition() { return 0; }
long FMOD_System_GetReverbProperties() { return 0; }
long FMOD_System_GetSoftwareChannels() { return 0; }
long FMOD_System_GetSoftwareFormat() { return 0; }
long FMOD_System_GetSoundRAM() { return 0; }
long FMOD_System_GetSpeakerModeChannels() { return 0; }
long FMOD_System_GetSpeakerPosition() { return 0; }
long FMOD_System_GetStreamBufferSize() { return 0; }
long FMOD_System_GetUserData() { return 0; }
long FMOD_System_GetVersion() { return 0; }
long FMOD_System_Init() { return 0; }
long FMOD_System_IsRecording() { return 0; }
long FMOD_System_LoadGeometry() { return 0; }
long FMOD_System_LoadPlugin() { return 0; }
long FMOD_System_LockDSP() { return 0; }
long FMOD_System_MixerResume() { return 0; }
long FMOD_System_MixerSuspend() { return 0; }
long FMOD_System_PlayDSP() { return 0; }
long FMOD_System_PlaySound() { return 0; }
long FMOD_System_RecordStart() { return 0; }
long FMOD_System_RecordStop() { return 0; }
long FMOD_System_RegisterDSP() { return 0; }
long FMOD_System_Release() { return 0; }
long FMOD_System_Set3DListenerAttributes() { return 0; }
long FMOD_System_Set3DNumListeners() { return 0; }
long FMOD_System_Set3DRolloffCallback() { return 0; }
long FMOD_System_Set3DSettings() { return 0; }
long FMOD_System_SetAdvancedSettings() { return 0; }
long FMOD_System_SetCallback() { return 0; }
long FMOD_System_SetDriver() { return 0; }
long FMOD_System_SetDSPBufferSize() { return 0; }
long FMOD_System_SetFileSystem() { return 0; }
long FMOD_System_SetGeometrySettings() { return 0; }
long FMOD_System_SetNetworkProxy() { return 0; }
long FMOD_System_SetNetworkTimeout() { return 0; }
long FMOD_System_SetOutput() { return 0; }
long FMOD_System_SetOutputByPlugin() { return 0; }
long FMOD_System_SetPluginPath() { return 0; }
long FMOD_System_SetReverbProperties() { return 0; }
long FMOD_System_SetSoftwareChannels() { return 0; }
long FMOD_System_SetSoftwareFormat() { return 0; }
long FMOD_System_SetSpeakerPosition() { return 0; }
long FMOD_System_SetStreamBufferSize() { return 0; }
long FMOD_System_SetUserData() { return 0; }
long FMOD_System_UnloadPlugin() { return 0; }
long FMOD_System_UnlockDSP() { return 0; }
long FMOD_System_Update() { return 0; }
