#ifndef METALSHARP_BOTTLES_CATALOGS_H
#define METALSHARP_BOTTLES_CATALOGS_H

/* Static catalogs ported from the v0.56.1 Rust backend. */

static const char BOTTLES_PROFILES_JSON[] =
    "{\"ok\":true,\"profiles\":[{\"arch\":\"wow64\",\"components\":[],\"id\":\"plain\",\"launch_pipeline\":\"win"
    "e_bare\",\"mono_runtime\":null,\"name\":\"Plain Wine\",\"wineboot\":true},{\"arch\":\"wow64\",\"componen"
    "ts\":[\"gecko\",\"vcrun2019_x64\",\"vcrun2019_x86\",\"corefonts\"],\"id\":\"launcher\",\"launch_pipeline"
    "\":\"wine_bare\",\"mono_runtime\":null,\"name\":\"Launcher\",\"wineboot\":true},{\"arch\":\"wow64\",\"comp"
    "onents\":[\"vcrun2019_x64\",\"vcrun2019_x86\",\"vcrun2013\",\"directx_jun2010\",\"corefonts\"],\"id\":\""
    "game_install\",\"launch_pipeline\":\"wine_bare\",\"mono_runtime\":null,\"name\":\"Game Installer\",\"w"
    "ineboot\":true},{\"arch\":\"wow64\",\"components\":[\"d3d9\",\"vcrun2019_x64\",\"vcrun2019_x86\",\"direc"
    "tx_jun2010\"],\"id\":\"m9\",\"launch_pipeline\":\"m9\",\"mono_runtime\":null,\"name\":\"D3D9 Metal\",\"win"
    "eboot\":true},{\"arch\":\"wow64\",\"components\":[\"d3d10\",\"d3d10_1\",\"dxgi\",\"vcrun2019_x64\",\"vcrun"
    "2019_x86\"],\"id\":\"m10\",\"launch_pipeline\":\"m10\",\"mono_runtime\":null,\"name\":\"D3D10 Metal\",\"wi"
    "neboot\":true},{\"arch\":\"win32\",\"components\":[\"d3d10core\",\"d3d10_1\",\"winemetal\",\"vcrun2019_x"
    "86\"],\"id\":\"m10_32\",\"launch_pipeline\":\"m10_32\",\"mono_runtime\":null,\"name\":\"D3D10 Metal (32-"
    "bit)\",\"wineboot\":true},{\"arch\":\"win64\",\"components\":[\"d3d11\",\"dxgi\",\"vcrun2019_x64\",\"vcrun"
    "2019_x86\"],\"id\":\"m11\",\"launch_pipeline\":\"m11\",\"mono_runtime\":null,\"name\":\"D3D11 Metal\",\"wi"
    "neboot\":true},{\"arch\":\"win32\",\"components\":[\"d3d11\",\"dxgi\",\"winemetal\",\"vcrun2019_x86\"],\"i"
    "d\":\"m11_32\",\"launch_pipeline\":\"m11_32\",\"mono_runtime\":null,\"name\":\"D3D11 Metal (32-bit)\",\""
    "wineboot\":true},{\"arch\":\"win64\",\"components\":[\"m12_d3d12\",\"m12_d3d11\",\"m12_d3d10core\",\"m12"
    "_dxgi_dxmt\",\"m12_dxgi\",\"m12_winemetal\",\"m12_gpu_stubs\",\"vcrun2019_x64\",\"vcrun2019_x86\",\"co"
    "refonts\"],\"id\":\"m12\",\"launch_pipeline\":\"m12\",\"mono_runtime\":null,\"name\":\"D3D12 Metal\",\"win"
    "eboot\":true},{\"arch\":\"win64\",\"components\":[\"d3d11\",\"d3d12\",\"dxgi\",\"d3d10\",\"vcrun2019_x64\","
    "\"vcrun2019_x86\",\"gpu_vendor_stubs\"],\"id\":\"m13\",\"launch_pipeline\":\"m13\",\"mono_runtime\":null"
    ",\"name\":\"GPTK D3DMetal\",\"wineboot\":true},{\"arch\":\"win64\",\"components\":[\"wine-mono\",\"gecko\""
    ",\"dotnet48\",\"vcrun2019_x64\",\"vcrun2019_x86\",\"corefonts\"],\"id\":\"dotnet\",\"launch_pipeline\":\""
    "wine_bare\",\"mono_runtime\":null,\"name\":\".NET\",\"wineboot\":true},{\"arch\":\"win32\",\"components\""
    ":[\"wine-mono\",\"gecko\",\"dotnet48\",\"vcrun2019_x64\",\"vcrun2019_x86\",\"corefonts\"],\"id\":\"win32_"
    "dotnet\",\"launch_pipeline\":\"m9\",\"mono_runtime\":null,\"name\":\"32-bit .NET\",\"wineboot\":true},{"
    "\"arch\":\"wow64\",\"components\":[\"gecko\",\"webview2\",\"dotnet48\",\"vcrun2019_x64\",\"vcrun2019_x86\""
    ",\"directx_jun2010\",\"openal\",\"corefonts\"],\"id\":\"webview\",\"launch_pipeline\":\"wine_bare\",\"mon"
    "o_runtime\":null,\"name\":\"WebView\",\"wineboot\":true},{\"arch\":\"wow64\",\"components\":[\"vcrun2019"
    "_x64\",\"vcrun2019_x86\",\"corefonts\"],\"id\":\"java_launcher\",\"launch_pipeline\":\"wine_bare\",\"mon"
    "o_runtime\":null,\"name\":\"Java Launcher\",\"wineboot\":true},{\"arch\":\"win64\",\"components\":[\"mon"
    "o-arm64\",\"fna\",\"xna\",\"sdl2\",\"fna3d\",\"faudio\"],\"id\":\"fna_arm64\",\"launch_pipeline\":\"fna_arm6"
    "4\",\"mono_runtime\":{\"binary_path\":\"@METALSHARP_HOME@/runtime/mono-arm64/bin/mono\",\"config_p"
    "ath\":\"configs/terraria-mono.config\",\"expected_arch\":\"arm64\",\"id\":\"mono-arm64\",\"known_versi"
    "on\":\"6.14.1\",\"launch_wrapper\":\"native_mono_fna\",\"notes\":\"Used by the Terraria-style FNA la"
    "ne that worked through native macOS Mono plus dllmaps and shims.\"},\"name\":\"FNA / Mono ARM6"
    "4\",\"wineboot\":false},{\"arch\":\"win64\",\"components\":[\"mono-x86\",\"fna\",\"xna\",\"sdl2\",\"fna3d\",\""
    "faudio\",\"fmod\"],\"id\":\"fna_x86\",\"launch_pipeline\":\"fna_arm64\",\"mono_runtime\":{\"binary_path\""
    ":\"@METALSHARP_HOME@/runtime/mono-x86/bin/mono\",\"config_path\":\"configs/celeste-x86-mono.con"
    "fig\",\"expected_arch\":\"x86_64\",\"id\":\"mono-x86\",\"known_version\":\"6.12.0.122\",\"launch_wrapper"
    "\":\"arch -x86_64 native_mono_fna\",\"notes\":\"Used by the Celeste-style legacy lane where x86_"
    "64 Mono 6.12 and dllmaps avoid newer ARM64-only assumptions.\"},\"name\":\"FNA / Mono x86_64\","
    "\"wineboot\":false}]}";

static const char BOTTLES_REDIST_SOURCES_JSON[] =
    "{\"ok\":true,\"sources\":[{\"id\":\"dotnet40\",\"local_targets\":[\"@METALSHARP_HOME@/runtime/redist/"
    "DotNet/4.0/dotNetFx40_Client_x86_x64.exe\",\"@METALSHARP_HOME@/runtime/redist/DotNet/4.0/dot"
    "NetFx40_Full_x86_x64.exe\"],\"name\":\".NET Framework 4.0 Runtime\",\"notes\":\"Use for CLR v4 gam"
    "es that ship C++/CLI launchers, including older UE3 titles such as Goat Simulator.\",\"polic"
    "y\":\"official_download_or_user_supplied\",\"source_url\":\"https://dotnet.microsoft.com/en-us/d"
    "ownload/dotnet-framework/net40\"},{\"id\":\"dotnet48\",\"local_targets\":[\"@METALSHARP_HOME@/runt"
    "ime/redist/DotNet/4.8/ndp48-x86-x64-allos-enu.exe\",\"@METALSHARP_HOME@/runtime/redist/DotNe"
    "t/4.8/NDP48-x86-x64-AllOS-ENU.exe\"],\"name\":\".NET Framework 4.8 Runtime\",\"notes\":\"Use the o"
    "fficial offline runtime installer; MetalSharp does not vendor it in this PR.\",\"policy\":\"of"
    "ficial_download_or_user_supplied\",\"source_url\":\"https://dotnet.microsoft.com/en-us/downloa"
    "d/dotnet-framework/net48\"},{\"id\":\"webview2\",\"local_targets\":[\"@METALSHARP_HOME@/runtime/re"
    "dist/MicrosoftEdgeWebView2RuntimeInstallerX64.exe\",\"@METALSHARP_HOME@/runtime/redist/Micro"
    "softEdgeWebView2RuntimeInstallerX86.exe\"],\"name\":\"Microsoft Edge WebView2 Evergreen Runtim"
    "e\",\"notes\":\"Use the Evergreen Standalone Installer for offline scenarios; Wine compatibili"
    "ty still needs per-installer evidence.\",\"policy\":\"official_download_or_user_supplied\",\"sou"
    "rce_url\":\"https://developer.microsoft.com/en-us/microsoft-edge/webview2/\"},{\"id\":\"vcrun201"
    "9_x64\",\"local_targets\":[\"@METALSHARP_HOME@/runtime/redist/vcredist/vc_redist.x64.exe\"],\"na"
    "me\":\"Microsoft Visual C++ 2015-2022 (x64)\",\"notes\":\"Installs vcruntime140.dll, vcruntime14"
    "0_1.dll, msvcp140.dll into system32\",\"policy\":\"official_download\",\"source_url\":\"https://ak"
    "a.ms/vs/17/release/vc_redist.x64.exe\"},{\"id\":\"vcrun2019_x86\",\"local_targets\":[\"@METALSHARP"
    "_HOME@/runtime/redist/vcredist/vc_redist.x86.exe\"],\"name\":\"Microsoft Visual C++ 2015-2022 "
    "(x86)\",\"notes\":\"Installs vcruntime140.dll, msvcp140.dll into syswow64\",\"policy\":\"official_"
    "download\",\"source_url\":\"https://aka.ms/vs/17/release/vc_redist.x86.exe\"},{\"id\":\"vcrun2010\""
    ",\"local_targets\":[\"@METALSHARP_HOME@/runtime/redist/vcredist/2010/vcredist_x64.exe\",\"@META"
    "LSHARP_HOME@/runtime/redist/vcredist/2010/vcredist_x86.exe\"],\"name\":\"Microsoft Visual C++ "
    "2010 Redistributable (10.0)\",\"notes\":\"Installs msvcr100.dll and msvcp100.dll. Required by "
    "older UE3/C++-CLI titles such as Goat Simulator.\",\"policy\":\"official_download_or_steam_com"
    "monredist\",\"source_url\":\"https://www.microsoft.com/download/details.aspx?id=26999\"},{\"id\":"
    "\"vcrun2013\",\"local_targets\":[\"@METALSHARP_HOME@/runtime/redist/vcredist_x64.exe\",\"@METALSH"
    "ARP_HOME@/runtime/redist/vcredist_x86.exe\"],\"name\":\"Microsoft Visual C++ 2013 Redistributa"
    "ble (12.0)\",\"notes\":\"Installs msvcr120.dll and msvcp120.dll. Required by some older titles"
    ".\",\"policy\":\"official_download_or_steam_commonredist\",\"source_url\":\"https://support.micros"
    "oft.com/en-us/topic/update-for-visual-c-2013-redistributable-package-d8ccd6a4-4a90-bdbd-a0"
    "60-8276036c0738\"},{\"id\":\"directx_jun2010\",\"local_targets\":[\"@METALSHARP_HOME@/runtime/redi"
    "st/DirectX/Jun2010/DXSETUP.exe\"],\"name\":\"DirectX June 2010 Runtime\",\"notes\":\"Prefer Steam "
    "CommonRedist game payloads; local offline payload should contain DXSETUP.exe.\",\"policy\":\"o"
    "fficial_download_or_steam_commonredist\",\"source_url\":\"https://www.microsoft.com/download/d"
    "etails.aspx?id=8109\"},{\"id\":\"openal\",\"local_targets\":[\"@METALSHARP_HOME@/runtime/redist/Op"
    "enAL/oalinst.exe\",\"@METALSHARP_HOME@/runtime/redist/oalinst.exe\"],\"name\":\"OpenAL Runtime\","
    "\"notes\":\"Prefer Steam CommonRedist when available; older games often ship oalinst.exe besi"
    "de installscript.vdf.\",\"policy\":\"official_download_or_steam_commonredist\",\"source_url\":\"ht"
    "tps://www.openal.org/downloads/\"},{\"id\":\"xna\",\"local_targets\":[\"@METALSHARP_HOME@/runtime/"
    "redist/XNA/4.0/xnafx40_redist.msi\",\"@METALSHARP_HOME@/runtime/redist/XNA/4.0/xnafx40_redis"
    "t.exe\",\"@METALSHARP_HOME@/bottles/*/installers/xnafx40_redist.msi\"],\"name\":\"Microsoft XNA "
    "Framework 4.0\",\"notes\":\"Use local, Sharp Library staged, or Steam-provided XNA 4.0 redist "
    "assets; this stays receipt-driven per bottle.\",\"policy\":\"official_download_or_steam_common"
    "redist\",\"source_url\":\"https://www.microsoft.com/download/details.aspx?id=20914\"},{\"id\":\"ph"
    "ysx\",\"local_targets\":[\"@METALSHARP_HOME@/runtime/redist/PhysX/PhysX-9.12.1031-SystemSoftwa"
    "re.msi\",\"@METALSHARP_HOME@/runtime/redist/PhysX/PhysX-9.13.0604-SystemSoftware.msi\"],\"name"
    "\":\"NVIDIA PhysX Legacy Runtime\",\"notes\":\"Only install when a game's install script or bund"
    "led redist explicitly requires legacy PhysX.\",\"policy\":\"official_download_or_steam_commonr"
    "edist\",\"source_url\":\"https://www.nvidia.com/en-us/drivers/physx/physx-9-13-0604-legacy-dri"
    "ver/\"}]}";

static const char BOTTLES_ROUTE_CONTRACTS_JSON[] =
    "{\"contracts\":[{\"binds_to_shared_steam_prefix\":true,\"bottle_id_template\":\"steam_{appid}\",\"c"
    "ompat_tool_name\":\"MetalSharp\",\"launch_route\":\"/steam/launch-game\",\"pipeline\":\"m9\",\"require"
    "s_wine\":true,\"runtime_profile\":\"m9\",\"steam_identity_mode\":\"wine_steam_background\",\"waits_f"
    "or_prefix_idle\":false},{\"binds_to_shared_steam_prefix\":true,\"bottle_id_template\":\"steam_{a"
    "ppid}\",\"compat_tool_name\":\"MetalSharp\",\"launch_route\":\"/steam/launch-game\",\"pipeline\":\"m10"
    "\",\"requires_wine\":true,\"runtime_profile\":\"m10\",\"steam_identity_mode\":\"wine_steam_backgroun"
    "d\",\"waits_for_prefix_idle\":false},{\"binds_to_shared_steam_prefix\":true,\"bottle_id_template"
    "\":\"steam_{appid}\",\"compat_tool_name\":\"MetalSharp\",\"launch_route\":\"/steam/launch-game\",\"pip"
    "eline\":\"m11\",\"requires_wine\":true,\"runtime_profile\":\"m11\",\"steam_identity_mode\":\"wine_stea"
    "m_background\",\"waits_for_prefix_idle\":false},{\"binds_to_shared_steam_prefix\":true,\"bottle_"
    "id_template\":\"steam_{appid}\",\"compat_tool_name\":\"MetalSharp\",\"launch_route\":\"/steam/launch"
    "-game\",\"pipeline\":\"m12\",\"requires_wine\":true,\"runtime_profile\":\"m12\",\"steam_identity_mode\""
    ":\"wine_steam_background\",\"waits_for_prefix_idle\":false},{\"binds_to_shared_steam_prefix\":tr"
    "ue,\"bottle_id_template\":\"steam_{appid}\",\"compat_tool_name\":\"MetalSharp\",\"launch_route\":\"/s"
    "team/launch-game\",\"pipeline\":\"m13\",\"requires_wine\":true,\"runtime_profile\":\"m13\",\"steam_ide"
    "ntity_mode\":\"wine_steam_background\",\"waits_for_prefix_idle\":false},{\"binds_to_shared_steam"
    "_prefix\":false,\"bottle_id_template\":\"steam_{appid}\",\"compat_tool_name\":\"MetalSharp\",\"launc"
    "h_route\":\"/steam/launch-game\",\"pipeline\":\"fna_arm64\",\"requires_wine\":false,\"runtime_profil"
    "e\":\"fna_arm64\",\"steam_identity_mode\":\"wine_steam_background\",\"waits_for_prefix_idle\":false"
    "},{\"binds_to_shared_steam_prefix\":true,\"bottle_id_template\":\"steam_{appid}\",\"compat_tool_n"
    "ame\":\"MetalSharp\",\"launch_route\":\"/steam/launch-game\",\"pipeline\":\"wine_bare\",\"requires_win"
    "e\":true,\"runtime_profile\":\"plain\",\"steam_identity_mode\":\"wine_steam_background\",\"waits_for"
    "_prefix_idle\":false},{\"binds_to_shared_steam_prefix\":false,\"bottle_id_template\":\"steam_{ap"
    "pid}\",\"compat_tool_name\":\"MetalSharp\",\"launch_route\":\"/steam/launch-offline\",\"pipeline\":\"d"
    "3dmetal\",\"requires_wine\":false,\"runtime_profile\":\"d3dmetal\",\"steam_identity_mode\":\"offline"
    "_steam_emulation\",\"waits_for_prefix_idle\":false}],\"ok\":true}";

static const char BOTTLES_COMPATIBILITY_MATRIX_JSON[] =
    "{\"cases\":[{\"bottle_id\":null,\"case_type\":\"32-bit .NET/WinRT bootstrapper\",\"evidence_updated"
    "_at\":null,\"final_app_detected\":\"pending\",\"final_app_launches\":\"pending\",\"id\":\"minecraft-in"
    "staller\",\"installer_opens\":\"needs_real_trace\",\"known_missing_runtime\":\"Wine Mono/.NET 4.x "
    "compatibility\",\"name\":\"Minecraft Installer\",\"notes\":\"\",\"per_game_prefix_recommendation\":\"n"
    "ot_applicable\",\"required_profile\":\"win32_dotnet\"},{\"bottle_id\":null,\"case_type\":\"indie ins"
    "taller/extracted demo\",\"evidence_updated_at\":null,\"final_app_detected\":\"pending\",\"final_ap"
    "p_launches\":\"pending\",\"id\":\"itch-windows-games\",\"installer_opens\":\"untested\",\"known_missin"
    "g_runtime\":\"VC runtime or DirectX June 2010 varies by game\",\"name\":\"Itch.io Windows Games\""
    ",\"notes\":\"\",\"per_game_prefix_recommendation\":\"not_applicable\",\"required_profile\":\"game_ins"
    "tall\"},{\"bottle_id\":null,\"case_type\":\"Unity player demo\",\"evidence_updated_at\":null,\"final"
    "_app_detected\":\"pending\",\"final_app_launches\":\"pending\",\"id\":\"unity-demos\",\"installer_open"
    "s\":\"untested\",\"known_missing_runtime\":\"VC runtime and Unity launcher handoff\",\"name\":\"Unit"
    "y Demos\",\"notes\":\"\",\"per_game_prefix_recommendation\":\"not_applicable\",\"required_profile\":\""
    "m11\"},{\"bottle_id\":null,\"case_type\":\"Unreal packaged demo\",\"evidence_updated_at\":null,\"fin"
    "al_app_detected\":\"pending\",\"final_app_launches\":\"pending\",\"id\":\"unreal-demos\",\"installer_o"
    "pens\":\"untested\",\"known_missing_runtime\":\"VC runtime, DirectX payloads, D3D12 route\",\"name"
    "\":\"Unreal Demos\",\"notes\":\"\",\"per_game_prefix_recommendation\":\"not_applicable\",\"required_pr"
    "ofile\":\"m12\"},{\"bottle_id\":null,\"case_type\":\"Squirrel/Electron launcher\",\"evidence_updated"
    "_at\":null,\"final_app_detected\":\"pending\",\"final_app_launches\":\"pending\",\"id\":\"electron-lau"
    "nchers\",\"installer_opens\":\"untested\",\"known_missing_runtime\":\"WebView/Gecko/browser runtim"
    "e varies\",\"name\":\"Electron Launchers\",\"notes\":\"\",\"per_game_prefix_recommendation\":\"not_app"
    "licable\",\"required_profile\":\"launcher\"},{\"bottle_id\":null,\"case_type\":\"offline game instal"
    "ler\",\"evidence_updated_at\":null,\"final_app_detected\":\"pending\",\"final_app_launches\":\"pendi"
    "ng\",\"id\":\"gog-offline-installers\",\"installer_opens\":\"untested\",\"known_missing_runtime\":\"VC"
    " runtime and DirectX June 2010\",\"name\":\"GOG Offline Installers\",\"notes\":\"\",\"per_game_prefi"
    "x_recommendation\":\"not_applicable\",\"required_profile\":\"game_install\"},{\"bottle_id\":null,\"c"
    "ase_type\":\"store-adjacent launcher\",\"evidence_updated_at\":null,\"final_app_detected\":\"pendi"
    "ng\",\"final_app_launches\":\"pending\",\"id\":\"webview-launchers\",\"installer_opens\":\"untested\",\""
    "known_missing_runtime\":\"WebView2 under Wine remains risky\",\"name\":\"Epic/EA/Ubisoft Launche"
    "rs\",\"notes\":\"\",\"per_game_prefix_recommendation\":\"not_applicable\",\"required_profile\":\"webvi"
    "ew\"},{\"bottle_id\":null,\"case_type\":\"runtime installer\",\"evidence_updated_at\":null,\"final_a"
    "pp_detected\":\"not_applicable\",\"final_app_launches\":\"not_applicable\",\"id\":\"vc-redists\",\"ins"
    "taller_opens\":\"supported\",\"known_missing_runtime\":\"local redistributable asset required\",\""
    "name\":\"VC Runtime Redistributables (2015-2022 + 2013)\",\"notes\":\"\",\"per_game_prefix_recomme"
    "ndation\":\"not_applicable\",\"required_profile\":\"plain\"}],\"ok\":true}";

#endif
