/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

struct _S8 {
  int8_t f0[40];
};
struct _S11 {
  int8_t f0[32];
};
struct _S14 {
  int8_t f0[16];
};
uint32_t _RNvCsaeCX7MzhkiK_6adler213adler32_slice(void *, __rustc_usize);
void _RNvMCsaeCX7MzhkiK_6adler2NtB2_7Adler3211write_slice(void *, void *, __rustc_usize);
static struct _S8 _RNvMNtCs41fFVwHnQdq_4core5sliceSh12chunks_exactCsaeCX7MzhkiK_6adler2(void *, __rustc_usize, __rustc_usize, void *);
static struct _S11 _RNvMNtCs41fFVwHnQdq_4core5sliceSh8split_atCsaeCX7MzhkiK_6adler2(void *, __rustc_usize, __rustc_usize, void *);
static void _RNvMNtCsaeCX7MzhkiK_6adler24algoNtB4_7Adler327compute(void *, void *, __rustc_usize);
static struct _S14 _RNvMs_NtCsaeCX7MzhkiK_6adler24algoNtB4_5U32X44from(void *, __rustc_usize);
void _RNvXs0_CsaeCX7MzhkiK_6adler2NtB5_7Adler32NtNtCs41fFVwHnQdq_4core4hash6Hasher5write(void *, void *, __rustc_usize);
static void _RNvXs1_NtCsaeCX7MzhkiK_6adler24algoNtB5_5U32X4INtNtNtCs41fFVwHnQdq_4core3ops5arith9RemAssignmE10rem_assign(void *, uint32_t);
void _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(void *, void *, void *);
void _RNvNtNtCs41fFVwHnQdq_4core9panicking11panic_const23panic_const_rem_by_zero(void *);
void _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(__rustc_usize, __rustc_usize, void *);

static const unsigned char _bytes0[] = { 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x20, 0x73, 0x69, 0x7a, 0x65, 0x20, 0x6d, 0x75, 0x73, 0x74, 0x20, 0x62, 0x65, 0x20, 0x6e, 0x6f, 0x6e, 0x2d, 0x7a, 0x65, 0x72, 0x6f };
static const unsigned char _bytes1[] = { 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x20, 0x73, 0x69, 0x7a, 0x65, 0x20, 0x6d, 0x75, 0x73, 0x74, 0x20, 0x62, 0x65, 0x20, 0x6e, 0x6f, 0x6e, 0x2d, 0x7a, 0x65, 0x72, 0x6f };
static const unsigned char _bytes3[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes2 = {   .f0 = (void *)_bytes3,   .f1 = { 0x97, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x07, 0x00, 0x00, 0x13, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes4[] = { 0x6d, 0x69, 0x64, 0x20, 0x3e, 0x20, 0x6c, 0x65, 0x6e };
static const unsigned char _bytes5[] = { 0x6d, 0x69, 0x64, 0x20, 0x3e, 0x20, 0x6c, 0x65, 0x6e };
static const unsigned char _bytes7[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes6 = {   .f0 = (void *)_bytes7,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes9[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes8 = {   .f0 = (void *)_bytes9,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes11[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes10 = {   .f0 = (void *)_bytes11,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x4e, 0x00, 0x00, 0x00, 0x29, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes13[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes12 = {   .f0 = (void *)_bytes13,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0x00, 0x00, 0x00, 0x23, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes15[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes14 = {   .f0 = (void *)_bytes15,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x76, 0x00, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes17[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes16 = {   .f0 = (void *)_bytes17,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x77, 0x00, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes19[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes18 = {   .f0 = (void *)_bytes19,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x78, 0x00, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes21[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes20 = {   .f0 = (void *)_bytes21,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x79, 0x00, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes23[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes22 = {   .f0 = (void *)_bytes23,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8c, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes25[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes24 = {   .f0 = (void *)_bytes25,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8d, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes27[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes26 = {   .f0 = (void *)_bytes27,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8e, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes29[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x61, 0x64, 0x6c, 0x65, 0x72, 0x32, 0x2d, 0x32, 0x2e, 0x30, 0x2e, 0x31, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes28 = {   .f0 = (void *)_bytes29,   .f1 = { 0x5f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8f, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00 } };
#pragma pack(pop)

#pragma weak _RNvCsaeCX7MzhkiK_6adler213adler32_slice
uint32_t _RNvCsaeCX7MzhkiK_6adler213adler32_slice(void * _arg0, __rustc_usize _arg1) {
  _Alignas(2) uint8_t _t0_storage[4];
  void *_t0 = (void *)_t0_storage;
  void * _t1;
  void * _t2;
  uint16_t _t3;
  uint32_t _t4;
  int32_t _t5;
  uint32_t _t6;
  uint16_t _t7;
  uint32_t _t8;
  uint32_t _t9;

bb_0_start:
  *(uint16_t *)_t0 = 1ULL;
  _t1 = (void *)((__rustc_usize)_t0 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint16_t *)_t1 = 0ULL;
  _RNvMCsaeCX7MzhkiK_6adler2NtB2_7Adler3211write_slice(_t0, _arg0, _arg1);
  _t2 = (void *)((__rustc_usize)_t0 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(int8_t));
  _t3 = *(uint16_t *)_t2;
  _t4 = (uint32_t)_t3;
  _t5 = 16LL & 31LL;
  _t6 = (uint32_t)(_t4) << (_t5);
  _t7 = *(uint16_t *)_t0;
  _t8 = (uint32_t)_t7;
  _t9 = _t6 | _t8;
  return _t9;
}

#pragma weak _RNvMCsaeCX7MzhkiK_6adler2NtB2_7Adler3211write_slice
void _RNvMCsaeCX7MzhkiK_6adler2NtB2_7Adler3211write_slice(void * _arg0, void * _arg1, __rustc_usize _arg2) {
bb_0_start:
  _RNvMNtCsaeCX7MzhkiK_6adler24algoNtB4_7Adler327compute(_arg0, _arg1, _arg2);
  return;
}

static struct _S8 _RNvMNtCs41fFVwHnQdq_4core5sliceSh12chunks_exactCsaeCX7MzhkiK_6adler2(void * _arg0, __rustc_usize _arg1, __rustc_usize _arg2, void * _arg3) {
  _Alignas(16) struct _S8 _retbuf;
  _Bool _t10;
  void * _t11;
  _Bool _t12;
  int32_t _t13;
  __rustc_usize _t14;
  __rustc_usize _t15;
  __rustc_usize _t16;
  void * _t17;
  _Bool _t18;
  _Bool _t19;
  __rustc_usize _t20;
  __rustc_usize _t21;
  void * _t22;
  __rustc_usize _t23;
  void * _t24;
  void * _t25;
  void * _t26;
  void * _t27;

bb_0_start:
  _t10 = (__rustc_isize)_arg2 == (__rustc_isize)0ULL;
  if (_t10) goto bb_1_bb2; else goto bb_2_bb1;
bb_1_bb2:
  _t11 = (void *)_bytes0;
  _t12 = (int64_t)_t11 != (int64_t)0;
  _t13 = 1LL & 63LL;
  _t14 = (__rustc_usize)(uint32_t)_t13;
  _t15 = (__rustc_usize)(27ULL) << (_t14);
  _t16 = _t15 | 1ULL;
  _t17 = (void *)_t16;
  _t18 = (int64_t)_t17 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t11, _t17, _arg3);
  abort();
bb_2_bb1:
  _t19 = (__rustc_isize)_arg2 == (__rustc_isize)0ULL;
  if (_t19) goto bb_4_panic; else goto bb_3_bb3;
bb_3_bb3:
  _t20 = _arg1 % _arg2;
  _t21 = _arg1 - _t20;
  goto bb_5_bb5;
bb_4_panic:
  _RNvNtNtCs41fFVwHnQdq_4core9panicking11panic_const23panic_const_rem_by_zero(&_bytes2);
  abort();
bb_5_bb5:
  goto bb_6_bb8;
bb_6_bb8:
  _t22 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(_t21) * (__rustc_isize)sizeof(uint8_t));
  _t23 = _arg1 - _t21;
  goto bb_7_bb11;
bb_7_bb11:
  *(void * *)(void *)&_retbuf = _arg0;
  _t24 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t24 = _t21;
  _t25 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t25 = _t22;
  _t26 = (void *)((__rustc_usize)_t25 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t26 = _t23;
  _t27 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t27 = _arg2;
  return _retbuf;
bb_8_bb4:
  abort();
bb_9_bb6:
  abort();
bb_10_bb7:
  abort();
bb_11_bb9:
  abort();
bb_12_bb10:
  abort();
}

static struct _S11 _RNvMNtCs41fFVwHnQdq_4core5sliceSh8split_atCsaeCX7MzhkiK_6adler2(void * _arg0, __rustc_usize _arg1, __rustc_usize _arg2, void * _arg3) {
  _Alignas(16) struct _S11 _retbuf;
  _Alignas(8) uint8_t _t28_storage[32];
  void *_t28 = (void *)_t28_storage;
  _Alignas(8) uint8_t _t29_storage[32];
  void *_t29 = (void *)_t29_storage;
  _Bool _t30;
  void * _t31;
  _Bool _t32;
  int32_t _t33;
  __rustc_usize _t34;
  __rustc_usize _t35;
  __rustc_usize _t36;
  void * _t37;
  _Bool _t38;
  void * _t39;
  __rustc_usize _t40;
  void * _t41;
  void * _t42;
  void * _t43;

bb_0_start:
  _t30 = (__rustc_usize)_arg2 <= (__rustc_usize)_arg1;
  if (_t30) goto bb_2_bb1; else goto bb_1_bb2;
bb_1_bb2:
  _t31 = (void *)_bytes4;
  _t32 = (int64_t)_t31 != (int64_t)0;
  _t33 = 1LL & 63LL;
  _t34 = (__rustc_usize)(uint32_t)_t33;
  _t35 = (__rustc_usize)(9ULL) << (_t34);
  _t36 = _t35 | 1ULL;
  _t37 = (void *)_t36;
  _t38 = (int64_t)_t37 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t31, _t37, _arg3);
  abort();
bb_2_bb1:
  goto bb_3_bb4;
bb_3_bb4:
  goto bb_4_bb7;
bb_4_bb7:
  _t39 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(_arg2) * (__rustc_isize)sizeof(uint8_t));
  _t40 = _arg1 - _arg2;
  goto bb_5_bb10;
bb_5_bb10:
  *(void * *)_t29 = _arg0;
  _t41 = (void *)((__rustc_usize)_t29 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t41 = _arg2;
  _t42 = (void *)((__rustc_usize)_t29 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t42 = _t39;
  _t43 = (void *)((__rustc_usize)_t42 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t43 = _t40;
  memcpy(_t28, _t29, 32ULL);
  memcpy((void *)&_retbuf, _t28, 32ULL);
  return _retbuf;
bb_6_bb3:
  abort();
bb_7_bb5:
  abort();
bb_8_bb6:
  abort();
bb_9_bb8:
  abort();
bb_10_bb9:
  abort();
}

static void _RNvMNtCsaeCX7MzhkiK_6adler24algoNtB4_7Adler327compute(void * _arg0, void * _arg1, __rustc_usize _arg2) {
  _Alignas(4) uint8_t _t44_storage[4];
  void *_t44 = (void *)_t44_storage;
  _Alignas(4) uint8_t _t45_storage[4];
  void *_t45 = (void *)_t45_storage;
  _Alignas(4) uint8_t _t46_storage[16];
  void *_t46 = (void *)_t46_storage;
  _Alignas(4) uint8_t _t47_storage[16];
  void *_t47 = (void *)_t47_storage;
  _Alignas(4) uint8_t _t48_storage[16];
  void *_t48 = (void *)_t48_storage;
  _Alignas(8) uint8_t _t49_storage[32];
  void *_t49 = (void *)_t49_storage;
  _Alignas(8) uint8_t _t50_storage[40];
  void *_t50 = (void *)_t50_storage;
  _Alignas(8) uint8_t _t51_storage[16];
  void *_t51 = (void *)_t51_storage;
  _Alignas(8) uint8_t _t52_storage[40];
  void *_t52 = (void *)_t52_storage;
  _Alignas(8) uint8_t _t53_storage[16];
  void *_t53 = (void *)_t53_storage;
  _Alignas(4) uint8_t _t54_storage[16];
  void *_t54 = (void *)_t54_storage;
  _Alignas(8) uint8_t _t55_storage[40];
  void *_t55 = (void *)_t55_storage;
  _Alignas(8) uint8_t _t56_storage[16];
  void *_t56 = (void *)_t56_storage;
  _Alignas(4) uint8_t _t57_storage[16];
  void *_t57 = (void *)_t57_storage;
  _Alignas(8) uint8_t _t58_storage[16];
  void *_t58 = (void *)_t58_storage;
  _Alignas(8) uint8_t _t59_storage[8];
  void *_t59 = (void *)_t59_storage;
  _Alignas(8) uint8_t _t60_storage[16];
  void *_t60 = (void *)_t60_storage;
  _Alignas(8) uint8_t _t61_storage[8];
  void *_t61 = (void *)_t61_storage;
  _Alignas(8) uint8_t _t62_storage[16];
  void *_t62 = (void *)_t62_storage;
  _Alignas(8) uint8_t _t63_storage[8];
  void *_t63 = (void *)_t63_storage;
  _Alignas(8) uint8_t _t64_storage[16];
  void *_t64 = (void *)_t64_storage;
  _Alignas(8) uint8_t _t65_storage[16];
  void *_t65 = (void *)_t65_storage;
  _Alignas(8) uint8_t _t66_storage[16];
  void *_t66 = (void *)_t66_storage;
  _Alignas(4) uint8_t _t67_storage[16];
  void *_t67 = (void *)_t67_storage;
  _Alignas(4) uint8_t _t68_storage[16];
  void *_t68 = (void *)_t68_storage;
  _Alignas(4) uint8_t _t69_storage[16];
  void *_t69 = (void *)_t69_storage;
  _Alignas(4) uint8_t _t70_storage[16];
  void *_t70 = (void *)_t70_storage;
  uint16_t _t71;
  uint32_t _t72;
  void * _t73;
  uint16_t _t74;
  uint32_t _t75;
  __rustc_usize _t76;
  __rustc_usize _t77;
  struct _S11 _t78;
  void * _t79;
  void * _t80;
  __rustc_usize _t81;
  void * _t82;
  void * _t83;
  void * _t84;
  __rustc_usize _t85;
  struct _S8 _t86;
  void * _t87;
  void * _t88;
  void * _t89;
  __rustc_usize _t90;
  void * _t91;
  void * _t92;
  __rustc_usize _t93;
  void * _t94;
  void * _t95;
  __rustc_usize _t96;
  void * _t97;
  void * _t98;
  __rustc_usize _t99;
  _Bool _t100;
  struct _S8 _t101;
  void * _t102;
  void * _t103;
  __rustc_usize _t104;
  void * _t105;
  void * _t106;
  void * _t107;
  void * _t108;
  __rustc_usize _t109;
  void * _t110;
  __rustc_usize _t111;
  void * _t112;
  void * _t113;
  __rustc_usize _t114;
  _Bool _t115;
  uint32_t _t116;
  uint32_t _t117;
  uint32_t _t118;
  uint32_t _t119;
  uint32_t _t120;
  uint32_t _t121;
  uint32_t _t122;
  void * _t123;
  void * _t124;
  uint32_t _t125;
  uint32_t _t126;
  void * _t127;
  void * _t128;
  uint32_t _t129;
  uint32_t _t130;
  void * _t131;
  void * _t132;
  uint32_t _t133;
  uint32_t _t134;
  void * _t135;
  void * _t136;
  uint32_t _t137;
  uint32_t _t138;
  void * _t139;
  uint32_t _t140;
  uint32_t _t141;
  void * _t142;
  void * _t143;
  uint32_t _t144;
  uint32_t _t145;
  void * _t146;
  uint32_t _t147;
  uint32_t _t148;
  uint32_t _t149;
  void * _t150;
  void * _t151;
  uint32_t _t152;
  uint32_t _t153;
  void * _t154;
  uint32_t _t155;
  uint32_t _t156;
  uint32_t _t157;
  void * _t158;
  void * _t159;
  uint32_t _t160;
  uint32_t _t161;
  void * _t162;
  _Bool _t163;
  void * _t164;
  void * _t165;
  void * _t166;
  void * _t167;
  void * _t168;
  void * _t169;
  void * _t170;
  _Bool _t171;
  _Bool _t172;
  void * _t173;
  _Bool _t174;
  void * _t175;
  _Bool _t176;
  _Bool _t177;
  void * _t178;
  void * _t179;
  void * _t180;
  _Bool _t181;
  void * _t182;
  uint32_t _t183;
  uint32_t _t184;
  uint32_t _t185;
  void * _t186;
  _Bool _t187;
  void * _t188;
  void * _t189;
  void * _t190;
  void * _t191;
  void * _t192;
  void * _t193;
  void * _t194;
  _Bool _t195;
  _Bool _t196;
  void * _t197;
  _Bool _t198;
  void * _t199;
  _Bool _t200;
  _Bool _t201;
  void * _t202;
  void * _t203;
  void * _t204;
  _Bool _t205;
  void * _t206;
  uint32_t _t207;
  uint32_t _t208;
  uint32_t _t209;
  void * _t210;
  _Bool _t211;
  void * _t212;
  void * _t213;
  void * _t214;
  void * _t215;
  void * _t216;
  void * _t217;
  void * _t218;
  _Bool _t219;
  _Bool _t220;
  void * _t221;
  _Bool _t222;
  void * _t223;
  _Bool _t224;
  _Bool _t225;
  void * _t226;
  void * _t227;
  void * _t228;
  _Bool _t229;
  void * _t230;
  uint8_t _t231;
  uint32_t _t232;
  uint32_t _t233;
  uint32_t _t234;
  uint32_t _t235;
  uint32_t _t236;
  uint32_t _t237;
  uint32_t _t238;
  uint32_t _t239;
  uint16_t _t240;
  uint32_t _t241;
  uint32_t _t242;
  void * _t243;
  uint16_t _t244;
  void * _t245;
  void * _t246;
  __rustc_usize _t247;
  void * _t248;
  __rustc_usize _t249;
  void * _t250;
  void * _t251;
  void * _t252;
  void * _t253;
  __rustc_usize _t254;
  struct _S14 _t255;
  void * _t256;
  uint32_t _t257;
  void * _t258;
  void * _t259;
  uint32_t _t260;
  uint32_t _t261;
  void * _t262;
  uint32_t _t263;
  void * _t264;
  void * _t265;
  uint32_t _t266;
  uint32_t _t267;
  void * _t268;
  uint32_t _t269;
  void * _t270;
  void * _t271;
  uint32_t _t272;
  uint32_t _t273;
  void * _t274;
  uint32_t _t275;
  void * _t276;
  void * _t277;
  uint32_t _t278;
  uint32_t _t279;
  void * _t280;
  uint32_t _t281;
  void * _t282;
  void * _t283;
  uint32_t _t284;
  uint32_t _t285;
  void * _t286;
  uint32_t _t287;
  void * _t288;
  void * _t289;
  uint32_t _t290;
  uint32_t _t291;
  void * _t292;
  uint32_t _t293;
  void * _t294;
  void * _t295;
  uint32_t _t296;
  uint32_t _t297;
  void * _t298;
  uint32_t _t299;
  void * _t300;
  void * _t301;
  uint32_t _t302;
  uint32_t _t303;
  void * _t304;
  void * _t305;
  __rustc_usize _t306;
  void * _t307;
  __rustc_usize _t308;
  void * _t309;
  void * _t310;
  void * _t311;
  void * _t312;
  __rustc_usize _t313;
  struct _S8 _t314;
  void * _t315;
  void * _t316;
  __rustc_usize _t317;
  void * _t318;
  void * _t319;
  void * _t320;
  void * _t321;
  __rustc_usize _t322;
  void * _t323;
  __rustc_usize _t324;
  void * _t325;
  void * _t326;
  __rustc_usize _t327;
  _Bool _t328;
  uint32_t _t329;
  uint32_t _t330;
  uint32_t _t331;
  uint32_t _t332;
  uint32_t _t333;
  uint32_t _t334;
  void * _t335;
  void * _t336;
  __rustc_usize _t337;
  void * _t338;
  __rustc_usize _t339;
  void * _t340;
  void * _t341;
  void * _t342;
  void * _t343;
  __rustc_usize _t344;
  struct _S14 _t345;
  void * _t346;
  uint32_t _t347;
  void * _t348;
  void * _t349;
  uint32_t _t350;
  uint32_t _t351;
  void * _t352;
  uint32_t _t353;
  void * _t354;
  void * _t355;
  uint32_t _t356;
  uint32_t _t357;
  void * _t358;
  uint32_t _t359;
  void * _t360;
  void * _t361;
  uint32_t _t362;
  uint32_t _t363;
  void * _t364;
  uint32_t _t365;
  void * _t366;
  void * _t367;
  uint32_t _t368;
  uint32_t _t369;
  void * _t370;
  uint32_t _t371;
  void * _t372;
  void * _t373;
  uint32_t _t374;
  uint32_t _t375;
  void * _t376;
  uint32_t _t377;
  void * _t378;
  void * _t379;
  uint32_t _t380;
  uint32_t _t381;
  void * _t382;
  uint32_t _t383;
  void * _t384;
  void * _t385;
  uint32_t _t386;
  uint32_t _t387;
  void * _t388;
  uint32_t _t389;
  void * _t390;
  void * _t391;
  uint32_t _t392;
  uint32_t _t393;

bb_0_start:
  _t71 = *(uint16_t *)_arg0;
  _t72 = (uint32_t)_t71;
  *(uint32_t *)_t44 = _t72;
  _t73 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(int8_t));
  _t74 = *(uint16_t *)_t73;
  _t75 = (uint32_t)_t74;
  *(uint32_t *)_t45 = _t75;
  memset(_t47, 0ULL, 16ULL);
  memcpy(_t46, _t47, 16ULL);
  memcpy(_t48, _t46, 16ULL);
  _t76 = _arg2 % 4ULL;
  _t77 = _arg2 - _t76;
  _t78 = _RNvMNtCs41fFVwHnQdq_4core5sliceSh8split_atCsaeCX7MzhkiK_6adler2(_arg1, _arg2, _t77, &_bytes6);
  *(struct _S11 *)_t49 = _t78;
  _t79 = *(void * *)_t49;
  _t80 = (void *)((__rustc_usize)_t49 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t81 = *(__rustc_usize *)_t80;
  _t82 = (void *)((__rustc_usize)_t49 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t83 = *(void * *)_t82;
  _t84 = (void *)((__rustc_usize)_t82 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t85 = *(__rustc_usize *)_t84;
  _t86 = _RNvMNtCs41fFVwHnQdq_4core5sliceSh12chunks_exactCsaeCX7MzhkiK_6adler2(_t79, _t81, 22208ULL, &_bytes8);
  *(struct _S8 *)_t50 = _t86;
  _t87 = (void *)((__rustc_usize)_t50 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t88 = *(void * *)_t87;
  _t89 = (void *)((__rustc_usize)_t87 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t90 = *(__rustc_usize *)_t89;
  _t91 = *(void * *)_t50;
  _t92 = (void *)((__rustc_usize)_t50 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t93 = *(__rustc_usize *)_t92;
  *(void * *)_t64 = _t91;
  _t94 = (void *)((__rustc_usize)_t64 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t94 = _t93;
  _t95 = (void *)((__rustc_usize)_t50 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  _t96 = *(__rustc_usize *)_t95;
  goto bb_1_bb3;
bb_1_bb3:
  _t97 = *(void * *)_t64;
  _t98 = (void *)((__rustc_usize)_t64 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t99 = *(__rustc_usize *)_t98;
  _t100 = (__rustc_usize)_t96 <= (__rustc_usize)_t99;
  if (_t100) goto bb_3_bb17; else goto bb_2_bb18;
bb_2_bb18:
  _t101 = _RNvMNtCs41fFVwHnQdq_4core5sliceSh12chunks_exactCsaeCX7MzhkiK_6adler2(_t88, _t90, 4ULL, &_bytes10);
  *(struct _S8 *)_t55 = _t101;
  _t102 = *(void * *)_t55;
  _t103 = (void *)((__rustc_usize)_t55 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t104 = *(__rustc_usize *)_t103;
  *(void * *)_t66 = _t102;
  _t105 = (void *)((__rustc_usize)_t66 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t105 = _t104;
  _t106 = (void *)((__rustc_usize)_t55 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t107 = *(void * *)_t106;
  _t108 = (void *)((__rustc_usize)_t106 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t109 = *(__rustc_usize *)_t108;
  _t110 = (void *)((__rustc_usize)_t55 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  _t111 = *(__rustc_usize *)_t110;
  goto bb_4_bb10;
bb_3_bb17:
  _t304 = *(void * *)_t64;
  _t305 = (void *)((__rustc_usize)_t64 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t306 = *(__rustc_usize *)_t305;
  _t307 = (void *)((__rustc_usize)_t304 + (__rustc_isize)(_t96) * (__rustc_isize)sizeof(uint8_t));
  _t308 = _t99 - _t96;
  *(void * *)_t64 = _t307;
  _t309 = (void *)((__rustc_usize)_t64 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t309 = _t308;
  *(void * *)_t51 = _t304;
  _t310 = (void *)((__rustc_usize)_t51 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t310 = _t96;
  _t311 = *(void * *)_t51;
  _t312 = (void *)((__rustc_usize)_t51 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t313 = *(__rustc_usize *)_t312;
  _t314 = _RNvMNtCs41fFVwHnQdq_4core5sliceSh12chunks_exactCsaeCX7MzhkiK_6adler2(_t311, _t313, 4ULL, &_bytes12);
  *(struct _S8 *)_t52 = _t314;
  _t315 = *(void * *)_t52;
  _t316 = (void *)((__rustc_usize)_t52 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t317 = *(__rustc_usize *)_t316;
  *(void * *)_t65 = _t315;
  _t318 = (void *)((__rustc_usize)_t65 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t318 = _t317;
  _t319 = (void *)((__rustc_usize)_t52 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t320 = *(void * *)_t319;
  _t321 = (void *)((__rustc_usize)_t319 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t322 = *(__rustc_usize *)_t321;
  _t323 = (void *)((__rustc_usize)_t52 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  _t324 = *(__rustc_usize *)_t323;
  goto bb_16_bb5;
bb_4_bb10:
  _t112 = *(void * *)_t66;
  _t113 = (void *)((__rustc_usize)_t66 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t114 = *(__rustc_usize *)_t113;
  _t115 = (__rustc_usize)_t111 <= (__rustc_usize)_t114;
  if (_t115) goto bb_6_bb21; else goto bb_5_bb22;
bb_5_bb22:
  _t116 = (uint32_t)_t90;
  _t117 = *(uint32_t *)_t44;
  _t118 = _t116 * _t117;
  _t119 = *(uint32_t *)_t45;
  _t120 = _t119 + _t118;
  *(uint32_t *)_t45 = _t120;
  _RNvXs1_NtCsaeCX7MzhkiK_6adler24algoNtB5_5U32X4INtNtNtCs41fFVwHnQdq_4core3ops5arith9RemAssignmE10rem_assign(_t46, 65521ULL);
  _RNvXs1_NtCsaeCX7MzhkiK_6adler24algoNtB5_5U32X4INtNtNtCs41fFVwHnQdq_4core3ops5arith9RemAssignmE10rem_assign(_t48, 65521ULL);
  _t121 = *(uint32_t *)_t45;
  _t122 = _t121 % 65521ULL;
  *(uint32_t *)_t45 = _t122;
  _t123 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t124 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t125 = *(uint32_t *)_t124;
  _t126 = _t125 * 4ULL;
  *(uint32_t *)_t123 = _t126;
  _t127 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t128 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t129 = *(uint32_t *)_t128;
  _t130 = _t129 * 4ULL;
  *(uint32_t *)_t127 = _t130;
  _t131 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t132 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t133 = *(uint32_t *)_t132;
  _t134 = _t133 * 4ULL;
  *(uint32_t *)_t131 = _t134;
  _t135 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t136 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t137 = *(uint32_t *)_t136;
  _t138 = _t137 * 4ULL;
  *(uint32_t *)_t135 = _t138;
  _t139 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t140 = *(uint32_t *)_t139;
  _t141 = 65521ULL - _t140;
  _t142 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t143 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t144 = *(uint32_t *)_t143;
  _t145 = _t144 + _t141;
  *(uint32_t *)_t142 = _t145;
  _t146 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t147 = *(uint32_t *)_t146;
  _t148 = 65521ULL - _t147;
  _t149 = _t148 * 2ULL;
  _t150 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t151 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t152 = *(uint32_t *)_t151;
  _t153 = _t152 + _t149;
  *(uint32_t *)_t150 = _t153;
  _t154 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t155 = *(uint32_t *)_t154;
  _t156 = 65521ULL - _t155;
  _t157 = _t156 * 3ULL;
  _t158 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t159 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t160 = *(uint32_t *)_t159;
  _t161 = _t160 + _t157;
  *(uint32_t *)_t158 = _t161;
  _t162 = (void *)_t46;
  _t163 = (int64_t)_t162 != (int64_t)0;
  _t164 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(uint32_t));
  _t165 = (void *)_t164;
  *(void * *)_t58 = _t162;
  _t166 = (void *)((__rustc_usize)_t58 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t166 = _t165;
  goto bb_7_bb14;
bb_6_bb21:
  _t245 = *(void * *)_t66;
  _t246 = (void *)((__rustc_usize)_t66 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t247 = *(__rustc_usize *)_t246;
  _t248 = (void *)((__rustc_usize)_t245 + (__rustc_isize)(_t111) * (__rustc_isize)sizeof(uint8_t));
  _t249 = _t114 - _t111;
  *(void * *)_t66 = _t248;
  _t250 = (void *)((__rustc_usize)_t66 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t250 = _t249;
  *(void * *)_t56 = _t245;
  _t251 = (void *)((__rustc_usize)_t56 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t251 = _t111;
  _t252 = *(void * *)_t56;
  _t253 = (void *)((__rustc_usize)_t56 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t254 = *(__rustc_usize *)_t253;
  _t255 = _RNvMs_NtCsaeCX7MzhkiK_6adler24algoNtB4_5U32X44from(_t252, _t254);
  *(struct _S14 *)_t57 = _t255;
  memcpy(_t69, _t57, 16ULL);
  _t256 = (void *)((__rustc_usize)_t69 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t257 = *(uint32_t *)_t256;
  _t258 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t259 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t260 = *(uint32_t *)_t259;
  _t261 = _t260 + _t257;
  *(uint32_t *)_t258 = _t261;
  _t262 = (void *)((__rustc_usize)_t69 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t263 = *(uint32_t *)_t262;
  _t264 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t265 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t266 = *(uint32_t *)_t265;
  _t267 = _t266 + _t263;
  *(uint32_t *)_t264 = _t267;
  _t268 = (void *)((__rustc_usize)_t69 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t269 = *(uint32_t *)_t268;
  _t270 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t271 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t272 = *(uint32_t *)_t271;
  _t273 = _t272 + _t269;
  *(uint32_t *)_t270 = _t273;
  _t274 = (void *)((__rustc_usize)_t69 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t275 = *(uint32_t *)_t274;
  _t276 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t277 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t278 = *(uint32_t *)_t277;
  _t279 = _t278 + _t275;
  *(uint32_t *)_t276 = _t279;
  memcpy(_t70, _t46, 16ULL);
  _t280 = (void *)((__rustc_usize)_t70 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t281 = *(uint32_t *)_t280;
  _t282 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t283 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t284 = *(uint32_t *)_t283;
  _t285 = _t284 + _t281;
  *(uint32_t *)_t282 = _t285;
  _t286 = (void *)((__rustc_usize)_t70 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t287 = *(uint32_t *)_t286;
  _t288 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t289 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t290 = *(uint32_t *)_t289;
  _t291 = _t290 + _t287;
  *(uint32_t *)_t288 = _t291;
  _t292 = (void *)((__rustc_usize)_t70 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t293 = *(uint32_t *)_t292;
  _t294 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t295 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t296 = *(uint32_t *)_t295;
  _t297 = _t296 + _t293;
  *(uint32_t *)_t294 = _t297;
  _t298 = (void *)((__rustc_usize)_t70 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t299 = *(uint32_t *)_t298;
  _t300 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t301 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t302 = *(uint32_t *)_t301;
  _t303 = _t302 + _t299;
  *(uint32_t *)_t300 = _t303;
  goto bb_4_bb10;
bb_7_bb14:
  _t167 = *(void * *)_t58;
  _t168 = (void *)((__rustc_usize)_t58 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t169 = *(void * *)_t168;
  _t170 = (void *)_t169;
  _t171 = (int64_t)_t170 != (int64_t)0;
  _t172 = (int64_t)_t167 != (int64_t)0;
  _t173 = (void *)_t167;
  _t174 = (int64_t)_t170 != (int64_t)0;
  _t175 = (void *)_t170;
  _t176 = (int64_t)_t173 == (int64_t)_t175;
  if (_t176) goto bb_9_bb23; else goto bb_8_bb24;
bb_8_bb24:
  _t177 = (int64_t)_t167 != (int64_t)0;
  _t178 = (void *)_t167;
  _t179 = (void *)((__rustc_usize)_t178 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t180 = (void *)_t179;
  _t181 = (int64_t)_t180 != (int64_t)0;
  *(void * *)_t58 = _t180;
  *(void * *)_t59 = _t178;
  _t182 = *(void * *)_t59;
  _t183 = *(uint32_t *)_t182;
  _t184 = *(uint32_t *)_t44;
  _t185 = _t184 + _t183;
  *(uint32_t *)_t44 = _t185;
  goto bb_7_bb14;
bb_9_bb23:
  _t186 = (void *)_t48;
  _t187 = (int64_t)_t186 != (int64_t)0;
  _t188 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(uint32_t));
  _t189 = (void *)_t188;
  *(void * *)_t60 = _t186;
  _t190 = (void *)((__rustc_usize)_t60 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t190 = _t189;
  goto bb_10_bb15;
bb_10_bb15:
  _t191 = *(void * *)_t60;
  _t192 = (void *)((__rustc_usize)_t60 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t193 = *(void * *)_t192;
  _t194 = (void *)_t193;
  _t195 = (int64_t)_t194 != (int64_t)0;
  _t196 = (int64_t)_t191 != (int64_t)0;
  _t197 = (void *)_t191;
  _t198 = (int64_t)_t194 != (int64_t)0;
  _t199 = (void *)_t194;
  _t200 = (int64_t)_t197 == (int64_t)_t199;
  if (_t200) goto bb_12_bb25; else goto bb_11_bb26;
bb_11_bb26:
  _t201 = (int64_t)_t191 != (int64_t)0;
  _t202 = (void *)_t191;
  _t203 = (void *)((__rustc_usize)_t202 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t204 = (void *)_t203;
  _t205 = (int64_t)_t204 != (int64_t)0;
  *(void * *)_t60 = _t204;
  *(void * *)_t61 = _t202;
  _t206 = *(void * *)_t61;
  _t207 = *(uint32_t *)_t206;
  _t208 = *(uint32_t *)_t45;
  _t209 = _t208 + _t207;
  *(uint32_t *)_t45 = _t209;
  goto bb_10_bb15;
bb_12_bb25:
  _t210 = (void *)_t83;
  _t211 = (int64_t)_t210 != (int64_t)0;
  _t212 = (void *)((__rustc_usize)_t83 + (__rustc_isize)(_t85) * (__rustc_isize)sizeof(uint8_t));
  _t213 = (void *)_t212;
  *(void * *)_t62 = _t210;
  _t214 = (void *)((__rustc_usize)_t62 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t214 = _t213;
  goto bb_13_bb16;
bb_13_bb16:
  _t215 = *(void * *)_t62;
  _t216 = (void *)((__rustc_usize)_t62 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t217 = *(void * *)_t216;
  _t218 = (void *)_t217;
  _t219 = (int64_t)_t218 != (int64_t)0;
  _t220 = (int64_t)_t215 != (int64_t)0;
  _t221 = (void *)_t215;
  _t222 = (int64_t)_t218 != (int64_t)0;
  _t223 = (void *)_t218;
  _t224 = (int64_t)_t221 == (int64_t)_t223;
  if (_t224) goto bb_15_bb27; else goto bb_14_bb28;
bb_14_bb28:
  _t225 = (int64_t)_t215 != (int64_t)0;
  _t226 = (void *)_t215;
  _t227 = (void *)((__rustc_usize)_t226 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint8_t));
  _t228 = (void *)_t227;
  _t229 = (int64_t)_t228 != (int64_t)0;
  *(void * *)_t62 = _t228;
  *(void * *)_t63 = _t226;
  _t230 = *(void * *)_t63;
  _t231 = *(uint8_t *)_t230;
  _t232 = (uint32_t)_t231;
  _t233 = *(uint32_t *)_t44;
  _t234 = _t233 + _t232;
  *(uint32_t *)_t44 = _t234;
  _t235 = *(uint32_t *)_t44;
  _t236 = *(uint32_t *)_t45;
  _t237 = _t236 + _t235;
  *(uint32_t *)_t45 = _t237;
  goto bb_13_bb16;
bb_15_bb27:
  _t238 = *(uint32_t *)_t44;
  _t239 = _t238 % 65521ULL;
  _t240 = (uint16_t)_t239;
  *(uint16_t *)_arg0 = _t240;
  _t241 = *(uint32_t *)_t45;
  _t242 = _t241 % 65521ULL;
  _t243 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(int8_t));
  _t244 = (uint16_t)_t242;
  *(uint16_t *)_t243 = _t244;
  return;
bb_16_bb5:
  _t325 = *(void * *)_t65;
  _t326 = (void *)((__rustc_usize)_t65 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t327 = *(__rustc_usize *)_t326;
  _t328 = (__rustc_usize)_t324 <= (__rustc_usize)_t327;
  if (_t328) goto bb_18_bb19; else goto bb_17_bb20;
bb_17_bb20:
  _t329 = *(uint32_t *)_t44;
  _t330 = 22208ULL * _t329;
  _t331 = *(uint32_t *)_t45;
  _t332 = _t331 + _t330;
  *(uint32_t *)_t45 = _t332;
  _RNvXs1_NtCsaeCX7MzhkiK_6adler24algoNtB5_5U32X4INtNtNtCs41fFVwHnQdq_4core3ops5arith9RemAssignmE10rem_assign(_t46, 65521ULL);
  _RNvXs1_NtCsaeCX7MzhkiK_6adler24algoNtB5_5U32X4INtNtNtCs41fFVwHnQdq_4core3ops5arith9RemAssignmE10rem_assign(_t48, 65521ULL);
  _t333 = *(uint32_t *)_t45;
  _t334 = _t333 % 65521ULL;
  *(uint32_t *)_t45 = _t334;
  goto bb_1_bb3;
bb_18_bb19:
  _t335 = *(void * *)_t65;
  _t336 = (void *)((__rustc_usize)_t65 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t337 = *(__rustc_usize *)_t336;
  _t338 = (void *)((__rustc_usize)_t335 + (__rustc_isize)(_t324) * (__rustc_isize)sizeof(uint8_t));
  _t339 = _t327 - _t324;
  *(void * *)_t65 = _t338;
  _t340 = (void *)((__rustc_usize)_t65 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t340 = _t339;
  *(void * *)_t53 = _t335;
  _t341 = (void *)((__rustc_usize)_t53 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t341 = _t324;
  _t342 = *(void * *)_t53;
  _t343 = (void *)((__rustc_usize)_t53 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t344 = *(__rustc_usize *)_t343;
  _t345 = _RNvMs_NtCsaeCX7MzhkiK_6adler24algoNtB4_5U32X44from(_t342, _t344);
  *(struct _S14 *)_t54 = _t345;
  memcpy(_t67, _t54, 16ULL);
  _t346 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t347 = *(uint32_t *)_t346;
  _t348 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t349 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t350 = *(uint32_t *)_t349;
  _t351 = _t350 + _t347;
  *(uint32_t *)_t348 = _t351;
  _t352 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t353 = *(uint32_t *)_t352;
  _t354 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t355 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t356 = *(uint32_t *)_t355;
  _t357 = _t356 + _t353;
  *(uint32_t *)_t354 = _t357;
  _t358 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t359 = *(uint32_t *)_t358;
  _t360 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t361 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t362 = *(uint32_t *)_t361;
  _t363 = _t362 + _t359;
  *(uint32_t *)_t360 = _t363;
  _t364 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t365 = *(uint32_t *)_t364;
  _t366 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t367 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t368 = *(uint32_t *)_t367;
  _t369 = _t368 + _t365;
  *(uint32_t *)_t366 = _t369;
  memcpy(_t68, _t46, 16ULL);
  _t370 = (void *)((__rustc_usize)_t68 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t371 = *(uint32_t *)_t370;
  _t372 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t373 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t374 = *(uint32_t *)_t373;
  _t375 = _t374 + _t371;
  *(uint32_t *)_t372 = _t375;
  _t376 = (void *)((__rustc_usize)_t68 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t377 = *(uint32_t *)_t376;
  _t378 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t379 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t380 = *(uint32_t *)_t379;
  _t381 = _t380 + _t377;
  *(uint32_t *)_t378 = _t381;
  _t382 = (void *)((__rustc_usize)_t68 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t383 = *(uint32_t *)_t382;
  _t384 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t385 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t386 = *(uint32_t *)_t385;
  _t387 = _t386 + _t383;
  *(uint32_t *)_t384 = _t387;
  _t388 = (void *)((__rustc_usize)_t68 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t389 = *(uint32_t *)_t388;
  _t390 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t391 = (void *)((__rustc_usize)_t48 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t392 = *(uint32_t *)_t391;
  _t393 = _t392 + _t389;
  *(uint32_t *)_t390 = _t393;
  goto bb_16_bb5;
}

static struct _S14 _RNvMs_NtCsaeCX7MzhkiK_6adler24algoNtB4_5U32X44from(void * _arg0, __rustc_usize _arg1) {
  _Alignas(16) struct _S14 _retbuf;
  _Alignas(4) uint8_t _t394_storage[16];
  void *_t394 = (void *)_t394_storage;
  _Bool _t395;
  void * _t396;
  uint8_t _t397;
  uint32_t _t398;
  _Bool _t399;
  void * _t400;
  uint8_t _t401;
  uint32_t _t402;
  _Bool _t403;
  void * _t404;
  uint8_t _t405;
  uint32_t _t406;
  _Bool _t407;
  void * _t408;
  uint8_t _t409;
  uint32_t _t410;
  void * _t411;
  void * _t412;
  void * _t413;
  void * _t414;

bb_0_start:
  _t395 = (__rustc_usize)0ULL < (__rustc_usize)_arg1;
  if (_t395) goto bb_1_bb1; else goto bb_2_panic;
bb_1_bb1:
  _t396 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint8_t));
  _t397 = *(uint8_t *)_t396;
  _t398 = (uint32_t)_t397;
  _t399 = (__rustc_usize)1ULL < (__rustc_usize)_arg1;
  if (_t399) goto bb_3_bb2; else goto bb_4_panic;
bb_2_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(0ULL, _arg1, &_bytes14);
  abort();
bb_3_bb2:
  _t400 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint8_t));
  _t401 = *(uint8_t *)_t400;
  _t402 = (uint32_t)_t401;
  _t403 = (__rustc_usize)2ULL < (__rustc_usize)_arg1;
  if (_t403) goto bb_5_bb3; else goto bb_6_panic;
bb_4_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(1ULL, _arg1, &_bytes16);
  abort();
bb_5_bb3:
  _t404 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint8_t));
  _t405 = *(uint8_t *)_t404;
  _t406 = (uint32_t)_t405;
  _t407 = (__rustc_usize)3ULL < (__rustc_usize)_arg1;
  if (_t407) goto bb_7_bb4; else goto bb_8_panic;
bb_6_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(2ULL, _arg1, &_bytes18);
  abort();
bb_7_bb4:
  _t408 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint8_t));
  _t409 = *(uint8_t *)_t408;
  _t410 = (uint32_t)_t409;
  _t411 = (void *)((__rustc_usize)_t394 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  *(uint32_t *)_t411 = _t398;
  _t412 = (void *)((__rustc_usize)_t394 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  *(uint32_t *)_t412 = _t402;
  _t413 = (void *)((__rustc_usize)_t394 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  *(uint32_t *)_t413 = _t406;
  _t414 = (void *)((__rustc_usize)_t394 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  *(uint32_t *)_t414 = _t410;
  memcpy((void *)&_retbuf, _t394, 16ULL);
  return _retbuf;
bb_8_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(3ULL, _arg1, &_bytes20);
  abort();
}

#pragma weak _RNvXs0_CsaeCX7MzhkiK_6adler2NtB5_7Adler32NtNtCs41fFVwHnQdq_4core4hash6Hasher5write
void _RNvXs0_CsaeCX7MzhkiK_6adler2NtB5_7Adler32NtNtCs41fFVwHnQdq_4core4hash6Hasher5write(void * _arg0, void * _arg1, __rustc_usize _arg2) {
bb_0_start:
  _RNvMCsaeCX7MzhkiK_6adler2NtB2_7Adler3211write_slice(_arg0, _arg1, _arg2);
  return;
}

static void _RNvXs1_NtCsaeCX7MzhkiK_6adler24algoNtB5_5U32X4INtNtNtCs41fFVwHnQdq_4core3ops5arith9RemAssignmE10rem_assign(void * _arg0, uint32_t _arg1) {
  _Bool _t415;
  void * _t416;
  void * _t417;
  uint32_t _t418;
  uint32_t _t419;
  void * _t420;
  void * _t421;
  uint32_t _t422;
  uint32_t _t423;
  void * _t424;
  void * _t425;
  uint32_t _t426;
  uint32_t _t427;
  void * _t428;
  void * _t429;
  uint32_t _t430;
  uint32_t _t431;

bb_0_start:
  _t415 = (int32_t)_arg1 == (int32_t)0ULL;
  if (_t415) goto bb_2_panic; else goto bb_1_bb1;
bb_1_bb1:
  _t416 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t417 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint32_t));
  _t418 = *(uint32_t *)_t417;
  _t419 = _t418 % _arg1;
  *(uint32_t *)_t416 = _t419;
  if (_t415) goto bb_4_panic; else goto bb_3_bb2;
bb_2_panic:
  _RNvNtNtCs41fFVwHnQdq_4core9panicking11panic_const23panic_const_rem_by_zero(&_bytes22);
  abort();
bb_3_bb2:
  _t420 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t421 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint32_t));
  _t422 = *(uint32_t *)_t421;
  _t423 = _t422 % _arg1;
  *(uint32_t *)_t420 = _t423;
  if (_t415) goto bb_6_panic; else goto bb_5_bb3;
bb_4_panic:
  _RNvNtNtCs41fFVwHnQdq_4core9panicking11panic_const23panic_const_rem_by_zero(&_bytes24);
  abort();
bb_5_bb3:
  _t424 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t425 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(2ULL) * (__rustc_isize)sizeof(uint32_t));
  _t426 = *(uint32_t *)_t425;
  _t427 = _t426 % _arg1;
  *(uint32_t *)_t424 = _t427;
  if (_t415) goto bb_8_panic; else goto bb_7_bb4;
bb_6_panic:
  _RNvNtNtCs41fFVwHnQdq_4core9panicking11panic_const23panic_const_rem_by_zero(&_bytes26);
  abort();
bb_7_bb4:
  _t428 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t429 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(3ULL) * (__rustc_isize)sizeof(uint32_t));
  _t430 = *(uint32_t *)_t429;
  _t431 = _t430 % _arg1;
  *(uint32_t *)_t428 = _t431;
  return;
bb_8_panic:
  _RNvNtNtCs41fFVwHnQdq_4core9panicking11panic_const23panic_const_rem_by_zero(&_bytes28);
  abort();
}

