/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

_Bool _RNvXs2_CshfbFwLOP151_8indexmapNtB5_15TryReserveErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void *, void *);
_Bool _RNvXs4_CshfbFwLOP151_8indexmapNtB5_19GetDisjointMutErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void *, void *);
_Bool _RNvXs2_NtCsb5RsJavtctd_5alloc11collectionsNtB5_15TryReserveErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void *, void *);
_Bool _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(void *, void *, __rustc_usize);
_Bool _RNvXsi_NtCs41fFVwHnQdq_4core3fmteNtB5_7Display3fmt(void *, __rustc_usize, void *);

static const unsigned char _bytes0[] = { 0x20, 0x62, 0x65, 0x63, 0x61, 0x75, 0x73, 0x65, 0x20, 0x74, 0x68, 0x65, 0x20, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x64, 0x20, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x20, 0x65, 0x78, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x20, 0x74, 0x68, 0x65, 0x20, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x27, 0x73, 0x20, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d };
static const unsigned char _bytes1[] = { 0x20, 0x62, 0x65, 0x63, 0x61, 0x75, 0x73, 0x65, 0x20, 0x74, 0x68, 0x65, 0x20, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x20, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x20, 0x61, 0x6e, 0x20, 0x65, 0x72, 0x72, 0x6f, 0x72 };
static const unsigned char _bytes2[] = { 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64 };
static const unsigned char _bytes3[] = { 0x61, 0x6e, 0x20, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x20, 0x69, 0x73, 0x20, 0x6f, 0x75, 0x74, 0x20, 0x6f, 0x66, 0x20, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73 };
static const unsigned char _bytes4[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x77, 0x65, 0x72, 0x65, 0x20, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x20, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73 };

#pragma weak _RNvXs2_CshfbFwLOP151_8indexmapNtB5_15TryReserveErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt
_Bool _RNvXs2_CshfbFwLOP151_8indexmapNtB5_15TryReserveErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void * _arg0, void * _arg1) {
  _Alignas(1) uint8_t _t0_storage[1];
  void *_t0 = (void *)_t0_storage;
  _Alignas(8) uint8_t _t1_storage[16];
  void *_t1 = (void *)_t1_storage;
  uint64_t _t2;
  __rustc_isize _t3;
  void * _t4;
  _Bool _t5;
  _Bool _t6;
  void * _t7;
  void * _t8;
  _Bool _t9;
  _Bool _t10;
  __rustc_isize _t11;
  _Bool _t12;
  void * _t13;
  void * _t14;
  __rustc_usize _t15;
  _Bool _t16;
  _Bool _t17;
  int8_t _t18;
  _Bool _t19;

bb_0_start:
  _t2 = *(uint64_t *)_arg0;
  _t3 = (__rustc_isize)_t2;
  switch ((__rustc_usize)_t3) {
    case 0ULL: goto bb_2_bb4;
    case 1ULL: goto bb_3_bb3;
    case 2ULL: goto bb_4_bb2;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  abort();
bb_2_bb4:
  _t4 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t5 = _RNvXs2_NtCsb5RsJavtctd_5alloc11collectionsNtB5_15TryReserveErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(_t4, _arg1);
  _t6 = (_Bool)(_t5);
  *(_Bool *)_t0 = _t6;
  goto bb_5_bb8;
bb_3_bb3:
  *(void * *)_t1 = _bytes0;
  _t7 = (void *)((__rustc_usize)_t1 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t7 = 64ULL;
  goto bb_6_bb5;
bb_4_bb2:
  *(void * *)_t1 = _bytes1;
  _t8 = (void *)((__rustc_usize)_t1 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t8 = 47ULL;
  goto bb_6_bb5;
bb_5_bb8:
  goto bb_9_bb9;
bb_6_bb5:
  _t9 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(_arg1, _bytes2, 24ULL);
  _t10 = (_Bool)(_t9);
  _t11 = (__rustc_isize)_t10;
  _t12 = (_Bool)_t11;
  if (_t12) goto bb_7_bb10; else goto bb_8_bb11;
bb_7_bb10:
  _t18 = (int8_t)(1ULL);
  *(int8_t *)_t0 = _t18;
  goto bb_5_bb8;
bb_8_bb11:
  _t13 = *(void * *)_t1;
  _t14 = (void *)((__rustc_usize)_t1 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t15 = *(__rustc_usize *)_t14;
  _t16 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(_arg1, _t13, _t15);
  _t17 = (_Bool)(_t16);
  *(_Bool *)_t0 = _t17;
  goto bb_9_bb9;
bb_9_bb9:
  _t19 = *(_Bool *)_t0;
  return _t19;
}

#pragma weak _RNvXs4_CshfbFwLOP151_8indexmapNtB5_19GetDisjointMutErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt
_Bool _RNvXs4_CshfbFwLOP151_8indexmapNtB5_19GetDisjointMutErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void * _arg0, void * _arg1) {
  _Alignas(8) uint8_t _t20_storage[16];
  void *_t20 = (void *)_t20_storage;
  _Bool _t21;
  __rustc_isize _t22;
  _Bool _t23;
  void * _t24;
  void * _t25;
  void * _t26;
  void * _t27;
  __rustc_usize _t28;
  _Bool _t29;
  _Bool _t30;

bb_0_start:
  _t21 = *(_Bool *)_arg0;
  _t22 = (__rustc_isize)_t21;
  _t23 = (_Bool)_t22;
  if (_t23) goto bb_1_bb2; else goto bb_2_bb3;
bb_1_bb2:
  *(void * *)_t20 = _bytes4;
  _t25 = (void *)((__rustc_usize)_t20 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t25 = 30ULL;
  goto bb_3_bb4;
bb_2_bb3:
  *(void * *)_t20 = _bytes3;
  _t24 = (void *)((__rustc_usize)_t20 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t24 = 25ULL;
  goto bb_3_bb4;
bb_3_bb4:
  _t26 = *(void * *)_t20;
  _t27 = (void *)((__rustc_usize)_t20 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t28 = *(__rustc_usize *)_t27;
  _t29 = _RNvXsi_NtCs41fFVwHnQdq_4core3fmteNtB5_7Display3fmt(_t26, _t28, _arg1);
  _t30 = (_Bool)(_t29);
  return _t30;
bb_4_bb1:
  abort();
}

