/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

struct _S8 {
  uint64_t f0;
  void * f1;
};
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_3pin3PinINtNtCsb5RsJavtctd_5alloc4sync3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtB1A_5alloc6SystemEEECs7XW3Yo0aMWr_9once_cell(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_4cell10UnsafeCellINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEEECs7XW3Yo0aMWr_9once_cell(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_4cell4CellINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEEECs7XW3Yo0aMWr_9once_cell(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEECs7XW3Yo0aMWr_9once_cell(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc4sync3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtB1k_5alloc6SystemEECs7XW3Yo0aMWr_9once_cell(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp5GuardEBK_(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBK_(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadECs7XW3Yo0aMWr_9once_cell(void *);
static void * _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadONtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBT_(void *, uint8_t);
static uint8_t _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadhECs7XW3Yo0aMWr_9once_cell(void *, uint8_t);
static void _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic12atomic_storehECs7XW3Yo0aMWr_9once_cell(void *, uint8_t, uint8_t);
static struct _S8 _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic23atomic_compare_exchangeONtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEB15_(void *, void *, void *, uint8_t, uint8_t);
void _RNvNtCs7XW3Yo0aMWr_9once_cell3imp18initialize_or_wait(void *, void *, void *);
static void _RNvNtCs7XW3Yo0aMWr_9once_cell3imp4wait(void *, void *);
static void _RNvNtNtCs41fFVwHnQdq_4core4sync6atomic5fence(uint8_t);
void _RNvXs3_NtCs7XW3Yo0aMWr_9once_cell3impNtB5_5GuardNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void *);
static void _RNvXsE_NtCsb5RsJavtctd_5alloc4syncINtB5_3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtBM_5alloc6SystemENtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4dropCs7XW3Yo0aMWr_9once_cell(void *);
void _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(void *, void *, void *);
void _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup(void);
void * _RNvNtNtCsMibNUK8RNN_3std6thread7current7current(void);
void _RNvNtNtCsMibNUK8RNN_3std6thread9functions4park(void);
void _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(void *);
void _RNvMs0_NtNtNtNtCsMibNUK8RNN_3std3sys4sync14thread_parking6darwinNtB5_6Parker6unpark(void *);
void _RINvNtCs41fFVwHnQdq_4core9panicking13assert_failedjjEB4_(uint8_t, void *, void *, void *, void *, void *);
void _RNvMsn_NtCsb5RsJavtctd_5alloc4syncINtB5_3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtBM_5alloc6SystemE9drop_slowBM_(void *);

static const unsigned char _bytes0[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes1[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes3[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes2 = {   .f0 = (void *)_bytes3,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xbe, 0x0f, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes4[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes5[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes7[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes6 = {   .f0 = (void *)_bytes7,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xbf, 0x0f, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes8[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes9[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes11[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes10 = {   .f0 = (void *)_bytes11,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xbe, 0x0f, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes12[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes13[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes15[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes14 = {   .f0 = (void *)_bytes15,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xbf, 0x0f, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes16[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65 };
static const unsigned char _bytes17[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65 };
static const unsigned char _bytes19[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes18 = {   .f0 = (void *)_bytes19,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xaf, 0x0f, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes20[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65 };
static const unsigned char _bytes21[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65 };
static const unsigned char _bytes23[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes22 = {   .f0 = (void *)_bytes23,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xb0, 0x0f, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes24[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x20, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67 };
static const unsigned char _bytes25[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x20, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67 };
static const unsigned char _bytes27[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes26 = {   .f0 = (void *)_bytes27,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x34, 0x10, 0x00, 0x00, 0x1d, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes28[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x20, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67 };
static const unsigned char _bytes29[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x20, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67 };
static const unsigned char _bytes31[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes30 = {   .f0 = (void *)_bytes31,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x33, 0x10, 0x00, 0x00, 0x1c, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes32[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x61, 0x78, 0x65, 0x64, 0x20, 0x66, 0x65, 0x6e, 0x63, 0x65 };
static const unsigned char _bytes33[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x61, 0x78, 0x65, 0x64, 0x20, 0x66, 0x65, 0x6e, 0x63, 0x65 };
static const unsigned char _bytes35[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes34 = {   .f0 = (void *)_bytes35,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xa2, 0x11, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
_Alignas(8) static const unsigned char _bytes36[] = { 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
static const unsigned char _bytes38[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x65, 0x6c, 0x6c, 0x2d, 0x31, 0x2e, 0x32, 0x31, 0x2e, 0x34, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6d, 0x70, 0x5f, 0x73, 0x74, 0x64, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes37 = {   .f0 = (void *)_bytes38,   .f1 = { 0x66, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xa1, 0x00, 0x00, 0x00, 0x36, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
_Alignas(8) static const unsigned char _bytes39[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
static const unsigned char _bytes41[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x65, 0x6c, 0x6c, 0x2d, 0x31, 0x2e, 0x32, 0x31, 0x2e, 0x34, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6d, 0x70, 0x5f, 0x73, 0x74, 0x64, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes40 = {   .f0 = (void *)_bytes41,   .f1 = { 0x66, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9b, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00 } };
#pragma pack(pop)

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_3pin3PinINtNtCsb5RsJavtctd_5alloc4sync3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtB1A_5alloc6SystemEEECs7XW3Yo0aMWr_9once_cell(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc4sync3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtB1k_5alloc6SystemEECs7XW3Yo0aMWr_9once_cell(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_4cell10UnsafeCellINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEEECs7XW3Yo0aMWr_9once_cell(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEECs7XW3Yo0aMWr_9once_cell(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_4cell4CellINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEEECs7XW3Yo0aMWr_9once_cell(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_4cell10UnsafeCellINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEEECs7XW3Yo0aMWr_9once_cell(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEECs7XW3Yo0aMWr_9once_cell(void * _arg0) {
  void * _t0;
  int64_t _t1;
  _Bool _t2;
  __rustc_isize _t3;
  _Bool _t4;

bb_0_start:
  _t0 = *(void * *)_arg0;
  _t1 = (int64_t)_t0;
  _t2 = (int64_t)_t1 == (int64_t)0LL;
  _t3 = (_t2) ? (0LL) : (1LL);
  _t4 = (__rustc_isize)_t3 == (__rustc_isize)0LL;
  if (_t4) goto bb_1_bb1; else goto bb_2_bb2;
bb_1_bb1:
  return;
bb_2_bb2:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadECs7XW3Yo0aMWr_9once_cell(_arg0);
  goto bb_1_bb1;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc4sync3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtB1k_5alloc6SystemEECs7XW3Yo0aMWr_9once_cell(void * _arg0) {
bb_0_start:
  _RNvXsE_NtCsb5RsJavtctd_5alloc4syncINtB5_3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtBM_5alloc6SystemENtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4dropCs7XW3Yo0aMWr_9once_cell(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp5GuardEBK_(void * _arg0) {
bb_0_start:
  _RNvXs3_NtCs7XW3Yo0aMWr_9once_cell3impNtB5_5GuardNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBK_(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_4cell4CellINtNtB4_6option6OptionNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadEEECs7XW3Yo0aMWr_9once_cell(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadECs7XW3Yo0aMWr_9once_cell(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_3pin3PinINtNtCsb5RsJavtctd_5alloc4sync3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtB1A_5alloc6SystemEEECs7XW3Yo0aMWr_9once_cell(_arg0);
  return;
}

static void * _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadONtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBT_(void * _arg0, uint8_t _arg1) {
  _Alignas(8) uint8_t _t5_storage[8];
  void *_t5 = (void *)_t5_storage;
  __rustc_isize _t6;
  void * _t7;
  void * _t8;
  _Bool _t9;
  int32_t _t10;
  __rustc_usize _t11;
  __rustc_usize _t12;
  __rustc_usize _t13;
  void * _t14;
  _Bool _t15;
  void * _t16;
  void * _t17;
  _Bool _t18;
  int32_t _t19;
  __rustc_usize _t20;
  __rustc_usize _t21;
  __rustc_usize _t22;
  void * _t23;
  _Bool _t24;
  void * _t25;
  void * _t26;

bb_0_start:
  _t6 = (__rustc_isize)_arg1;
  switch ((__rustc_usize)_t6) {
    case 0ULL: goto bb_2_bb6;
    case 1ULL: goto bb_3_bb3;
    case 2ULL: goto bb_4_bb5;
    case 3ULL: goto bb_5_bb2;
    case 4ULL: goto bb_6_bb4;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  abort();
bb_2_bb6:
  _t7 = atomic_load((_Atomic(void *) *)_arg0);
  *(void * *)_t5 = _t7;
  goto bb_7_bb7;
bb_3_bb3:
  _t8 = (void *)_bytes0;
  _t9 = (int64_t)_t8 != (int64_t)0;
  _t10 = 1LL & 63LL;
  _t11 = (__rustc_usize)(uint32_t)_t10;
  _t12 = (__rustc_usize)(40ULL) << (_t11);
  _t13 = _t12 | 1ULL;
  _t14 = (void *)_t13;
  _t15 = (int64_t)_t14 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t8, _t14, &_bytes2);
  abort();
bb_4_bb5:
  _t16 = atomic_load((_Atomic(void *) *)_arg0);
  *(void * *)_t5 = _t16;
  goto bb_7_bb7;
bb_5_bb2:
  _t17 = (void *)_bytes4;
  _t18 = (int64_t)_t17 != (int64_t)0;
  _t19 = 1LL & 63LL;
  _t20 = (__rustc_usize)(uint32_t)_t19;
  _t21 = (__rustc_usize)(49ULL) << (_t20);
  _t22 = _t21 | 1ULL;
  _t23 = (void *)_t22;
  _t24 = (int64_t)_t23 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t17, _t23, &_bytes6);
  abort();
bb_6_bb4:
  _t25 = atomic_load((_Atomic(void *) *)_arg0);
  *(void * *)_t5 = _t25;
  goto bb_7_bb7;
bb_7_bb7:
  _t26 = *(void * *)_t5;
  return _t26;
}

static uint8_t _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadhECs7XW3Yo0aMWr_9once_cell(void * _arg0, uint8_t _arg1) {
  _Alignas(1) uint8_t _t27_storage[1];
  void *_t27 = (void *)_t27_storage;
  __rustc_isize _t28;
  uint8_t _t29;
  void * _t30;
  _Bool _t31;
  int32_t _t32;
  __rustc_usize _t33;
  __rustc_usize _t34;
  __rustc_usize _t35;
  void * _t36;
  _Bool _t37;
  uint8_t _t38;
  void * _t39;
  _Bool _t40;
  int32_t _t41;
  __rustc_usize _t42;
  __rustc_usize _t43;
  __rustc_usize _t44;
  void * _t45;
  _Bool _t46;
  uint8_t _t47;
  uint8_t _t48;

bb_0_start:
  _t28 = (__rustc_isize)_arg1;
  switch ((__rustc_usize)_t28) {
    case 0ULL: goto bb_2_bb6;
    case 1ULL: goto bb_3_bb3;
    case 2ULL: goto bb_4_bb5;
    case 3ULL: goto bb_5_bb2;
    case 4ULL: goto bb_6_bb4;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  abort();
bb_2_bb6:
  _t29 = atomic_load((_Atomic(uint8_t) *)_arg0);
  *(uint8_t *)_t27 = _t29;
  goto bb_7_bb7;
bb_3_bb3:
  _t30 = (void *)_bytes8;
  _t31 = (int64_t)_t30 != (int64_t)0;
  _t32 = 1LL & 63LL;
  _t33 = (__rustc_usize)(uint32_t)_t32;
  _t34 = (__rustc_usize)(40ULL) << (_t33);
  _t35 = _t34 | 1ULL;
  _t36 = (void *)_t35;
  _t37 = (int64_t)_t36 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t30, _t36, &_bytes10);
  abort();
bb_4_bb5:
  _t38 = atomic_load((_Atomic(uint8_t) *)_arg0);
  *(uint8_t *)_t27 = _t38;
  goto bb_7_bb7;
bb_5_bb2:
  _t39 = (void *)_bytes12;
  _t40 = (int64_t)_t39 != (int64_t)0;
  _t41 = 1LL & 63LL;
  _t42 = (__rustc_usize)(uint32_t)_t41;
  _t43 = (__rustc_usize)(49ULL) << (_t42);
  _t44 = _t43 | 1ULL;
  _t45 = (void *)_t44;
  _t46 = (int64_t)_t45 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t39, _t45, &_bytes14);
  abort();
bb_6_bb4:
  _t47 = atomic_load((_Atomic(uint8_t) *)_arg0);
  *(uint8_t *)_t27 = _t47;
  goto bb_7_bb7;
bb_7_bb7:
  _t48 = *(uint8_t *)_t27;
  return _t48;
}

static void _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic12atomic_storehECs7XW3Yo0aMWr_9once_cell(void * _arg0, uint8_t _arg1, uint8_t _arg2) {
  __rustc_isize _t49;
  void * _t50;
  _Bool _t51;
  int32_t _t52;
  __rustc_usize _t53;
  __rustc_usize _t54;
  __rustc_usize _t55;
  void * _t56;
  _Bool _t57;
  void * _t58;
  _Bool _t59;
  int32_t _t60;
  __rustc_usize _t61;
  __rustc_usize _t62;
  __rustc_usize _t63;
  void * _t64;
  _Bool _t65;

bb_0_start:
  _t49 = (__rustc_isize)_arg2;
  switch ((__rustc_usize)_t49) {
    case 0ULL: goto bb_2_bb6;
    case 1ULL: goto bb_3_bb5;
    case 2ULL: goto bb_4_bb3;
    case 3ULL: goto bb_5_bb2;
    case 4ULL: goto bb_6_bb4;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  abort();
bb_2_bb6:
  atomic_store((_Atomic(uint8_t) *)_arg0, _arg1);
  goto bb_7_bb7;
bb_3_bb5:
  atomic_store((_Atomic(uint8_t) *)_arg0, _arg1);
  goto bb_7_bb7;
bb_4_bb3:
  _t50 = (void *)_bytes16;
  _t51 = (int64_t)_t50 != (int64_t)0;
  _t52 = 1LL & 63LL;
  _t53 = (__rustc_usize)(uint32_t)_t52;
  _t54 = (__rustc_usize)(42ULL) << (_t53);
  _t55 = _t54 | 1ULL;
  _t56 = (void *)_t55;
  _t57 = (int64_t)_t56 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t50, _t56, &_bytes18);
  abort();
bb_5_bb2:
  _t58 = (void *)_bytes20;
  _t59 = (int64_t)_t58 != (int64_t)0;
  _t60 = 1LL & 63LL;
  _t61 = (__rustc_usize)(uint32_t)_t60;
  _t62 = (__rustc_usize)(50ULL) << (_t61);
  _t63 = _t62 | 1ULL;
  _t64 = (void *)_t63;
  _t65 = (int64_t)_t64 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t58, _t64, &_bytes22);
  abort();
bb_6_bb4:
  atomic_store((_Atomic(uint8_t) *)_arg0, _arg1);
  goto bb_7_bb7;
bb_7_bb7:
  return;
}

static struct _S8 _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic23atomic_compare_exchangeONtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEB15_(void * _arg0, void * _arg1, void * _arg2, uint8_t _arg3, uint8_t _arg4) {
  _Alignas(8) uint8_t _t66_storage[16];
  void *_t66 = (void *)_t66_storage;
  _Alignas(8) uint8_t _t67_storage[16];
  void *_t67 = (void *)_t67_storage;
  __rustc_isize _t68;
  __rustc_isize _t69;
  void * _t70;
  _Bool _t71;
  int8_t _t72;
  void * _t73;
  void * _t74;
  _Bool _t75;
  int8_t _t76;
  void * _t77;
  void * _t78;
  _Bool _t79;
  int8_t _t80;
  void * _t81;
  __rustc_isize _t82;
  void * _t83;
  _Bool _t84;
  int8_t _t85;
  void * _t86;
  void * _t87;
  _Bool _t88;
  int8_t _t89;
  void * _t90;
  void * _t91;
  _Bool _t92;
  int8_t _t93;
  void * _t94;
  __rustc_isize _t95;
  void * _t96;
  _Bool _t97;
  int8_t _t98;
  void * _t99;
  void * _t100;
  _Bool _t101;
  int8_t _t102;
  void * _t103;
  void * _t104;
  _Bool _t105;
  int8_t _t106;
  void * _t107;
  __rustc_isize _t108;
  void * _t109;
  _Bool _t110;
  int8_t _t111;
  void * _t112;
  void * _t113;
  _Bool _t114;
  int8_t _t115;
  void * _t116;
  void * _t117;
  _Bool _t118;
  int8_t _t119;
  void * _t120;
  __rustc_isize _t121;
  void * _t122;
  _Bool _t123;
  int8_t _t124;
  void * _t125;
  void * _t126;
  _Bool _t127;
  int8_t _t128;
  void * _t129;
  void * _t130;
  _Bool _t131;
  int8_t _t132;
  void * _t133;
  void * _t134;
  void * _t135;
  _Bool _t136;
  void * _t137;
  void * _t138;
  uint64_t _t139;
  void * _t140;
  void * _t141;
  struct _S8 _t142;
  struct _S8 _t143;
  __rustc_isize _t144;
  void * _t145;
  _Bool _t146;
  int32_t _t147;
  __rustc_usize _t148;
  __rustc_usize _t149;
  __rustc_usize _t150;
  void * _t151;
  _Bool _t152;
  void * _t153;
  _Bool _t154;
  int32_t _t155;
  __rustc_usize _t156;
  __rustc_usize _t157;
  __rustc_usize _t158;
  void * _t159;
  _Bool _t160;

bb_0_start:
  _t68 = (__rustc_isize)_arg3;
  switch ((__rustc_usize)_t68) {
    case 0ULL: goto bb_2_bb2;
    case 1ULL: goto bb_3_bb4;
    case 2ULL: goto bb_4_bb3;
    case 3ULL: goto bb_5_bb5;
    case 4ULL: goto bb_6_bb6;
    default: goto bb_1_bb7;
  }
bb_1_bb7:
  abort();
bb_2_bb2:
  _t69 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t69) {
    case 0ULL: goto bb_8_bb24;
    case 2ULL: goto bb_9_bb23;
    case 4ULL: goto bb_10_bb22;
    default: goto bb_7_bb1;
  }
bb_3_bb4:
  _t82 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t82) {
    case 0ULL: goto bb_12_bb18;
    case 2ULL: goto bb_13_bb17;
    case 4ULL: goto bb_14_bb16;
    default: goto bb_7_bb1;
  }
bb_4_bb3:
  _t95 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t95) {
    case 0ULL: goto bb_15_bb21;
    case 2ULL: goto bb_16_bb20;
    case 4ULL: goto bb_17_bb19;
    default: goto bb_7_bb1;
  }
bb_5_bb5:
  _t108 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t108) {
    case 0ULL: goto bb_18_bb15;
    case 2ULL: goto bb_19_bb14;
    case 4ULL: goto bb_20_bb13;
    default: goto bb_7_bb1;
  }
bb_6_bb6:
  _t121 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t121) {
    case 0ULL: goto bb_21_bb12;
    case 2ULL: goto bb_22_bb11;
    case 4ULL: goto bb_23_bb10;
    default: goto bb_7_bb1;
  }
bb_7_bb1:
  _t144 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t144) {
    case 1ULL: goto bb_27_bb8;
    case 3ULL: goto bb_28_bb9;
    default: goto bb_1_bb7;
  }
bb_8_bb24:
  _t70 = _arg1;
  _t71 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t70, _arg2);
  _t72 = (int8_t)(_t71);
  *(void * *)_t67 = _t70;
  _t73 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t73 = _t72;
  goto bb_11_bb25;
bb_9_bb23:
  _t74 = _arg1;
  _t75 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t74, _arg2);
  _t76 = (int8_t)(_t75);
  *(void * *)_t67 = _t74;
  _t77 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t77 = _t76;
  goto bb_11_bb25;
bb_10_bb22:
  _t78 = _arg1;
  _t79 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t78, _arg2);
  _t80 = (int8_t)(_t79);
  *(void * *)_t67 = _t78;
  _t81 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t81 = _t80;
  goto bb_11_bb25;
bb_11_bb25:
  _t134 = *(void * *)_t67;
  _t135 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t136 = *(_Bool *)_t135;
  if (_t136) goto bb_25_bb26; else goto bb_24_bb27;
bb_12_bb18:
  _t83 = _arg1;
  _t84 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t83, _arg2);
  _t85 = (int8_t)(_t84);
  *(void * *)_t67 = _t83;
  _t86 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t86 = _t85;
  goto bb_11_bb25;
bb_13_bb17:
  _t87 = _arg1;
  _t88 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t87, _arg2);
  _t89 = (int8_t)(_t88);
  *(void * *)_t67 = _t87;
  _t90 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t90 = _t89;
  goto bb_11_bb25;
bb_14_bb16:
  _t91 = _arg1;
  _t92 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t91, _arg2);
  _t93 = (int8_t)(_t92);
  *(void * *)_t67 = _t91;
  _t94 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t94 = _t93;
  goto bb_11_bb25;
bb_15_bb21:
  _t96 = _arg1;
  _t97 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t96, _arg2);
  _t98 = (int8_t)(_t97);
  *(void * *)_t67 = _t96;
  _t99 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t99 = _t98;
  goto bb_11_bb25;
bb_16_bb20:
  _t100 = _arg1;
  _t101 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t100, _arg2);
  _t102 = (int8_t)(_t101);
  *(void * *)_t67 = _t100;
  _t103 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t103 = _t102;
  goto bb_11_bb25;
bb_17_bb19:
  _t104 = _arg1;
  _t105 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t104, _arg2);
  _t106 = (int8_t)(_t105);
  *(void * *)_t67 = _t104;
  _t107 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t107 = _t106;
  goto bb_11_bb25;
bb_18_bb15:
  _t109 = _arg1;
  _t110 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t109, _arg2);
  _t111 = (int8_t)(_t110);
  *(void * *)_t67 = _t109;
  _t112 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t112 = _t111;
  goto bb_11_bb25;
bb_19_bb14:
  _t113 = _arg1;
  _t114 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t113, _arg2);
  _t115 = (int8_t)(_t114);
  *(void * *)_t67 = _t113;
  _t116 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t116 = _t115;
  goto bb_11_bb25;
bb_20_bb13:
  _t117 = _arg1;
  _t118 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t117, _arg2);
  _t119 = (int8_t)(_t118);
  *(void * *)_t67 = _t117;
  _t120 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t120 = _t119;
  goto bb_11_bb25;
bb_21_bb12:
  _t122 = _arg1;
  _t123 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t122, _arg2);
  _t124 = (int8_t)(_t123);
  *(void * *)_t67 = _t122;
  _t125 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t125 = _t124;
  goto bb_11_bb25;
bb_22_bb11:
  _t126 = _arg1;
  _t127 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t126, _arg2);
  _t128 = (int8_t)(_t127);
  *(void * *)_t67 = _t126;
  _t129 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t129 = _t128;
  goto bb_11_bb25;
bb_23_bb10:
  _t130 = _arg1;
  _t131 = atomic_compare_exchange_strong((_Atomic(void *) *)_arg0, &_t130, _arg2);
  _t132 = (int8_t)(_t131);
  *(void * *)_t67 = _t130;
  _t133 = (void *)((__rustc_usize)_t67 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t133 = _t132;
  goto bb_11_bb25;
bb_24_bb27:
  _t137 = (void *)((__rustc_usize)_t66 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t137 = _t134;
  *(uint64_t *)_t66 = 1ULL;
  goto bb_26_bb28;
bb_25_bb26:
  _t138 = (void *)((__rustc_usize)_t66 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t138 = _t134;
  *(uint64_t *)_t66 = 0ULL;
  goto bb_26_bb28;
bb_26_bb28:
  _t139 = *(uint64_t *)_t66;
  _t140 = (void *)((__rustc_usize)_t66 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t141 = *(void * *)_t140;
  memset(&_t142, 0, sizeof(_t142));
  _t142.f0 = _t139;
  _t143 = _t142;
  _t143.f1 = _t141;
  return _t143;
bb_27_bb8:
  _t145 = (void *)_bytes24;
  _t146 = (int64_t)_t145 != (int64_t)0;
  _t147 = 1LL & 63LL;
  _t148 = (__rustc_usize)(uint32_t)_t147;
  _t149 = (__rustc_usize)(52ULL) << (_t148);
  _t150 = _t149 | 1ULL;
  _t151 = (void *)_t150;
  _t152 = (int64_t)_t151 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t145, _t151, &_bytes26);
  abort();
bb_28_bb9:
  _t153 = (void *)_bytes28;
  _t154 = (int64_t)_t153 != (int64_t)0;
  _t155 = 1LL & 63LL;
  _t156 = (__rustc_usize)(uint32_t)_t155;
  _t157 = (__rustc_usize)(61ULL) << (_t156);
  _t158 = _t157 | 1ULL;
  _t159 = (void *)_t158;
  _t160 = (int64_t)_t159 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t153, _t159, &_bytes30);
  abort();
}

#pragma weak _RNvNtCs7XW3Yo0aMWr_9once_cell3imp18initialize_or_wait
void _RNvNtCs7XW3Yo0aMWr_9once_cell3imp18initialize_or_wait(void * _arg0, void * _arg1, void * _arg2) {
  _Alignas(8) uint8_t _t161_storage[16];
  void *_t161 = (void *)_t161_storage;
  void * _t162;
  _Alignas(8) uint8_t _t163_storage[16];
  void *_t163 = (void *)_t163_storage;
  _Alignas(8) uint8_t _t164_storage[16];
  void *_t164 = (void *)_t164_storage;
  _Alignas(8) uint8_t _t165_storage[8];
  void *_t165 = (void *)_t165_storage;
  void * _t166;
  void * _t167;
  void * _t168;
  int64_t _t169;
  uint64_t _t170;
  void * _t171;
  void * _t172;
  void * _t173;
  int64_t _t174;
  _Bool _t175;
  __rustc_isize _t176;
  _Bool _t177;
  void * _t178;
  void * _t179;
  int64_t _t180;
  uint64_t _t181;
  uint64_t _t182;
  __rustc_isize _t183;
  __rustc_isize _t184;
  __rustc_isize _t185;
  void * _t186;
  void * _t187;
  _Alignas(8) uint8_t _t188_storage[8];
  void *_t188 = (void *)_t188_storage;
  void * _t189;
  void * _t190;
  void * _t191;
  void * _t192;
  struct _S8 _t193;
  uint64_t _t194;
  void * _t195;
  void * _t196;
  __rustc_isize _t197;
  _Bool _t198;
  void * _t199;
  void * _t200;
  void * _t201;
  void * _t202;
  void * _t203;
  void * _t204;
  void * _t205;
  _Bool (*_t206)(void *);
  _Alignas(8) uint8_t _t207_storage[16];
  void *_t207 = (void *)_t207_storage;
  void * _t208;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  _Bool _t209;
  _Bool _t210;
  void * _t211;
  void * _t212;
  void * _t213;
  int32_t _t214;
  void * _t215;
  void * _t216;
  void * _t217;

bb_0_start:
  *(void * *)_t161 = _arg1;
  _t162 = (void *)((__rustc_usize)_t161 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t162 = _arg2;
  _t166 = (void *)_arg0;
  _t167 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadONtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBT_(_t166, 2ULL);
  *(void * *)_t165 = _t167;
  goto bb_1_bb1;
bb_1_bb1:
  _t168 = *(void * *)_t165;
  _t169 = (int64_t)_t168;
  _t170 = _t169 & 3ULL;
  switch (_t170) {
    case 2ULL: goto bb_2_bb11;
    case 0ULL: goto bb_3_bb2;
    case 1ULL: goto bb_4_bb3;
    default: goto bb_1_bb1;
  }
bb_2_bb11:
  return;
bb_3_bb2:
  _t171 = *(void * *)_t161;
  _t172 = (void *)((__rustc_usize)_t161 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t173 = *(void * *)_t172;
  _t174 = (int64_t)_t171;
  _t175 = (int64_t)_t174 == (int64_t)0LL;
  _t176 = (_t175) ? (0LL) : (1LL);
  _t177 = (_Bool)_t176;
  if (_t177) goto bb_5_bb4; else goto bb_4_bb3;
bb_4_bb3:
  _t215 = *(void * *)_t165;
  _RNvNtCs7XW3Yo0aMWr_9once_cell3imp4wait(_arg0, _t215);
  _t216 = (void *)_arg0;
  _t217 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadONtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBT_(_t216, 2ULL);
  *(void * *)_t165 = _t217;
  goto bb_1_bb1;
bb_5_bb4:
  _t178 = *(void * *)_t165;
  _t179 = *(void * *)_t165;
  _t180 = (int64_t)_t179;
  _t181 = _t180 & 18446744073709551612ULL;
  _t182 = _t181 | 1ULL;
  _t183 = (__rustc_isize)_t180;
  _t184 = (__rustc_isize)_t182;
  _t185 = _t184 - _t183;
  _t186 = *(void * *)_t165;
  _t187 = (void *)_t186;
  _t189 = (void *)((__rustc_usize)_t187 + (__rustc_isize)(_t185) * (__rustc_isize)sizeof(uint8_t));
  *(void * *)_t188 = _t189;
  _t190 = *(void * *)_t188;
  _t191 = (void *)_t190;
  _t192 = (void *)_arg0;
  _t193 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic23atomic_compare_exchangeONtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEB15_(_t192, _t178, _t191, 2ULL, 2ULL);
  *(struct _S8 *)_t163 = _t193;
  _t194 = *(uint64_t *)_t163;
  _t195 = (void *)((__rustc_usize)_t163 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t196 = *(void * *)_t195;
  _t197 = (__rustc_isize)_t194;
  _t198 = (_Bool)_t197;
  if (_t198) goto bb_6_bb5; else goto bb_7_bb6;
bb_6_bb5:
  _t199 = (void *)((__rustc_usize)_t163 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t200 = *(void * *)_t199;
  *(void * *)_t165 = _t200;
  goto bb_1_bb1;
bb_7_bb6:
  *(void * *)_t164 = _arg0;
  _t201 = (void *)((__rustc_usize)_t164 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t201 = (void *)(__rustc_usize)0ULL;
  _t202 = *(void * *)_t161;
  _t203 = (void *)((__rustc_usize)_t161 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t204 = *(void * *)_t203;
  _t205 = (void *)((__rustc_usize)_t204 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  _t206 = *(_Bool (**)(void *))_t205;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_9_cleanup; }
  _t209 = ((_Bool (*)(void *))_t206)(_t202);
  _t210 = (_Bool)(_t209);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_10_bb17;
bb_8_bb12:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_13_terminate; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp5GuardEBK_(_t164);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_14_bb13;
bb_9_cleanup:
  *(void * *)_t207 = __exn_ptr;
  _t208 = (void *)((__rustc_usize)_t207 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t208 = 0LL;
  goto bb_8_bb12;
bb_10_bb17:
  if (_t210) goto bb_12_bb7; else goto bb_11_bb8;
bb_11_bb8:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp5GuardEBK_(_t164);
  goto bb_2_bb11;
bb_12_bb7:
  _t211 = (void *)((__rustc_usize)_t164 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t211 = (void *)(__rustc_usize)2ULL;
  goto bb_11_bb8;
bb_13_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_14_bb13:
  _t212 = *(void * *)_t207;
  _t213 = (void *)((__rustc_usize)_t207 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t214 = *(int32_t *)_t213;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t212; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
bb_15_bb19:
  abort();
}

static void _RNvNtCs7XW3Yo0aMWr_9once_cell3imp4wait(void * _arg0, void * _arg1) {
  _Alignas(8) uint8_t _t218_storage[8];
  void *_t218 = (void *)_t218_storage;
  _Alignas(8) uint8_t _t219_storage[24];
  void *_t219 = (void *)_t219_storage;
  _Alignas(1) uint8_t _t220_storage[1];
  void *_t220 = (void *)_t220_storage;
  _Alignas(8) uint8_t _t221_storage[16];
  void *_t221 = (void *)_t221_storage;
  void * _t222;
  int64_t _t223;
  uint64_t _t224;
  void * _t225;
  _Bool _t226;
  void * _t227;
  void * _t228;
  void * _t229;
  int64_t _t230;
  uint64_t _t231;
  __rustc_isize _t232;
  __rustc_isize _t233;
  __rustc_isize _t234;
  void * _t235;
  _Alignas(8) uint8_t _t236_storage[8];
  void *_t236 = (void *)_t236_storage;
  void * _t237;
  void * _t238;
  void * _t239;
  void * _t240;
  void * _t241;
  void * _t242;
  int64_t _t243;
  uint64_t _t244;
  __rustc_isize _t245;
  __rustc_isize _t246;
  __rustc_isize _t247;
  void * _t248;
  _Alignas(8) uint8_t _t249_storage[8];
  void *_t249 = (void *)_t249_storage;
  void * _t250;
  void * _t251;
  void * _t252;
  void * _t253;
  void * _t254;
  _Alignas(8) uint8_t _t255_storage[16];
  void *_t255 = (void *)_t255_storage;
  void * _t256;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  struct _S8 _t257;
  uint64_t _t258;
  void * _t259;
  void * _t260;
  __rustc_isize _t261;
  _Bool _t262;
  void * _t263;
  void * _t264;
  void * _t265;
  int64_t _t266;
  uint64_t _t267;
  _Bool _t268;
  void * _t269;
  void * _t270;
  uint8_t _t271;
  _Bool _t272;
  void * _t273;
  void * _t274;
  int32_t _t275;

bb_0_start:
  *(void * *)_t218 = _arg1;
  _t222 = *(void * *)_t218;
  _t223 = (int64_t)_t222;
  _t224 = _t223 & 3ULL;
  goto bb_1_bb1;
bb_1_bb1:
  _t225 = _RNvNtNtCsMibNUK8RNN_3std6thread7current7current();
  _t226 = (int64_t)_t225 != (int64_t)0;
  _t227 = (void *)_t225;
  _t228 = (void *)_t227;
  *(uint8_t *)_t220 = 0ULL;
  _t229 = *(void * *)_t218;
  _t230 = (int64_t)_t229;
  _t231 = _t230 & 18446744073709551612ULL;
  _t232 = (__rustc_isize)_t230;
  _t233 = (__rustc_isize)_t231;
  _t234 = _t233 - _t232;
  _t235 = (void *)_t229;
  _t237 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(_t234) * (__rustc_isize)sizeof(uint8_t));
  *(void * *)_t236 = _t237;
  _t238 = *(void * *)_t236;
  _t239 = (void *)_t238;
  *(void * *)_t219 = _t228;
  _t240 = (void *)((__rustc_usize)_t219 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  memcpy(_t240, _t220, 1ULL);
  _t241 = (void *)((__rustc_usize)_t219 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t241 = _t239;
  _t242 = (void *)_t219;
  _t243 = (int64_t)_t219;
  _t244 = _t243 | _t224;
  _t245 = (__rustc_isize)_t243;
  _t246 = (__rustc_isize)_t244;
  _t247 = _t246 - _t245;
  _t248 = (void *)_t219;
  _t250 = (void *)((__rustc_usize)_t248 + (__rustc_isize)(_t247) * (__rustc_isize)sizeof(uint8_t));
  *(void * *)_t249 = _t250;
  _t251 = *(void * *)_t249;
  _t252 = (void *)_t251;
  _t253 = (void *)_arg0;
  _t254 = *(void * *)_t218;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_3_cleanup; }
  _t257 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic23atomic_compare_exchangeONtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEB15_(_t253, _t254, _t252, 1ULL, 0ULL);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_4_bb18;
bb_2_bb14:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_15_terminate; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBK_(_t219);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_16_bb15;
bb_3_cleanup:
  *(void * *)_t255 = __exn_ptr;
  _t256 = (void *)((__rustc_usize)_t255 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t256 = 0LL;
  goto bb_2_bb14;
bb_4_bb18:
  *(struct _S8 *)_t221 = _t257;
  _t258 = *(uint64_t *)_t221;
  _t259 = (void *)((__rustc_usize)_t221 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t260 = *(void * *)_t259;
  _t261 = (__rustc_isize)_t258;
  _t262 = (_Bool)_t261;
  if (_t262) goto bb_5_bb3; else goto bb_6_bb6;
bb_5_bb3:
  _t263 = (void *)((__rustc_usize)_t221 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t264 = *(void * *)_t263;
  *(void * *)_t218 = _t264;
  _t265 = *(void * *)_t218;
  _t266 = (int64_t)_t265;
  _t267 = _t266 & 3ULL;
  _t268 = (int64_t)_t267 != (int64_t)_t224;
  if (_t268) goto bb_8_bb4; else goto bb_7_bb5;
bb_6_bb6:
  _t269 = (void *)((__rustc_usize)_t219 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t270 = (void *)_t269;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_3_cleanup; }
  _t271 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadhECs7XW3Yo0aMWr_9once_cell(_t270, 2ULL);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_10_bb19;
bb_7_bb5:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBK_(_t219);
  goto bb_1_bb1;
bb_8_bb4:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBK_(_t219);
  goto bb_9_bb13;
bb_9_bb13:
  return;
bb_10_bb19:
  _t272 = (int8_t)_t271 == (int8_t)0ULL;
  if (_t272) goto bb_11_bb8; else goto bb_12_bb7;
bb_11_bb8:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_3_cleanup; }
  _RNvNtNtCsMibNUK8RNN_3std6thread9functions4park();
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_13_bb9;
bb_12_bb7:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs7XW3Yo0aMWr_9once_cell3imp6WaiterEBK_(_t219);
  goto bb_9_bb13;
bb_13_bb9:
  goto bb_6_bb6;
bb_14_bb20:
  abort();
bb_15_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_16_bb15:
  _t273 = *(void * *)_t255;
  _t274 = (void *)((__rustc_usize)_t255 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t275 = *(int32_t *)_t274;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t273; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
}

static void _RNvNtNtCs41fFVwHnQdq_4core4sync6atomic5fence(uint8_t _arg0) {
  __rustc_isize _t276;
  void * _t277;
  _Bool _t278;
  int32_t _t279;
  __rustc_usize _t280;
  __rustc_usize _t281;
  __rustc_usize _t282;
  void * _t283;
  _Bool _t284;

bb_0_start:
  _t276 = (__rustc_isize)_arg0;
  switch ((__rustc_usize)_t276) {
    case 0ULL: goto bb_2_bb2;
    case 1ULL: goto bb_3_bb5;
    case 2ULL: goto bb_4_bb6;
    case 3ULL: goto bb_5_bb4;
    case 4ULL: goto bb_6_bb3;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  abort();
bb_2_bb2:
  _t277 = (void *)_bytes32;
  _t278 = (int64_t)_t277 != (int64_t)0;
  _t279 = 1LL & 63LL;
  _t280 = (__rustc_usize)(uint32_t)_t279;
  _t281 = (__rustc_usize)(41ULL) << (_t280);
  _t282 = _t281 | 1ULL;
  _t283 = (void *)_t282;
  _t284 = (int64_t)_t283 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t277, _t283, &_bytes34);
  abort();
bb_3_bb5:
  atomic_thread_fence(memory_order_release);
  goto bb_7_bb7;
bb_4_bb6:
  atomic_thread_fence(memory_order_acquire);
  goto bb_7_bb7;
bb_5_bb4:
  atomic_thread_fence(memory_order_acq_rel);
  goto bb_7_bb7;
bb_6_bb3:
  atomic_thread_fence(memory_order_seq_cst);
  goto bb_7_bb7;
bb_7_bb7:
  return;
}

#pragma weak _RNvXs3_NtCs7XW3Yo0aMWr_9once_cell3impNtB5_5GuardNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop
void _RNvXs3_NtCs7XW3Yo0aMWr_9once_cell3impNtB5_5GuardNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void * _arg0) {
  _Alignas(8) uint8_t _t285_storage[8];
  void *_t285 = (void *)_t285_storage;
  _Alignas(8) uint8_t _t286_storage[8];
  void *_t286 = (void *)_t286_storage;
  _Alignas(8) uint8_t _t287_storage[8];
  void *_t287 = (void *)_t287_storage;
  _Alignas(8) uint8_t _t288_storage[8];
  void *_t288 = (void *)_t288_storage;
  void * _t289;
  void * _t290;
  void * _t291;
  void * _t292;
  _Alignas(8) uint8_t _t293_storage[8];
  void *_t293 = (void *)_t293_storage;
  void * _t294;
  void * _t295;
  int64_t _t296;
  uint64_t _t297;
  __rustc_usize _t298;
  _Bool _t299;
  int64_t _t300;
  uint64_t _t301;
  __rustc_isize _t302;
  __rustc_isize _t303;
  __rustc_isize _t304;
  void * _t305;
  _Alignas(8) uint8_t _t306_storage[8];
  void *_t306 = (void *)_t306_storage;
  void * _t307;
  void * _t308;
  void * _t309;
  void * _t310;
  int64_t _t311;
  _Bool _t312;
  void * _t313;
  void * _t314;
  void * _t315;
  void * _t316;
  void * _t317;
  void * _t318;
  void * _t319;
  int64_t _t320;
  _Bool _t321;
  __rustc_isize _t322;
  _Bool _t323;
  void * _t324;
  void * _t325;
  void * _t326;
  void * _t327;
  _Alignas(8) uint8_t _t328_storage[16];
  void *_t328 = (void *)_t328_storage;
  void * _t329;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t330;
  _Bool _t331;
  void * _t332;
  void * _t333;
  void * _t334;
  void * _t335;
  void * _t336;
  int32_t _t337;
  void * _t338;
  void * _t339;
  void * _t340;

bb_0_start:
  _t289 = *(void * *)_arg0;
  _t290 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t291 = *(void * *)_t290;
  _t292 = (void *)_t289;
  _t294 = atomic_exchange((_Atomic(void *) *)_t292, _t291);
  *(void * *)_t293 = _t294;
  _t295 = *(void * *)_t293;
  _t296 = (int64_t)_t295;
  _t297 = _t296 & 3ULL;
  *(uint64_t *)_t285 = _t297;
  _t298 = *(__rustc_usize *)_t285;
  _t299 = (__rustc_isize)_t298 == (__rustc_isize)1ULL;
  if (_t299) goto bb_1_bb1; else goto bb_2_bb2;
bb_1_bb1:
  _t300 = (int64_t)_t295;
  _t301 = _t300 & 18446744073709551612ULL;
  _t302 = (__rustc_isize)_t300;
  _t303 = (__rustc_isize)_t301;
  _t304 = _t303 - _t302;
  _t305 = (void *)_t295;
  _t307 = (void *)((__rustc_usize)_t305 + (__rustc_isize)(_t304) * (__rustc_isize)sizeof(uint8_t));
  *(void * *)_t306 = _t307;
  _t308 = *(void * *)_t306;
  _t309 = (void *)_t308;
  *(void * *)_t286 = _t309;
  goto bb_3_bb3;
bb_2_bb2:
  _t338 = *(void * *)_bytes39;
  _t339 = (void *)((__rustc_usize)_bytes39 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t340 = *(void * *)_t339;
  _RINvNtCs41fFVwHnQdq_4core9panicking13assert_failedjjEB4_(0ULL, _t285, _bytes36, _t338, _t340, &_bytes40);
  abort();
bb_3_bb3:
  _t310 = *(void * *)_t286;
  _t311 = (int64_t)_t310;
  _t312 = (__rustc_isize)_t311 == (__rustc_isize)0ULL;
  if (_t312) goto bb_4_bb4; else goto bb_5_bb5;
bb_4_bb4:
  return;
bb_5_bb5:
  _t313 = *(void * *)_t286;
  _t314 = (void *)((__rustc_usize)_t313 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t315 = *(void * *)_t314;
  _t316 = *(void * *)_t286;
  _t317 = (void *)_t316;
  _t318 = *(void * *)_t317;
  *(void * *)_t288 = _t318;
  *(void * *)_t317 = (void *)(__rustc_usize)0ULL;
  _t319 = *(void * *)_t288;
  _t320 = (int64_t)_t319;
  _t321 = (int64_t)_t320 == (int64_t)0LL;
  _t322 = (_t321) ? (0LL) : (1LL);
  _t323 = (_Bool)_t322;
  if (_t323) goto bb_6_bb13; else goto bb_7_bb12;
bb_6_bb13:
  _t324 = *(void * *)_t288;
  *(void * *)_t287 = _t324;
  _t325 = *(void * *)_t286;
  _t326 = (void *)((__rustc_usize)_t325 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t327 = (void *)_t326;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_9_cleanup; }
  _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic12atomic_storehECs7XW3Yo0aMWr_9once_cell(_t327, 1ULL, 1ULL);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_10_bb14;
bb_7_bb12:
  _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(&_bytes37);
  abort();
bb_8_bb7:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_12_terminate; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadECs7XW3Yo0aMWr_9once_cell(_t287);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_13_bb8;
bb_9_cleanup:
  *(void * *)_t328 = __exn_ptr;
  _t329 = (void *)((__rustc_usize)_t328 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t329 = 0LL;
  goto bb_8_bb7;
bb_10_bb14:
  *(void * *)_t286 = _t315;
  _t330 = *(void * *)_t287;
  _t331 = (int64_t)_t330 != (int64_t)0;
  _t332 = (void *)_t330;
  _t333 = (void *)((__rustc_usize)_t332 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t334 = (void *)((__rustc_usize)_t333 + (__rustc_isize)(24ULL) * (__rustc_isize)sizeof(int8_t));
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_9_cleanup; }
  _RNvMs0_NtNtNtNtCsMibNUK8RNN_3std3sys4sync14thread_parking6darwinNtB5_6Parker6unpark(_t334);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_11_bb15;
bb_11_bb15:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtCsMibNUK8RNN_3std6thread6thread6ThreadECs7XW3Yo0aMWr_9once_cell(_t287);
  goto bb_3_bb3;
bb_12_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_13_bb8:
  _t335 = *(void * *)_t328;
  _t336 = (void *)((__rustc_usize)_t328 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t337 = *(int32_t *)_t336;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t335; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
bb_14_bb10:
  abort();
}

static void _RNvXsE_NtCsb5RsJavtctd_5alloc4syncINtB5_3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtBM_5alloc6SystemENtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4dropCs7XW3Yo0aMWr_9once_cell(void * _arg0) {
  void * _t341;
  _Bool _t342;
  void * _t343;
  void * _t344;
  _Alignas(8) uint8_t _t345_storage[8];
  void *_t345 = (void *)_t345_storage;
  __rustc_usize _t346;
  __rustc_usize _t347;
  _Bool _t348;

bb_0_start:
  _t341 = *(void * *)_arg0;
  _t342 = (int64_t)_t341 != (int64_t)0;
  _t343 = (void *)_t341;
  _t344 = (void *)_t343;
  _t346 = atomic_fetch_sub((_Atomic(__rustc_usize) *)_t344, 1ULL);
  *(__rustc_usize *)_t345 = _t346;
  _t347 = *(__rustc_usize *)_t345;
  _t348 = (__rustc_isize)_t347 == (__rustc_isize)1ULL;
  if (_t348) goto bb_1_bb2; else goto bb_2_bb1;
bb_1_bb2:
  _RNvNtNtCs41fFVwHnQdq_4core4sync6atomic5fence(2ULL);
  _RNvMsn_NtCsb5RsJavtctd_5alloc4syncINtB5_3ArcNtNtNtCsMibNUK8RNN_3std6thread6thread5InnerNtNtBM_5alloc6SystemE9drop_slowBM_(_arg0);
  goto bb_3_bb4;
bb_2_bb1:
  goto bb_3_bb4;
bb_3_bb4:
  return;
}

