/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

struct _S6 {
  int8_t f0[24];
};
struct _S23 {
  int8_t f0[152];
};
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_6option6OptionNtNtCsMibNUK8RNN_3std2fs4FileEECscAc5aJE8qBJ_9same_file(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtCscAc5aJE8qBJ_9same_file6HandleEBI_(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCsMibNUK8RNN_3std2fs4FileECscAc5aJE8qBJ_9same_file(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCscAc5aJE8qBJ_9same_file4unix6HandleEBK_(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std2os2fd5owned7OwnedFdECscAc5aJE8qBJ_9same_file(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std3sys2fd4unix8FileDescECscAc5aJE8qBJ_9same_file(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std3sys2fs4unix4FileECscAc5aJE8qBJ_9same_file(void *);
void * _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle11as_file_mut(void *);
struct _S6 _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle5stdin(void);
struct _S6 _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle6stderr(void);
struct _S6 _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle6stdout(void);
void * _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle7as_file(void *);
struct _S6 _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle9from_file(int32_t);
static void * _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle11as_file_mut(void *);
static struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle5stdin(void);
static struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle6stderr(void);
static struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle6stdout(void);
static void * _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle7as_file(void *);
static struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle8from_std(int32_t);
struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle9from_file(int32_t);
static void _RNvNtNtNtCsMibNUK8RNN_3std3sys2fs4unix23debug_assert_fd_is_open(int32_t);
void _RNvXNtCscAc5aJE8qBJ_9same_file4unixNtB2_6HandleNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void *);
int32_t _RNvXs1_NtCscAc5aJE8qBJ_9same_file4unixNtB7_6HandleNtNtNtNtCsMibNUK8RNN_3std2os2fd3raw7AsRawFd9as_raw_fd(void *);
int32_t _RNvXs2_NtCscAc5aJE8qBJ_9same_file4unixNtB7_6HandleNtNtNtNtCsMibNUK8RNN_3std2os2fd3raw9IntoRawFd11into_raw_fd(void *);
static void _RNvXs5_NtNtNtCsMibNUK8RNN_3std2os2fd5ownedNtB5_7OwnedFdNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void *);
void _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup(void);
void _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(void *);
struct _S23 _RNvMs2_NtCsMibNUK8RNN_3std2fsNtB5_4File8metadata(void *);
int32_t close(int32_t);

static const unsigned char _bytes1[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x73, 0x61, 0x6d, 0x65, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x31, 0x2e, 0x30, 0x2e, 0x36, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x6e, 0x69, 0x78, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes0 = {   .f0 = (void *)_bytes1,   .f1 = { 0x62, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x66, 0x00, 0x00, 0x00, 0x23, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes3[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x73, 0x61, 0x6d, 0x65, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x31, 0x2e, 0x30, 0x2e, 0x36, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x6e, 0x69, 0x78, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes2 = {   .f0 = (void *)_bytes3,   .f1 = { 0x62, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x23, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes5[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x73, 0x61, 0x6d, 0x65, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x31, 0x2e, 0x30, 0x2e, 0x36, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x6e, 0x69, 0x78, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes4 = {   .f0 = (void *)_bytes5,   .f1 = { 0x62, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes7[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x73, 0x61, 0x6d, 0x65, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x31, 0x2e, 0x30, 0x2e, 0x36, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x6e, 0x69, 0x78, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes6 = {   .f0 = (void *)_bytes7,   .f1 = { 0x62, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x25, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes9[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x73, 0x61, 0x6d, 0x65, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x31, 0x2e, 0x30, 0x2e, 0x36, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x6e, 0x69, 0x78, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes8 = {   .f0 = (void *)_bytes9,   .f1 = { 0x62, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x00, 0x00, 0x00, 0x1c, 0x00, 0x00, 0x00 } };
#pragma pack(pop)

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_6option6OptionNtNtCsMibNUK8RNN_3std2fs4FileEECscAc5aJE8qBJ_9same_file(void * _arg0) {
  int32_t _t0;
  _Bool _t1;
  __rustc_isize _t2;
  _Bool _t3;

bb_0_start:
  _t0 = *(int32_t *)_arg0;
  _t1 = (int32_t)_t0 == (int32_t)-1LL;
  _t2 = (_t1) ? (0LL) : (1LL);
  _t3 = (__rustc_isize)_t2 == (__rustc_isize)0LL;
  if (_t3) goto bb_1_bb1; else goto bb_2_bb2;
bb_1_bb1:
  return;
bb_2_bb2:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCsMibNUK8RNN_3std2fs4FileECscAc5aJE8qBJ_9same_file(_arg0);
  goto bb_1_bb1;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtCscAc5aJE8qBJ_9same_file6HandleEBI_(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCscAc5aJE8qBJ_9same_file4unix6HandleEBK_(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCsMibNUK8RNN_3std2fs4FileECscAc5aJE8qBJ_9same_file(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std3sys2fs4unix4FileECscAc5aJE8qBJ_9same_file(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCscAc5aJE8qBJ_9same_file4unix6HandleEBK_(void * _arg0) {
  _Alignas(8) uint8_t _t4_storage[16];
  void *_t4 = (void *)_t4_storage;
  void * _t5;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t6;
  void * _t7;
  void * _t8;
  void * _t9;
  int32_t _t10;

bb_0_start:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _RNvXNtCscAc5aJE8qBJ_9same_file4unixNtB2_6HandleNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(_arg0);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb4;
bb_1_bb3:
  _t7 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_4_terminate; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_6option6OptionNtNtCsMibNUK8RNN_3std2fs4FileEECscAc5aJE8qBJ_9same_file(_t7);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_5_bb1;
bb_2_cleanup:
  *(void * *)_t4 = __exn_ptr;
  _t5 = (void *)((__rustc_usize)_t4 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t5 = 0LL;
  goto bb_1_bb3;
bb_3_bb4:
  _t6 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtB4_6option6OptionNtNtCsMibNUK8RNN_3std2fs4FileEECscAc5aJE8qBJ_9same_file(_t6);
  return;
bb_4_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_5_bb1:
  _t8 = *(void * *)_t4;
  _t9 = (void *)((__rustc_usize)_t4 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t10 = *(int32_t *)_t9;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t8; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std2os2fd5owned7OwnedFdECscAc5aJE8qBJ_9same_file(void * _arg0) {
bb_0_start:
  _RNvXs5_NtNtNtCsMibNUK8RNN_3std2os2fd5ownedNtB5_7OwnedFdNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std3sys2fd4unix8FileDescECscAc5aJE8qBJ_9same_file(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std2os2fd5owned7OwnedFdECscAc5aJE8qBJ_9same_file(_arg0);
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std3sys2fs4unix4FileECscAc5aJE8qBJ_9same_file(void * _arg0) {
bb_0_start:
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtNtNtCsMibNUK8RNN_3std3sys2fd4unix8FileDescECscAc5aJE8qBJ_9same_file(_arg0);
  return;
}

#pragma weak _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle11as_file_mut
void * _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle11as_file_mut(void * _arg0) {
  void * _t11;

bb_0_start:
  _t11 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle11as_file_mut(_arg0);
  return _t11;
}

#pragma weak _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle5stdin
struct _S6 _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle5stdin(void) {
  _Alignas(16) struct _S6 _retbuf;
  _Alignas(8) uint8_t _t12_storage[24];
  void *_t12 = (void *)_t12_storage;
  _Alignas(8) uint8_t _t13_storage[24];
  void *_t13 = (void *)_t13_storage;
  _Alignas(8) uint8_t _t14_storage[24];
  void *_t14 = (void *)_t14_storage;
  struct _S6 _t15;
  void * _t16;
  uint8_t _t17;
  _Bool _t18;
  __rustc_isize _t19;
  _Bool _t20;
  void * _t21;
  void * _t22;

bb_0_start:
  _t15 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle5stdin();
  *(struct _S6 *)_t12 = _t15;
  _t16 = (void *)((__rustc_usize)_t12 + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t17 = *(uint8_t *)_t16;
  _t18 = (int8_t)_t17 == (int8_t)2ULL;
  _t19 = (_t18) ? (1LL) : (0LL);
  _t20 = (_Bool)_t19;
  if (_t20) goto bb_1_bb4; else goto bb_2_bb5;
bb_1_bb4:
  _t21 = *(void * *)_t12;
  *(void * *)(void *)&_retbuf = _t21;
  _t22 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint8_t *)_t22 = 2ULL;
  goto bb_3_bb2;
bb_2_bb5:
  memcpy(_t13, _t12, 24ULL);
  memcpy(_t14, _t13, 24ULL);
  memcpy((void *)&_retbuf, _t14, 24ULL);
  goto bb_3_bb2;
bb_3_bb2:
  return _retbuf;
bb_4_bb3:
  abort();
}

#pragma weak _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle6stderr
struct _S6 _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle6stderr(void) {
  _Alignas(16) struct _S6 _retbuf;
  _Alignas(8) uint8_t _t23_storage[24];
  void *_t23 = (void *)_t23_storage;
  _Alignas(8) uint8_t _t24_storage[24];
  void *_t24 = (void *)_t24_storage;
  _Alignas(8) uint8_t _t25_storage[24];
  void *_t25 = (void *)_t25_storage;
  struct _S6 _t26;
  void * _t27;
  uint8_t _t28;
  _Bool _t29;
  __rustc_isize _t30;
  _Bool _t31;
  void * _t32;
  void * _t33;

bb_0_start:
  _t26 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle6stderr();
  *(struct _S6 *)_t23 = _t26;
  _t27 = (void *)((__rustc_usize)_t23 + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t28 = *(uint8_t *)_t27;
  _t29 = (int8_t)_t28 == (int8_t)2ULL;
  _t30 = (_t29) ? (1LL) : (0LL);
  _t31 = (_Bool)_t30;
  if (_t31) goto bb_1_bb4; else goto bb_2_bb5;
bb_1_bb4:
  _t32 = *(void * *)_t23;
  *(void * *)(void *)&_retbuf = _t32;
  _t33 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint8_t *)_t33 = 2ULL;
  goto bb_3_bb2;
bb_2_bb5:
  memcpy(_t24, _t23, 24ULL);
  memcpy(_t25, _t24, 24ULL);
  memcpy((void *)&_retbuf, _t25, 24ULL);
  goto bb_3_bb2;
bb_3_bb2:
  return _retbuf;
bb_4_bb3:
  abort();
}

#pragma weak _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle6stdout
struct _S6 _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle6stdout(void) {
  _Alignas(16) struct _S6 _retbuf;
  _Alignas(8) uint8_t _t34_storage[24];
  void *_t34 = (void *)_t34_storage;
  _Alignas(8) uint8_t _t35_storage[24];
  void *_t35 = (void *)_t35_storage;
  _Alignas(8) uint8_t _t36_storage[24];
  void *_t36 = (void *)_t36_storage;
  struct _S6 _t37;
  void * _t38;
  uint8_t _t39;
  _Bool _t40;
  __rustc_isize _t41;
  _Bool _t42;
  void * _t43;
  void * _t44;

bb_0_start:
  _t37 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle6stdout();
  *(struct _S6 *)_t34 = _t37;
  _t38 = (void *)((__rustc_usize)_t34 + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t39 = *(uint8_t *)_t38;
  _t40 = (int8_t)_t39 == (int8_t)2ULL;
  _t41 = (_t40) ? (1LL) : (0LL);
  _t42 = (_Bool)_t41;
  if (_t42) goto bb_1_bb4; else goto bb_2_bb5;
bb_1_bb4:
  _t43 = *(void * *)_t34;
  *(void * *)(void *)&_retbuf = _t43;
  _t44 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint8_t *)_t44 = 2ULL;
  goto bb_3_bb2;
bb_2_bb5:
  memcpy(_t35, _t34, 24ULL);
  memcpy(_t36, _t35, 24ULL);
  memcpy((void *)&_retbuf, _t36, 24ULL);
  goto bb_3_bb2;
bb_3_bb2:
  return _retbuf;
bb_4_bb3:
  abort();
}

#pragma weak _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle7as_file
void * _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle7as_file(void * _arg0) {
  void * _t45;

bb_0_start:
  _t45 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle7as_file(_arg0);
  return _t45;
}

#pragma weak _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle9from_file
struct _S6 _RNvMCscAc5aJE8qBJ_9same_fileNtB2_6Handle9from_file(int32_t _arg0) {
  _Alignas(16) struct _S6 _retbuf;
  _Alignas(8) uint8_t _t46_storage[24];
  void *_t46 = (void *)_t46_storage;
  _Alignas(8) uint8_t _t47_storage[24];
  void *_t47 = (void *)_t47_storage;
  _Alignas(8) uint8_t _t48_storage[24];
  void *_t48 = (void *)_t48_storage;
  struct _S6 _t49;
  void * _t50;
  uint8_t _t51;
  _Bool _t52;
  __rustc_isize _t53;
  _Bool _t54;
  void * _t55;
  void * _t56;

bb_0_start:
  _t49 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle9from_file(_arg0);
  *(struct _S6 *)_t46 = _t49;
  _t50 = (void *)((__rustc_usize)_t46 + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t51 = *(uint8_t *)_t50;
  _t52 = (int8_t)_t51 == (int8_t)2ULL;
  _t53 = (_t52) ? (1LL) : (0LL);
  _t54 = (_Bool)_t53;
  if (_t54) goto bb_1_bb4; else goto bb_2_bb5;
bb_1_bb4:
  _t55 = *(void * *)_t46;
  *(void * *)(void *)&_retbuf = _t55;
  _t56 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint8_t *)_t56 = 2ULL;
  goto bb_3_bb2;
bb_2_bb5:
  memcpy(_t47, _t46, 24ULL);
  memcpy(_t48, _t47, 24ULL);
  memcpy((void *)&_retbuf, _t48, 24ULL);
  goto bb_3_bb2;
bb_3_bb2:
  return _retbuf;
bb_4_bb3:
  abort();
}

static void * _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle11as_file_mut(void * _arg0) {
  _Alignas(8) uint8_t _t57_storage[8];
  void *_t57 = (void *)_t57_storage;
  void * _t58;
  int32_t _t59;
  _Bool _t60;
  __rustc_isize _t61;
  _Bool _t62;
  void * _t63;
  void * _t64;

bb_0_start:
  _t58 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t59 = *(int32_t *)_t58;
  _t60 = (int32_t)_t59 == (int32_t)-1LL;
  _t61 = (_t60) ? (0LL) : (1LL);
  _t62 = (_Bool)_t61;
  if (_t62) goto bb_1_bb3; else goto bb_2_bb2;
bb_1_bb3:
  _t63 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t57 = _t63;
  _t64 = *(void * *)_t57;
  return _t64;
bb_2_bb2:
  _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(&_bytes0);
  abort();
bb_3_bb1:
  abort();
}

static struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle5stdin(void) {
  _Alignas(16) struct _S6 _retbuf;
  struct _S6 _t65;

bb_0_start:
  _t65 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle8from_std(0LL);
  *(struct _S6 *)(void *)&_retbuf = _t65;
  return _retbuf;
}

static struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle6stderr(void) {
  _Alignas(16) struct _S6 _retbuf;
  struct _S6 _t66;

bb_0_start:
  _t66 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle8from_std(2LL);
  *(struct _S6 *)(void *)&_retbuf = _t66;
  return _retbuf;
}

static struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle6stdout(void) {
  _Alignas(16) struct _S6 _retbuf;
  struct _S6 _t67;

bb_0_start:
  _t67 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle8from_std(1LL);
  *(struct _S6 *)(void *)&_retbuf = _t67;
  return _retbuf;
}

static void * _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle7as_file(void * _arg0) {
  _Alignas(8) uint8_t _t68_storage[8];
  void *_t68 = (void *)_t68_storage;
  void * _t69;
  int32_t _t70;
  _Bool _t71;
  __rustc_isize _t72;
  _Bool _t73;
  void * _t74;
  void * _t75;

bb_0_start:
  _t69 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t70 = *(int32_t *)_t69;
  _t71 = (int32_t)_t70 == (int32_t)-1LL;
  _t72 = (_t71) ? (0LL) : (1LL);
  _t73 = (_Bool)_t72;
  if (_t73) goto bb_1_bb3; else goto bb_2_bb2;
bb_1_bb3:
  _t74 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t68 = _t74;
  _t75 = *(void * *)_t68;
  return _t75;
bb_2_bb2:
  _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(&_bytes2);
  abort();
bb_3_bb1:
  abort();
}

static struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle8from_std(int32_t _arg0) {
  _Alignas(16) struct _S6 _retbuf;
  _Alignas(8) uint8_t _t76_storage[24];
  void *_t76 = (void *)_t76_storage;
  struct _S6 _t77;
  void * _t78;
  uint8_t _t79;
  _Bool _t80;
  __rustc_isize _t81;
  _Bool _t82;
  void * _t83;
  int8_t _t84;

bb_0_start:
  _t77 = _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle9from_file(_arg0);
  *(struct _S6 *)(void *)&_retbuf = _t77;
  _t78 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t79 = *(uint8_t *)_t78;
  _t80 = (int8_t)_t79 == (int8_t)2ULL;
  _t81 = (_t80) ? (1LL) : (0LL);
  _t82 = (_Bool)_t81;
  if (_t82) goto bb_1_bb4; else goto bb_2_bb5;
bb_1_bb4:
  goto bb_3_bb2;
bb_2_bb5:
  memcpy(_t76, (void *)&_retbuf, 24ULL);
  _t83 = (void *)((__rustc_usize)_t76 + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t84 = (int8_t)(1ULL);
  *(int8_t *)_t83 = _t84;
  memcpy((void *)&_retbuf, _t76, 24ULL);
  goto bb_3_bb2;
bb_3_bb2:
  return _retbuf;
bb_4_bb3:
  abort();
}

#pragma weak _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle9from_file
struct _S6 _RNvMs4_NtCscAc5aJE8qBJ_9same_file4unixNtB5_6Handle9from_file(int32_t _arg0) {
  _Alignas(4) uint8_t _t85_storage[4];
  void *_t85 = (void *)_t85_storage;
  _Alignas(16) struct _S6 _retbuf;
  _Alignas(8) uint8_t _t86_storage[152];
  void *_t86 = (void *)_t86_storage;
  _Alignas(8) uint8_t _t87_storage[152];
  void *_t87 = (void *)_t87_storage;
  _Alignas(8) uint8_t _t88_storage[24];
  void *_t88 = (void *)_t88_storage;
  _Alignas(8) uint8_t _t89_storage[144];
  void *_t89 = (void *)_t89_storage;
  _Alignas(8) uint8_t _t90_storage[16];
  void *_t90 = (void *)_t90_storage;
  _Alignas(8) uint8_t _t91_storage[16];
  void *_t91 = (void *)_t91_storage;
  void * _t92;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  struct _S23 _t93;
  uint64_t _t94;
  __rustc_isize _t95;
  _Bool _t96;
  void * _t97;
  void * _t98;
  void * _t99;
  int32_t _t100;
  void * _t101;
  void * _t102;
  uint16_t _t103;
  void * _t104;
  void * _t105;
  uint16_t _t106;
  void * _t107;
  void * _t108;
  uint64_t _t109;
  void * _t110;
  void * _t111;
  uint32_t _t112;
  void * _t113;
  void * _t114;
  uint32_t _t115;
  void * _t116;
  void * _t117;
  int32_t _t118;
  void * _t119;
  void * _t120;
  int64_t _t121;
  void * _t122;
  void * _t123;
  int64_t _t124;
  void * _t125;
  void * _t126;
  int64_t _t127;
  void * _t128;
  void * _t129;
  int64_t _t130;
  void * _t131;
  void * _t132;
  int64_t _t133;
  void * _t134;
  void * _t135;
  int64_t _t136;
  void * _t137;
  void * _t138;
  int64_t _t139;
  void * _t140;
  void * _t141;
  int64_t _t142;
  void * _t143;
  void * _t144;
  int64_t _t145;
  void * _t146;
  void * _t147;
  int64_t _t148;
  void * _t149;
  void * _t150;
  int32_t _t151;
  void * _t152;
  void * _t153;
  uint32_t _t154;
  void * _t155;
  void * _t156;
  uint32_t _t157;
  void * _t158;
  void * _t159;
  int32_t _t160;
  void * _t161;
  void * _t162;
  int32_t _t163;
  _Bool _t164;
  uint64_t _t165;
  void * _t166;
  void * _t167;
  int8_t _t168;
  void * _t169;
  void * _t170;
  void * _t171;
  void * _t172;
  void * _t173;
  void * _t174;
  void * _t175;
  void * _t176;
  void * _t177;
  int32_t _t178;

bb_0_start:
  *(int32_t *)_t85 = _arg0;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t93 = _RNvMs2_NtCsMibNUK8RNN_3std2fsNtB5_4File8metadata(_t85);
  *(struct _S23 *)_t87 = _t93;
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb1;
bb_1_bb5:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_8_terminate; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCsMibNUK8RNN_3std2fs4FileECscAc5aJE8qBJ_9same_file(_t85);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_9_bb4;
bb_2_cleanup:
  *(void * *)_t91 = __exn_ptr;
  _t92 = (void *)((__rustc_usize)_t91 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t92 = 0LL;
  goto bb_1_bb5;
bb_3_bb1:
  _t94 = *(uint64_t *)_t87;
  _t95 = (__rustc_isize)_t94;
  _t96 = (_Bool)_t95;
  if (_t96) goto bb_4_bb6; else goto bb_5_bb7;
bb_4_bb6:
  _t170 = (void *)((__rustc_usize)_t87 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t171 = *(void * *)_t170;
  _t172 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t172 = _t171;
  *(uint64_t *)_t86 = 1ULL;
  _t173 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t174 = *(void * *)_t173;
  *(void * *)(void *)&_retbuf = _t174;
  _t175 = (void *)((__rustc_usize)(void *)&_retbuf + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint8_t *)_t175 = 2ULL;
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCsMibNUK8RNN_3std2fs4FileECscAc5aJE8qBJ_9same_file(_t85);
  goto bb_6_bb3;
bb_5_bb7:
  _t97 = (void *)((__rustc_usize)_t87 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  memcpy(_t89, _t97, 144ULL);
  _t98 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  memcpy(_t98, _t89, 144ULL);
  *(uint64_t *)_t86 = 0ULL;
  _t99 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t100 = *(int32_t *)_t99;
  _t101 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t102 = (void *)((__rustc_usize)_t101 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t103 = *(uint16_t *)_t102;
  _t104 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t105 = (void *)((__rustc_usize)_t104 + (__rustc_isize)(6ULL) * (__rustc_isize)sizeof(int8_t));
  _t106 = *(uint16_t *)_t105;
  _t107 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t108 = (void *)((__rustc_usize)_t107 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t109 = *(uint64_t *)_t108;
  _t110 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t111 = (void *)((__rustc_usize)_t110 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t112 = *(uint32_t *)_t111;
  _t113 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t114 = (void *)((__rustc_usize)_t113 + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t115 = *(uint32_t *)_t114;
  _t116 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t117 = (void *)((__rustc_usize)_t116 + (__rustc_isize)(24ULL) * (__rustc_isize)sizeof(int8_t));
  _t118 = *(int32_t *)_t117;
  _t119 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t120 = (void *)((__rustc_usize)_t119 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  _t121 = *(int64_t *)_t120;
  _t122 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t123 = (void *)((__rustc_usize)_t122 + (__rustc_isize)(40ULL) * (__rustc_isize)sizeof(int8_t));
  _t124 = *(int64_t *)_t123;
  _t125 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t126 = (void *)((__rustc_usize)_t125 + (__rustc_isize)(48ULL) * (__rustc_isize)sizeof(int8_t));
  _t127 = *(int64_t *)_t126;
  _t128 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t129 = (void *)((__rustc_usize)_t128 + (__rustc_isize)(56ULL) * (__rustc_isize)sizeof(int8_t));
  _t130 = *(int64_t *)_t129;
  _t131 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t132 = (void *)((__rustc_usize)_t131 + (__rustc_isize)(64ULL) * (__rustc_isize)sizeof(int8_t));
  _t133 = *(int64_t *)_t132;
  _t134 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t135 = (void *)((__rustc_usize)_t134 + (__rustc_isize)(72ULL) * (__rustc_isize)sizeof(int8_t));
  _t136 = *(int64_t *)_t135;
  _t137 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t138 = (void *)((__rustc_usize)_t137 + (__rustc_isize)(80ULL) * (__rustc_isize)sizeof(int8_t));
  _t139 = *(int64_t *)_t138;
  _t140 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t141 = (void *)((__rustc_usize)_t140 + (__rustc_isize)(88ULL) * (__rustc_isize)sizeof(int8_t));
  _t142 = *(int64_t *)_t141;
  _t143 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t144 = (void *)((__rustc_usize)_t143 + (__rustc_isize)(96ULL) * (__rustc_isize)sizeof(int8_t));
  _t145 = *(int64_t *)_t144;
  _t146 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t147 = (void *)((__rustc_usize)_t146 + (__rustc_isize)(104ULL) * (__rustc_isize)sizeof(int8_t));
  _t148 = *(int64_t *)_t147;
  _t149 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t150 = (void *)((__rustc_usize)_t149 + (__rustc_isize)(112ULL) * (__rustc_isize)sizeof(int8_t));
  _t151 = *(int32_t *)_t150;
  _t152 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t153 = (void *)((__rustc_usize)_t152 + (__rustc_isize)(116ULL) * (__rustc_isize)sizeof(int8_t));
  _t154 = *(uint32_t *)_t153;
  _t155 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t156 = (void *)((__rustc_usize)_t155 + (__rustc_isize)(120ULL) * (__rustc_isize)sizeof(int8_t));
  _t157 = *(uint32_t *)_t156;
  _t158 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t159 = (void *)((__rustc_usize)_t158 + (__rustc_isize)(124ULL) * (__rustc_isize)sizeof(int8_t));
  _t160 = *(int32_t *)_t159;
  _t161 = (void *)((__rustc_usize)_t86 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t162 = (void *)((__rustc_usize)_t161 + (__rustc_isize)(128ULL) * (__rustc_isize)sizeof(int8_t));
  memcpy(_t90, _t162, 16ULL);
  _t163 = *(int32_t *)_t85;
  _t164 = (uint32_t)_t163 <= (uint32_t)-2LL;
  _t165 = (uint64_t)_t100;
  _t166 = (void *)((__rustc_usize)_t88 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t166 = _t163;
  _t167 = (void *)((__rustc_usize)_t88 + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t168 = (int8_t)(0ULL);
  *(int8_t *)_t167 = _t168;
  *(uint64_t *)_t88 = _t165;
  _t169 = (void *)((__rustc_usize)_t88 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t169 = _t109;
  memcpy((void *)&_retbuf, _t88, 24ULL);
  goto bb_6_bb3;
bb_6_bb3:
  return _retbuf;
bb_7_bb2:
  abort();
bb_8_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_9_bb4:
  _t176 = *(void * *)_t91;
  _t177 = (void *)((__rustc_usize)_t91 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t178 = *(int32_t *)_t177;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t176; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
}

static void _RNvNtNtNtCsMibNUK8RNN_3std3sys2fs4unix23debug_assert_fd_is_open(int32_t _arg0) {
bb_0_start:
  goto bb_1_bb10;
bb_1_bb10:
  return;
bb_2_bb1:
  abort();
bb_3_bb2:
  abort();
bb_4_bb3:
  abort();
bb_5_bb4:
  abort();
bb_6_bb5:
  abort();
bb_7_bb6:
  abort();
bb_8_bb7:
  abort();
bb_9_bb8:
  abort();
bb_10_bb9:
  abort();
bb_11_bb11:
  abort();
}

#pragma weak _RNvXNtCscAc5aJE8qBJ_9same_file4unixNtB2_6HandleNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop
void _RNvXNtCscAc5aJE8qBJ_9same_file4unixNtB2_6HandleNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void * _arg0) {
  void * _t179;
  _Bool _t180;
  void * _t181;
  int32_t _t182;
  void * _t183;
  _Bool _t184;
  __rustc_isize _t185;
  _Bool _t186;

bb_0_start:
  _t179 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(20ULL) * (__rustc_isize)sizeof(int8_t));
  _t180 = *(_Bool *)_t179;
  if (_t180) goto bb_2_bb1; else goto bb_1_bb2;
bb_1_bb2:
  return;
bb_2_bb1:
  _t181 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t182 = *(int32_t *)_t181;
  _t183 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t183 = -1LL;
  _t184 = (int32_t)_t182 == (int32_t)-1LL;
  _t185 = (_t184) ? (0LL) : (1LL);
  _t186 = (_Bool)_t185;
  if (_t186) goto bb_3_bb5; else goto bb_4_bb4;
bb_3_bb5:
  goto bb_1_bb2;
bb_4_bb4:
  _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(&_bytes4);
  abort();
bb_5_bb3:
  abort();
}

#pragma weak _RNvXs1_NtCscAc5aJE8qBJ_9same_file4unixNtB7_6HandleNtNtNtNtCsMibNUK8RNN_3std2os2fd3raw7AsRawFd9as_raw_fd
int32_t _RNvXs1_NtCscAc5aJE8qBJ_9same_file4unixNtB7_6HandleNtNtNtNtCsMibNUK8RNN_3std2os2fd3raw7AsRawFd9as_raw_fd(void * _arg0) {
  _Alignas(8) uint8_t _t187_storage[8];
  void *_t187 = (void *)_t187_storage;
  void * _t188;
  int32_t _t189;
  _Bool _t190;
  __rustc_isize _t191;
  _Bool _t192;
  void * _t193;
  void * _t194;
  int32_t _t195;
  _Bool _t196;

bb_0_start:
  _t188 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t189 = *(int32_t *)_t188;
  _t190 = (int32_t)_t189 == (int32_t)-1LL;
  _t191 = (_t190) ? (0LL) : (1LL);
  _t192 = (_Bool)_t191;
  if (_t192) goto bb_1_bb3; else goto bb_2_bb2;
bb_1_bb3:
  _t193 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t187 = _t193;
  _t194 = *(void * *)_t187;
  _t195 = *(int32_t *)_t194;
  _t196 = (uint32_t)_t195 <= (uint32_t)-2LL;
  return _t195;
bb_2_bb2:
  _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(&_bytes6);
  abort();
bb_3_bb1:
  abort();
}

#pragma weak _RNvXs2_NtCscAc5aJE8qBJ_9same_file4unixNtB7_6HandleNtNtNtNtCsMibNUK8RNN_3std2os2fd3raw9IntoRawFd11into_raw_fd
int32_t _RNvXs2_NtCscAc5aJE8qBJ_9same_file4unixNtB7_6HandleNtNtNtNtCsMibNUK8RNN_3std2os2fd3raw9IntoRawFd11into_raw_fd(void * _arg0) {
  _Alignas(4) uint8_t _t197_storage[4];
  void *_t197 = (void *)_t197_storage;
  void * _t198;
  int32_t _t199;
  void * _t200;
  int32_t _t201;
  _Bool _t202;
  __rustc_isize _t203;
  _Bool _t204;
  _Alignas(8) uint8_t _t205_storage[16];
  void *_t205 = (void *)_t205_storage;
  void * _t206;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t207;
  void * _t208;
  int32_t _t209;
  int32_t _t210;
  _Bool _t211;

bb_0_start:
  _t198 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t199 = *(int32_t *)_t198;
  *(int32_t *)_t197 = _t199;
  _t200 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t200 = -1LL;
  _t201 = *(int32_t *)_t197;
  _t202 = (int32_t)_t201 == (int32_t)-1LL;
  _t203 = (_t202) ? (0LL) : (1LL);
  _t204 = (_Bool)_t203;
  if (_t204) goto bb_1_bb6; else goto bb_2_bb5;
bb_1_bb6:
  _t210 = *(int32_t *)_t197;
  _t211 = (uint32_t)_t210 <= (uint32_t)-2LL;
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtCscAc5aJE8qBJ_9same_file6HandleEBI_(_arg0);
  return _t210;
bb_2_bb5:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_4_cleanup; }
  _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(&_bytes8);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_5_unreachable;
bb_3_bb2:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_6_terminate; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtCscAc5aJE8qBJ_9same_file6HandleEBI_(_arg0);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_7_bb3;
bb_4_cleanup:
  *(void * *)_t205 = __exn_ptr;
  _t206 = (void *)((__rustc_usize)_t205 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t206 = 0LL;
  goto bb_3_bb2;
bb_5_unreachable:
  abort();
bb_6_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_7_bb3:
  _t207 = *(void * *)_t205;
  _t208 = (void *)((__rustc_usize)_t205 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t209 = *(int32_t *)_t208;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t207; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
bb_8_bb4:
  abort();
}

static void _RNvXs5_NtNtNtCsMibNUK8RNN_3std2os2fd5ownedNtB5_7OwnedFdNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void * _arg0) {
  int32_t _t212;
  _Bool _t213;
  int32_t _t214;
  _Bool _t215;
  int32_t _t216;

bb_0_start:
  _t212 = *(int32_t *)_arg0;
  _t213 = (uint32_t)_t212 <= (uint32_t)-2LL;
  _RNvNtNtNtCsMibNUK8RNN_3std3sys2fs4unix23debug_assert_fd_is_open(_t212);
  _t214 = *(int32_t *)_arg0;
  _t215 = (uint32_t)_t214 <= (uint32_t)-2LL;
  _t216 = close(_t214);
  return;
}

