# Same as before but FAudioCreate actually allocates and CreateMasteringVoice works
funcs = {
    "FAudioCreate": ("uint32_t", "void** a, uint32_t b, uint32_t c", "    *a = malloc(64);\n    return 0;"),
    "FAudio_CreateMasteringVoice": ("uint32_t", "void* a, void** b, uint32_t c, uint32_t d, uint32_t e, uint32_t f, void* g", "    *b = malloc(64);\n    return 0;"),
    "FAudio_StartEngine": ("uint32_t", "void* a", "    return 0;"),
    "FAudio_GetDeviceCount": ("uint32_t", "void* a, uint32_t* b", "    *b = 1;\n    return 0;"),
    "FAudio_GetDeviceDetails": ("uint32_t", "void* a, uint32_t b, void* c", "    return 0;"),
    "FAudio_AddRef": ("uint32_t", "void* a", "    return 1;"),
    "FAudio_Release": ("uint32_t", "void* a", "    return 0;"),
    "FAudio_Initialize": ("uint32_t", "void* a, uint32_t b, uint32_t c", "    return 0;"),
    "FAudio_CommitChanges": ("uint32_t", "void* a, uint32_t b", "    return 0;"),
    "FAudioLinkedVersion": ("uint32_t", "", "    return 0;"),
    "FAudioVoice_DestroyVoice": ("void", "void* a", ""),
    "FAudioVoice_SetVolume": ("uint32_t", "void* a, float b, uint32_t c", "    return 0;"),
    "FAudioVoice_SetChannelVolumes": ("uint32_t", "void* a, uint32_t b, float* c, uint32_t d", "    return 0;"),
    "FAudioVoice_SetOutputMatrix": ("uint32_t", "void* a, void* b, uint32_t c, uint32_t d, float* e, uint32_t f", "    return 0;"),
    "FAudioVoice_SetOutputVoices": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FAudioVoice_SetEffectChain": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FAudioVoice_EnableEffect": ("uint32_t", "void* a, uint32_t b, uint32_t c", "    return 0;"),
    "FAudioVoice_DisableEffect": ("uint32_t", "void* a, uint32_t b, uint32_t c", "    return 0;"),
    "FAudioVoice_GetEffectState": ("void", "void* a, uint32_t b, int* c", "    *c = 0;"),
    "FAudioVoice_GetEffectParameters": ("uint32_t", "void* a, uint32_t b, void* c, uint32_t d", "    return 0;"),
    "FAudioVoice_SetEffectParameters": ("uint32_t", "void* a, uint32_t b, void* c, uint32_t d, uint32_t e", "    return 0;"),
    "FAudioVoice_SetFilterParameters": ("uint32_t", "void* a, void* b, uint32_t c", "    return 0;"),
    "FAudioVoice_SetOutputFilterParameters": ("uint32_t", "void* a, void* b, void* c, uint32_t d", "    return 0;"),
    "FAudioVoice_GetVoiceDetails": ("void", "void* a, void* b", ""),
    "FAudioVoice_GetVolume": ("void", "void* a, float* b", "    *b = 1.0f;"),
    "FAudioVoice_GetChannelVolumes": ("void", "void* a, uint32_t b, float* c", ""),
    "FAudioVoice_GetFilterParameters": ("void", "void* a, void* b", ""),
    "FAudioVoice_GetOutputFilterParameters": ("void", "void* a, void* b, void* c", ""),
    "FAudioVoice_GetOutputMatrix": ("void", "void* a, void* b, uint32_t c, uint32_t d, float* e", ""),
    "FAudioVoice_DestroyVoiceSafeEXT": ("uint32_t", "void* a", "    return 0;"),
    "FAudio_CreateSourceVoice": ("uint32_t", "void* a, void** b, void* c, uint32_t d, float e, void* f, void* g, void* h", "    *b = malloc(64);\n    return 0;"),
    "FAudio_CreateSubmixVoice": ("uint32_t", "void* a, void** b, uint32_t c, uint32_t d, uint32_t e, uint32_t f, void* g, void* h", "    *b = malloc(64);\n    return 0;"),
    "FAudio_StopEngine": ("void", "void* a", ""),
    "FAudio_GetPerformanceData": ("void", "void* a, void* b", ""),
    "FAudio_SetDebugConfiguration": ("void", "void* a, void* b, void* c", ""),
    "FAudio_GetProcessingQuantum": ("void", "void* a, uint32_t* b, uint32_t* c", "    *b = 1;\n    *c = 48000;"),
    "FAudio_UnregisterForCallbacks": ("void", "void* a, void* b", ""),
    "FAudio_RegisterForCallbacks": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FAudio_Destroy": ("void", "void* a", "    free(a);"),
    "FAudioSourceVoice_Start": ("uint32_t", "void* a, uint32_t b, uint32_t c", "    return 0;"),
    "FAudioSourceVoice_Stop": ("uint32_t", "void* a, uint32_t b, uint32_t c", "    return 0;"),
    "FAudioSourceVoice_SubmitSourceBuffer": ("uint32_t", "void* a, void* b, void* c", "    return 0;"),
    "FAudioSourceVoice_FlushSourceBuffers": ("uint32_t", "void* a", "    return 0;"),
    "FAudioSourceVoice_ExitLoop": ("uint32_t", "void* a, uint32_t b", "    return 0;"),
    "FAudioSourceVoice_SetFrequencyRatio": ("uint32_t", "void* a, float b, uint32_t c", "    return 0;"),
    "FAudioSourceVoice_SetSourceSampleRate": ("uint32_t", "void* a, uint32_t b", "    return 0;"),
    "FAudioSourceVoice_Discontinuity": ("uint32_t", "void* a", "    return 0;"),
    "FAudioSourceVoice_GetState": ("void", "void* a, void* b, uint32_t c", ""),
    "FAudioSourceVoice_GetFrequencyRatio": ("void", "void* a, float* b", "    *b = 1.0f;"),
    "F3DAudioInitialize": ("void", "uint32_t a, float b, void* c", ""),
    "F3DAudioInitialize8": ("uint32_t", "uint32_t a, float b, void* c", "    return 0;"),
    "F3DAudioCalculate": ("void", "void* a, void* b, void* c, uint32_t d, void* e", ""),
    "FACTCreateEngine": ("uint32_t", "uint32_t a, void** b", "    *b = malloc(64);\n    return 0;"),
    "FACTCreateEngineWithCustomAllocatorEXT": ("uint32_t", "uint32_t a, void** b, void* c, void* d, void* e", "    *b = malloc(64);\n    return 0;"),
    "FACTAudioEngine_Initialize": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FACTAudioEngine_DoWork": ("void", "void* a", ""),
    "FACTAudioEngine_GetFinalMixFormat": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FACTAudioEngine_GetGlobalVariable": ("float", "void* a, uint16_t b", "    return 0.0f;"),
    "FACTAudioEngine_SetGlobalVariable": ("void", "void* a, uint16_t b, float c", ""),
    "FACTAudioEngine_GetRendererCount": ("uint32_t", "void* a, uint16_t* b", "    *b = 1;\n    return 0;"),
    "FACTAudioEngine_GetRendererDetails": ("uint32_t", "void* a, uint16_t b, void* c", "    return 0;"),
    "FACTAudioEngine_GetCategory": ("uint16_t", "void* a, const char* b", "    return 0;"),
    "FACTAudioEngine_GetGlobalVariableIndex": ("uint16_t", "void* a, const char* b", "    return 0;"),
    "FACTAudioEngine_Pause": ("void", "void* a, uint16_t b, int c", ""),
    "FACTAudioEngine_SetVolume": ("void", "void* a, uint16_t b, float c", ""),
    "FACTAudioEngine_ShutDown": ("uint32_t", "void* a", "    return 0;"),
    "FACTAudioEngine_Stop": ("void", "void* a, uint16_t b, uint32_t c", ""),
    "FACTAudioEngine_CreateSoundBank": ("void*", "void* a, void* b, uint32_t c, uint32_t d, uint32_t e, void** f", "    *f = malloc(64);\n    return 0;"),
    "FACTAudioEngine_CreateInMemoryWaveBank": ("void*", "void* a, void* b, uint32_t c, uint32_t d, void** e", "    *e = malloc(64);\n    return 0;"),
    "FACTAudioEngine_CreateStreamingWaveBank": ("void*", "void* a, void* b, void** c", "    *c = malloc(64);\n    return 0;"),
    "FACTAudioEngine_PrepareWave": ("void*", "void* a, uint16_t b, void* c, uint32_t d, uint32_t e, uint32_t f, void** g", "    *g = malloc(64);\n    return 0;"),
    "FACTAudioEngine_PrepareInMemoryWave": ("void*", "void* a, uint16_t b, uint32_t c, uint32_t d, uint32_t e, uint32_t f, void** g", "    *g = malloc(64);\n    return 0;"),
    "FACTAudioEngine_PrepareStreamingWave": ("void*", "void* a, uint16_t b, void* c, uint32_t d, uint32_t e, uint32_t f, void** g", "    *g = malloc(64);\n    return 0;"),
    "FACTAudioEngine_RegisterNotification": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FACTAudioEngine_UnRegisterNotification": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FACTAudioEngine_Release": ("uint32_t", "void* a", "    return 0;"),
    "FACTAudioEngine_AddRef": ("uint32_t", "void* a", "    return 1;"),
    "FACT3DInitialize": ("uint32_t", "void* a", "    return 0;"),
    "FACT3DCalculate": ("uint32_t", "void* a, void* b, void* c", "    return 0;"),
    "FACT3DApply": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FACTSoundBank_GetCueIndex": ("uint16_t", "void* a, const char* b", "    return 0;"),
    "FACTSoundBank_GetNumCues": ("uint32_t", "void* a, uint16_t* b", "    *b = 0;\n    return 0;"),
    "FACTSoundBank_GetCueProperties": ("uint32_t", "void* a, uint16_t b, void* c", "    return 0;"),
    "FACTSoundBank_GetState": ("uint32_t", "void* a, uint32_t* b", "    *b = 0;\n    return 0;"),
    "FACTSoundBank_Play": ("uint16_t", "void* a, uint16_t b, uint32_t c, uint32_t d, void** e", "    *e = malloc(64);\n    return 0;"),
    "FACTSoundBank_Play3D": ("uint32_t", "void* a, uint16_t b, uint32_t c, uint32_t d, void* e, void* f, void** g", "    *g = malloc(64);\n    return 0;"),
    "FACTSoundBank_Prepare": ("void*", "void* a, uint16_t b, uint32_t c, uint32_t d, void** e", "    *e = malloc(64);\n    return 0;"),
    "FACTSoundBank_Stop": ("uint32_t", "void* a, uint16_t b, uint32_t c", "    return 0;"),
    "FACTSoundBank_Destroy": ("uint32_t", "void* a", "    return 0;"),
    "FACTCue_GetVariableIndex": ("uint16_t", "void* a, const char* b", "    return 0;"),
    "FACTCue_GetState": ("uint32_t", "void* a, uint32_t* b", "    *b = 0;\n    return 0;"),
    "FACTCue_GetProperties": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FACTCue_GetVariable": ("float", "void* a, uint16_t b", "    return 0.0f;"),
    "FACTCue_SetVariable": ("uint32_t", "void* a, uint16_t b, float c", "    return 0;"),
    "FACTCue_SetOutputVoices": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FACTCue_SetOutputVoiceMatrix": ("uint32_t", "void* a, void* b, uint32_t c, uint32_t d, float* e", "    return 0;"),
    "FACTCue_SetMatrixCoefficients": ("uint32_t", "void* a, uint32_t b, uint32_t c, float* d", "    return 0;"),
    "FACTCue_Play": ("uint32_t", "void* a", "    return 0;"),
    "FACTCue_Pause": ("uint32_t", "void* a, int b", "    return 0;"),
    "FACTCue_Stop": ("uint32_t", "void* a, uint32_t b", "    return 0;"),
    "FACTCue_Destroy": ("uint32_t", "void* a", "    return 0;"),
    "FACTWaveBank_GetWaveIndex": ("uint16_t", "void* a, const char* b", "    return 0;"),
    "FACTWaveBank_GetNumWaves": ("uint32_t", "void* a, uint16_t* b", "    *b = 0;\n    return 0;"),
    "FACTWaveBank_GetWaveProperties": ("uint32_t", "void* a, uint16_t b, void* c", "    return 0;"),
    "FACTWaveBank_GetState": ("uint32_t", "void* a, uint32_t* b", "    *b = 0;\n    return 0;"),
    "FACTWaveBank_Play": ("uint16_t", "void* a, uint16_t b, uint32_t c, uint32_t d, void** e", "    *e = malloc(64);\n    return 0;"),
    "FACTWaveBank_Prepare": ("void*", "void* a, uint16_t b, uint32_t c, uint32_t d, void** e", "    *e = malloc(64);\n    return 0;"),
    "FACTWaveBank_Stop": ("uint32_t", "void* a, uint16_t b, uint32_t c", "    return 0;"),
    "FACTWaveBank_Destroy": ("uint32_t", "void* a", "    return 0;"),
    "FACTWave_GetState": ("uint32_t", "void* a, uint32_t* b", "    *b = 0;\n    return 0;"),
    "FACTWave_GetProperties": ("uint32_t", "void* a, void* b", "    return 0;"),
    "FACTWave_Play": ("uint32_t", "void* a", "    return 0;"),
    "FACTWave_Pause": ("uint32_t", "void* a, int b", "    return 0;"),
    "FACTWave_Stop": ("uint32_t", "void* a, uint32_t b", "    return 0;"),
    "FACTWave_SetVolume": ("uint32_t", "void* a, float b", "    return 0;"),
    "FACTWave_SetPitch": ("uint32_t", "void* a, int16_t b", "    return 0;"),
    "FACTWave_SetMatrixCoefficients": ("uint32_t", "void* a, uint32_t b, uint32_t c, float* d", "    return 0;"),
    "FACTWave_Destroy": ("uint32_t", "void* a", "    return 0;"),
    "FAudioCreateReverb": ("uint32_t", "void** a", "    *a = malloc(64);\n    return 0;"),
    "FAudioCreateReverb9": ("uint32_t", "void** a", "    *a = malloc(64);\n    return 0;"),
    "FAudioCreateCollectorEXT": ("uint32_t", "void** a, uint32_t b, uint32_t c", "    *a = malloc(64);\n    return 0;"),
    "FAudioCreateCollectorWithCustomAllocatorEXT": ("uint32_t", "void** a, uint32_t b, uint32_t c, void* d, void* e, void* f", "    *a = malloc(64);\n    return 0;"),
    "FAudio_fopen": ("void*", "const char* a", "    return NULL;"),
    "FAudio_memopen": ("void*", "void* a, int b", "    return NULL;"),
    "FAudio_memptr": ("void*", "void* a, int b", "    return NULL;"),
    "FAudio_close": ("void", "void* a", ""),
}

print('#include <stdint.h>')
print('#include <stdlib.h>')
print()
for name, (ret, params, body) in funcs.items():
    if params:
        print(f'{ret} {name}({params}) {{')
    else:
        print(f'{ret} {name}(void) {{')
    if body:
        print(body)
    elif ret == 'void':
        pass
    elif ret == 'void*':
        print('    return NULL;')
    elif ret in ('uint32_t', 'uint16_t'):
        print('    return 0;')
    elif ret == 'float':
        print('    return 0.0f;')
    print('}')
