/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

struct _S9 {
  uint64_t f0;
  uint64_t f1;
};
struct _S12 {
  void * f0;
  void * f1;
};
struct _S32 {
  void * f0;
  __rustc_usize f1;
};
#pragma pack(push, 1)
struct _gs__RNvCsdZu6hNdFJFF_3log6LOGGER { void *f0; void *f1; };
#pragma pack(pop)
#pragma pack(push, 1)
struct _gs__RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES { void *f0; unsigned char f1[8]; void *f2; unsigned char f3[8]; void *f4; unsigned char f5[8]; void *f6; unsigned char f7[8]; void *f8; unsigned char f9[8]; void *f10; unsigned char f11[8]; };
#pragma pack(pop)
#pragma pack(push, 1)
struct _gs__RNvCsdZu6hNdFJFF_3log16SET_LOGGER_ERROR { void *f0; unsigned char f1[8]; };
#pragma pack(pop)
#pragma pack(push, 1)
struct _gs__RNvCsdZu6hNdFJFF_3log17LEVEL_PARSE_ERROR { void *f0; unsigned char f1[8]; };
#pragma pack(pop)

extern uint8_t _RNvCsdZu6hNdFJFF_3log5STATE[];
extern struct _gs__RNvCsdZu6hNdFJFF_3log6LOGGER _RNvCsdZu6hNdFJFF_3log6LOGGER;
extern struct _gs__RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES _RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES;
extern struct _gs__RNvCsdZu6hNdFJFF_3log16SET_LOGGER_ERROR _RNvCsdZu6hNdFJFF_3log16SET_LOGGER_ERROR;
extern struct _gs__RNvCsdZu6hNdFJFF_3log17LEVEL_PARSE_ERROR _RNvCsdZu6hNdFJFF_3log17LEVEL_PARSE_ERROR;
extern uint8_t _RNvNvCsdZu6hNdFJFF_3log6logger3NOP[];

static _Bool _RINvCsdZu6hNdFJFF_3log16set_logger_innerNCNvB2_10set_logger0EB2_(void *, void *);
static __rustc_usize _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadjECsdZu6hNdFJFF_3log(void *, uint8_t);
static void _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic12atomic_storejECsdZu6hNdFJFF_3log(void *, __rustc_usize, uint8_t);
static struct _S9 _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic23atomic_compare_exchangejECsdZu6hNdFJFF_3log(void *, __rustc_usize, __rustc_usize, uint8_t, uint8_t);
static void _RINvNtNtNtCs41fFVwHnQdq_4core9core_arch10arm_shared7barrier5___isbNtNtB2_6common2SYECsdZu6hNdFJFF_3log(void);
static struct _S12 _RNCNvCsdZu6hNdFJFF_3log10set_logger0B3_(void *, void *);
_Bool _RNvCsdZu6hNdFJFF_3log10set_logger(void *, void *);
_Bool _RNvCsdZu6hNdFJFF_3log15set_logger_racy(void *, void *);
struct _S12 _RNvCsdZu6hNdFJFF_3log6logger(void);
static _Bool _RNvMNtNtCs41fFVwHnQdq_4core5slice5asciiSh20eq_ignore_ascii_case(void *, __rustc_usize, void *, __rustc_usize);
static void _RNvXNtNtNtNtCs41fFVwHnQdq_4core9core_arch10arm_shared7barrier6commonNtB2_2SYNtNtB6_6sealed3Isb5___isb(void *);
uint64_t _RNvXs0_CsdZu6hNdFJFF_3logNtB5_5LevelNtNtNtCs41fFVwHnQdq_4core3str6traits7FromStr8from_str(void *, __rustc_usize);
void _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log3log(void *, void *);
void _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log5flush(void *);
_Bool _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log7enabled(void *, void *);
_Bool _RNvXs1_CsdZu6hNdFJFF_3logNtB5_5LevelNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void *, void *);
uint64_t _RNvXs5_CsdZu6hNdFJFF_3logNtB5_11LevelFilterNtNtNtCs41fFVwHnQdq_4core3str6traits7FromStr8from_str(void *, __rustc_usize);
_Bool _RNvXs6_CsdZu6hNdFJFF_3logNtB5_11LevelFilterNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void *, void *);
static void _RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log3log(void *, void *);
static void _RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log5flush(void *);
static _Bool _RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log7enabled(void *, void *);
_Bool _RNvXsh_CsdZu6hNdFJFF_3logNtB5_14SetLoggerErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void *, void *);
_Bool _RNvXsi_CsdZu6hNdFJFF_3logNtB5_15ParseLevelErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void *, void *);
void _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(void *, void *, void *);
void _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(__rustc_usize, __rustc_usize, void *);
void _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(void *);
_Bool _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter3pad(void *, void *, __rustc_usize);
_Bool _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(void *, void *, __rustc_usize);

static const unsigned char _bytes0[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes1[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes3[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes2 = {   .f0 = (void *)_bytes3,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xbe, 0x0f, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes4[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes5[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x6c, 0x6f, 0x61, 0x64 };
static const unsigned char _bytes7[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes6 = {   .f0 = (void *)_bytes7,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xbf, 0x0f, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes8[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65 };
static const unsigned char _bytes9[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65 };
static const unsigned char _bytes11[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes10 = {   .f0 = (void *)_bytes11,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xaf, 0x0f, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes12[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65 };
static const unsigned char _bytes13[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65 };
static const unsigned char _bytes15[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes14 = {   .f0 = (void *)_bytes15,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xb0, 0x0f, 0x00, 0x00, 0x17, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes16[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x20, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67 };
static const unsigned char _bytes17[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x20, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67 };
static const unsigned char _bytes19[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes18 = {   .f0 = (void *)_bytes19,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x34, 0x10, 0x00, 0x00, 0x1d, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes20[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x20, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67 };
static const unsigned char _bytes21[] = { 0x74, 0x68, 0x65, 0x72, 0x65, 0x20, 0x69, 0x73, 0x20, 0x6e, 0x6f, 0x20, 0x73, 0x75, 0x63, 0x68, 0x20, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x20, 0x61, 0x73, 0x20, 0x61, 0x6e, 0x20, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x2d, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x20, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x20, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67 };
static const unsigned char _bytes23[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes22 = {   .f0 = (void *)_bytes23,   .f1 = { 0x98, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x33, 0x10, 0x00, 0x00, 0x1c, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes24[] = { 0x4f, 0x46, 0x46 };
static const unsigned char _bytes25[] = { 0x45, 0x52, 0x52, 0x4f, 0x52 };
static const unsigned char _bytes26[] = { 0x57, 0x41, 0x52, 0x4e };
static const unsigned char _bytes27[] = { 0x49, 0x4e, 0x46, 0x4f };
static const unsigned char _bytes28[] = { 0x44, 0x45, 0x42, 0x55, 0x47 };
static const unsigned char _bytes29[] = { 0x54, 0x52, 0x41, 0x43, 0x45 };
static const unsigned char _bytes30[] = { 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x20, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x3a, 0x20, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x64, 0x20, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x3a, 0x20, 0x73, 0x65, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x72, 0x61, 0x63, 0x79, 0x20, 0x6d, 0x75, 0x73, 0x74, 0x20, 0x6e, 0x6f, 0x74, 0x20, 0x62, 0x65, 0x20, 0x75, 0x73, 0x65, 0x64, 0x20, 0x77, 0x69, 0x74, 0x68, 0x20, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x20, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73 };
static const unsigned char _bytes31[] = { 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x20, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x3a, 0x20, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x64, 0x20, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x3a, 0x20, 0x73, 0x65, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x72, 0x61, 0x63, 0x79, 0x20, 0x6d, 0x75, 0x73, 0x74, 0x20, 0x6e, 0x6f, 0x74, 0x20, 0x62, 0x65, 0x20, 0x75, 0x73, 0x65, 0x64, 0x20, 0x77, 0x69, 0x74, 0x68, 0x20, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x20, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73 };
static const unsigned char _bytes33[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6c, 0x6f, 0x67, 0x2d, 0x30, 0x2e, 0x34, 0x2e, 0x33, 0x32, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes32 = {   .f0 = (void *)_bytes33,   .f1 = { 0x5c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x06, 0x00, 0x00, 0x0d, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes34[] = { 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x65, 0x64, 0x20, 0x74, 0x6f, 0x20, 0x73, 0x65, 0x74, 0x20, 0x61, 0x20, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x20, 0x61, 0x66, 0x74, 0x65, 0x72, 0x20, 0x74, 0x68, 0x65, 0x20, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x20, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x20, 0x77, 0x61, 0x73, 0x20, 0x61, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x20, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64 };
static const unsigned char _bytes35[] = { 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x65, 0x64, 0x20, 0x74, 0x6f, 0x20, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x20, 0x61, 0x20, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x20, 0x74, 0x68, 0x61, 0x74, 0x20, 0x64, 0x6f, 0x65, 0x73, 0x6e, 0x27, 0x74, 0x20, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x20, 0x61, 0x6e, 0x20, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x20, 0x6c, 0x6f, 0x67, 0x20, 0x6c, 0x65, 0x76, 0x65, 0x6c };
static const unsigned char _bytes36[] = {  };
#pragma pack(push, 1)
static const struct {   unsigned char f0[24];   void *f1;   void *f2;   void *f3; } _bytes37 = {   .f0 = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },   .f1 = (void *)(void (*)(void))_RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log7enabled,   .f2 = (void *)(void (*)(void))_RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log3log,   .f3 = (void *)(void (*)(void))_RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log5flush };
#pragma pack(pop)
#pragma pack(push, 1)
static const struct {   unsigned char f0[24];   void *f1;   void *f2;   void *f3; } _bytes38 = {   .f0 = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },   .f1 = (void *)(void (*)(void))_RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log7enabled,   .f2 = (void *)(void (*)(void))_RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log3log,   .f3 = (void *)(void (*)(void))_RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log5flush };
#pragma pack(pop)
static const unsigned char _bytes40[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6c, 0x6f, 0x67, 0x2d, 0x30, 0x2e, 0x34, 0x2e, 0x33, 0x32, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes39 = {   .f0 = (void *)_bytes40,   .f1 = { 0x5c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x02, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes42[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6c, 0x6f, 0x67, 0x2d, 0x30, 0x2e, 0x34, 0x2e, 0x33, 0x32, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes41 = {   .f0 = (void *)_bytes42,   .f1 = { 0x5c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x02, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes44[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6c, 0x6f, 0x67, 0x2d, 0x30, 0x2e, 0x34, 0x2e, 0x33, 0x32, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes43 = {   .f0 = (void *)_bytes44,   .f1 = { 0x5c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x32, 0x02, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes46[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6c, 0x6f, 0x67, 0x2d, 0x30, 0x2e, 0x34, 0x2e, 0x33, 0x32, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes45 = {   .f0 = (void *)_bytes46,   .f1 = { 0x5c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9e, 0x02, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes48[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6c, 0x6f, 0x67, 0x2d, 0x30, 0x2e, 0x34, 0x2e, 0x33, 0x32, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes47 = {   .f0 = (void *)_bytes48,   .f1 = { 0x5c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9f, 0x02, 0x00, 0x00, 0x38, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes50[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x6c, 0x6f, 0x67, 0x2d, 0x30, 0x2e, 0x34, 0x2e, 0x33, 0x32, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes49 = {   .f0 = (void *)_bytes50,   .f1 = { 0x5c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xcb, 0x02, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00 } };
#pragma pack(pop)

struct _gs__RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES _RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES = { .f0 = (void *)_bytes24, .f1 = { 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, .f2 = (void *)_bytes25, .f3 = { 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, .f4 = (void *)_bytes26, .f5 = { 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, .f6 = (void *)_bytes27, .f7 = { 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, .f8 = (void *)_bytes28, .f9 = { 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, .f10 = (void *)_bytes29, .f11 = { 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } };
struct _gs__RNvCsdZu6hNdFJFF_3log16SET_LOGGER_ERROR _RNvCsdZu6hNdFJFF_3log16SET_LOGGER_ERROR = { .f0 = (void *)_bytes34, .f1 = { 0x4a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } };
struct _gs__RNvCsdZu6hNdFJFF_3log17LEVEL_PARSE_ERROR _RNvCsdZu6hNdFJFF_3log17LEVEL_PARSE_ERROR = { .f0 = (void *)_bytes35, .f1 = { 0x46, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } };
_Alignas(8) uint8_t _RNvCsdZu6hNdFJFF_3log20MAX_LOG_LEVEL_FILTER[8] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
_Alignas(8) uint8_t _RNvCsdZu6hNdFJFF_3log5STATE[8] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
struct _gs__RNvCsdZu6hNdFJFF_3log6LOGGER _RNvCsdZu6hNdFJFF_3log6LOGGER = { .f0 = (void *)_bytes36, .f1 = (void *)&_bytes37 };
uint8_t _RNvNvCsdZu6hNdFJFF_3log6logger3NOP[0];

static _Bool _RINvCsdZu6hNdFJFF_3log16set_logger_innerNCNvB2_10set_logger0EB2_(void * _arg0, void * _arg1) {
  _Alignas(1) uint8_t _t0_storage[1];
  void *_t0 = (void *)_t0_storage;
  _Alignas(8) uint8_t _t1_storage[16];
  void *_t1 = (void *)_t1_storage;
  _Alignas(1) uint8_t _t2_storage[1];
  void *_t2 = (void *)_t2_storage;
  int8_t _t3;
  void * _t4;
  _Alignas(8) uint8_t _t5_storage[16];
  void *_t5 = (void *)_t5_storage;
  void * _t6;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  struct _S9 _t7;
  uint64_t _t8;
  void * _t9;
  uint64_t _t10;
  __rustc_isize _t11;
  _Bool _t12;
  void * _t13;
  __rustc_usize _t14;
  _Bool _t15;
  int8_t _t16;
  struct _S12 _t17;
  void * _t18;
  void * _t19;
  void * _t20;
  void * _t21;
  int8_t _t22;
  void * _t23;
  __rustc_usize _t24;
  _Bool _t25;
  void * _t26;
  __rustc_usize _t27;
  _Bool _t28;
  int8_t _t29;
  _Bool _t30;
  int8_t _t31;
  _Bool _t32;
  _Bool _t33;
  void * _t34;
  void * _t35;
  int32_t _t36;

bb_0_start:
  _t3 = (int8_t)(1ULL);
  *(int8_t *)_t2 = _t3;
  _t4 = (void *)&_RNvCsdZu6hNdFJFF_3log5STATE;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t7 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic23atomic_compare_exchangejECsdZu6hNdFJFF_3log(_t4, 0ULL, 1ULL, 2ULL, 0ULL);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb14;
bb_1_bb13:
  _t33 = *(_Bool *)_t2;
  if (_t33) goto bb_19_bb12; else goto bb_18_bb10;
bb_2_cleanup:
  *(void * *)_t5 = __exn_ptr;
  _t6 = (void *)((__rustc_usize)_t5 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t6 = 0LL;
  goto bb_1_bb13;
bb_3_bb14:
  *(struct _S9 *)_t1 = _t7;
  _t8 = *(uint64_t *)_t1;
  _t9 = (void *)((__rustc_usize)_t1 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t10 = *(uint64_t *)_t9;
  _t11 = (__rustc_isize)_t8;
  _t12 = (_Bool)_t11;
  if (_t12) goto bb_4_bb3; else goto bb_5_bb2;
bb_4_bb3:
  _t23 = (void *)((__rustc_usize)_t1 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t24 = *(__rustc_usize *)_t23;
  _t25 = (__rustc_isize)_t24 == (__rustc_isize)1ULL;
  if (_t25) goto bb_11_bb6; else goto bb_7_bb1;
bb_5_bb2:
  _t13 = (void *)((__rustc_usize)_t1 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t14 = *(__rustc_usize *)_t13;
  _t15 = (__rustc_isize)_t14 == (__rustc_isize)0ULL;
  if (_t15) goto bb_6_bb4; else goto bb_7_bb1;
bb_6_bb4:
  _t16 = (int8_t)(0ULL);
  *(int8_t *)_t2 = _t16;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t17 = _RNCNvCsdZu6hNdFJFF_3log10set_logger0B3_(_arg0, _arg1);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_8_bb5;
bb_7_bb1:
  _t31 = (int8_t)(1ULL);
  *(int8_t *)_t0 = _t31;
  goto bb_15_bb11;
bb_8_bb5:
  _t18 = _t17.f0;
  _t19 = _t17.f1;
  *(void * *)&_RNvCsdZu6hNdFJFF_3log6LOGGER = _t18;
  _t20 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log6LOGGER + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t20 = _t19;
  _t21 = (void *)&_RNvCsdZu6hNdFJFF_3log5STATE;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic12atomic_storejECsdZu6hNdFJFF_3log(_t21, 2ULL, 1ULL);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_9_bb15;
bb_9_bb15:
  _t22 = (int8_t)(0ULL);
  *(int8_t *)_t0 = _t22;
  goto bb_10_bb9;
bb_10_bb9:
  _t32 = *(_Bool *)_t0;
  return _t32;
bb_11_bb6:
  _t26 = (void *)&_RNvCsdZu6hNdFJFF_3log5STATE;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t27 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadjECsdZu6hNdFJFF_3log(_t26, 0ULL);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_12_bb16;
bb_12_bb16:
  _t28 = (__rustc_isize)_t27 == (__rustc_isize)1ULL;
  if (_t28) goto bb_14_bb7; else goto bb_13_bb8;
bb_13_bb8:
  _t29 = (int8_t)(1ULL);
  *(int8_t *)_t0 = _t29;
  _t30 = *(_Bool *)_t2;
  if (_t30) goto bb_15_bb11; else goto bb_10_bb9;
bb_14_bb7:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _RINvNtNtNtCs41fFVwHnQdq_4core9core_arch10arm_shared7barrier5___isbNtNtB2_6common2SYECsdZu6hNdFJFF_3log();
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_16_bb17;
bb_15_bb11:
  goto bb_10_bb9;
bb_16_bb17:
  goto bb_11_bb6;
bb_17_bb18:
  abort();
bb_18_bb10:
  _t34 = *(void * *)_t5;
  _t35 = (void *)((__rustc_usize)_t5 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t36 = *(int32_t *)_t35;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t34; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
bb_19_bb12:
  goto bb_18_bb10;
}

static __rustc_usize _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadjECsdZu6hNdFJFF_3log(void * _arg0, uint8_t _arg1) {
  _Alignas(8) uint8_t _t37_storage[8];
  void *_t37 = (void *)_t37_storage;
  __rustc_isize _t38;
  __rustc_usize _t39;
  void * _t40;
  _Bool _t41;
  int32_t _t42;
  __rustc_usize _t43;
  __rustc_usize _t44;
  __rustc_usize _t45;
  void * _t46;
  _Bool _t47;
  __rustc_usize _t48;
  void * _t49;
  _Bool _t50;
  int32_t _t51;
  __rustc_usize _t52;
  __rustc_usize _t53;
  __rustc_usize _t54;
  void * _t55;
  _Bool _t56;
  __rustc_usize _t57;
  __rustc_usize _t58;

bb_0_start:
  _t38 = (__rustc_isize)_arg1;
  switch ((__rustc_usize)_t38) {
    case 0ULL: goto bb_2_bb6;
    case 1ULL: goto bb_3_bb3;
    case 2ULL: goto bb_4_bb5;
    case 3ULL: goto bb_5_bb2;
    case 4ULL: goto bb_6_bb4;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  abort();
bb_2_bb6:
  _t39 = atomic_load((_Atomic(__rustc_usize) *)_arg0);
  *(__rustc_usize *)_t37 = _t39;
  goto bb_7_bb7;
bb_3_bb3:
  _t40 = (void *)_bytes0;
  _t41 = (int64_t)_t40 != (int64_t)0;
  _t42 = 1LL & 63LL;
  _t43 = (__rustc_usize)(uint32_t)_t42;
  _t44 = (__rustc_usize)(40ULL) << (_t43);
  _t45 = _t44 | 1ULL;
  _t46 = (void *)_t45;
  _t47 = (int64_t)_t46 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t40, _t46, &_bytes2);
  abort();
bb_4_bb5:
  _t48 = atomic_load((_Atomic(__rustc_usize) *)_arg0);
  *(__rustc_usize *)_t37 = _t48;
  goto bb_7_bb7;
bb_5_bb2:
  _t49 = (void *)_bytes4;
  _t50 = (int64_t)_t49 != (int64_t)0;
  _t51 = 1LL & 63LL;
  _t52 = (__rustc_usize)(uint32_t)_t51;
  _t53 = (__rustc_usize)(49ULL) << (_t52);
  _t54 = _t53 | 1ULL;
  _t55 = (void *)_t54;
  _t56 = (int64_t)_t55 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t49, _t55, &_bytes6);
  abort();
bb_6_bb4:
  _t57 = atomic_load((_Atomic(__rustc_usize) *)_arg0);
  *(__rustc_usize *)_t37 = _t57;
  goto bb_7_bb7;
bb_7_bb7:
  _t58 = *(__rustc_usize *)_t37;
  return _t58;
}

static void _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic12atomic_storejECsdZu6hNdFJFF_3log(void * _arg0, __rustc_usize _arg1, uint8_t _arg2) {
  __rustc_isize _t59;
  void * _t60;
  _Bool _t61;
  int32_t _t62;
  __rustc_usize _t63;
  __rustc_usize _t64;
  __rustc_usize _t65;
  void * _t66;
  _Bool _t67;
  void * _t68;
  _Bool _t69;
  int32_t _t70;
  __rustc_usize _t71;
  __rustc_usize _t72;
  __rustc_usize _t73;
  void * _t74;
  _Bool _t75;

bb_0_start:
  _t59 = (__rustc_isize)_arg2;
  switch ((__rustc_usize)_t59) {
    case 0ULL: goto bb_2_bb6;
    case 1ULL: goto bb_3_bb5;
    case 2ULL: goto bb_4_bb3;
    case 3ULL: goto bb_5_bb2;
    case 4ULL: goto bb_6_bb4;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  abort();
bb_2_bb6:
  atomic_store((_Atomic(__rustc_usize) *)_arg0, _arg1);
  goto bb_7_bb7;
bb_3_bb5:
  atomic_store((_Atomic(__rustc_usize) *)_arg0, _arg1);
  goto bb_7_bb7;
bb_4_bb3:
  _t60 = (void *)_bytes8;
  _t61 = (int64_t)_t60 != (int64_t)0;
  _t62 = 1LL & 63LL;
  _t63 = (__rustc_usize)(uint32_t)_t62;
  _t64 = (__rustc_usize)(42ULL) << (_t63);
  _t65 = _t64 | 1ULL;
  _t66 = (void *)_t65;
  _t67 = (int64_t)_t66 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t60, _t66, &_bytes10);
  abort();
bb_5_bb2:
  _t68 = (void *)_bytes12;
  _t69 = (int64_t)_t68 != (int64_t)0;
  _t70 = 1LL & 63LL;
  _t71 = (__rustc_usize)(uint32_t)_t70;
  _t72 = (__rustc_usize)(50ULL) << (_t71);
  _t73 = _t72 | 1ULL;
  _t74 = (void *)_t73;
  _t75 = (int64_t)_t74 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t68, _t74, &_bytes14);
  abort();
bb_6_bb4:
  atomic_store((_Atomic(__rustc_usize) *)_arg0, _arg1);
  goto bb_7_bb7;
bb_7_bb7:
  return;
}

static struct _S9 _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic23atomic_compare_exchangejECsdZu6hNdFJFF_3log(void * _arg0, __rustc_usize _arg1, __rustc_usize _arg2, uint8_t _arg3, uint8_t _arg4) {
  _Alignas(8) uint8_t _t76_storage[16];
  void *_t76 = (void *)_t76_storage;
  _Alignas(8) uint8_t _t77_storage[16];
  void *_t77 = (void *)_t77_storage;
  __rustc_isize _t78;
  __rustc_isize _t79;
  __rustc_usize _t80;
  _Bool _t81;
  int8_t _t82;
  void * _t83;
  __rustc_usize _t84;
  _Bool _t85;
  int8_t _t86;
  void * _t87;
  __rustc_usize _t88;
  _Bool _t89;
  int8_t _t90;
  void * _t91;
  __rustc_isize _t92;
  __rustc_usize _t93;
  _Bool _t94;
  int8_t _t95;
  void * _t96;
  __rustc_usize _t97;
  _Bool _t98;
  int8_t _t99;
  void * _t100;
  __rustc_usize _t101;
  _Bool _t102;
  int8_t _t103;
  void * _t104;
  __rustc_isize _t105;
  __rustc_usize _t106;
  _Bool _t107;
  int8_t _t108;
  void * _t109;
  __rustc_usize _t110;
  _Bool _t111;
  int8_t _t112;
  void * _t113;
  __rustc_usize _t114;
  _Bool _t115;
  int8_t _t116;
  void * _t117;
  __rustc_isize _t118;
  __rustc_usize _t119;
  _Bool _t120;
  int8_t _t121;
  void * _t122;
  __rustc_usize _t123;
  _Bool _t124;
  int8_t _t125;
  void * _t126;
  __rustc_usize _t127;
  _Bool _t128;
  int8_t _t129;
  void * _t130;
  __rustc_isize _t131;
  __rustc_usize _t132;
  _Bool _t133;
  int8_t _t134;
  void * _t135;
  __rustc_usize _t136;
  _Bool _t137;
  int8_t _t138;
  void * _t139;
  __rustc_usize _t140;
  _Bool _t141;
  int8_t _t142;
  void * _t143;
  __rustc_usize _t144;
  void * _t145;
  _Bool _t146;
  void * _t147;
  void * _t148;
  uint64_t _t149;
  void * _t150;
  uint64_t _t151;
  struct _S9 _t152;
  struct _S9 _t153;
  __rustc_isize _t154;
  void * _t155;
  _Bool _t156;
  int32_t _t157;
  __rustc_usize _t158;
  __rustc_usize _t159;
  __rustc_usize _t160;
  void * _t161;
  _Bool _t162;
  void * _t163;
  _Bool _t164;
  int32_t _t165;
  __rustc_usize _t166;
  __rustc_usize _t167;
  __rustc_usize _t168;
  void * _t169;
  _Bool _t170;

bb_0_start:
  _t78 = (__rustc_isize)_arg3;
  switch ((__rustc_usize)_t78) {
    case 0ULL: goto bb_2_bb2;
    case 1ULL: goto bb_3_bb4;
    case 2ULL: goto bb_4_bb3;
    case 3ULL: goto bb_5_bb5;
    case 4ULL: goto bb_6_bb6;
    default: goto bb_1_bb7;
  }
bb_1_bb7:
  abort();
bb_2_bb2:
  _t79 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t79) {
    case 0ULL: goto bb_8_bb24;
    case 2ULL: goto bb_9_bb23;
    case 4ULL: goto bb_10_bb22;
    default: goto bb_7_bb1;
  }
bb_3_bb4:
  _t92 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t92) {
    case 0ULL: goto bb_12_bb18;
    case 2ULL: goto bb_13_bb17;
    case 4ULL: goto bb_14_bb16;
    default: goto bb_7_bb1;
  }
bb_4_bb3:
  _t105 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t105) {
    case 0ULL: goto bb_15_bb21;
    case 2ULL: goto bb_16_bb20;
    case 4ULL: goto bb_17_bb19;
    default: goto bb_7_bb1;
  }
bb_5_bb5:
  _t118 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t118) {
    case 0ULL: goto bb_18_bb15;
    case 2ULL: goto bb_19_bb14;
    case 4ULL: goto bb_20_bb13;
    default: goto bb_7_bb1;
  }
bb_6_bb6:
  _t131 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t131) {
    case 0ULL: goto bb_21_bb12;
    case 2ULL: goto bb_22_bb11;
    case 4ULL: goto bb_23_bb10;
    default: goto bb_7_bb1;
  }
bb_7_bb1:
  _t154 = (__rustc_isize)_arg4;
  switch ((__rustc_usize)_t154) {
    case 1ULL: goto bb_27_bb8;
    case 3ULL: goto bb_28_bb9;
    default: goto bb_1_bb7;
  }
bb_8_bb24:
  _t80 = _arg1;
  _t81 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t80, _arg2);
  _t82 = (int8_t)(_t81);
  *(__rustc_usize *)_t77 = _t80;
  _t83 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t83 = _t82;
  goto bb_11_bb25;
bb_9_bb23:
  _t84 = _arg1;
  _t85 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t84, _arg2);
  _t86 = (int8_t)(_t85);
  *(__rustc_usize *)_t77 = _t84;
  _t87 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t87 = _t86;
  goto bb_11_bb25;
bb_10_bb22:
  _t88 = _arg1;
  _t89 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t88, _arg2);
  _t90 = (int8_t)(_t89);
  *(__rustc_usize *)_t77 = _t88;
  _t91 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t91 = _t90;
  goto bb_11_bb25;
bb_11_bb25:
  _t144 = *(__rustc_usize *)_t77;
  _t145 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t146 = *(_Bool *)_t145;
  if (_t146) goto bb_25_bb26; else goto bb_24_bb27;
bb_12_bb18:
  _t93 = _arg1;
  _t94 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t93, _arg2);
  _t95 = (int8_t)(_t94);
  *(__rustc_usize *)_t77 = _t93;
  _t96 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t96 = _t95;
  goto bb_11_bb25;
bb_13_bb17:
  _t97 = _arg1;
  _t98 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t97, _arg2);
  _t99 = (int8_t)(_t98);
  *(__rustc_usize *)_t77 = _t97;
  _t100 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t100 = _t99;
  goto bb_11_bb25;
bb_14_bb16:
  _t101 = _arg1;
  _t102 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t101, _arg2);
  _t103 = (int8_t)(_t102);
  *(__rustc_usize *)_t77 = _t101;
  _t104 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t104 = _t103;
  goto bb_11_bb25;
bb_15_bb21:
  _t106 = _arg1;
  _t107 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t106, _arg2);
  _t108 = (int8_t)(_t107);
  *(__rustc_usize *)_t77 = _t106;
  _t109 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t109 = _t108;
  goto bb_11_bb25;
bb_16_bb20:
  _t110 = _arg1;
  _t111 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t110, _arg2);
  _t112 = (int8_t)(_t111);
  *(__rustc_usize *)_t77 = _t110;
  _t113 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t113 = _t112;
  goto bb_11_bb25;
bb_17_bb19:
  _t114 = _arg1;
  _t115 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t114, _arg2);
  _t116 = (int8_t)(_t115);
  *(__rustc_usize *)_t77 = _t114;
  _t117 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t117 = _t116;
  goto bb_11_bb25;
bb_18_bb15:
  _t119 = _arg1;
  _t120 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t119, _arg2);
  _t121 = (int8_t)(_t120);
  *(__rustc_usize *)_t77 = _t119;
  _t122 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t122 = _t121;
  goto bb_11_bb25;
bb_19_bb14:
  _t123 = _arg1;
  _t124 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t123, _arg2);
  _t125 = (int8_t)(_t124);
  *(__rustc_usize *)_t77 = _t123;
  _t126 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t126 = _t125;
  goto bb_11_bb25;
bb_20_bb13:
  _t127 = _arg1;
  _t128 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t127, _arg2);
  _t129 = (int8_t)(_t128);
  *(__rustc_usize *)_t77 = _t127;
  _t130 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t130 = _t129;
  goto bb_11_bb25;
bb_21_bb12:
  _t132 = _arg1;
  _t133 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t132, _arg2);
  _t134 = (int8_t)(_t133);
  *(__rustc_usize *)_t77 = _t132;
  _t135 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t135 = _t134;
  goto bb_11_bb25;
bb_22_bb11:
  _t136 = _arg1;
  _t137 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t136, _arg2);
  _t138 = (int8_t)(_t137);
  *(__rustc_usize *)_t77 = _t136;
  _t139 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t139 = _t138;
  goto bb_11_bb25;
bb_23_bb10:
  _t140 = _arg1;
  _t141 = atomic_compare_exchange_strong((_Atomic(__rustc_usize) *)_arg0, &_t140, _arg2);
  _t142 = (int8_t)(_t141);
  *(__rustc_usize *)_t77 = _t140;
  _t143 = (void *)((__rustc_usize)_t77 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int8_t *)_t143 = _t142;
  goto bb_11_bb25;
bb_24_bb27:
  _t147 = (void *)((__rustc_usize)_t76 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t147 = _t144;
  *(uint64_t *)_t76 = 1ULL;
  goto bb_26_bb28;
bb_25_bb26:
  _t148 = (void *)((__rustc_usize)_t76 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t148 = _t144;
  *(uint64_t *)_t76 = 0ULL;
  goto bb_26_bb28;
bb_26_bb28:
  _t149 = *(uint64_t *)_t76;
  _t150 = (void *)((__rustc_usize)_t76 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t151 = *(uint64_t *)_t150;
  memset(&_t152, 0, sizeof(_t152));
  _t152.f0 = _t149;
  _t153 = _t152;
  _t153.f1 = _t151;
  return _t153;
bb_27_bb8:
  _t155 = (void *)_bytes16;
  _t156 = (int64_t)_t155 != (int64_t)0;
  _t157 = 1LL & 63LL;
  _t158 = (__rustc_usize)(uint32_t)_t157;
  _t159 = (__rustc_usize)(52ULL) << (_t158);
  _t160 = _t159 | 1ULL;
  _t161 = (void *)_t160;
  _t162 = (int64_t)_t161 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t155, _t161, &_bytes18);
  abort();
bb_28_bb9:
  _t163 = (void *)_bytes20;
  _t164 = (int64_t)_t163 != (int64_t)0;
  _t165 = 1LL & 63LL;
  _t166 = (__rustc_usize)(uint32_t)_t165;
  _t167 = (__rustc_usize)(61ULL) << (_t166);
  _t168 = _t167 | 1ULL;
  _t169 = (void *)_t168;
  _t170 = (int64_t)_t169 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t163, _t169, &_bytes22);
  abort();
}

static void _RINvNtNtNtCs41fFVwHnQdq_4core9core_arch10arm_shared7barrier5___isbNtNtB2_6common2SYECsdZu6hNdFJFF_3log(void) {
  _Alignas(1) uint8_t _t171_storage[0];
  void *_t171 = (void *)_t171_storage;
  _Alignas(8) uint8_t _t172_storage[16];
  void *_t172 = (void *)_t172_storage;
  void * _t173;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t174;
  void * _t175;
  int32_t _t176;

bb_0_start:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _RNvXNtNtNtNtCs41fFVwHnQdq_4core9core_arch10arm_shared7barrier6commonNtB2_2SYNtNtB6_6sealed3Isb5___isb(_t171);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb1;
bb_1_bb3:
  _t174 = *(void * *)_t172;
  _t175 = (void *)((__rustc_usize)_t172 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t176 = *(int32_t *)_t175;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t174; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
bb_2_cleanup:
  *(void * *)_t172 = __exn_ptr;
  _t173 = (void *)((__rustc_usize)_t172 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t173 = 0LL;
  goto bb_1_bb3;
bb_3_bb1:
  return;
}

static struct _S12 _RNCNvCsdZu6hNdFJFF_3log10set_logger0B3_(void * _arg0, void * _arg1) {
  struct _S12 _t177;
  struct _S12 _t178;

bb_0_start:
  memset(&_t177, 0, sizeof(_t177));
  _t177.f0 = _arg0;
  _t178 = _t177;
  _t178.f1 = _arg1;
  return _t178;
}

#pragma weak _RNvCsdZu6hNdFJFF_3log10set_logger
_Bool _RNvCsdZu6hNdFJFF_3log10set_logger(void * _arg0, void * _arg1) {
  _Bool _t179;
  _Bool _t180;

bb_0_start:
  _t179 = _RINvCsdZu6hNdFJFF_3log16set_logger_innerNCNvB2_10set_logger0EB2_(_arg0, _arg1);
  _t180 = (_Bool)(_t179);
  return _t180;
}

#pragma weak _RNvCsdZu6hNdFJFF_3log15set_logger_racy
_Bool _RNvCsdZu6hNdFJFF_3log15set_logger_racy(void * _arg0, void * _arg1) {
  _Alignas(1) uint8_t _t181_storage[1];
  void *_t181 = (void *)_t181_storage;
  void * _t182;
  __rustc_usize _t183;
  void * _t184;
  void * _t185;
  int8_t _t186;
  void * _t187;
  _Bool _t188;
  int32_t _t189;
  __rustc_usize _t190;
  __rustc_usize _t191;
  __rustc_usize _t192;
  void * _t193;
  _Bool _t194;
  int8_t _t195;
  _Bool _t196;

bb_0_start:
  _t182 = (void *)&_RNvCsdZu6hNdFJFF_3log5STATE;
  _t183 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadjECsdZu6hNdFJFF_3log(_t182, 2ULL);
  switch (_t183) {
    case 0ULL: goto bb_2_bb3;
    case 1ULL: goto bb_3_bb2;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  _t195 = (int8_t)(1ULL);
  *(int8_t *)_t181 = _t195;
  goto bb_4_bb4;
bb_2_bb3:
  *(void * *)&_RNvCsdZu6hNdFJFF_3log6LOGGER = _arg0;
  _t184 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log6LOGGER + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t184 = _arg1;
  _t185 = (void *)&_RNvCsdZu6hNdFJFF_3log5STATE;
  _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic12atomic_storejECsdZu6hNdFJFF_3log(_t185, 2ULL, 1ULL);
  _t186 = (int8_t)(0ULL);
  *(int8_t *)_t181 = _t186;
  goto bb_4_bb4;
bb_3_bb2:
  _t187 = (void *)_bytes30;
  _t188 = (int64_t)_t187 != (int64_t)0;
  _t189 = 1LL & 63LL;
  _t190 = (__rustc_usize)(uint32_t)_t189;
  _t191 = (__rustc_usize)(110ULL) << (_t190);
  _t192 = _t191 | 1ULL;
  _t193 = (void *)_t192;
  _t194 = (int64_t)_t193 != (int64_t)0;
  _RNvNtCs41fFVwHnQdq_4core9panicking9panic_fmt(_t187, _t193, &_bytes32);
  abort();
bb_4_bb4:
  _t196 = *(_Bool *)_t181;
  return _t196;
}

#pragma weak _RNvCsdZu6hNdFJFF_3log6logger
struct _S12 _RNvCsdZu6hNdFJFF_3log6logger(void) {
  _Alignas(8) uint8_t _t197_storage[16];
  void *_t197 = (void *)_t197_storage;
  void * _t198;
  __rustc_usize _t199;
  _Bool _t200;
  void * _t201;
  void * _t202;
  void * _t203;
  void * _t204;
  void * _t205;
  void * _t206;
  void * _t207;
  void * _t208;
  struct _S12 _t209;
  struct _S12 _t210;

bb_0_start:
  _t198 = (void *)&_RNvCsdZu6hNdFJFF_3log5STATE;
  _t199 = _RINvNtNtCs41fFVwHnQdq_4core4sync6atomic11atomic_loadjECsdZu6hNdFJFF_3log(_t198, 2ULL);
  _t200 = (__rustc_isize)_t199 != (__rustc_isize)2ULL;
  if (_t200) goto bb_2_bb1; else goto bb_1_bb2;
bb_1_bb2:
  _t201 = *(void * *)&_RNvCsdZu6hNdFJFF_3log6LOGGER;
  _t202 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log6LOGGER + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t203 = *(void * *)_t202;
  *(void * *)_t197 = _t201;
  _t204 = (void *)((__rustc_usize)_t197 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t204 = _t203;
  goto bb_3_bb3;
bb_2_bb1:
  *(void * *)_t197 = &_RNvNvCsdZu6hNdFJFF_3log6logger3NOP;
  _t205 = (void *)((__rustc_usize)_t197 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t205 = &_bytes38;
  goto bb_3_bb3;
bb_3_bb3:
  _t206 = *(void * *)_t197;
  _t207 = (void *)((__rustc_usize)_t197 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t208 = *(void * *)_t207;
  memset(&_t209, 0, sizeof(_t209));
  _t209.f0 = _t206;
  _t210 = _t209;
  _t210.f1 = _t208;
  return _t210;
}

static _Bool _RNvMNtNtCs41fFVwHnQdq_4core5slice5asciiSh20eq_ignore_ascii_case(void * _arg0, __rustc_usize _arg1, void * _arg2, __rustc_usize _arg3) {
  _Alignas(8) uint8_t _t211_storage[16];
  void *_t211 = (void *)_t211_storage;
  void * _t212;
  _Alignas(8) uint8_t _t213_storage[16];
  void *_t213 = (void *)_t213_storage;
  void * _t214;
  _Alignas(1) uint8_t _t215_storage[1];
  void *_t215 = (void *)_t215_storage;
  _Alignas(1) uint8_t _t216_storage[1];
  void *_t216 = (void *)_t216_storage;
  _Alignas(1) uint8_t _t217_storage[1];
  void *_t217 = (void *)_t217_storage;
  void * _t218;
  void * _t219;
  __rustc_usize _t220;
  void * _t221;
  void * _t222;
  __rustc_usize _t223;
  _Bool _t224;
  void * _t225;
  void * _t226;
  __rustc_usize _t227;
  _Bool _t228;
  void * _t229;
  void * _t230;
  __rustc_usize _t231;
  _Bool _t232;
  int8_t _t233;
  void * _t234;
  void * _t235;
  __rustc_usize _t236;
  void * _t237;
  __rustc_usize _t238;
  void * _t239;
  void * _t240;
  __rustc_usize _t241;
  void * _t242;
  __rustc_usize _t243;
  void * _t244;
  void * _t245;
  __rustc_usize _t246;
  void * _t247;
  uint8_t _t248;
  _Bool _t249;
  int8_t _t250;
  _Bool _t251;
  int8_t _t252;
  _Bool _t253;
  _Bool _t254;
  uint8_t _t255;
  uint8_t _t256;
  uint8_t _t257;
  void * _t258;
  void * _t259;
  __rustc_usize _t260;
  void * _t261;
  uint8_t _t262;
  _Bool _t263;
  int8_t _t264;
  _Bool _t265;
  int8_t _t266;
  _Bool _t267;
  _Bool _t268;
  uint8_t _t269;
  uint8_t _t270;
  uint8_t _t271;
  _Bool _t272;
  int8_t _t273;
  void * _t274;
  void * _t275;
  int8_t _t276;
  _Bool _t277;

bb_0_start:
  *(void * *)_t211 = _arg0;
  _t212 = (void *)((__rustc_usize)_t211 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t212 = _arg1;
  *(void * *)_t213 = _arg2;
  _t214 = (void *)((__rustc_usize)_t213 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t214 = _arg3;
  _t218 = *(void * *)_t211;
  _t219 = (void *)((__rustc_usize)_t211 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t220 = *(__rustc_usize *)_t219;
  _t221 = *(void * *)_t213;
  _t222 = (void *)((__rustc_usize)_t213 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t223 = *(__rustc_usize *)_t222;
  _t224 = (__rustc_isize)_t220 != (__rustc_isize)_t223;
  if (_t224) goto bb_2_bb1; else goto bb_1_bb2;
bb_1_bb2:
  goto bb_3_bb3;
bb_2_bb1:
  _t276 = (int8_t)(0ULL);
  *(int8_t *)_t215 = _t276;
  goto bb_7_bb9;
bb_3_bb3:
  _t225 = *(void * *)_t211;
  _t226 = (void *)((__rustc_usize)_t211 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t227 = *(__rustc_usize *)_t226;
  _t228 = (__rustc_usize)_t227 >= (__rustc_usize)1ULL;
  if (_t228) goto bb_5_bb4; else goto bb_4_bb8;
bb_4_bb8:
  _t233 = (int8_t)(1ULL);
  *(int8_t *)_t215 = _t233;
  goto bb_7_bb9;
bb_5_bb4:
  _t229 = *(void * *)_t213;
  _t230 = (void *)((__rustc_usize)_t213 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t231 = *(__rustc_usize *)_t230;
  _t232 = (__rustc_usize)_t231 >= (__rustc_usize)1ULL;
  if (_t232) goto bb_6_bb5; else goto bb_4_bb8;
bb_6_bb5:
  _t234 = *(void * *)_t211;
  _t235 = (void *)((__rustc_usize)_t211 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t236 = *(__rustc_usize *)_t235;
  _t237 = (void *)((__rustc_usize)_t234 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint8_t));
  _t238 = _t236 - 1ULL;
  _t239 = *(void * *)_t213;
  _t240 = (void *)((__rustc_usize)_t213 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t241 = *(__rustc_usize *)_t240;
  _t242 = (void *)((__rustc_usize)_t239 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(uint8_t));
  _t243 = _t241 - 1ULL;
  _t244 = *(void * *)_t211;
  _t245 = (void *)((__rustc_usize)_t211 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t246 = *(__rustc_usize *)_t245;
  _t247 = (void *)((__rustc_usize)_t244 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint8_t));
  _t248 = *(uint8_t *)_t247;
  _t249 = (uint8_t)65ULL <= (uint8_t)_t248;
  if (_t249) goto bb_9_bb12; else goto bb_8_bb11;
bb_7_bb9:
  _t277 = *(_Bool *)_t215;
  return _t277;
bb_8_bb11:
  _t250 = (int8_t)(0ULL);
  *(int8_t *)_t216 = _t250;
  goto bb_10_bb10;
bb_9_bb12:
  _t251 = (uint8_t)_t248 <= (uint8_t)90ULL;
  _t252 = (int8_t)(_t251);
  *(int8_t *)_t216 = _t252;
  goto bb_10_bb10;
bb_10_bb10:
  _t253 = *(_Bool *)_t216;
  _t254 = (_Bool)_t253 <= (_Bool)1ULL;
  _t255 = (uint8_t)_t253;
  _t256 = _t255 * 32ULL;
  _t257 = _t248 | _t256;
  _t258 = *(void * *)_t213;
  _t259 = (void *)((__rustc_usize)_t213 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t260 = *(__rustc_usize *)_t259;
  _t261 = (void *)((__rustc_usize)_t258 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(uint8_t));
  _t262 = *(uint8_t *)_t261;
  _t263 = (uint8_t)65ULL <= (uint8_t)_t262;
  if (_t263) goto bb_12_bb15; else goto bb_11_bb14;
bb_11_bb14:
  _t264 = (int8_t)(0ULL);
  *(int8_t *)_t217 = _t264;
  goto bb_13_bb13;
bb_12_bb15:
  _t265 = (uint8_t)_t262 <= (uint8_t)90ULL;
  _t266 = (int8_t)(_t265);
  *(int8_t *)_t217 = _t266;
  goto bb_13_bb13;
bb_13_bb13:
  _t267 = *(_Bool *)_t217;
  _t268 = (_Bool)_t267 <= (_Bool)1ULL;
  _t269 = (uint8_t)_t267;
  _t270 = _t269 * 32ULL;
  _t271 = _t262 | _t270;
  _t272 = (int8_t)_t257 == (int8_t)_t271;
  if (_t272) goto bb_15_bb6; else goto bb_14_bb7;
bb_14_bb7:
  _t273 = (int8_t)(0ULL);
  *(int8_t *)_t215 = _t273;
  goto bb_7_bb9;
bb_15_bb6:
  *(void * *)_t211 = _t237;
  _t274 = (void *)((__rustc_usize)_t211 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t274 = _t238;
  *(void * *)_t213 = _t242;
  _t275 = (void *)((__rustc_usize)_t213 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t275 = _t243;
  goto bb_3_bb3;
}

static void _RNvXNtNtNtNtCs41fFVwHnQdq_4core9core_arch10arm_shared7barrier6commonNtB2_2SYNtNtB6_6sealed3Isb5___isb(void * _arg0) {
bb_0_start:
  return;
}

#pragma weak _RNvXs0_CsdZu6hNdFJFF_3logNtB5_5LevelNtNtNtCs41fFVwHnQdq_4core3str6traits7FromStr8from_str
uint64_t _RNvXs0_CsdZu6hNdFJFF_3logNtB5_5LevelNtNtNtCs41fFVwHnQdq_4core3str6traits7FromStr8from_str(void * _arg0, __rustc_usize _arg1) {
  _Alignas(8) uint8_t _t278_storage[8];
  void *_t278 = (void *)_t278_storage;
  _Alignas(8) uint8_t _t279_storage[16];
  void *_t279 = (void *)_t279_storage;
  _Alignas(8) uint8_t _t280_storage[8];
  void *_t280 = (void *)_t280_storage;
  _Alignas(8) uint8_t _t281_storage[8];
  void *_t281 = (void *)_t281_storage;
  __rustc_usize _t282;
  _Bool _t283;
  __rustc_usize _t284;
  uint64_t _t285;
  void * _t286;
  void * _t287;
  __rustc_usize _t288;
  _Bool _t289;
  void * _t290;
  void * _t291;
  void * _t292;
  __rustc_usize _t293;
  _Bool _t294;
  _Bool _t295;
  uint64_t _t296;
  uint64_t _t297;

bb_0_start:
  *(__rustc_usize *)_t281 = 1ULL;
  goto bb_1_bb1;
bb_1_bb1:
  _t282 = *(__rustc_usize *)_t281;
  _t283 = (__rustc_usize)_t282 < (__rustc_usize)6ULL;
  if (_t283) goto bb_3_bb6; else goto bb_2_bb7;
bb_2_bb7:
  *(uint64_t *)_t278 = 0ULL;
  goto bb_4_bb5;
bb_3_bb6:
  _t284 = *(__rustc_usize *)_t281;
  _t285 = _t284 + 1ULL;
  *(uint64_t *)_t281 = _t285;
  _t286 = (void *)((__rustc_usize)_t279 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t286 = _t284;
  *(uint64_t *)_t279 = 1ULL;
  _t287 = (void *)((__rustc_usize)_t279 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t288 = *(__rustc_usize *)_t287;
  _t289 = (__rustc_usize)_t288 < (__rustc_usize)6ULL;
  if (_t289) goto bb_5_bb2; else goto bb_6_panic;
bb_4_bb5:
  _t297 = *(uint64_t *)_t278;
  return _t297;
bb_5_bb2:
  _t290 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES + (__rustc_isize)(_t288) * (__rustc_isize)sizeof(struct _S32));
  _t291 = *(void * *)_t290;
  _t292 = (void *)((__rustc_usize)_t290 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t293 = *(__rustc_usize *)_t292;
  _t294 = _RNvMNtNtCs41fFVwHnQdq_4core5slice5asciiSh20eq_ignore_ascii_case(_t291, _t293, _arg0, _arg1);
  _t295 = (_Bool)(_t294);
  if (_t295) goto bb_8_bb3; else goto bb_7_bb4;
bb_6_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(_t288, 6ULL, &_bytes39);
  abort();
bb_7_bb4:
  goto bb_1_bb1;
bb_8_bb3:
  switch (_t288) {
    case 1ULL: goto bb_10_bb14;
    case 2ULL: goto bb_11_bb13;
    case 3ULL: goto bb_12_bb12;
    case 4ULL: goto bb_13_bb11;
    case 5ULL: goto bb_14_bb10;
    default: goto bb_9_bb9;
  }
bb_9_bb9:
  _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(&_bytes41);
  abort();
bb_10_bb14:
  *(uint64_t *)_t280 = 1ULL;
  goto bb_15_bb15;
bb_11_bb13:
  *(uint64_t *)_t280 = 2ULL;
  goto bb_15_bb15;
bb_12_bb12:
  *(uint64_t *)_t280 = 3ULL;
  goto bb_15_bb15;
bb_13_bb11:
  *(uint64_t *)_t280 = 4ULL;
  goto bb_15_bb15;
bb_14_bb10:
  *(uint64_t *)_t280 = 5ULL;
  goto bb_15_bb15;
bb_15_bb15:
  _t296 = *(uint64_t *)_t280;
  *(uint64_t *)_t278 = _t296;
  goto bb_4_bb5;
}

#pragma weak _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log3log
void _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log3log(void * _arg0, void * _arg1) {
  struct _S12 _t298;
  void * _t299;
  void * _t300;
  void * _t301;
  void (*_t302)(void *, void *);

bb_0_start:
  _t298 = _RNvCsdZu6hNdFJFF_3log6logger();
  _t299 = _t298.f0;
  _t300 = _t298.f1;
  _t301 = (void *)((__rustc_usize)_t300 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  _t302 = *(void (**)(void *, void *))_t301;
  ((void (*)(void *, void *))_t302)(_t299, _arg1);
  return;
}

#pragma weak _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log5flush
void _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log5flush(void * _arg0) {
  struct _S12 _t303;
  void * _t304;
  void * _t305;
  void * _t306;
  void (*_t307)(void *);

bb_0_start:
  _t303 = _RNvCsdZu6hNdFJFF_3log6logger();
  _t304 = _t303.f0;
  _t305 = _t303.f1;
  _t306 = (void *)((__rustc_usize)_t305 + (__rustc_isize)(40ULL) * (__rustc_isize)sizeof(int8_t));
  _t307 = *(void (**)(void *))_t306;
  ((void (*)(void *))_t307)(_t304);
  return;
}

#pragma weak _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log7enabled
_Bool _RNvXs0_NtCsdZu6hNdFJFF_3log13___private_apiNtB5_12GlobalLoggerNtB7_3Log7enabled(void * _arg0, void * _arg1) {
  struct _S12 _t308;
  void * _t309;
  void * _t310;
  void * _t311;
  _Bool (*_t312)(void *, void *);
  _Bool _t313;
  _Bool _t314;

bb_0_start:
  _t308 = _RNvCsdZu6hNdFJFF_3log6logger();
  _t309 = _t308.f0;
  _t310 = _t308.f1;
  _t311 = (void *)((__rustc_usize)_t310 + (__rustc_isize)(24ULL) * (__rustc_isize)sizeof(int8_t));
  _t312 = *(_Bool (**)(void *, void *))_t311;
  _t313 = ((_Bool (*)(void *, void *))_t312)(_t309, _arg1);
  _t314 = (_Bool)(_t313);
  return _t314;
}

#pragma weak _RNvXs1_CsdZu6hNdFJFF_3logNtB5_5LevelNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt
_Bool _RNvXs1_CsdZu6hNdFJFF_3logNtB5_5LevelNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void * _arg0, void * _arg1) {
  uint64_t _t315;
  __rustc_usize _t316;
  _Bool _t317;
  void * _t318;
  void * _t319;
  void * _t320;
  __rustc_usize _t321;
  _Bool _t322;
  _Bool _t323;

bb_0_start:
  _t315 = *(uint64_t *)_arg0;
  _t316 = (__rustc_usize)_t315;
  _t317 = (__rustc_usize)_t316 < (__rustc_usize)6ULL;
  if (_t317) goto bb_1_bb2; else goto bb_2_panic;
bb_1_bb2:
  _t318 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES + (__rustc_isize)(_t316) * (__rustc_isize)sizeof(struct _S32));
  _t319 = *(void * *)_t318;
  _t320 = (void *)((__rustc_usize)_t318 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t321 = *(__rustc_usize *)_t320;
  _t322 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter3pad(_arg1, _t319, _t321);
  _t323 = (_Bool)(_t322);
  return _t323;
bb_2_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(_t316, 6ULL, &_bytes43);
  abort();
}

#pragma weak _RNvXs5_CsdZu6hNdFJFF_3logNtB5_11LevelFilterNtNtNtCs41fFVwHnQdq_4core3str6traits7FromStr8from_str
uint64_t _RNvXs5_CsdZu6hNdFJFF_3logNtB5_11LevelFilterNtNtNtCs41fFVwHnQdq_4core3str6traits7FromStr8from_str(void * _arg0, __rustc_usize _arg1) {
  _Alignas(8) uint8_t _t324_storage[8];
  void *_t324 = (void *)_t324_storage;
  _Alignas(8) uint8_t _t325_storage[16];
  void *_t325 = (void *)_t325_storage;
  _Alignas(8) uint8_t _t326_storage[8];
  void *_t326 = (void *)_t326_storage;
  _Alignas(8) uint8_t _t327_storage[8];
  void *_t327 = (void *)_t327_storage;
  __rustc_usize _t328;
  _Bool _t329;
  __rustc_usize _t330;
  uint64_t _t331;
  void * _t332;
  void * _t333;
  __rustc_usize _t334;
  _Bool _t335;
  void * _t336;
  void * _t337;
  void * _t338;
  __rustc_usize _t339;
  _Bool _t340;
  _Bool _t341;
  uint64_t _t342;
  uint64_t _t343;

bb_0_start:
  *(__rustc_usize *)_t327 = 0ULL;
  goto bb_1_bb1;
bb_1_bb1:
  _t328 = *(__rustc_usize *)_t327;
  _t329 = (__rustc_usize)_t328 < (__rustc_usize)6ULL;
  if (_t329) goto bb_3_bb6; else goto bb_2_bb7;
bb_2_bb7:
  *(uint64_t *)_t324 = 6ULL;
  goto bb_4_bb5;
bb_3_bb6:
  _t330 = *(__rustc_usize *)_t327;
  _t331 = _t330 + 1ULL;
  *(uint64_t *)_t327 = _t331;
  _t332 = (void *)((__rustc_usize)_t325 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t332 = _t330;
  *(uint64_t *)_t325 = 1ULL;
  _t333 = (void *)((__rustc_usize)_t325 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t334 = *(__rustc_usize *)_t333;
  _t335 = (__rustc_usize)_t334 < (__rustc_usize)6ULL;
  if (_t335) goto bb_5_bb2; else goto bb_6_panic;
bb_4_bb5:
  _t343 = *(uint64_t *)_t324;
  return _t343;
bb_5_bb2:
  _t336 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES + (__rustc_isize)(_t334) * (__rustc_isize)sizeof(struct _S32));
  _t337 = *(void * *)_t336;
  _t338 = (void *)((__rustc_usize)_t336 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t339 = *(__rustc_usize *)_t338;
  _t340 = _RNvMNtNtCs41fFVwHnQdq_4core5slice5asciiSh20eq_ignore_ascii_case(_t337, _t339, _arg0, _arg1);
  _t341 = (_Bool)(_t340);
  if (_t341) goto bb_8_bb3; else goto bb_7_bb4;
bb_6_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(_t334, 6ULL, &_bytes45);
  abort();
bb_7_bb4:
  goto bb_1_bb1;
bb_8_bb3:
  switch (_t334) {
    case 0ULL: goto bb_10_bb15;
    case 1ULL: goto bb_11_bb14;
    case 2ULL: goto bb_12_bb13;
    case 3ULL: goto bb_13_bb12;
    case 4ULL: goto bb_14_bb11;
    case 5ULL: goto bb_15_bb10;
    default: goto bb_9_bb9;
  }
bb_9_bb9:
  _RNvNtCs41fFVwHnQdq_4core6option13unwrap_failed(&_bytes47);
  abort();
bb_10_bb15:
  *(uint64_t *)_t326 = 0ULL;
  goto bb_16_bb16;
bb_11_bb14:
  *(uint64_t *)_t326 = 1ULL;
  goto bb_16_bb16;
bb_12_bb13:
  *(uint64_t *)_t326 = 2ULL;
  goto bb_16_bb16;
bb_13_bb12:
  *(uint64_t *)_t326 = 3ULL;
  goto bb_16_bb16;
bb_14_bb11:
  *(uint64_t *)_t326 = 4ULL;
  goto bb_16_bb16;
bb_15_bb10:
  *(uint64_t *)_t326 = 5ULL;
  goto bb_16_bb16;
bb_16_bb16:
  _t342 = *(uint64_t *)_t326;
  *(uint64_t *)_t324 = _t342;
  goto bb_4_bb5;
}

#pragma weak _RNvXs6_CsdZu6hNdFJFF_3logNtB5_11LevelFilterNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt
_Bool _RNvXs6_CsdZu6hNdFJFF_3logNtB5_11LevelFilterNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void * _arg0, void * _arg1) {
  uint64_t _t344;
  __rustc_usize _t345;
  _Bool _t346;
  void * _t347;
  void * _t348;
  void * _t349;
  __rustc_usize _t350;
  _Bool _t351;
  _Bool _t352;

bb_0_start:
  _t344 = *(uint64_t *)_arg0;
  _t345 = (__rustc_usize)_t344;
  _t346 = (__rustc_usize)_t345 < (__rustc_usize)6ULL;
  if (_t346) goto bb_1_bb2; else goto bb_2_panic;
bb_1_bb2:
  _t347 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log15LOG_LEVEL_NAMES + (__rustc_isize)(_t345) * (__rustc_isize)sizeof(struct _S32));
  _t348 = *(void * *)_t347;
  _t349 = (void *)((__rustc_usize)_t347 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t350 = *(__rustc_usize *)_t349;
  _t351 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter3pad(_arg1, _t348, _t350);
  _t352 = (_Bool)(_t351);
  return _t352;
bb_2_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(_t345, 6ULL, &_bytes49);
  abort();
}

static void _RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log3log(void * _arg0, void * _arg1) {
bb_0_start:
  return;
}

static void _RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log5flush(void * _arg0) {
bb_0_start:
  return;
}

static _Bool _RNvXsf_CsdZu6hNdFJFF_3logNtB5_9NopLoggerNtB5_3Log7enabled(void * _arg0, void * _arg1) {
bb_0_start:
  return 0ULL;
}

#pragma weak _RNvXsh_CsdZu6hNdFJFF_3logNtB5_14SetLoggerErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt
_Bool _RNvXsh_CsdZu6hNdFJFF_3logNtB5_14SetLoggerErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void * _arg0, void * _arg1) {
  void * _t353;
  void * _t354;
  __rustc_usize _t355;
  _Bool _t356;
  _Bool _t357;

bb_0_start:
  _t353 = *(void * *)&_RNvCsdZu6hNdFJFF_3log16SET_LOGGER_ERROR;
  _t354 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log16SET_LOGGER_ERROR + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t355 = *(__rustc_usize *)_t354;
  _t356 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(_arg1, _t353, _t355);
  _t357 = (_Bool)(_t356);
  return _t357;
}

#pragma weak _RNvXsi_CsdZu6hNdFJFF_3logNtB5_15ParseLevelErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt
_Bool _RNvXsi_CsdZu6hNdFJFF_3logNtB5_15ParseLevelErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void * _arg0, void * _arg1) {
  void * _t358;
  void * _t359;
  __rustc_usize _t360;
  _Bool _t361;
  _Bool _t362;

bb_0_start:
  _t358 = *(void * *)&_RNvCsdZu6hNdFJFF_3log17LEVEL_PARSE_ERROR;
  _t359 = (void *)((__rustc_usize)&_RNvCsdZu6hNdFJFF_3log17LEVEL_PARSE_ERROR + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t360 = *(__rustc_usize *)_t359;
  _t361 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(_arg1, _t358, _t360);
  _t362 = (_Bool)(_t361);
  return _t362;
}

