/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

struct _S9 {
  void * f0;
  uint64_t f1;
};
struct _S14 {
  void * f0;
  void * f1;
};
extern uint8_t _RNvNtCs6uInAuYWU05_12panic_unwind3imp6CANARY[];

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeDNtNtB4_3any3AnyNtNtB4_6marker4SendEL_ECs6uInAuYWU05_12panic_unwind(void *, void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc5boxed3BoxDNtNtB4_3any3AnyNtNtB4_6marker4SendEL_EECs6uInAuYWU05_12panic_unwind(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc5boxed3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionEEB1j_(void *);
static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionEBK_(void *);
uint32_t _RNvCs1amGoZoSFzf_7___rustc18___rust_start_panic(void *, void *);
int128_t _RNvCs1amGoZoSFzf_7___rustc20___rust_panic_cleanup(void *);
static struct _S9 _RNvMNtCsb5RsJavtctd_5alloc5allocNtB2_6Global18alloc_impl_runtime(__rustc_usize, uint64_t, _Bool);
static void * _RNvMNtCsb5RsJavtctd_5alloc5boxedINtB2_3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionE3newBI_(void *);
static uint32_t _RNvNtCs6uInAuYWU05_12panic_unwind3imp5panic(void *, void *);
static struct _S14 _RNvNtCs6uInAuYWU05_12panic_unwind3imp7cleanup(void *);
static void * _RNvNtCsb5RsJavtctd_5alloc5alloc15exchange_malloc(__rustc_usize, __rustc_usize);
static void _RNvNvNtCs6uInAuYWU05_12panic_unwind3imp5panic17exception_cleanup(uint32_t, void *);
static void _RNvXs8_NtCsb5RsJavtctd_5alloc5boxedINtB5_3BoxDNtNtCs41fFVwHnQdq_4core3any3AnyNtNtBM_6marker4SendEL_ENtNtNtBM_3ops4drop4Drop4dropCs6uInAuYWU05_12panic_unwind(void *);
static void _RNvXs8_NtCsb5RsJavtctd_5alloc5boxedINtB5_3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionENtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4dropBL_(void *);
static void _RNvXs_NtCsb5RsJavtctd_5alloc5allocNtB4_6GlobalNtNtCs41fFVwHnQdq_4core5alloc9Allocator10deallocate(void *, void *, __rustc_usize, uint64_t);
void _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup(void);
void _RNvNtCs41fFVwHnQdq_4core9panicking19panic_cannot_unwind(void);
void _RNvCs1amGoZoSFzf_7___rustc35___rust_no_alloc_shim_is_unstable_v2(void);
void * _RNvCs1amGoZoSFzf_7___rustc12___rust_alloc(__rustc_usize, __rustc_usize);
void * _RNvCs1amGoZoSFzf_7___rustc19___rust_alloc_zeroed(__rustc_usize, __rustc_usize);
void _RNvCs1amGoZoSFzf_7___rustc24___rust_foreign_exception(void);
void _RNvCs1amGoZoSFzf_7___rustc14___rust_dealloc(void *, __rustc_usize, __rustc_usize);
void _Unwind_DeleteException(void *);
void _RNvNtCsb5RsJavtctd_5alloc5alloc18handle_alloc_error(__rustc_usize, uint64_t);
void _RNvCs1amGoZoSFzf_7___rustc17___rust_drop_panic(void);

_Alignas(8) static const unsigned char _bytes0[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };

_Alignas(8) uint8_t _RNvNtCs6uInAuYWU05_12panic_unwind3imp6CANARY[1] = { 0x00 };

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeDNtNtB4_3any3AnyNtNtB4_6marker4SendEL_ECs6uInAuYWU05_12panic_unwind(void * _arg0, void * _arg1) {
  void * _t0;
  void (*_t1)(void *);
  _Bool _t2;

bb_0_start:
  _t0 = (void *)((__rustc_usize)_arg1 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(int8_t));
  _t1 = *(void (**)(void *))_t0;
  _t2 = _t1 != 0;
  if (_t2) goto bb_1_is_not_null; else goto bb_2_bb1;
bb_1_is_not_null:
  ((void (*)(void *))_t1)(_arg0);
  goto bb_2_bb1;
bb_2_bb1:
  return;
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc5boxed3BoxDNtNtB4_3any3AnyNtNtB4_6marker4SendEL_EECs6uInAuYWU05_12panic_unwind(void * _arg0) {
  void * _t3;
  void * _t4;
  void * _t5;
  _Bool _t6;
  void * _t7;
  void * _t8;
  void (*_t9)(void *);
  _Bool _t10;
  _Alignas(8) uint8_t _t11_storage[16];
  void *_t11 = (void *)_t11_storage;
  void * _t12;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t13;
  void * _t14;
  int32_t _t15;

bb_0_start:
  _t3 = *(void * *)_arg0;
  _t4 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t5 = *(void * *)_t4;
  _t6 = (int64_t)_t3 != (int64_t)0;
  _t7 = (void *)_t3;
  _t8 = (void *)((__rustc_usize)_t5 + (__rustc_isize)(0ULL) * (__rustc_isize)sizeof(int8_t));
  _t9 = *(void (**)(void *))_t8;
  _t10 = _t9 != 0;
  if (_t10) goto bb_1_is_not_null; else goto bb_2_bb3;
bb_1_is_not_null:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_4_cleanup; }
  ((void (*)(void *))_t9)(_t7);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_2_bb3;
bb_2_bb3:
  _RNvXs8_NtCsb5RsJavtctd_5alloc5boxedINtB5_3BoxDNtNtCs41fFVwHnQdq_4core3any3AnyNtNtBM_6marker4SendEL_ENtNtNtBM_3ops4drop4Drop4dropCs6uInAuYWU05_12panic_unwind(_arg0);
  return;
bb_3_bb4:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_5_terminate; }
  _RNvXs8_NtCsb5RsJavtctd_5alloc5boxedINtB5_3BoxDNtNtCs41fFVwHnQdq_4core3any3AnyNtNtBM_6marker4SendEL_ENtNtNtBM_3ops4drop4Drop4dropCs6uInAuYWU05_12panic_unwind(_arg0);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_6_bb1;
bb_4_cleanup:
  *(void * *)_t11 = __exn_ptr;
  _t12 = (void *)((__rustc_usize)_t11 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t12 = 0LL;
  goto bb_3_bb4;
bb_5_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_6_bb1:
  _t13 = *(void * *)_t11;
  _t14 = (void *)((__rustc_usize)_t11 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t15 = *(int32_t *)_t14;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t13; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc5boxed3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionEEB1j_(void * _arg0) {
  void * _t16;
  _Bool _t17;
  void * _t18;
  _Alignas(8) uint8_t _t19_storage[16];
  void *_t19 = (void *)_t19_storage;
  void * _t20;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t21;
  void * _t22;
  int32_t _t23;

bb_0_start:
  _t16 = *(void * *)_arg0;
  _t17 = (int64_t)_t16 != (int64_t)0;
  _t18 = (void *)_t16;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionEBK_(_t18);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb3;
bb_1_bb4:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_4_terminate; }
  _RNvXs8_NtCsb5RsJavtctd_5alloc5boxedINtB5_3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionENtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4dropBL_(_arg0);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_5_bb1;
bb_2_cleanup:
  *(void * *)_t19 = __exn_ptr;
  _t20 = (void *)((__rustc_usize)_t19 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t20 = 0LL;
  goto bb_1_bb4;
bb_3_bb3:
  _RNvXs8_NtCsb5RsJavtctd_5alloc5boxedINtB5_3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionENtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4dropBL_(_arg0);
  return;
bb_4_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_5_bb1:
  _t21 = *(void * *)_t19;
  _t22 = (void *)((__rustc_usize)_t19 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t23 = *(int32_t *)_t22;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t21; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
}

static void _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionEBK_(void * _arg0) {
  void * _t24;

bb_0_start:
  _t24 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(40ULL) * (__rustc_isize)sizeof(int8_t));
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc5boxed3BoxDNtNtB4_3any3AnyNtNtB4_6marker4SendEL_EECs6uInAuYWU05_12panic_unwind(_t24);
  return;
}

#pragma weak _RNvCs1amGoZoSFzf_7___rustc18___rust_start_panic
uint32_t _RNvCs1amGoZoSFzf_7___rustc18___rust_start_panic(void * _arg0, void * _arg1) {
  void * _t25;
  struct _S14 (*_t26)(void *);
  struct _S14 _t27;
  void * _t28;
  void * _t29;
  void * _t30;
  _Bool _t31;
  uint32_t _t32;

bb_0_start:
  _t25 = (void *)((__rustc_usize)_arg1 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  _t26 = *(struct _S14 (**)(void *))_t25;
  _t27 = ((struct _S14 (*)(void *))_t26)(_arg0);
  _t28 = _t27.f0;
  _t29 = _t27.f1;
  _t30 = (void *)_t28;
  _t31 = (int64_t)_t30 != (int64_t)0;
  _t32 = _RNvNtCs6uInAuYWU05_12panic_unwind3imp5panic(_t30, _t29);
  return _t32;
}

#pragma weak _RNvCs1amGoZoSFzf_7___rustc20___rust_panic_cleanup
int128_t _RNvCs1amGoZoSFzf_7___rustc20___rust_panic_cleanup(void * _arg0) {
  _Alignas(8) uint8_t _t33_storage[16];
  void *_t33 = (void *)_t33_storage;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  struct _S14 _t34;
  void * _t35;
  void * _t36;
  _Bool _t37;
  void * _t38;
  void * _t39;
  int128_t _t40;

bb_0_start:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_1_terminate; }
  _t34 = _RNvNtCs6uInAuYWU05_12panic_unwind3imp7cleanup(_arg0);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_2_bb1;
bb_1_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking19panic_cannot_unwind();
  abort();
bb_2_bb1:
  _t35 = _t34.f0;
  _t36 = _t34.f1;
  _t37 = (int64_t)_t35 != (int64_t)0;
  _t38 = (void *)_t35;
  *(void * *)_t33 = _t38;
  _t39 = (void *)((__rustc_usize)_t33 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t39 = _t36;
  memcpy(&_t40, _t33, sizeof(_t40));
  return _t40;
}

static struct _S9 _RNvMNtCsb5RsJavtctd_5alloc5allocNtB2_6Global18alloc_impl_runtime(__rustc_usize _arg0, uint64_t _arg1, _Bool _arg2) {
  _Alignas(8) uint8_t _t41_storage[16];
  void *_t41 = (void *)_t41_storage;
  _Alignas(8) uint8_t _t42_storage[8];
  void *_t42 = (void *)_t42_storage;
  _Alignas(8) uint8_t _t43_storage[8];
  void *_t43 = (void *)_t43_storage;
  _Alignas(8) uint8_t _t44_storage[8];
  void *_t44 = (void *)_t44_storage;
  _Alignas(8) uint8_t _t45_storage[8];
  void *_t45 = (void *)_t45_storage;
  _Bool _t46;
  __rustc_usize _t47;
  _Bool _t48;
  int64_t _t49;
  uint64_t _t50;
  _Bool _t51;
  void * _t52;
  void * _t53;
  _Bool _t54;
  void * _t55;
  __rustc_usize _t56;
  void * _t57;
  __rustc_usize _t58;
  void * _t59;
  void * _t60;
  void * _t61;
  void * _t62;
  int64_t _t63;
  _Bool _t64;
  void * _t65;
  void * _t66;
  uint64_t _t67;
  void * _t68;
  void * _t69;
  _Bool _t70;
  void * _t71;
  void * _t72;
  void * _t73;
  _Bool _t74;
  void * _t75;
  void * _t76;
  _Bool _t77;
  void * _t78;
  void * _t79;
  void * _t80;
  uint64_t _t81;
  struct _S9 _t82;
  struct _S9 _t83;

bb_0_start:
  _t46 = (__rustc_isize)_arg1 == (__rustc_isize)0ULL;
  if (_t46) goto bb_1_bb2; else goto bb_2_bb1;
bb_1_bb2:
  _t47 = _arg0 - 1LL;
  _t48 = (__rustc_usize)_t47 <= (__rustc_usize)9223372036854775807LL;
  _t49 = (int64_t)_arg0;
  _t50 = _t49 - 1LL;
  _t51 = (uint64_t)_t50 <= (uint64_t)-2LL;
  _t52 = (void *)_t49;
  goto bb_3_bb9;
bb_2_bb1:
  if (_arg2) goto bb_6_bb3; else goto bb_5_bb4;
bb_3_bb9:
  _t53 = (void *)_t52;
  _t54 = (int64_t)_t53 != (int64_t)0;
  *(void * *)_t41 = _t53;
  _t55 = (void *)((__rustc_usize)_t41 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t55 = 0ULL;
  goto bb_4_bb6;
bb_4_bb6:
  _t79 = *(void * *)_t41;
  _t80 = (void *)((__rustc_usize)_t41 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t81 = *(uint64_t *)_t80;
  memset(&_t82, 0, sizeof(_t82));
  _t82.f0 = _t79;
  _t83 = _t82;
  _t83.f1 = _t81;
  return _t83;
bb_5_bb4:
  _RNvCs1amGoZoSFzf_7___rustc35___rust_no_alloc_shim_is_unstable_v2();
  _t56 = (__rustc_usize)_arg0;
  _t57 = _RNvCs1amGoZoSFzf_7___rustc12___rust_alloc(_arg1, _t56);
  *(void * *)_t42 = _t57;
  goto bb_7_bb5;
bb_6_bb3:
  _RNvCs1amGoZoSFzf_7___rustc35___rust_no_alloc_shim_is_unstable_v2();
  _t58 = (__rustc_usize)_arg0;
  _t59 = _RNvCs1amGoZoSFzf_7___rustc19___rust_alloc_zeroed(_arg1, _t58);
  *(void * *)_t42 = _t59;
  goto bb_7_bb5;
bb_7_bb5:
  _t60 = *(void * *)_t42;
  _t61 = (void *)_t60;
  _t62 = *(void * *)_t42;
  _t63 = (int64_t)_t62;
  _t64 = (__rustc_isize)_t63 == (__rustc_isize)0ULL;
  if (_t64) goto bb_8_bb14; else goto bb_9_bb15;
bb_8_bb14:
  _t65 = *(void * *)_bytes0;
  _t66 = (void *)((__rustc_usize)_bytes0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t67 = *(uint64_t *)_t66;
  *(void * *)_t41 = _t65;
  _t68 = (void *)((__rustc_usize)_t41 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t68 = _t67;
  goto bb_4_bb6;
bb_9_bb15:
  goto bb_10_bb18;
bb_10_bb18:
  _t69 = (void *)_t61;
  _t70 = (int64_t)_t69 != (int64_t)0;
  *(void * *)_t45 = _t69;
  _t71 = *(void * *)_t45;
  *(void * *)_t44 = _t71;
  _t72 = *(void * *)_t44;
  *(void * *)_t43 = _t72;
  _t73 = *(void * *)_t43;
  _t74 = (int64_t)_t73 != (int64_t)0;
  _t75 = (void *)_t73;
  goto bb_11_bb21;
bb_11_bb21:
  _t76 = (void *)_t75;
  _t77 = (int64_t)_t76 != (int64_t)0;
  *(void * *)_t41 = _t76;
  _t78 = (void *)((__rustc_usize)_t41 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t78 = _arg1;
  goto bb_4_bb6;
bb_12_bb7:
  abort();
bb_13_bb8:
  abort();
bb_14_bb16:
  abort();
bb_15_bb17:
  abort();
bb_16_bb19:
  abort();
bb_17_bb20:
  abort();
}

static void * _RNvMNtCsb5RsJavtctd_5alloc5boxedINtB2_3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionE3newBI_(void * _arg0) {
  _Alignas(8) uint8_t _t84_storage[16];
  void *_t84 = (void *)_t84_storage;
  void * _t85;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t86;
  void * _t87;
  void * _t88;
  _Bool _t89;
  void * _t90;
  void * _t91;
  int32_t _t92;

bb_0_start:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t86 = _RNvNtCsb5RsJavtctd_5alloc5alloc15exchange_malloc(56ULL, 8ULL);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb1;
bb_1_bb2:
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_4_terminate; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionEBK_(_arg0);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_5_bb3;
bb_2_cleanup:
  *(void * *)_t84 = __exn_ptr;
  _t85 = (void *)((__rustc_usize)_t84 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t85 = 0LL;
  goto bb_1_bb2;
bb_3_bb1:
  _t87 = (void *)_t86;
  _t88 = (void *)_t87;
  _t89 = (int64_t)_t88 != (int64_t)0;
  memcpy(_t87, _arg0, 56ULL);
  return _t88;
bb_4_terminate:
  _RNvNtCs41fFVwHnQdq_4core9panicking16panic_in_cleanup();
  abort();
bb_5_bb3:
  _t90 = *(void * *)_t84;
  _t91 = (void *)((__rustc_usize)_t84 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t92 = *(int32_t *)_t91;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t90; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
}

static uint32_t _RNvNtCs6uInAuYWU05_12panic_unwind3imp5panic(void * _arg0, void * _arg1) {
  _Alignas(8) uint8_t _t93_storage[56];
  void *_t93 = (void *)_t93_storage;
  _Alignas(8) uint8_t _t94_storage[32];
  void *_t94 = (void *)_t94_storage;
  _Alignas(8) uint8_t _t95_storage[16];
  void *_t95 = (void *)_t95_storage;
  _Bool _t96;
  void * _t97;
  void * _t98;
  void * _t99;
  void * _t100;
  void * _t101;
  void * _t102;
  void * _t103;
  void * _t104;
  _Bool _t105;
  void * _t106;
  void * _t107;
  uint32_t _t108;
  __rustc_isize _t109;
  uint32_t _t110;

bb_0_start:
  _t96 = (int64_t)_RNvNvNtCs6uInAuYWU05_12panic_unwind3imp5panic17exception_cleanup != (int64_t)0;
  _t97 = (void *)_RNvNvNtCs6uInAuYWU05_12panic_unwind3imp5panic17exception_cleanup;
  *(void * *)_t95 = (void *)(__rustc_usize)0ULL;
  _t98 = (void *)((__rustc_usize)_t95 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t98 = (void *)(__rustc_usize)0ULL;
  *(uint64_t *)_t94 = 6076294132934528845ULL;
  _t99 = (void *)((__rustc_usize)_t94 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t99 = _t97;
  _t100 = (void *)((__rustc_usize)_t94 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  memcpy(_t100, _t95, 16ULL);
  memcpy(_t93, _t94, 32ULL);
  _t101 = (void *)((__rustc_usize)_t93 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t101 = &_RNvNtCs6uInAuYWU05_12panic_unwind3imp6CANARY;
  _t102 = (void *)((__rustc_usize)_t93 + (__rustc_isize)(40ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t102 = _arg0;
  _t103 = (void *)((__rustc_usize)_t102 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t103 = _arg1;
  _t104 = _RNvMNtCsb5RsJavtctd_5alloc5boxedINtB2_3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionE3newBI_(_t93);
  _t105 = (int64_t)_t104 != (int64_t)0;
  _t106 = (void *)_t104;
  _t107 = (void *)_t106;
  _t108 = _Unwind_RaiseException(_t107);
  _t109 = (__rustc_isize)_t108;
  _t110 = (uint32_t)_t109;
  return _t110;
}

static struct _S14 _RNvNtCs6uInAuYWU05_12panic_unwind3imp7cleanup(void * _arg0) {
  void * _t111;
  uint64_t _t112;
  _Bool _t113;
  void * _t114;
  void * _t115;
  void * _t116;
  _Bool _t117;
  void * _t118;
  void * _t119;
  _Bool _t120;
  void * _t121;
  void * _t122;
  void * _t123;
  void * _t124;
  _Alignas(8) uint8_t _t125_storage[8];
  void *_t125 = (void *)_t125_storage;
  __rustc_usize _t126;
  _Alignas(8) uint8_t _t127_storage[8];
  void *_t127 = (void *)_t127_storage;
  __rustc_usize _t128;
  int64_t _t129;
  int64_t _t130;
  _Bool _t131;
  _Bool _t132;
  __rustc_usize _t133;
  struct _S14 _t134;
  struct _S14 _t135;

bb_0_start:
  _t111 = (void *)_arg0;
  _t112 = *(uint64_t *)_t111;
  _t113 = (int64_t)_t112 != (int64_t)6076294132934528845ULL;
  if (_t113) goto bb_2_bb1; else goto bb_1_bb3;
bb_1_bb3:
  _t114 = (void *)_arg0;
  _t115 = (void *)((__rustc_usize)_t114 + (__rustc_isize)(32ULL) * (__rustc_isize)sizeof(int8_t));
  _t116 = *(void * *)_t115;
  _t117 = (int64_t)_t116 == (int64_t)&_RNvNtCs6uInAuYWU05_12panic_unwind3imp6CANARY;
  if (_t117) goto bb_4_bb4; else goto bb_3_bb5;
bb_2_bb1:
  _Unwind_DeleteException(_t111);
  _RNvCs1amGoZoSFzf_7___rustc24___rust_foreign_exception();
  abort();
bb_3_bb5:
  _RNvCs1amGoZoSFzf_7___rustc24___rust_foreign_exception();
  abort();
bb_4_bb4:
  _t118 = (void *)_arg0;
  _t119 = (void *)_t118;
  _t120 = (int64_t)_t119 != (int64_t)0;
  _t121 = (void *)((__rustc_usize)_t118 + (__rustc_isize)(40ULL) * (__rustc_isize)sizeof(int8_t));
  _t122 = *(void * *)_t121;
  _t123 = (void *)((__rustc_usize)_t121 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t124 = *(void * *)_t123;
  *(__rustc_usize *)_t125 = 56ULL;
  _t126 = *(__rustc_usize *)_t125;
  *(__rustc_usize *)_t127 = 8ULL;
  _t128 = *(__rustc_usize *)_t127;
  _t129 = (int64_t)_t128;
  _t130 = _t129 - 1LL;
  _t131 = (uint64_t)_t130 <= (uint64_t)9223372036854775807LL;
  _t132 = (__rustc_isize)_t126 == (__rustc_isize)0ULL;
  if (_t132) goto bb_5_bb7; else goto bb_6_bb6;
bb_5_bb7:
  memset(&_t134, 0, sizeof(_t134));
  _t134.f0 = _t122;
  _t135 = _t134;
  _t135.f1 = _t124;
  return _t135;
bb_6_bb6:
  _t133 = (__rustc_usize)_t129;
  _RNvCs1amGoZoSFzf_7___rustc14___rust_dealloc(_arg0, _t126, _t133);
  goto bb_5_bb7;
}

static void * _RNvNtCsb5RsJavtctd_5alloc5alloc15exchange_malloc(__rustc_usize _arg0, __rustc_usize _arg1) {
  _Alignas(8) uint8_t _t136_storage[16];
  void *_t136 = (void *)_t136_storage;
  int64_t _t137;
  int64_t _t138;
  _Bool _t139;
  struct _S9 _t140;
  void * _t141;
  void * _t142;
  uint64_t _t143;
  int64_t _t144;
  _Bool _t145;
  __rustc_isize _t146;
  _Bool _t147;
  void * _t148;
  void * _t149;
  uint64_t _t150;
  _Bool _t151;
  void * _t152;

bb_0_start:
  goto bb_1_bb5;
bb_1_bb5:
  _t137 = (int64_t)_arg1;
  _t138 = _t137 - 1LL;
  _t139 = (uint64_t)_t138 <= (uint64_t)9223372036854775807LL;
  _t140 = _RNvMNtCsb5RsJavtctd_5alloc5allocNtB2_6Global18alloc_impl_runtime(_t137, _arg0, 0ULL);
  *(struct _S9 *)_t136 = _t140;
  _t141 = *(void * *)_t136;
  _t142 = (void *)((__rustc_usize)_t136 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t143 = *(uint64_t *)_t142;
  _t144 = (int64_t)_t141;
  _t145 = (int64_t)_t144 == (int64_t)0LL;
  _t146 = (_t145) ? (1LL) : (0LL);
  _t147 = (_Bool)_t146;
  if (_t147) goto bb_2_bb2; else goto bb_3_bb3;
bb_2_bb2:
  _RNvNtCsb5RsJavtctd_5alloc5alloc18handle_alloc_error(_t137, _arg0);
  abort();
bb_3_bb3:
  _t148 = *(void * *)_t136;
  _t149 = (void *)((__rustc_usize)_t136 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t150 = *(uint64_t *)_t149;
  _t151 = (int64_t)_t148 != (int64_t)0;
  _t152 = (void *)_t148;
  return _t152;
bb_4_bb1:
  abort();
bb_5_bb4:
  abort();
}

static void _RNvNvNtCs6uInAuYWU05_12panic_unwind3imp5panic17exception_cleanup(uint32_t _arg0, void * _arg1) {
  _Alignas(8) uint8_t _t153_storage[8];
  void *_t153 = (void *)_t153_storage;
  void * _t154;
  void * _t155;
  _Bool _t156;
  _Alignas(8) uint8_t _t157_storage[16];
  void *_t157 = (void *)_t157_storage;
  void * _t158;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;

bb_0_start:
  _t154 = (void *)_arg1;
  _t155 = (void *)_t154;
  _t156 = (int64_t)_t155 != (int64_t)0;
  *(void * *)_t153 = _t155;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _RINvNtCs41fFVwHnQdq_4core3ptr13drop_in_placeINtNtCsb5RsJavtctd_5alloc5boxed3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionEEB1j_(_t153);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb1;
bb_1_bb2:
  _RNvNtCs41fFVwHnQdq_4core9panicking19panic_cannot_unwind();
  abort();
bb_2_cleanup:
  *(void * *)_t157 = __exn_ptr;
  _t158 = (void *)((__rustc_usize)_t157 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t158 = 0LL;
  goto bb_1_bb2;
bb_3_bb1:
  _RNvCs1amGoZoSFzf_7___rustc17___rust_drop_panic();
  abort();
}

static void _RNvXs8_NtCsb5RsJavtctd_5alloc5boxedINtB5_3BoxDNtNtCs41fFVwHnQdq_4core3any3AnyNtNtBM_6marker4SendEL_ENtNtNtBM_3ops4drop4Drop4dropCs6uInAuYWU05_12panic_unwind(void * _arg0) {
  void * _t159;
  void * _t160;
  void * _t161;
  _Bool _t162;
  void * _t163;
  _Bool _t164;
  void * _t165;
  _Alignas(8) uint8_t _t166_storage[8];
  void *_t166 = (void *)_t166_storage;
  void * _t167;
  __rustc_isize _t168;
  void * _t169;
  __rustc_isize _t170;
  __rustc_usize _t171;
  _Alignas(8) uint8_t _t172_storage[8];
  void *_t172 = (void *)_t172_storage;
  void * _t173;
  __rustc_isize _t174;
  void * _t175;
  __rustc_isize _t176;
  __rustc_usize _t177;
  int64_t _t178;
  int64_t _t179;
  _Bool _t180;
  _Bool _t181;
  void * _t182;
  void * _t183;
  _Bool _t184;

bb_0_start:
  _t159 = *(void * *)_arg0;
  _t160 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t161 = *(void * *)_t160;
  _t162 = (int64_t)_t159 != (int64_t)0;
  _t163 = (void *)_t159;
  _t164 = (int64_t)_t159 != (int64_t)0;
  _t165 = (void *)_t159;
  _t167 = (void *)((__rustc_usize)_t161 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t168 = *(__rustc_isize *)_t167;
  _t169 = (void *)((__rustc_usize)_t161 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t170 = *(__rustc_isize *)_t169;
  *(__rustc_isize *)_t166 = _t168;
  _t171 = *(__rustc_usize *)_t166;
  _t173 = (void *)((__rustc_usize)_t161 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t174 = *(__rustc_isize *)_t173;
  _t175 = (void *)((__rustc_usize)_t161 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t176 = *(__rustc_isize *)_t175;
  *(__rustc_isize *)_t172 = _t176;
  _t177 = *(__rustc_usize *)_t172;
  goto bb_1_bb7;
bb_1_bb7:
  _t178 = (int64_t)_t177;
  _t179 = _t178 - 1LL;
  _t180 = (uint64_t)_t179 <= (uint64_t)9223372036854775807LL;
  _t181 = (__rustc_isize)_t171 == (__rustc_isize)0ULL;
  if (_t181) goto bb_2_bb3; else goto bb_3_bb1;
bb_2_bb3:
  return;
bb_3_bb1:
  _t182 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t183 = (void *)_t163;
  _t184 = (int64_t)_t183 != (int64_t)0;
  _RNvXs_NtCsb5RsJavtctd_5alloc5allocNtB4_6GlobalNtNtCs41fFVwHnQdq_4core5alloc9Allocator10deallocate(_t182, _t183, _t178, _t171);
  goto bb_2_bb3;
bb_4_bb6:
  abort();
}

static void _RNvXs8_NtCsb5RsJavtctd_5alloc5boxedINtB5_3BoxNtNtCs6uInAuYWU05_12panic_unwind3imp9ExceptionENtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4dropBL_(void * _arg0) {
  void * _t185;
  _Bool _t186;
  void * _t187;
  _Bool _t188;
  void * _t189;
  _Alignas(8) uint8_t _t190_storage[8];
  void *_t190 = (void *)_t190_storage;
  __rustc_usize _t191;
  _Alignas(8) uint8_t _t192_storage[8];
  void *_t192 = (void *)_t192_storage;
  __rustc_usize _t193;
  int64_t _t194;
  int64_t _t195;
  _Bool _t196;
  _Bool _t197;
  void * _t198;
  void * _t199;
  void * _t200;
  _Bool _t201;

bb_0_start:
  _t185 = *(void * *)_arg0;
  _t186 = (int64_t)_t185 != (int64_t)0;
  _t187 = (void *)_t185;
  _t188 = (int64_t)_t185 != (int64_t)0;
  _t189 = (void *)_t185;
  *(__rustc_usize *)_t190 = 56ULL;
  _t191 = *(__rustc_usize *)_t190;
  *(__rustc_usize *)_t192 = 8ULL;
  _t193 = *(__rustc_usize *)_t192;
  goto bb_1_bb7;
bb_1_bb7:
  _t194 = (int64_t)_t193;
  _t195 = _t194 - 1LL;
  _t196 = (uint64_t)_t195 <= (uint64_t)9223372036854775807LL;
  _t197 = (__rustc_isize)_t191 == (__rustc_isize)0ULL;
  if (_t197) goto bb_2_bb3; else goto bb_3_bb1;
bb_2_bb3:
  return;
bb_3_bb1:
  _t198 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t199 = (void *)_t187;
  _t200 = (void *)_t199;
  _t201 = (int64_t)_t200 != (int64_t)0;
  _RNvXs_NtCsb5RsJavtctd_5alloc5allocNtB4_6GlobalNtNtCs41fFVwHnQdq_4core5alloc9Allocator10deallocate(_t198, _t200, _t194, _t191);
  goto bb_2_bb3;
bb_4_bb6:
  abort();
}

static void _RNvXs_NtCsb5RsJavtctd_5alloc5allocNtB4_6GlobalNtNtCs41fFVwHnQdq_4core5alloc9Allocator10deallocate(void * _arg0, void * _arg1, __rustc_usize _arg2, uint64_t _arg3) {
  _Bool _t202;
  _Bool _t203;
  void * _t204;
  __rustc_usize _t205;

bb_0_start:
  _t202 = (__rustc_isize)_arg3 == (__rustc_isize)0ULL;
  if (_t202) goto bb_1_bb2; else goto bb_2_bb1;
bb_1_bb2:
  return;
bb_2_bb1:
  _t203 = (int64_t)_arg1 != (int64_t)0;
  _t204 = (void *)_arg1;
  _t205 = (__rustc_usize)_arg2;
  _RNvCs1amGoZoSFzf_7___rustc14___rust_dealloc(_t204, _arg3, _t205);
  goto bb_1_bb2;
}

