/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

struct _S12 {
  void * f0;
  __rustc_usize f1;
};
#pragma pack(push, 1)
struct _gs__RNvNvXs7_NtCs1Tqig01902y_13serde_spanned7spannedINtB7_7SpannedpENtNtCsazb1FB8fAjk_10serde_core2de11Deserialize11deserialize6FIELDS { void *f0; unsigned char f1[8]; void *f2; unsigned char f3[8]; void *f4; unsigned char f5[8]; };
#pragma pack(pop)

extern struct _gs__RNvNvXs7_NtCs1Tqig01902y_13serde_spanned7spannedINtB7_7SpannedpENtNtCsazb1FB8fAjk_10serde_core2de11Deserialize11deserialize6FIELDS _RNvNvXs7_NtCs1Tqig01902y_13serde_spanned7spannedINtB7_7SpannedpENtNtCsazb1FB8fAjk_10serde_core2de11Deserialize11deserialize6FIELDS;

_Bool _RNvNtCs1Tqig01902y_13serde_spanned7spanned10is_spanned(void *, __rustc_usize, void *, __rustc_usize);
static _Bool _RNvXs2_NtNtCs41fFVwHnQdq_4core5slice3cmpSReINtB5_14SlicePartialEqBD_E5equalCs1Tqig01902y_13serde_spanned(void *, __rustc_usize, void *, __rustc_usize);
static _Bool _RNvXs3_NtNtCs41fFVwHnQdq_4core5slice3cmpShINtB5_14SlicePartialEqhE5equalCs1Tqig01902y_13serde_spanned(void *, __rustc_usize, void *, __rustc_usize);
static _Bool _RNvXs7_NtNtCs41fFVwHnQdq_4core3cmp5implsReNtB7_9PartialEq2neCs1Tqig01902y_13serde_spanned(void *, void *);
static _Bool _RNvXs_NtNtCs41fFVwHnQdq_4core3str6traitseNtNtB8_3cmp9PartialEq2eq(void *, __rustc_usize, void *, __rustc_usize);
static _Bool _RNvYeNtNtCs41fFVwHnQdq_4core3cmp9PartialEq2neCs1Tqig01902y_13serde_spanned(void *, __rustc_usize, void *, __rustc_usize);
void _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(__rustc_usize, __rustc_usize, void *);

static const unsigned char _bytes1[] = { 0x24, 0x5f, 0x5f, 0x73, 0x65, 0x72, 0x64, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x53, 0x70, 0x61, 0x6e, 0x6e, 0x65, 0x64 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[8]; } _bytes0 = {   .f0 = (void *)_bytes1,   .f1 = { 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes3[] = { 0x24, 0x5f, 0x5f, 0x73, 0x65, 0x72, 0x64, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74 };
static const unsigned char _bytes4[] = { 0x24, 0x5f, 0x5f, 0x73, 0x65, 0x72, 0x64, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x64 };
static const unsigned char _bytes5[] = { 0x24, 0x5f, 0x5f, 0x73, 0x65, 0x72, 0x64, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[8];   void *f2;   unsigned char f3[8];   void *f4;   unsigned char f5[8]; } _bytes2 = {   .f0 = (void *)_bytes3,   .f1 = { 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },   .f2 = (void *)_bytes4,   .f3 = { 0x1c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },   .f4 = (void *)_bytes5,   .f5 = { 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes6[] = { 0x24, 0x5f, 0x5f, 0x73, 0x65, 0x72, 0x64, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74 };
static const unsigned char _bytes7[] = { 0x24, 0x5f, 0x5f, 0x73, 0x65, 0x72, 0x64, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x64 };
static const unsigned char _bytes8[] = { 0x24, 0x5f, 0x5f, 0x73, 0x65, 0x72, 0x64, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65 };
static const unsigned char _bytes10[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6d, 0x70, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes9 = {   .f0 = (void *)_bytes10,   .f1 = { 0x96, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7c, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes12[] = { 0x2f, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x41, 0x76, 0x65, 0x72, 0x79, 0x53, 0x53, 0x44, 0x2f, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x70, 0x5f, 0x44, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x63, 0x2d, 0x6d, 0x61, 0x63, 0x6f, 0x73, 0x2d, 0x73, 0x70, 0x69, 0x6b, 0x65, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x61, 0x61, 0x72, 0x63, 0x68, 0x36, 0x34, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x61, 0x72, 0x77, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x6c, 0x69, 0x62, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6d, 0x70, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes11 = {   .f0 = (void *)_bytes12,   .f1 = { 0x96, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7c, 0x00, 0x00, 0x00, 0x1d, 0x00, 0x00, 0x00 } };
#pragma pack(pop)

struct _gs__RNvNvXs7_NtCs1Tqig01902y_13serde_spanned7spannedINtB7_7SpannedpENtNtCsazb1FB8fAjk_10serde_core2de11Deserialize11deserialize6FIELDS _RNvNvXs7_NtCs1Tqig01902y_13serde_spanned7spannedINtB7_7SpannedpENtNtCsazb1FB8fAjk_10serde_core2de11Deserialize11deserialize6FIELDS = { .f0 = (void *)_bytes6, .f1 = { 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, .f2 = (void *)_bytes7, .f3 = { 0x1c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, .f4 = (void *)_bytes8, .f5 = { 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } };

#pragma weak _RNvNtCs1Tqig01902y_13serde_spanned7spanned10is_spanned
_Bool _RNvNtCs1Tqig01902y_13serde_spanned7spanned10is_spanned(void * _arg0, __rustc_usize _arg1, void * _arg2, __rustc_usize _arg3) {
  _Alignas(1) uint8_t _t0_storage[1];
  void *_t0 = (void *)_t0_storage;
  void * _t1;
  void * _t2;
  __rustc_usize _t3;
  _Bool _t4;
  _Bool _t5;
  int8_t _t6;
  _Bool _t7;
  _Bool _t8;
  _Bool _t9;
  int8_t _t10;
  _Bool _t11;

bb_0_start:
  _t1 = *(void * *)&_bytes0;
  _t2 = (void *)((__rustc_usize)&_bytes0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t3 = *(__rustc_usize *)_t2;
  _t4 = _RNvXs3_NtNtCs41fFVwHnQdq_4core5slice3cmpShINtB5_14SlicePartialEqhE5equalCs1Tqig01902y_13serde_spanned(_arg0, _arg1, _t1, _t3);
  _t5 = (_Bool)(_t4);
  if (_t5) goto bb_2_bb1; else goto bb_1_bb2;
bb_1_bb2:
  _t6 = (int8_t)(0ULL);
  *(int8_t *)_t0 = _t6;
  goto bb_3_bb3;
bb_2_bb1:
  _t7 = (__rustc_isize)_arg3 == (__rustc_isize)3ULL;
  if (_t7) goto bb_4_bb5; else goto bb_5_bb6;
bb_3_bb3:
  _t11 = *(_Bool *)_t0;
  return _t11;
bb_4_bb5:
  _t8 = _RNvXs2_NtNtCs41fFVwHnQdq_4core5slice3cmpSReINtB5_14SlicePartialEqBD_E5equalCs1Tqig01902y_13serde_spanned(_arg2, 3ULL, &_bytes2, 3ULL);
  _t9 = (_Bool)(_t8);
  *(_Bool *)_t0 = _t9;
  goto bb_3_bb3;
bb_5_bb6:
  _t10 = (int8_t)(0ULL);
  *(int8_t *)_t0 = _t10;
  goto bb_3_bb3;
}

static _Bool _RNvXs2_NtNtCs41fFVwHnQdq_4core5slice3cmpSReINtB5_14SlicePartialEqBD_E5equalCs1Tqig01902y_13serde_spanned(void * _arg0, __rustc_usize _arg1, void * _arg2, __rustc_usize _arg3) {
  _Alignas(1) uint8_t _t12_storage[1];
  void *_t12 = (void *)_t12_storage;
  _Alignas(8) uint8_t _t13_storage[8];
  void *_t13 = (void *)_t13_storage;
  _Bool _t14;
  __rustc_usize _t15;
  _Bool _t16;
  int8_t _t17;
  __rustc_usize _t18;
  _Bool _t19;
  void * _t20;
  __rustc_usize _t21;
  _Bool _t22;
  void * _t23;
  _Bool _t24;
  _Bool _t25;
  __rustc_usize _t26;
  uint64_t _t27;
  int8_t _t28;
  int8_t _t29;
  _Bool _t30;

bb_0_start:
  _t14 = (__rustc_isize)_arg1 != (__rustc_isize)_arg3;
  if (_t14) goto bb_2_bb1; else goto bb_1_bb2;
bb_1_bb2:
  *(__rustc_usize *)_t13 = 0ULL;
  goto bb_3_bb3;
bb_2_bb1:
  _t29 = (int8_t)(0ULL);
  *(int8_t *)_t12 = _t29;
  goto bb_6_bb11;
bb_3_bb3:
  _t15 = *(__rustc_usize *)_t13;
  _t16 = (__rustc_usize)_t15 < (__rustc_usize)_arg1;
  if (_t16) goto bb_5_bb4; else goto bb_4_bb10;
bb_4_bb10:
  _t17 = (int8_t)(1ULL);
  *(int8_t *)_t12 = _t17;
  goto bb_6_bb11;
bb_5_bb4:
  _t18 = *(__rustc_usize *)_t13;
  _t19 = (__rustc_usize)_t18 < (__rustc_usize)_arg1;
  if (_t19) goto bb_7_bb5; else goto bb_8_panic;
bb_6_bb11:
  _t30 = *(_Bool *)_t12;
  return _t30;
bb_7_bb5:
  _t20 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(_t18) * (__rustc_isize)sizeof(struct _S12));
  _t21 = *(__rustc_usize *)_t13;
  _t22 = (__rustc_usize)_t21 < (__rustc_usize)_arg3;
  if (_t22) goto bb_9_bb6; else goto bb_10_panic;
bb_8_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(_t18, _arg1, &_bytes9);
  abort();
bb_9_bb6:
  _t23 = (void *)((__rustc_usize)_arg2 + (__rustc_isize)(_t21) * (__rustc_isize)sizeof(struct _S12));
  _t24 = _RNvXs7_NtNtCs41fFVwHnQdq_4core3cmp5implsReNtB7_9PartialEq2neCs1Tqig01902y_13serde_spanned(_t20, _t23);
  _t25 = (_Bool)(_t24);
  if (_t25) goto bb_12_bb8; else goto bb_11_bb9;
bb_10_panic:
  _RNvNtCs41fFVwHnQdq_4core9panicking18panic_bounds_check(_t21, _arg3, &_bytes11);
  abort();
bb_11_bb9:
  _t26 = *(__rustc_usize *)_t13;
  _t27 = _t26 + 1ULL;
  *(uint64_t *)_t13 = _t27;
  goto bb_3_bb3;
bb_12_bb8:
  _t28 = (int8_t)(0ULL);
  *(int8_t *)_t12 = _t28;
  goto bb_6_bb11;
}

static _Bool _RNvXs3_NtNtCs41fFVwHnQdq_4core5slice3cmpShINtB5_14SlicePartialEqhE5equalCs1Tqig01902y_13serde_spanned(void * _arg0, __rustc_usize _arg1, void * _arg2, __rustc_usize _arg3) {
  _Alignas(1) uint8_t _t31_storage[1];
  void *_t31 = (void *)_t31_storage;
  _Bool _t32;
  _Alignas(8) uint8_t _t33_storage[8];
  void *_t33 = (void *)_t33_storage;
  __rustc_usize _t34;
  __rustc_usize _t35;
  _Alignas(4) uint8_t _t36_storage[4];
  void *_t36 = (void *)_t36_storage;
  int32_t _t37;
  int32_t _t38;
  _Bool _t39;
  int8_t _t40;
  int8_t _t41;
  _Bool _t42;

bb_0_start:
  _t32 = (__rustc_isize)_arg1 != (__rustc_isize)_arg3;
  if (_t32) goto bb_2_bb1; else goto bb_1_bb2;
bb_1_bb2:
  _t34 = _arg1 * 1ULL;
  *(__rustc_usize *)_t33 = _t34;
  _t35 = *(__rustc_usize *)_t33;
  _t37 = memcmp(_arg0, _arg2, _t35);
  *(int32_t *)_t36 = _t37;
  _t38 = *(int32_t *)_t36;
  _t39 = (int32_t)_t38 == (int32_t)0LL;
  _t40 = (int8_t)(_t39);
  *(int8_t *)_t31 = _t40;
  goto bb_3_bb4;
bb_2_bb1:
  _t41 = (int8_t)(0ULL);
  *(int8_t *)_t31 = _t41;
  goto bb_3_bb4;
bb_3_bb4:
  _t42 = *(_Bool *)_t31;
  return _t42;
}

static _Bool _RNvXs7_NtNtCs41fFVwHnQdq_4core3cmp5implsReNtB7_9PartialEq2neCs1Tqig01902y_13serde_spanned(void * _arg0, void * _arg1) {
  void * _t43;
  void * _t44;
  __rustc_usize _t45;
  void * _t46;
  void * _t47;
  __rustc_usize _t48;
  _Bool _t49;
  _Bool _t50;

bb_0_start:
  _t43 = *(void * *)_arg0;
  _t44 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t45 = *(__rustc_usize *)_t44;
  _t46 = *(void * *)_arg1;
  _t47 = (void *)((__rustc_usize)_arg1 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t48 = *(__rustc_usize *)_t47;
  _t49 = _RNvYeNtNtCs41fFVwHnQdq_4core3cmp9PartialEq2neCs1Tqig01902y_13serde_spanned(_t43, _t45, _t46, _t48);
  _t50 = (_Bool)(_t49);
  return _t50;
}

static _Bool _RNvXs_NtNtCs41fFVwHnQdq_4core3str6traitseNtNtB8_3cmp9PartialEq2eq(void * _arg0, __rustc_usize _arg1, void * _arg2, __rustc_usize _arg3) {
  _Bool _t51;
  _Bool _t52;

bb_0_start:
  _t51 = _RNvXs3_NtNtCs41fFVwHnQdq_4core5slice3cmpShINtB5_14SlicePartialEqhE5equalCs1Tqig01902y_13serde_spanned(_arg0, _arg1, _arg2, _arg3);
  _t52 = (_Bool)(_t51);
  return _t52;
}

static _Bool _RNvYeNtNtCs41fFVwHnQdq_4core3cmp9PartialEq2neCs1Tqig01902y_13serde_spanned(void * _arg0, __rustc_usize _arg1, void * _arg2, __rustc_usize _arg3) {
  _Bool _t53;
  _Bool _t54;
  _Bool _t55;

bb_0_start:
  _t53 = _RNvXs_NtNtCs41fFVwHnQdq_4core3str6traitseNtNtB8_3cmp9PartialEq2eq(_arg0, _arg1, _arg2, _arg3);
  _t54 = (_Bool)(_t53);
  _t55 = !(_t54);
  return _t55;
}

