/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

struct _S2 {
  uint64_t f0;
  uint64_t f1;
};
struct _S15 {
  void * f0;
  __rustc_usize f1;
};
struct _S50 {
  int8_t f0[24];
};
static struct _S2 _RINvYShNtCskQUcIKPqzjg_9zstd_safe8WriteBuf10write_fromNCINvMs0_B7_NtB7_4CCtx20compress_using_cdictB3_E0EB7_(void *, __rustc_usize, void *);
static struct _S2 _RINvYShNtCskQUcIKPqzjg_9zstd_safe8WriteBuf10write_fromNCINvMs5_B7_NtB7_4DCtx22decompress_using_ddictB3_E0EB7_(void *, __rustc_usize, void *);
static struct _S2 _RNCINvMs0_CskQUcIKPqzjg_9zstd_safeNtB8_4CCtx20compress_using_cdictShE0B8_(void *, void *, __rustc_usize);
static struct _S2 _RNCINvMs5_CskQUcIKPqzjg_9zstd_safeNtB8_4DCtx22decompress_using_ddictShE0B8_(void *, void *, __rustc_usize);
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(__rustc_usize);
uint32_t _RNvCskQUcIKPqzjg_9zstd_safe11get_dict_id(void *, __rustc_usize);
int32_t _RNvCskQUcIKPqzjg_9zstd_safe11max_c_level(void);
int32_t _RNvCskQUcIKPqzjg_9zstd_safe11min_c_level(void);
void * _RNvCskQUcIKPqzjg_9zstd_safe12create_cdict(void *, __rustc_usize, int32_t);
void * _RNvCskQUcIKPqzjg_9zstd_safe12create_ddict(void *, __rustc_usize);
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe12init_cstream(void *, int32_t);
static struct _S15 _RNvCskQUcIKPqzjg_9zstd_safe13c_char_to_str(void *);
__rustc_usize _RNvCskQUcIKPqzjg_9zstd_safe14compress_bound(__rustc_usize);
void * _RNvCskQUcIKPqzjg_9zstd_safe14create_cstream(void);
struct _S15 _RNvCskQUcIKPqzjg_9zstd_safe14get_error_name(__rustc_usize);
uint32_t _RNvCskQUcIKPqzjg_9zstd_safe14version_number(void);
struct _S15 _RNvCskQUcIKPqzjg_9zstd_safe14version_string(void);
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe20compress_using_cdict(void *, void *, __rustc_usize, void *, __rustc_usize, void *);
uint64_t _RNvCskQUcIKPqzjg_9zstd_safe21get_decompressed_size(void *, __rustc_usize);
uint32_t _RNvCskQUcIKPqzjg_9zstd_safe21get_dict_id_from_dict(void *, __rustc_usize);
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe22decompress_using_ddict(void *, void *, __rustc_usize, void *, __rustc_usize, void *);
uint32_t _RNvCskQUcIKPqzjg_9zstd_safe22get_dict_id_from_frame(void *, __rustc_usize);
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe22get_frame_content_size(void *, __rustc_usize);
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe26find_frame_compressed_size(void *, __rustc_usize);
static _Bool _RNvCskQUcIKPqzjg_9zstd_safe8is_error(__rustc_usize);
static struct _S15 _RNvMNtCs41fFVwHnQdq_4core6resultINtB2_6ResultReNtNtNtB4_3str5error9Utf8ErrorE6expectCskQUcIKPqzjg_9zstd_safe(void *, void *, __rustc_usize, void *);
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx10ref_prefix(void *, void *, __rustc_usize);
void * _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx10try_create(void);
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx13set_parameter(void *, int64_t);
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx15load_dictionary(void *, void *, __rustc_usize);
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx18disable_dictionary(void *);
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx20set_pledged_src_size(void *, uint64_t, uint64_t);
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx4init(void *, int32_t);
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx5reset(void *, uint8_t);
void * _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx6create(void);
__rustc_usize _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx6sizeof(void *);
__rustc_usize _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx7in_size(void);
__rustc_usize _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx8out_size(void);
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx9ref_cdict(void *, void *);
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx10ref_prefix(void *, void *, __rustc_usize);
void * _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx10try_create(void);
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx13set_parameter(void *, uint32_t);
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx15load_dictionary(void *, void *, __rustc_usize);
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx18disable_dictionary(void *);
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx4init(void *);
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx5reset(void *, uint8_t);
void * _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx6create(void);
__rustc_usize _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx6sizeof(void *);
__rustc_usize _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx7in_size(void);
__rustc_usize _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx8out_size(void);
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx9ref_ddict(void *, void *);
void * _RNvMs9_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict10try_create(void *, __rustc_usize, int32_t);
void * _RNvMs9_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict6create(void *, __rustc_usize, int32_t);
uint32_t _RNvMsa_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict11get_dict_id(void *);
__rustc_usize _RNvMsa_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict6sizeof(void *);
void * _RNvMse_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict10try_create(void *, __rustc_usize);
void * _RNvMse_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict6create(void *, __rustc_usize);
uint32_t _RNvMsf_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict11get_dict_id(void *);
__rustc_usize _RNvMsf_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict6sizeof(void *);
void _RNvMsu_CskQUcIKPqzjg_9zstd_safeNtB5_8InBuffer7set_pos(void *, __rustc_usize);
_Bool _RNvXCskQUcIKPqzjg_9zstd_safeNtB2_16ContentSizeErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void *, void *);
void _RNvXs1_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtxNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void *);
static _Bool _RNvXs1g_NtCs41fFVwHnQdq_4core3fmtRINtNtB8_6option6OptionhENtB6_5Debug3fmtCskQUcIKPqzjg_9zstd_safe(void *, void *);
static _Bool _RNvXs1g_NtCs41fFVwHnQdq_4core3fmtRhNtB6_5Debug3fmtCskQUcIKPqzjg_9zstd_safe(void *, void *);
void * _RNvXs4_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtxNtNtCs41fFVwHnQdq_4core7default7Default7default(void);
void _RNvXs6_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtxNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void *);
static _Bool _RNvXs9_NtNtCs41fFVwHnQdq_4core3str5errorNtB5_9Utf8ErrorNtNtB9_3fmt5Debug3fmt(void *, void *);
static _Bool _RNvXsR_NtCs41fFVwHnQdq_4core6optionINtB5_6OptionhENtNtB7_3fmt5Debug3fmtCskQUcIKPqzjg_9zstd_safe(void *, void *);
static _Bool _RNvXsU_NtNtCs41fFVwHnQdq_4core3fmt3numhNtB7_5Debug3fmt(void *, void *);
static _Bool _RNvXsZ_NtNtCs41fFVwHnQdq_4core3fmt3numjNtB7_5Debug3fmt(void *, void *);
void * _RNvXs_CskQUcIKPqzjg_9zstd_safeNtB4_4CCtxNtNtCs41fFVwHnQdq_4core7default7Default7default(void);
void _RNvXsb_CskQUcIKPqzjg_9zstd_safeNtB5_5CDictNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void *);
void _RNvXsg_CskQUcIKPqzjg_9zstd_safeNtB5_5DDictNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void *);
static void * _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf10as_mut_ptr(void *, __rustc_usize);
static void _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf12filled_until(void *, __rustc_usize, __rustc_usize);
static __rustc_usize _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf8capacity(void *, __rustc_usize);
void _RNvXsv_CskQUcIKPqzjg_9zstd_safeNtB5_15InBufferWrapperNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void *);
__rustc_usize ZSTD_compress_usingCDict(void *, void *, __rustc_usize, void *, __rustc_usize, void *);
__rustc_usize ZSTD_decompress_usingDDict(void *, void *, __rustc_usize, void *, __rustc_usize, void *);
uint32_t ZDICT_getDictID(void *, __rustc_usize);
int32_t ZSTD_maxCLevel(void);
int32_t ZSTD_minCLevel(void);
__rustc_usize strlen(void *);
struct _S50 _RNvMs3_NtNtCs41fFVwHnQdq_4core3ffi5c_strNtB5_4CStr6to_str(void *, __rustc_usize);
__rustc_usize ZSTD_compressBound(__rustc_usize);
void * ZSTD_getErrorName(__rustc_usize);
uint32_t ZSTD_versionNumber(void);
void * ZSTD_versionString(void);
uint64_t ZSTD_getDecompressedSize(void *, __rustc_usize);
uint32_t ZSTD_getDictID_fromDict(void *, __rustc_usize);
uint32_t ZSTD_getDictID_fromFrame(void *, __rustc_usize);
uint64_t ZSTD_getFrameContentSize(void *, __rustc_usize);
__rustc_usize ZSTD_findFrameCompressedSize(void *, __rustc_usize);
uint32_t ZSTD_isError(__rustc_usize);
void _RNvNtCs41fFVwHnQdq_4core6result13unwrap_failed(void *, __rustc_usize, void *, void *, void *);
__rustc_usize ZSTD_CCtx_refPrefix(void *, void *, __rustc_usize);
void * ZSTD_createCCtx(void);
__rustc_usize ZSTD_CCtx_setParameter(void *, uint32_t, int32_t);
__rustc_usize ZSTD_CCtx_loadDictionary(void *, void *, __rustc_usize);
__rustc_usize ZSTD_CCtx_setPledgedSrcSize(void *, uint64_t);
__rustc_usize ZSTD_initCStream(void *, int32_t);
__rustc_usize ZSTD_CCtx_reset(void *, uint32_t);
void _RNvNtCs41fFVwHnQdq_4core6option13expect_failed(void *, __rustc_usize, void *);
__rustc_usize ZSTD_sizeof_CCtx(void *);
__rustc_usize ZSTD_CStreamInSize(void);
__rustc_usize ZSTD_CStreamOutSize(void);
__rustc_usize ZSTD_CCtx_refCDict(void *, void *);
__rustc_usize ZSTD_DCtx_refPrefix(void *, void *, __rustc_usize);
void * ZSTD_createDCtx(void);
__rustc_usize ZSTD_DCtx_setParameter(void *, uint32_t, int32_t);
__rustc_usize ZSTD_DCtx_loadDictionary(void *, void *, __rustc_usize);
__rustc_usize ZSTD_initDStream(void *);
__rustc_usize ZSTD_DCtx_reset(void *, uint32_t);
__rustc_usize ZSTD_sizeof_DCtx(void *);
__rustc_usize ZSTD_DStreamInSize(void);
__rustc_usize ZSTD_DStreamOutSize(void);
__rustc_usize ZSTD_DCtx_refDDict(void *, void *);
void * ZSTD_createCDict(void *, __rustc_usize, int32_t);
uint32_t ZSTD_getDictID_fromCDict(void *);
__rustc_usize ZSTD_sizeof_CDict(void *);
void * ZSTD_createDDict(void *, __rustc_usize);
uint32_t ZSTD_getDictID_fromDDict(void *);
__rustc_usize ZSTD_sizeof_DDict(void *);
void _RNvNtCs41fFVwHnQdq_4core9panicking5panic(void *, __rustc_usize, void *);
_Bool _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(void *, void *, __rustc_usize);
__rustc_usize ZSTD_freeCCtx(void *);
__rustc_usize ZSTD_freeDCtx(void *);
_Bool _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter26debug_struct_field2_finish(void *, void *, __rustc_usize, void *, __rustc_usize, void *, void *, void *, __rustc_usize, void *, void *);
_Bool _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter25debug_tuple_field1_finish(void *, void *, __rustc_usize, void *, void *);
_Bool _RNvXNtNtNtCs41fFVwHnQdq_4core3fmt3num3imphNtB6_7Display3fmt(void *, void *);
_Bool _RNvXsg_NtNtCs41fFVwHnQdq_4core3fmt3numhNtB7_8UpperHex3fmt(void *, void *);
_Bool _RNvXse_NtNtCs41fFVwHnQdq_4core3fmt3numhNtB7_8LowerHex3fmt(void *, void *);
_Bool _RNvXsi_NtNtNtCs41fFVwHnQdq_4core3fmt3num3impjNtB9_7Display3fmt(void *, void *);
_Bool _RNvXs8_NtNtCs41fFVwHnQdq_4core3fmt3numjNtB7_8UpperHex3fmt(void *, void *);
_Bool _RNvXs6_NtNtCs41fFVwHnQdq_4core3fmt3numjNtB7_8LowerHex3fmt(void *, void *);
__rustc_usize ZSTD_freeCDict(void *);
__rustc_usize ZSTD_freeDDict(void *);

static const unsigned char _bytes0[] = { 0x62, 0x61, 0x64, 0x20, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x20, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x20, 0x66, 0x72, 0x6f, 0x6d, 0x20, 0x7a, 0x73, 0x74, 0x64 };
static const unsigned char _bytes2[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x7a, 0x73, 0x74, 0x64, 0x2d, 0x73, 0x61, 0x66, 0x65, 0x2d, 0x37, 0x2e, 0x32, 0x2e, 0x34, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes1 = {   .f0 = (void *)_bytes2,   .f1 = { 0x61, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x6b, 0x03, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
_Alignas(8) static const unsigned char _bytes3[] = { 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
_Alignas(8) static const unsigned char _bytes4[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
#pragma pack(push, 1)
static const struct {   unsigned char f0[24];   void *f1; } _bytes5 = {   .f0 = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },   .f1 = (void *)(void (*)(void))_RNvXs9_NtNtCs41fFVwHnQdq_4core3str5errorNtB5_9Utf8ErrorNtNtB9_3fmt5Debug3fmt };
#pragma pack(pop)
static const unsigned char _bytes6[] = { 0x7a, 0x73, 0x74, 0x64, 0x20, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x20, 0x6e, 0x75, 0x6c, 0x6c, 0x20, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x20, 0x77, 0x68, 0x65, 0x6e, 0x20, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x20, 0x6e, 0x65, 0x77, 0x20, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74 };
static const unsigned char _bytes8[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x7a, 0x73, 0x74, 0x64, 0x2d, 0x73, 0x61, 0x66, 0x65, 0x2d, 0x37, 0x2e, 0x32, 0x2e, 0x34, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes7 = {   .f0 = (void *)_bytes8,   .f1 = { 0x61, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xfe, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes9[] = { 0x7a, 0x73, 0x74, 0x64, 0x20, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x20, 0x6e, 0x75, 0x6c, 0x6c, 0x20, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x20, 0x77, 0x68, 0x65, 0x6e, 0x20, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x20, 0x6e, 0x65, 0x77, 0x20, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74 };
static const unsigned char _bytes11[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x7a, 0x73, 0x74, 0x64, 0x2d, 0x73, 0x61, 0x66, 0x65, 0x2d, 0x37, 0x2e, 0x32, 0x2e, 0x34, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes10 = {   .f0 = (void *)_bytes11,   .f1 = { 0x61, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x98, 0x03, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes12[] = { 0x7a, 0x73, 0x74, 0x64, 0x20, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x20, 0x6e, 0x75, 0x6c, 0x6c, 0x20, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x20, 0x77, 0x68, 0x65, 0x6e, 0x20, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x20, 0x64, 0x69, 0x63, 0x74 };
static const unsigned char _bytes14[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x7a, 0x73, 0x74, 0x64, 0x2d, 0x73, 0x61, 0x66, 0x65, 0x2d, 0x37, 0x2e, 0x32, 0x2e, 0x34, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes13 = {   .f0 = (void *)_bytes14,   .f1 = { 0x61, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x05, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes15[] = { 0x7a, 0x73, 0x74, 0x64, 0x20, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x20, 0x6e, 0x75, 0x6c, 0x6c, 0x20, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x20, 0x77, 0x68, 0x65, 0x6e, 0x20, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x20, 0x64, 0x69, 0x63, 0x74 };
static const unsigned char _bytes17[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x7a, 0x73, 0x74, 0x64, 0x2d, 0x73, 0x61, 0x66, 0x65, 0x2d, 0x37, 0x2e, 0x32, 0x2e, 0x34, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes16 = {   .f0 = (void *)_bytes17,   .f1 = { 0x61, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x6b, 0x05, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes18[] = { 0x47, 0x69, 0x76, 0x65, 0x6e, 0x20, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x20, 0x6f, 0x66, 0x20, 0x74, 0x68, 0x65, 0x20, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x20, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x2e };
static const unsigned char _bytes20[] = { 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x6c, 0x74, 0x73, 0x2f, 0x2e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x72, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x69, 0x6f, 0x2d, 0x31, 0x39, 0x34, 0x39, 0x63, 0x66, 0x38, 0x63, 0x36, 0x62, 0x35, 0x62, 0x35, 0x35, 0x37, 0x66, 0x2f, 0x7a, 0x73, 0x74, 0x64, 0x2d, 0x73, 0x61, 0x66, 0x65, 0x2d, 0x37, 0x2e, 0x32, 0x2e, 0x34, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73, 0x00 };
#pragma pack(push, 1)
static const struct {   void *f0;   unsigned char f1[16]; } _bytes19 = {   .f0 = (void *)_bytes20,   .f1 = { 0x61, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8c, 0x07, 0x00, 0x00, 0x0d, 0x00, 0x00, 0x00 } };
#pragma pack(pop)
static const unsigned char _bytes21[] = { 0x43, 0x6f, 0x75, 0x6c, 0x64, 0x20, 0x6e, 0x6f, 0x74, 0x20, 0x67, 0x65, 0x74, 0x20, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x20, 0x73, 0x69, 0x7a, 0x65 };
#pragma pack(push, 1)
static const struct {   unsigned char f0[24];   void *f1; } _bytes22 = {   .f0 = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },   .f1 = (void *)(void (*)(void))_RNvXsZ_NtNtCs41fFVwHnQdq_4core3fmt3numjNtB7_5Debug3fmt };
#pragma pack(pop)
#pragma pack(push, 1)
static const struct {   unsigned char f0[24];   void *f1; } _bytes23 = {   .f0 = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },   .f1 = (void *)(void (*)(void))_RNvXs1g_NtCs41fFVwHnQdq_4core3fmtRINtNtB8_6option6OptionhENtB6_5Debug3fmtCskQUcIKPqzjg_9zstd_safe };
#pragma pack(pop)
static const unsigned char _bytes24[] = { 0x55, 0x74, 0x66, 0x38, 0x45, 0x72, 0x72, 0x6f, 0x72 };
static const unsigned char _bytes25[] = { 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x75, 0x70, 0x5f, 0x74, 0x6f };
static const unsigned char _bytes26[] = { 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6c, 0x65, 0x6e };
static const unsigned char _bytes27[] = { 0x4e, 0x6f, 0x6e, 0x65 };
#pragma pack(push, 1)
static const struct {   unsigned char f0[24];   void *f1; } _bytes28 = {   .f0 = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },   .f1 = (void *)(void (*)(void))_RNvXs1g_NtCs41fFVwHnQdq_4core3fmtRhNtB6_5Debug3fmtCskQUcIKPqzjg_9zstd_safe };
#pragma pack(pop)
static const unsigned char _bytes29[] = { 0x53, 0x6f, 0x6d, 0x65 };

static struct _S2 _RINvYShNtCskQUcIKPqzjg_9zstd_safe8WriteBuf10write_fromNCINvMs0_B7_NtB7_4CCtx20compress_using_cdictB3_E0EB7_(void * _arg0, __rustc_usize _arg1, void * _arg2) {
  _Alignas(8) uint8_t _t0_storage[16];
  void *_t0 = (void *)_t0_storage;
  _Alignas(8) uint8_t _t1_storage[24];
  void *_t1 = (void *)_t1_storage;
  _Alignas(1) uint8_t _t2_storage[1];
  void *_t2 = (void *)_t2_storage;
  int8_t _t3;
  _Alignas(8) uint8_t _t4_storage[16];
  void *_t4 = (void *)_t4_storage;
  void * _t5;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t6;
  void * _t7;
  __rustc_usize _t8;
  int8_t _t9;
  struct _S2 _t10;
  uint64_t _t11;
  void * _t12;
  uint64_t _t13;
  __rustc_isize _t14;
  _Bool _t15;
  void * _t16;
  __rustc_usize _t17;
  uint64_t _t18;
  void * _t19;
  uint64_t _t20;
  struct _S2 _t21;
  struct _S2 _t22;
  _Bool _t23;
  void * _t24;
  void * _t25;
  int32_t _t26;

bb_0_start:
  _t3 = (int8_t)(1ULL);
  *(int8_t *)_t2 = _t3;
  memcpy(_t1, _arg2, 24ULL);
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t6 = _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf10as_mut_ptr(_arg0, _arg1);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb8;
bb_1_bb7:
  _t23 = *(_Bool *)_t2;
  if (_t23) goto bb_10_bb6; else goto bb_9_bb5;
bb_2_cleanup:
  *(void * *)_t4 = __exn_ptr;
  _t5 = (void *)((__rustc_usize)_t4 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t5 = 0LL;
  goto bb_1_bb7;
bb_3_bb8:
  _t7 = (void *)_t6;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t8 = _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf8capacity(_arg0, _arg1);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_4_bb1;
bb_4_bb1:
  _t9 = (int8_t)(0ULL);
  *(int8_t *)_t2 = _t9;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t10 = _RNCINvMs0_CskQUcIKPqzjg_9zstd_safeNtB8_4CCtx20compress_using_cdictShE0B8_(_t1, _t7, _t8);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_5_bb2;
bb_5_bb2:
  *(struct _S2 *)_t0 = _t10;
  _t11 = *(uint64_t *)_t0;
  _t12 = (void *)((__rustc_usize)_t0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t13 = *(uint64_t *)_t12;
  _t14 = (__rustc_isize)_t11;
  _t15 = (_Bool)_t14;
  if (_t15) goto bb_6_bb4; else goto bb_7_bb3;
bb_6_bb4:
  _t18 = *(uint64_t *)_t0;
  _t19 = (void *)((__rustc_usize)_t0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t20 = *(uint64_t *)_t19;
  memset(&_t21, 0, sizeof(_t21));
  _t21.f0 = _t18;
  _t22 = _t21;
  _t22.f1 = _t20;
  return _t22;
bb_7_bb3:
  _t16 = (void *)((__rustc_usize)_t0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t17 = *(__rustc_usize *)_t16;
  _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf12filled_until(_arg0, _arg1, _t17);
  goto bb_6_bb4;
bb_8_bb9:
  abort();
bb_9_bb5:
  _t24 = *(void * *)_t4;
  _t25 = (void *)((__rustc_usize)_t4 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t26 = *(int32_t *)_t25;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t24; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
bb_10_bb6:
  goto bb_9_bb5;
}

static struct _S2 _RINvYShNtCskQUcIKPqzjg_9zstd_safe8WriteBuf10write_fromNCINvMs5_B7_NtB7_4DCtx22decompress_using_ddictB3_E0EB7_(void * _arg0, __rustc_usize _arg1, void * _arg2) {
  _Alignas(8) uint8_t _t27_storage[16];
  void *_t27 = (void *)_t27_storage;
  _Alignas(8) uint8_t _t28_storage[24];
  void *_t28 = (void *)_t28_storage;
  _Alignas(1) uint8_t _t29_storage[1];
  void *_t29 = (void *)_t29_storage;
  int8_t _t30;
  _Alignas(8) uint8_t _t31_storage[16];
  void *_t31 = (void *)_t31_storage;
  void * _t32;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t33;
  void * _t34;
  __rustc_usize _t35;
  int8_t _t36;
  struct _S2 _t37;
  uint64_t _t38;
  void * _t39;
  uint64_t _t40;
  __rustc_isize _t41;
  _Bool _t42;
  void * _t43;
  __rustc_usize _t44;
  uint64_t _t45;
  void * _t46;
  uint64_t _t47;
  struct _S2 _t48;
  struct _S2 _t49;
  _Bool _t50;
  void * _t51;
  void * _t52;
  int32_t _t53;

bb_0_start:
  _t30 = (int8_t)(1ULL);
  *(int8_t *)_t29 = _t30;
  memcpy(_t28, _arg2, 24ULL);
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t33 = _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf10as_mut_ptr(_arg0, _arg1);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_3_bb8;
bb_1_bb7:
  _t50 = *(_Bool *)_t29;
  if (_t50) goto bb_10_bb6; else goto bb_9_bb5;
bb_2_cleanup:
  *(void * *)_t31 = __exn_ptr;
  _t32 = (void *)((__rustc_usize)_t31 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t32 = 0LL;
  goto bb_1_bb7;
bb_3_bb8:
  _t34 = (void *)_t33;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t35 = _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf8capacity(_arg0, _arg1);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_4_bb1;
bb_4_bb1:
  _t36 = (int8_t)(0ULL);
  *(int8_t *)_t29 = _t36;
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_2_cleanup; }
  _t37 = _RNCINvMs5_CskQUcIKPqzjg_9zstd_safeNtB8_4DCtx22decompress_using_ddictShE0B8_(_t28, _t34, _t35);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_5_bb2;
bb_5_bb2:
  *(struct _S2 *)_t27 = _t37;
  _t38 = *(uint64_t *)_t27;
  _t39 = (void *)((__rustc_usize)_t27 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t40 = *(uint64_t *)_t39;
  _t41 = (__rustc_isize)_t38;
  _t42 = (_Bool)_t41;
  if (_t42) goto bb_6_bb4; else goto bb_7_bb3;
bb_6_bb4:
  _t45 = *(uint64_t *)_t27;
  _t46 = (void *)((__rustc_usize)_t27 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t47 = *(uint64_t *)_t46;
  memset(&_t48, 0, sizeof(_t48));
  _t48.f0 = _t45;
  _t49 = _t48;
  _t49.f1 = _t47;
  return _t49;
bb_7_bb3:
  _t43 = (void *)((__rustc_usize)_t27 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t44 = *(__rustc_usize *)_t43;
  _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf12filled_until(_arg0, _arg1, _t44);
  goto bb_6_bb4;
bb_8_bb9:
  abort();
bb_9_bb5:
  _t51 = *(void * *)_t31;
  _t52 = (void *)((__rustc_usize)_t31 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t53 = *(int32_t *)_t52;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t51; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
bb_10_bb6:
  goto bb_9_bb5;
}

static struct _S2 _RNCINvMs0_CskQUcIKPqzjg_9zstd_safeNtB8_4CCtx20compress_using_cdictShE0B8_(void * _arg0, void * _arg1, __rustc_usize _arg2) {
  void * _t54;
  void * _t55;
  void * _t56;
  _Bool _t57;
  void * _t58;
  void * _t59;
  void * _t60;
  void * _t61;
  void * _t62;
  __rustc_usize _t63;
  void * _t64;
  void * _t65;
  void * _t66;
  void * _t67;
  _Bool _t68;
  void * _t69;
  __rustc_usize _t70;
  struct _S2 _t71;
  uint64_t _t72;
  uint64_t _t73;
  struct _S2 _t74;
  struct _S2 _t75;

bb_0_start:
  _t54 = *(void * *)_arg0;
  _t55 = *(void * *)_t54;
  _t56 = *(void * *)_t55;
  _t57 = (int64_t)_t56 != (int64_t)0;
  _t58 = (void *)_t56;
  _t59 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t60 = *(void * *)_t59;
  _t61 = *(void * *)_t60;
  _t62 = (void *)((__rustc_usize)_t60 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t63 = *(__rustc_usize *)_t62;
  _t64 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t65 = *(void * *)_t64;
  _t66 = *(void * *)_t65;
  _t67 = *(void * *)_t66;
  _t68 = (int64_t)_t67 != (int64_t)0;
  _t69 = (void *)_t67;
  _t70 = ZSTD_compress_usingCDict(_t58, _arg1, _arg2, _t61, _t63, _t69);
  _t71 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t70);
  _t72 = _t71.f0;
  _t73 = _t71.f1;
  memset(&_t74, 0, sizeof(_t74));
  _t74.f0 = _t72;
  _t75 = _t74;
  _t75.f1 = _t73;
  return _t75;
}

static struct _S2 _RNCINvMs5_CskQUcIKPqzjg_9zstd_safeNtB8_4DCtx22decompress_using_ddictShE0B8_(void * _arg0, void * _arg1, __rustc_usize _arg2) {
  void * _t76;
  void * _t77;
  void * _t78;
  _Bool _t79;
  void * _t80;
  void * _t81;
  void * _t82;
  void * _t83;
  void * _t84;
  __rustc_usize _t85;
  void * _t86;
  void * _t87;
  void * _t88;
  void * _t89;
  _Bool _t90;
  void * _t91;
  __rustc_usize _t92;
  struct _S2 _t93;
  uint64_t _t94;
  uint64_t _t95;
  struct _S2 _t96;
  struct _S2 _t97;

bb_0_start:
  _t76 = *(void * *)_arg0;
  _t77 = *(void * *)_t76;
  _t78 = *(void * *)_t77;
  _t79 = (int64_t)_t78 != (int64_t)0;
  _t80 = (void *)_t78;
  _t81 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t82 = *(void * *)_t81;
  _t83 = *(void * *)_t82;
  _t84 = (void *)((__rustc_usize)_t82 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t85 = *(__rustc_usize *)_t84;
  _t86 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t87 = *(void * *)_t86;
  _t88 = *(void * *)_t87;
  _t89 = *(void * *)_t88;
  _t90 = (int64_t)_t89 != (int64_t)0;
  _t91 = (void *)_t89;
  _t92 = ZSTD_decompress_usingDDict(_t80, _arg1, _arg2, _t83, _t85, _t91);
  _t93 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t92);
  _t94 = _t93.f0;
  _t95 = _t93.f1;
  memset(&_t96, 0, sizeof(_t96));
  _t96.f0 = _t94;
  _t97 = _t96;
  _t97.f1 = _t95;
  return _t97;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe10parse_code
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(__rustc_usize _arg0) {
  _Alignas(8) uint8_t _t98_storage[16];
  void *_t98 = (void *)_t98_storage;
  _Bool _t99;
  _Bool _t100;
  void * _t101;
  void * _t102;
  uint64_t _t103;
  void * _t104;
  uint64_t _t105;
  struct _S2 _t106;
  struct _S2 _t107;

bb_0_start:
  _t99 = _RNvCskQUcIKPqzjg_9zstd_safe8is_error(_arg0);
  _t100 = (_Bool)(_t99);
  if (_t100) goto bb_2_bb2; else goto bb_1_bb3;
bb_1_bb3:
  _t101 = (void *)((__rustc_usize)_t98 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t101 = _arg0;
  *(uint64_t *)_t98 = 0ULL;
  goto bb_3_bb4;
bb_2_bb2:
  _t102 = (void *)((__rustc_usize)_t98 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t102 = _arg0;
  *(uint64_t *)_t98 = 1ULL;
  goto bb_3_bb4;
bb_3_bb4:
  _t103 = *(uint64_t *)_t98;
  _t104 = (void *)((__rustc_usize)_t98 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t105 = *(uint64_t *)_t104;
  memset(&_t106, 0, sizeof(_t106));
  _t106.f0 = _t103;
  _t107 = _t106;
  _t107.f1 = _t105;
  return _t107;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe11get_dict_id
uint32_t _RNvCskQUcIKPqzjg_9zstd_safe11get_dict_id(void * _arg0, __rustc_usize _arg1) {
  uint32_t _t108;
  int32_t _t109;

bb_0_start:
  _t108 = ZDICT_getDictID(_arg0, _arg1);
  _t109 = (int32_t)_t108;
  return _t109;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe11max_c_level
int32_t _RNvCskQUcIKPqzjg_9zstd_safe11max_c_level(void) {
  int32_t _t110;

bb_0_start:
  _t110 = ZSTD_maxCLevel();
  return _t110;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe11min_c_level
int32_t _RNvCskQUcIKPqzjg_9zstd_safe11min_c_level(void) {
  int32_t _t111;

bb_0_start:
  _t111 = ZSTD_minCLevel();
  return _t111;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe12create_cdict
void * _RNvCskQUcIKPqzjg_9zstd_safe12create_cdict(void * _arg0, __rustc_usize _arg1, int32_t _arg2) {
  void * _t112;

bb_0_start:
  _t112 = _RNvMs9_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict6create(_arg0, _arg1, _arg2);
  return _t112;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe12create_ddict
void * _RNvCskQUcIKPqzjg_9zstd_safe12create_ddict(void * _arg0, __rustc_usize _arg1) {
  void * _t113;

bb_0_start:
  _t113 = _RNvMse_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict6create(_arg0, _arg1);
  return _t113;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe12init_cstream
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe12init_cstream(void * _arg0, int32_t _arg1) {
  struct _S2 _t114;
  uint64_t _t115;
  uint64_t _t116;
  struct _S2 _t117;
  struct _S2 _t118;

bb_0_start:
  _t114 = _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx4init(_arg0, _arg1);
  _t115 = _t114.f0;
  _t116 = _t114.f1;
  memset(&_t117, 0, sizeof(_t117));
  _t117.f0 = _t115;
  _t118 = _t117;
  _t118.f1 = _t116;
  return _t118;
}

static struct _S15 _RNvCskQUcIKPqzjg_9zstd_safe13c_char_to_str(void * _arg0) {
  _Alignas(8) uint8_t _t119_storage[24];
  void *_t119 = (void *)_t119_storage;
  __rustc_usize _t120;
  __rustc_usize _t121;
  struct _S50 _t122;
  struct _S15 _t123;
  void * _t124;
  __rustc_usize _t125;
  struct _S15 _t126;
  struct _S15 _t127;

bb_0_start:
  _t120 = strlen(_arg0);
  _t121 = _t120 + 1ULL;
  _t122 = _RNvMs3_NtNtCs41fFVwHnQdq_4core3ffi5c_strNtB5_4CStr6to_str(_arg0, _t121);
  *(struct _S50 *)_t119 = _t122;
  _t123 = _RNvMNtCs41fFVwHnQdq_4core6resultINtB2_6ResultReNtNtNtB4_3str5error9Utf8ErrorE6expectCskQUcIKPqzjg_9zstd_safe(_t119, _bytes0, 27ULL, &_bytes1);
  _t124 = _t123.f0;
  _t125 = _t123.f1;
  memset(&_t126, 0, sizeof(_t126));
  _t126.f0 = _t124;
  _t127 = _t126;
  _t127.f1 = _t125;
  return _t127;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe14compress_bound
__rustc_usize _RNvCskQUcIKPqzjg_9zstd_safe14compress_bound(__rustc_usize _arg0) {
  __rustc_usize _t128;

bb_0_start:
  _t128 = ZSTD_compressBound(_arg0);
  return _t128;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe14create_cstream
void * _RNvCskQUcIKPqzjg_9zstd_safe14create_cstream(void) {
  void * _t129;

bb_0_start:
  _t129 = _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx6create();
  return _t129;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe14get_error_name
struct _S15 _RNvCskQUcIKPqzjg_9zstd_safe14get_error_name(__rustc_usize _arg0) {
  void * _t130;
  struct _S15 _t131;
  void * _t132;
  __rustc_usize _t133;
  struct _S15 _t134;
  struct _S15 _t135;

bb_0_start:
  _t130 = ZSTD_getErrorName(_arg0);
  _t131 = _RNvCskQUcIKPqzjg_9zstd_safe13c_char_to_str(_t130);
  _t132 = _t131.f0;
  _t133 = _t131.f1;
  memset(&_t134, 0, sizeof(_t134));
  _t134.f0 = _t132;
  _t135 = _t134;
  _t135.f1 = _t133;
  return _t135;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe14version_number
uint32_t _RNvCskQUcIKPqzjg_9zstd_safe14version_number(void) {
  uint32_t _t136;

bb_0_start:
  _t136 = ZSTD_versionNumber();
  return _t136;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe14version_string
struct _S15 _RNvCskQUcIKPqzjg_9zstd_safe14version_string(void) {
  void * _t137;
  struct _S15 _t138;
  void * _t139;
  __rustc_usize _t140;
  struct _S15 _t141;
  struct _S15 _t142;

bb_0_start:
  _t137 = ZSTD_versionString();
  _t138 = _RNvCskQUcIKPqzjg_9zstd_safe13c_char_to_str(_t137);
  _t139 = _t138.f0;
  _t140 = _t138.f1;
  memset(&_t141, 0, sizeof(_t141));
  _t141.f0 = _t139;
  _t142 = _t141;
  _t142.f1 = _t140;
  return _t142;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe20compress_using_cdict
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe20compress_using_cdict(void * _arg0, void * _arg1, __rustc_usize _arg2, void * _arg3, __rustc_usize _arg4, void * _arg5) {
  _Alignas(8) uint8_t _t143_storage[8];
  void *_t143 = (void *)_t143_storage;
  _Alignas(8) uint8_t _t144_storage[16];
  void *_t144 = (void *)_t144_storage;
  _Alignas(8) uint8_t _t145_storage[8];
  void *_t145 = (void *)_t145_storage;
  _Alignas(8) uint8_t _t146_storage[24];
  void *_t146 = (void *)_t146_storage;
  void * _t147;
  void * _t148;
  void * _t149;
  struct _S2 _t150;
  uint64_t _t151;
  uint64_t _t152;
  struct _S2 _t153;
  struct _S2 _t154;

bb_0_start:
  *(void * *)_t143 = _arg0;
  *(void * *)_t144 = _arg3;
  _t147 = (void *)((__rustc_usize)_t144 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t147 = _arg4;
  *(void * *)_t145 = _arg5;
  *(void * *)_t146 = _t143;
  _t148 = (void *)((__rustc_usize)_t146 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t148 = _t144;
  _t149 = (void *)((__rustc_usize)_t146 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t149 = _t145;
  _t150 = _RINvYShNtCskQUcIKPqzjg_9zstd_safe8WriteBuf10write_fromNCINvMs0_B7_NtB7_4CCtx20compress_using_cdictB3_E0EB7_(_arg1, _arg2, _t146);
  _t151 = _t150.f0;
  _t152 = _t150.f1;
  memset(&_t153, 0, sizeof(_t153));
  _t153.f0 = _t151;
  _t154 = _t153;
  _t154.f1 = _t152;
  return _t154;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe21get_decompressed_size
uint64_t _RNvCskQUcIKPqzjg_9zstd_safe21get_decompressed_size(void * _arg0, __rustc_usize _arg1) {
  uint64_t _t155;
  int64_t _t156;

bb_0_start:
  _t155 = ZSTD_getDecompressedSize(_arg0, _arg1);
  _t156 = (int64_t)_t155;
  return _t156;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe21get_dict_id_from_dict
uint32_t _RNvCskQUcIKPqzjg_9zstd_safe21get_dict_id_from_dict(void * _arg0, __rustc_usize _arg1) {
  uint32_t _t157;
  int32_t _t158;

bb_0_start:
  _t157 = ZSTD_getDictID_fromDict(_arg0, _arg1);
  _t158 = (int32_t)_t157;
  return _t158;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe22decompress_using_ddict
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe22decompress_using_ddict(void * _arg0, void * _arg1, __rustc_usize _arg2, void * _arg3, __rustc_usize _arg4, void * _arg5) {
  _Alignas(8) uint8_t _t159_storage[8];
  void *_t159 = (void *)_t159_storage;
  _Alignas(8) uint8_t _t160_storage[16];
  void *_t160 = (void *)_t160_storage;
  _Alignas(8) uint8_t _t161_storage[8];
  void *_t161 = (void *)_t161_storage;
  _Alignas(8) uint8_t _t162_storage[24];
  void *_t162 = (void *)_t162_storage;
  void * _t163;
  void * _t164;
  void * _t165;
  struct _S2 _t166;
  uint64_t _t167;
  uint64_t _t168;
  struct _S2 _t169;
  struct _S2 _t170;

bb_0_start:
  *(void * *)_t159 = _arg0;
  *(void * *)_t160 = _arg3;
  _t163 = (void *)((__rustc_usize)_t160 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t163 = _arg4;
  *(void * *)_t161 = _arg5;
  *(void * *)_t162 = _t159;
  _t164 = (void *)((__rustc_usize)_t162 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t164 = _t160;
  _t165 = (void *)((__rustc_usize)_t162 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t165 = _t161;
  _t166 = _RINvYShNtCskQUcIKPqzjg_9zstd_safe8WriteBuf10write_fromNCINvMs5_B7_NtB7_4DCtx22decompress_using_ddictB3_E0EB7_(_arg1, _arg2, _t162);
  _t167 = _t166.f0;
  _t168 = _t166.f1;
  memset(&_t169, 0, sizeof(_t169));
  _t169.f0 = _t167;
  _t170 = _t169;
  _t170.f1 = _t168;
  return _t170;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe22get_dict_id_from_frame
uint32_t _RNvCskQUcIKPqzjg_9zstd_safe22get_dict_id_from_frame(void * _arg0, __rustc_usize _arg1) {
  uint32_t _t171;
  int32_t _t172;

bb_0_start:
  _t171 = ZSTD_getDictID_fromFrame(_arg0, _arg1);
  _t172 = (int32_t)_t171;
  return _t172;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe22get_frame_content_size
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe22get_frame_content_size(void * _arg0, __rustc_usize _arg1) {
  _Alignas(8) uint8_t _t173_storage[16];
  void *_t173 = (void *)_t173_storage;
  uint64_t _t174;
  uint64_t _t175;
  void * _t176;
  uint64_t _t177;
  void * _t178;
  uint64_t _t179;
  void * _t180;
  uint64_t _t181;
  void * _t182;
  int64_t _t183;
  void * _t184;
  uint64_t _t185;
  void * _t186;
  uint64_t _t187;
  struct _S2 _t188;
  struct _S2 _t189;

bb_0_start:
  _t174 = ZSTD_getFrameContentSize(_arg0, _arg1);
  switch (_t174) {
    case 18446744073709551614ULL: goto bb_2_bb5;
    case 18446744073709551615ULL: goto bb_3_bb4;
    default: goto bb_1_bb3;
  }
bb_1_bb3:
  _t183 = (int64_t)_t174;
  *(uint64_t *)_t173 = 1ULL;
  _t184 = (void *)((__rustc_usize)_t173 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t184 = _t183;
  goto bb_4_bb2;
bb_2_bb5:
  _t175 = *(uint64_t *)_bytes3;
  _t176 = (void *)((__rustc_usize)_bytes3 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t177 = *(uint64_t *)_t176;
  *(uint64_t *)_t173 = _t175;
  _t178 = (void *)((__rustc_usize)_t173 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t178 = _t177;
  goto bb_4_bb2;
bb_3_bb4:
  _t179 = *(uint64_t *)_bytes4;
  _t180 = (void *)((__rustc_usize)_bytes4 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t181 = *(uint64_t *)_t180;
  *(uint64_t *)_t173 = _t179;
  _t182 = (void *)((__rustc_usize)_t173 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t182 = _t181;
  goto bb_4_bb2;
bb_4_bb2:
  _t185 = *(uint64_t *)_t173;
  _t186 = (void *)((__rustc_usize)_t173 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t187 = *(uint64_t *)_t186;
  memset(&_t188, 0, sizeof(_t188));
  _t188.f0 = _t185;
  _t189 = _t188;
  _t189.f1 = _t187;
  return _t189;
}

#pragma weak _RNvCskQUcIKPqzjg_9zstd_safe26find_frame_compressed_size
struct _S2 _RNvCskQUcIKPqzjg_9zstd_safe26find_frame_compressed_size(void * _arg0, __rustc_usize _arg1) {
  __rustc_usize _t190;
  struct _S2 _t191;
  uint64_t _t192;
  uint64_t _t193;
  struct _S2 _t194;
  struct _S2 _t195;

bb_0_start:
  _t190 = ZSTD_findFrameCompressedSize(_arg0, _arg1);
  _t191 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t190);
  _t192 = _t191.f0;
  _t193 = _t191.f1;
  memset(&_t194, 0, sizeof(_t194));
  _t194.f0 = _t192;
  _t195 = _t194;
  _t195.f1 = _t193;
  return _t195;
}

static _Bool _RNvCskQUcIKPqzjg_9zstd_safe8is_error(__rustc_usize _arg0) {
  uint32_t _t196;
  _Bool _t197;

bb_0_start:
  _t196 = ZSTD_isError(_arg0);
  _t197 = (int32_t)_t196 != (int32_t)0ULL;
  return _t197;
}

static struct _S15 _RNvMNtCs41fFVwHnQdq_4core6resultINtB2_6ResultReNtNtNtB4_3str5error9Utf8ErrorE6expectCskQUcIKPqzjg_9zstd_safe(void * _arg0, void * _arg1, __rustc_usize _arg2, void * _arg3) {
  _Alignas(8) uint8_t _t198_storage[16];
  void *_t198 = (void *)_t198_storage;
  uint64_t _t199;
  __rustc_isize _t200;
  _Bool _t201;
  void * _t202;
  void * _t203;
  void * _t204;
  __rustc_usize _t205;
  struct _S15 _t206;
  struct _S15 _t207;
  void * _t208;
  _Alignas(8) uint8_t _t209_storage[16];
  void *_t209 = (void *)_t209_storage;
  void * _t210;
  void *__exn_ptr;
  struct __rustc_unwind_context __unwind_ctx;
  void * _t211;
  void * _t212;
  int32_t _t213;

bb_0_start:
  _t199 = *(uint64_t *)_arg0;
  _t200 = (__rustc_isize)_t199;
  _t201 = (_Bool)_t200;
  if (_t201) goto bb_1_bb2; else goto bb_2_bb3;
bb_1_bb2:
  _t208 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  memcpy(_t198, _t208, 16ULL);
  __unwind_ctx.prev = __rustc_unwind_chain;
  __unwind_ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__unwind_ctx;
  if (__rustc_setjmp(__unwind_ctx.buf) != 0) { __exn_ptr = __unwind_ctx.exception_ptr; __rustc_unwind_chain = __unwind_ctx.prev; goto bb_4_cleanup; }
  _RNvNtCs41fFVwHnQdq_4core6result13unwrap_failed(_arg1, _arg2, _t198, &_bytes5, _arg3);
  __rustc_unwind_chain = __unwind_ctx.prev;
  goto bb_5_unreachable;
bb_2_bb3:
  _t202 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t203 = *(void * *)_t202;
  _t204 = (void *)((__rustc_usize)_t202 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t205 = *(__rustc_usize *)_t204;
  memset(&_t206, 0, sizeof(_t206));
  _t206.f0 = _t203;
  _t207 = _t206;
  _t207.f1 = _t205;
  return _t207;
bb_3_bb4:
  _t211 = *(void * *)_t209;
  _t212 = (void *)((__rustc_usize)_t209 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t213 = *(int32_t *)_t212;
  if (__rustc_unwind_chain) { __rustc_unwind_chain->exception_ptr = (void *)_t211; __rustc_longjmp(__rustc_unwind_chain->buf, 1); } else { abort(); }
bb_4_cleanup:
  *(void * *)_t209 = __exn_ptr;
  _t210 = (void *)((__rustc_usize)_t209 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(int32_t *)_t210 = 0LL;
  goto bb_3_bb4;
bb_5_unreachable:
  abort();
bb_6_bb1:
  abort();
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx10ref_prefix
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx10ref_prefix(void * _arg0, void * _arg1, __rustc_usize _arg2) {
  void * _t214;
  _Bool _t215;
  void * _t216;
  __rustc_usize _t217;
  struct _S2 _t218;
  uint64_t _t219;
  uint64_t _t220;
  struct _S2 _t221;
  struct _S2 _t222;

bb_0_start:
  _t214 = *(void * *)_arg0;
  _t215 = (int64_t)_t214 != (int64_t)0;
  _t216 = (void *)_t214;
  _t217 = ZSTD_CCtx_refPrefix(_t216, _arg1, _arg2);
  _t218 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t217);
  _t219 = _t218.f0;
  _t220 = _t218.f1;
  memset(&_t221, 0, sizeof(_t221));
  _t221.f0 = _t219;
  _t222 = _t221;
  _t222.f1 = _t220;
  return _t222;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx10try_create
void * _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx10try_create(void) {
  _Alignas(8) uint8_t _t223_storage[8];
  void *_t223 = (void *)_t223_storage;
  _Alignas(8) uint8_t _t224_storage[8];
  void *_t224 = (void *)_t224_storage;
  _Alignas(8) uint8_t _t225_storage[8];
  void *_t225 = (void *)_t225_storage;
  void * _t226;
  int64_t _t227;
  _Bool _t228;
  void * _t229;
  void * _t230;
  _Bool _t231;
  void * _t232;
  void * _t233;
  void * _t234;

bb_0_start:
  _t226 = ZSTD_createCCtx();
  _t227 = (int64_t)_t226;
  _t228 = (__rustc_isize)_t227 == (__rustc_isize)0ULL;
  if (_t228) goto bb_1_bb3; else goto bb_2_bb4;
bb_1_bb3:
  *(void * *)_t223 = (void *)(__rustc_usize)0ULL;
  goto bb_3_bb2;
bb_2_bb4:
  _t229 = (void *)_t226;
  _t230 = (void *)_t229;
  _t231 = (int64_t)_t230 != (int64_t)0;
  *(void * *)_t225 = _t230;
  _t232 = *(void * *)_t225;
  *(void * *)_t224 = _t232;
  _t233 = *(void * *)_t224;
  *(void * *)_t223 = _t233;
  goto bb_3_bb2;
bb_3_bb2:
  _t234 = *(void * *)_t223;
  return _t234;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx13set_parameter
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx13set_parameter(void * _arg0, int64_t _arg1) {
  _Alignas(4) uint8_t _t235_storage[8];
  void *_t235 = (void *)_t235_storage;
  _Alignas(8) uint8_t _t236_storage[8];
  void *_t236 = (void *)_t236_storage;
  _Alignas(4) uint8_t _t237_storage[4];
  void *_t237 = (void *)_t237_storage;
  _Alignas(4) uint8_t _t238_storage[4];
  void *_t238 = (void *)_t238_storage;
  uint8_t _t239;
  __rustc_isize _t240;
  void * _t241;
  uint32_t _t242;
  int32_t _t243;
  void * _t244;
  int32_t _t245;
  void * _t246;
  uint32_t _t247;
  int32_t _t248;
  void * _t249;
  uint32_t _t250;
  int32_t _t251;
  void * _t252;
  uint32_t _t253;
  int32_t _t254;
  void * _t255;
  uint32_t _t256;
  int32_t _t257;
  void * _t258;
  uint32_t _t259;
  int32_t _t260;
  void * _t261;
  uint32_t _t262;
  int32_t _t263;
  void * _t264;
  uint32_t _t265;
  uint32_t _t266;
  int32_t _t267;
  void * _t268;
  _Bool _t269;
  _Bool _t270;
  int32_t _t271;
  void * _t272;
  uint32_t _t273;
  int32_t _t274;
  void * _t275;
  uint32_t _t276;
  int32_t _t277;
  void * _t278;
  uint32_t _t279;
  int32_t _t280;
  void * _t281;
  uint32_t _t282;
  int32_t _t283;
  void * _t284;
  _Bool _t285;
  _Bool _t286;
  int32_t _t287;
  void * _t288;
  _Bool _t289;
  _Bool _t290;
  int32_t _t291;
  void * _t292;
  _Bool _t293;
  _Bool _t294;
  int32_t _t295;
  void * _t296;
  uint32_t _t297;
  int32_t _t298;
  void * _t299;
  uint32_t _t300;
  int32_t _t301;
  void * _t302;
  uint32_t _t303;
  int32_t _t304;
  void * _t305;
  _Bool _t306;
  void * _t307;
  uint32_t _t308;
  int32_t _t309;
  __rustc_usize _t310;
  struct _S2 _t311;
  uint64_t _t312;
  uint64_t _t313;
  struct _S2 _t314;
  struct _S2 _t315;

bb_0_start:
  *(int64_t *)_t236 = _arg1;
  memcpy(_t235, _t236, 8ULL);
  _t239 = *(uint8_t *)_t235;
  _t240 = (__rustc_isize)_t239;
  switch ((__rustc_usize)_t240) {
    case 0ULL: goto bb_2_bb21;
    case 1ULL: goto bb_3_bb20;
    case 2ULL: goto bb_4_bb19;
    case 3ULL: goto bb_5_bb18;
    case 4ULL: goto bb_6_bb17;
    case 5ULL: goto bb_7_bb16;
    case 6ULL: goto bb_8_bb15;
    case 7ULL: goto bb_9_bb14;
    case 8ULL: goto bb_10_bb13;
    case 9ULL: goto bb_11_bb12;
    case 10ULL: goto bb_12_bb11;
    case 11ULL: goto bb_13_bb10;
    case 12ULL: goto bb_14_bb9;
    case 13ULL: goto bb_15_bb8;
    case 14ULL: goto bb_16_bb7;
    case 15ULL: goto bb_17_bb6;
    case 16ULL: goto bb_18_bb5;
    case 17ULL: goto bb_19_bb4;
    case 18ULL: goto bb_20_bb3;
    case 19ULL: goto bb_21_bb2;
    default: goto bb_1_bb1;
  }
bb_1_bb1:
  abort();
bb_2_bb21:
  _t241 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t242 = *(uint32_t *)_t241;
  _t243 = (int32_t)_t242;
  *(int32_t *)_t237 = _t243;
  *(uint32_t *)_t238 = 130ULL;
  goto bb_22_bb22;
bb_3_bb20:
  _t244 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t245 = *(int32_t *)_t244;
  *(int32_t *)_t237 = _t245;
  *(uint32_t *)_t238 = 100ULL;
  goto bb_22_bb22;
bb_4_bb19:
  _t246 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t247 = *(uint32_t *)_t246;
  _t248 = (int32_t)_t247;
  *(int32_t *)_t237 = _t248;
  *(uint32_t *)_t238 = 101ULL;
  goto bb_22_bb22;
bb_5_bb18:
  _t249 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t250 = *(uint32_t *)_t249;
  _t251 = (int32_t)_t250;
  *(int32_t *)_t237 = _t251;
  *(uint32_t *)_t238 = 102ULL;
  goto bb_22_bb22;
bb_6_bb17:
  _t252 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t253 = *(uint32_t *)_t252;
  _t254 = (int32_t)_t253;
  *(int32_t *)_t237 = _t254;
  *(uint32_t *)_t238 = 103ULL;
  goto bb_22_bb22;
bb_7_bb16:
  _t255 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t256 = *(uint32_t *)_t255;
  _t257 = (int32_t)_t256;
  *(int32_t *)_t237 = _t257;
  *(uint32_t *)_t238 = 104ULL;
  goto bb_22_bb22;
bb_8_bb15:
  _t258 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t259 = *(uint32_t *)_t258;
  _t260 = (int32_t)_t259;
  *(int32_t *)_t237 = _t260;
  *(uint32_t *)_t238 = 105ULL;
  goto bb_22_bb22;
bb_9_bb14:
  _t261 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t262 = *(uint32_t *)_t261;
  _t263 = (int32_t)_t262;
  *(int32_t *)_t237 = _t263;
  *(uint32_t *)_t238 = 106ULL;
  goto bb_22_bb22;
bb_10_bb13:
  _t264 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t265 = *(uint32_t *)_t264;
  _t266 = (uint32_t)_t265;
  _t267 = (int32_t)_t266;
  *(int32_t *)_t237 = _t267;
  *(uint32_t *)_t238 = 107ULL;
  goto bb_22_bb22;
bb_11_bb12:
  _t268 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(int8_t));
  _t269 = *(_Bool *)_t268;
  _t270 = (_Bool)_t269 <= (_Bool)1ULL;
  _t271 = (int32_t)_t269;
  *(int32_t *)_t237 = _t271;
  *(uint32_t *)_t238 = 160ULL;
  goto bb_22_bb22;
bb_12_bb11:
  _t272 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t273 = *(uint32_t *)_t272;
  _t274 = (int32_t)_t273;
  *(int32_t *)_t237 = _t274;
  *(uint32_t *)_t238 = 161ULL;
  goto bb_22_bb22;
bb_13_bb10:
  _t275 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t276 = *(uint32_t *)_t275;
  _t277 = (int32_t)_t276;
  *(int32_t *)_t237 = _t277;
  *(uint32_t *)_t238 = 162ULL;
  goto bb_22_bb22;
bb_14_bb9:
  _t278 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t279 = *(uint32_t *)_t278;
  _t280 = (int32_t)_t279;
  *(int32_t *)_t237 = _t280;
  *(uint32_t *)_t238 = 163ULL;
  goto bb_22_bb22;
bb_15_bb8:
  _t281 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t282 = *(uint32_t *)_t281;
  _t283 = (int32_t)_t282;
  *(int32_t *)_t237 = _t283;
  *(uint32_t *)_t238 = 164ULL;
  goto bb_22_bb22;
bb_16_bb7:
  _t284 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(int8_t));
  _t285 = *(_Bool *)_t284;
  _t286 = (_Bool)_t285 <= (_Bool)1ULL;
  _t287 = (int32_t)_t285;
  *(int32_t *)_t237 = _t287;
  *(uint32_t *)_t238 = 200ULL;
  goto bb_22_bb22;
bb_17_bb6:
  _t288 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(int8_t));
  _t289 = *(_Bool *)_t288;
  _t290 = (_Bool)_t289 <= (_Bool)1ULL;
  _t291 = (int32_t)_t289;
  *(int32_t *)_t237 = _t291;
  *(uint32_t *)_t238 = 201ULL;
  goto bb_22_bb22;
bb_18_bb5:
  _t292 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(int8_t));
  _t293 = *(_Bool *)_t292;
  _t294 = (_Bool)_t293 <= (_Bool)1ULL;
  _t295 = (int32_t)_t293;
  *(int32_t *)_t237 = _t295;
  *(uint32_t *)_t238 = 202ULL;
  goto bb_22_bb22;
bb_19_bb4:
  _t296 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t297 = *(uint32_t *)_t296;
  _t298 = (int32_t)_t297;
  *(int32_t *)_t237 = _t298;
  *(uint32_t *)_t238 = 400ULL;
  goto bb_22_bb22;
bb_20_bb3:
  _t299 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t300 = *(uint32_t *)_t299;
  _t301 = (int32_t)_t300;
  *(int32_t *)_t237 = _t301;
  *(uint32_t *)_t238 = 401ULL;
  goto bb_22_bb22;
bb_21_bb2:
  _t302 = (void *)((__rustc_usize)_t235 + (__rustc_isize)(4ULL) * (__rustc_isize)sizeof(int8_t));
  _t303 = *(uint32_t *)_t302;
  _t304 = (int32_t)_t303;
  *(int32_t *)_t237 = _t304;
  *(uint32_t *)_t238 = 402ULL;
  goto bb_22_bb22;
bb_22_bb22:
  _t305 = *(void * *)_arg0;
  _t306 = (int64_t)_t305 != (int64_t)0;
  _t307 = (void *)_t305;
  _t308 = *(uint32_t *)_t238;
  _t309 = *(int32_t *)_t237;
  _t310 = ZSTD_CCtx_setParameter(_t307, _t308, _t309);
  _t311 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t310);
  _t312 = _t311.f0;
  _t313 = _t311.f1;
  memset(&_t314, 0, sizeof(_t314));
  _t314.f0 = _t312;
  _t315 = _t314;
  _t315.f1 = _t313;
  return _t315;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx15load_dictionary
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx15load_dictionary(void * _arg0, void * _arg1, __rustc_usize _arg2) {
  void * _t316;
  _Bool _t317;
  void * _t318;
  __rustc_usize _t319;
  struct _S2 _t320;
  uint64_t _t321;
  uint64_t _t322;
  struct _S2 _t323;
  struct _S2 _t324;

bb_0_start:
  _t316 = *(void * *)_arg0;
  _t317 = (int64_t)_t316 != (int64_t)0;
  _t318 = (void *)_t316;
  _t319 = ZSTD_CCtx_loadDictionary(_t318, _arg1, _arg2);
  _t320 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t319);
  _t321 = _t320.f0;
  _t322 = _t320.f1;
  memset(&_t323, 0, sizeof(_t323));
  _t323.f0 = _t321;
  _t324 = _t323;
  _t324.f1 = _t322;
  return _t324;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx18disable_dictionary
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx18disable_dictionary(void * _arg0) {
  void * _t325;
  _Bool _t326;
  void * _t327;
  __rustc_usize _t328;
  struct _S2 _t329;
  uint64_t _t330;
  uint64_t _t331;
  struct _S2 _t332;
  struct _S2 _t333;

bb_0_start:
  _t325 = *(void * *)_arg0;
  _t326 = (int64_t)_t325 != (int64_t)0;
  _t327 = (void *)_t325;
  _t328 = ZSTD_CCtx_loadDictionary(_t327, (void *)(__rustc_usize)0ULL, 0ULL);
  _t329 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t328);
  _t330 = _t329.f0;
  _t331 = _t329.f1;
  memset(&_t332, 0, sizeof(_t332));
  _t332.f0 = _t330;
  _t333 = _t332;
  _t333.f1 = _t331;
  return _t333;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx20set_pledged_src_size
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx20set_pledged_src_size(void * _arg0, uint64_t _arg1, uint64_t _arg2) {
  _Alignas(8) uint8_t _t334_storage[16];
  void *_t334 = (void *)_t334_storage;
  void * _t335;
  _Alignas(8) uint8_t _t336_storage[8];
  void *_t336 = (void *)_t336_storage;
  void * _t337;
  _Bool _t338;
  void * _t339;
  uint64_t _t340;
  void * _t341;
  uint64_t _t342;
  __rustc_isize _t343;
  _Bool _t344;
  void * _t345;
  uint64_t _t346;
  uint64_t _t347;
  __rustc_usize _t348;
  struct _S2 _t349;
  uint64_t _t350;
  uint64_t _t351;
  struct _S2 _t352;
  struct _S2 _t353;

bb_0_start:
  *(uint64_t *)_t334 = _arg1;
  _t335 = (void *)((__rustc_usize)_t334 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(uint64_t *)_t335 = _arg2;
  _t337 = *(void * *)_arg0;
  _t338 = (int64_t)_t337 != (int64_t)0;
  _t339 = (void *)_t337;
  _t340 = *(uint64_t *)_t334;
  _t341 = (void *)((__rustc_usize)_t334 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t342 = *(uint64_t *)_t341;
  _t343 = (__rustc_isize)_t340;
  _t344 = (_Bool)_t343;
  if (_t344) goto bb_1_bb6; else goto bb_2_bb5;
bb_1_bb6:
  _t345 = (void *)((__rustc_usize)_t334 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t346 = *(uint64_t *)_t345;
  *(uint64_t *)_t336 = _t346;
  goto bb_3_bb3;
bb_2_bb5:
  *(uint64_t *)_t336 = 18446744073709551615ULL;
  goto bb_3_bb3;
bb_3_bb3:
  _t347 = *(uint64_t *)_t336;
  _t348 = ZSTD_CCtx_setPledgedSrcSize(_t339, _t347);
  _t349 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t348);
  _t350 = _t349.f0;
  _t351 = _t349.f1;
  memset(&_t352, 0, sizeof(_t352));
  _t352.f0 = _t350;
  _t353 = _t352;
  _t353.f1 = _t351;
  return _t353;
bb_4_bb4:
  abort();
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx4init
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx4init(void * _arg0, int32_t _arg1) {
  void * _t354;
  _Bool _t355;
  void * _t356;
  __rustc_usize _t357;
  struct _S2 _t358;
  uint64_t _t359;
  uint64_t _t360;
  struct _S2 _t361;
  struct _S2 _t362;

bb_0_start:
  _t354 = *(void * *)_arg0;
  _t355 = (int64_t)_t354 != (int64_t)0;
  _t356 = (void *)_t354;
  _t357 = ZSTD_initCStream(_t356, _arg1);
  _t358 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t357);
  _t359 = _t358.f0;
  _t360 = _t358.f1;
  memset(&_t361, 0, sizeof(_t361));
  _t361.f0 = _t359;
  _t362 = _t361;
  _t362.f1 = _t360;
  return _t362;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx5reset
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx5reset(void * _arg0, uint8_t _arg1) {
  _Alignas(4) uint8_t _t363_storage[4];
  void *_t363 = (void *)_t363_storage;
  void * _t364;
  _Bool _t365;
  void * _t366;
  __rustc_isize _t367;
  uint32_t _t368;
  __rustc_usize _t369;
  struct _S2 _t370;
  uint64_t _t371;
  uint64_t _t372;
  struct _S2 _t373;
  struct _S2 _t374;

bb_0_start:
  _t364 = *(void * *)_arg0;
  _t365 = (int64_t)_t364 != (int64_t)0;
  _t366 = (void *)_t364;
  _t367 = (__rustc_isize)_arg1;
  switch ((__rustc_usize)_t367) {
    case 0ULL: goto bb_2_bb7;
    case 1ULL: goto bb_3_bb6;
    case 2ULL: goto bb_4_bb5;
    default: goto bb_1_bb4;
  }
bb_1_bb4:
  abort();
bb_2_bb7:
  *(uint32_t *)_t363 = 1ULL;
  goto bb_5_bb3;
bb_3_bb6:
  *(uint32_t *)_t363 = 2ULL;
  goto bb_5_bb3;
bb_4_bb5:
  *(uint32_t *)_t363 = 3ULL;
  goto bb_5_bb3;
bb_5_bb3:
  _t368 = *(uint32_t *)_t363;
  _t369 = ZSTD_CCtx_reset(_t366, _t368);
  _t370 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t369);
  _t371 = _t370.f0;
  _t372 = _t370.f1;
  memset(&_t373, 0, sizeof(_t373));
  _t373.f0 = _t371;
  _t374 = _t373;
  _t374.f1 = _t372;
  return _t374;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx6create
void * _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx6create(void) {
  _Alignas(8) uint8_t _t375_storage[8];
  void *_t375 = (void *)_t375_storage;
  void * _t376;
  void * _t377;
  int64_t _t378;
  _Bool _t379;
  __rustc_isize _t380;
  _Bool _t381;
  void * _t382;

bb_0_start:
  _t376 = _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx10try_create();
  *(void * *)_t375 = _t376;
  _t377 = *(void * *)_t375;
  _t378 = (int64_t)_t377;
  _t379 = (int64_t)_t378 == (int64_t)0LL;
  _t380 = (_t379) ? (0LL) : (1LL);
  _t381 = (_Bool)_t380;
  if (_t381) goto bb_1_bb4; else goto bb_2_bb3;
bb_1_bb4:
  _t382 = *(void * *)_t375;
  return _t382;
bb_2_bb3:
  _RNvNtCs41fFVwHnQdq_4core6option13expect_failed(_bytes6, 52ULL, &_bytes7);
  abort();
bb_3_bb2:
  abort();
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx6sizeof
__rustc_usize _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx6sizeof(void * _arg0) {
  void * _t383;
  _Bool _t384;
  void * _t385;
  __rustc_usize _t386;

bb_0_start:
  _t383 = *(void * *)_arg0;
  _t384 = (int64_t)_t383 != (int64_t)0;
  _t385 = (void *)_t383;
  _t386 = ZSTD_sizeof_CCtx(_t385);
  return _t386;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx7in_size
__rustc_usize _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx7in_size(void) {
  __rustc_usize _t387;

bb_0_start:
  _t387 = ZSTD_CStreamInSize();
  return _t387;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx8out_size
__rustc_usize _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx8out_size(void) {
  __rustc_usize _t388;

bb_0_start:
  _t388 = ZSTD_CStreamOutSize();
  return _t388;
}

#pragma weak _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx9ref_cdict
struct _S2 _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx9ref_cdict(void * _arg0, void * _arg1) {
  void * _t389;
  _Bool _t390;
  void * _t391;
  void * _t392;
  _Bool _t393;
  void * _t394;
  __rustc_usize _t395;
  struct _S2 _t396;
  uint64_t _t397;
  uint64_t _t398;
  struct _S2 _t399;
  struct _S2 _t400;

bb_0_start:
  _t389 = *(void * *)_arg0;
  _t390 = (int64_t)_t389 != (int64_t)0;
  _t391 = (void *)_t389;
  _t392 = *(void * *)_arg1;
  _t393 = (int64_t)_t392 != (int64_t)0;
  _t394 = (void *)_t392;
  _t395 = ZSTD_CCtx_refCDict(_t391, _t394);
  _t396 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t395);
  _t397 = _t396.f0;
  _t398 = _t396.f1;
  memset(&_t399, 0, sizeof(_t399));
  _t399.f0 = _t397;
  _t400 = _t399;
  _t400.f1 = _t398;
  return _t400;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx10ref_prefix
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx10ref_prefix(void * _arg0, void * _arg1, __rustc_usize _arg2) {
  void * _t401;
  _Bool _t402;
  void * _t403;
  __rustc_usize _t404;
  struct _S2 _t405;
  uint64_t _t406;
  uint64_t _t407;
  struct _S2 _t408;
  struct _S2 _t409;

bb_0_start:
  _t401 = *(void * *)_arg0;
  _t402 = (int64_t)_t401 != (int64_t)0;
  _t403 = (void *)_t401;
  _t404 = ZSTD_DCtx_refPrefix(_t403, _arg1, _arg2);
  _t405 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t404);
  _t406 = _t405.f0;
  _t407 = _t405.f1;
  memset(&_t408, 0, sizeof(_t408));
  _t408.f0 = _t406;
  _t409 = _t408;
  _t409.f1 = _t407;
  return _t409;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx10try_create
void * _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx10try_create(void) {
  _Alignas(8) uint8_t _t410_storage[8];
  void *_t410 = (void *)_t410_storage;
  _Alignas(8) uint8_t _t411_storage[8];
  void *_t411 = (void *)_t411_storage;
  _Alignas(8) uint8_t _t412_storage[8];
  void *_t412 = (void *)_t412_storage;
  void * _t413;
  int64_t _t414;
  _Bool _t415;
  void * _t416;
  void * _t417;
  _Bool _t418;
  void * _t419;
  void * _t420;
  void * _t421;

bb_0_start:
  _t413 = ZSTD_createDCtx();
  _t414 = (int64_t)_t413;
  _t415 = (__rustc_isize)_t414 == (__rustc_isize)0ULL;
  if (_t415) goto bb_1_bb3; else goto bb_2_bb4;
bb_1_bb3:
  *(void * *)_t410 = (void *)(__rustc_usize)0ULL;
  goto bb_3_bb2;
bb_2_bb4:
  _t416 = (void *)_t413;
  _t417 = (void *)_t416;
  _t418 = (int64_t)_t417 != (int64_t)0;
  *(void * *)_t412 = _t417;
  _t419 = *(void * *)_t412;
  *(void * *)_t411 = _t419;
  _t420 = *(void * *)_t411;
  *(void * *)_t410 = _t420;
  goto bb_3_bb2;
bb_3_bb2:
  _t421 = *(void * *)_t410;
  return _t421;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx13set_parameter
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx13set_parameter(void * _arg0, uint32_t _arg1) {
  int32_t _t422;
  void * _t423;
  _Bool _t424;
  void * _t425;
  __rustc_usize _t426;
  struct _S2 _t427;
  uint64_t _t428;
  uint64_t _t429;
  struct _S2 _t430;
  struct _S2 _t431;

bb_0_start:
  _t422 = (int32_t)_arg1;
  _t423 = *(void * *)_arg0;
  _t424 = (int64_t)_t423 != (int64_t)0;
  _t425 = (void *)_t423;
  _t426 = ZSTD_DCtx_setParameter(_t425, 100ULL, _t422);
  _t427 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t426);
  _t428 = _t427.f0;
  _t429 = _t427.f1;
  memset(&_t430, 0, sizeof(_t430));
  _t430.f0 = _t428;
  _t431 = _t430;
  _t431.f1 = _t429;
  return _t431;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx15load_dictionary
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx15load_dictionary(void * _arg0, void * _arg1, __rustc_usize _arg2) {
  void * _t432;
  _Bool _t433;
  void * _t434;
  __rustc_usize _t435;
  struct _S2 _t436;
  uint64_t _t437;
  uint64_t _t438;
  struct _S2 _t439;
  struct _S2 _t440;

bb_0_start:
  _t432 = *(void * *)_arg0;
  _t433 = (int64_t)_t432 != (int64_t)0;
  _t434 = (void *)_t432;
  _t435 = ZSTD_DCtx_loadDictionary(_t434, _arg1, _arg2);
  _t436 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t435);
  _t437 = _t436.f0;
  _t438 = _t436.f1;
  memset(&_t439, 0, sizeof(_t439));
  _t439.f0 = _t437;
  _t440 = _t439;
  _t440.f1 = _t438;
  return _t440;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx18disable_dictionary
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx18disable_dictionary(void * _arg0) {
  void * _t441;
  _Bool _t442;
  void * _t443;
  __rustc_usize _t444;
  struct _S2 _t445;
  uint64_t _t446;
  uint64_t _t447;
  struct _S2 _t448;
  struct _S2 _t449;

bb_0_start:
  _t441 = *(void * *)_arg0;
  _t442 = (int64_t)_t441 != (int64_t)0;
  _t443 = (void *)_t441;
  _t444 = ZSTD_DCtx_loadDictionary(_t443, (void *)(__rustc_usize)0ULL, 0ULL);
  _t445 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t444);
  _t446 = _t445.f0;
  _t447 = _t445.f1;
  memset(&_t448, 0, sizeof(_t448));
  _t448.f0 = _t446;
  _t449 = _t448;
  _t449.f1 = _t447;
  return _t449;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx4init
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx4init(void * _arg0) {
  void * _t450;
  _Bool _t451;
  void * _t452;
  __rustc_usize _t453;
  struct _S2 _t454;
  uint64_t _t455;
  uint64_t _t456;
  struct _S2 _t457;
  struct _S2 _t458;

bb_0_start:
  _t450 = *(void * *)_arg0;
  _t451 = (int64_t)_t450 != (int64_t)0;
  _t452 = (void *)_t450;
  _t453 = ZSTD_initDStream(_t452);
  _t454 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t453);
  _t455 = _t454.f0;
  _t456 = _t454.f1;
  memset(&_t457, 0, sizeof(_t457));
  _t457.f0 = _t455;
  _t458 = _t457;
  _t458.f1 = _t456;
  return _t458;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx5reset
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx5reset(void * _arg0, uint8_t _arg1) {
  _Alignas(4) uint8_t _t459_storage[4];
  void *_t459 = (void *)_t459_storage;
  void * _t460;
  _Bool _t461;
  void * _t462;
  __rustc_isize _t463;
  uint32_t _t464;
  __rustc_usize _t465;
  struct _S2 _t466;
  uint64_t _t467;
  uint64_t _t468;
  struct _S2 _t469;
  struct _S2 _t470;

bb_0_start:
  _t460 = *(void * *)_arg0;
  _t461 = (int64_t)_t460 != (int64_t)0;
  _t462 = (void *)_t460;
  _t463 = (__rustc_isize)_arg1;
  switch ((__rustc_usize)_t463) {
    case 0ULL: goto bb_2_bb7;
    case 1ULL: goto bb_3_bb6;
    case 2ULL: goto bb_4_bb5;
    default: goto bb_1_bb4;
  }
bb_1_bb4:
  abort();
bb_2_bb7:
  *(uint32_t *)_t459 = 1ULL;
  goto bb_5_bb3;
bb_3_bb6:
  *(uint32_t *)_t459 = 2ULL;
  goto bb_5_bb3;
bb_4_bb5:
  *(uint32_t *)_t459 = 3ULL;
  goto bb_5_bb3;
bb_5_bb3:
  _t464 = *(uint32_t *)_t459;
  _t465 = ZSTD_DCtx_reset(_t462, _t464);
  _t466 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t465);
  _t467 = _t466.f0;
  _t468 = _t466.f1;
  memset(&_t469, 0, sizeof(_t469));
  _t469.f0 = _t467;
  _t470 = _t469;
  _t470.f1 = _t468;
  return _t470;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx6create
void * _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx6create(void) {
  _Alignas(8) uint8_t _t471_storage[8];
  void *_t471 = (void *)_t471_storage;
  void * _t472;
  void * _t473;
  int64_t _t474;
  _Bool _t475;
  __rustc_isize _t476;
  _Bool _t477;
  void * _t478;

bb_0_start:
  _t472 = _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx10try_create();
  *(void * *)_t471 = _t472;
  _t473 = *(void * *)_t471;
  _t474 = (int64_t)_t473;
  _t475 = (int64_t)_t474 == (int64_t)0LL;
  _t476 = (_t475) ? (0LL) : (1LL);
  _t477 = (_Bool)_t476;
  if (_t477) goto bb_1_bb4; else goto bb_2_bb3;
bb_1_bb4:
  _t478 = *(void * *)_t471;
  return _t478;
bb_2_bb3:
  _RNvNtCs41fFVwHnQdq_4core6option13expect_failed(_bytes9, 52ULL, &_bytes10);
  abort();
bb_3_bb2:
  abort();
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx6sizeof
__rustc_usize _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx6sizeof(void * _arg0) {
  void * _t479;
  _Bool _t480;
  void * _t481;
  __rustc_usize _t482;

bb_0_start:
  _t479 = *(void * *)_arg0;
  _t480 = (int64_t)_t479 != (int64_t)0;
  _t481 = (void *)_t479;
  _t482 = ZSTD_sizeof_DCtx(_t481);
  return _t482;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx7in_size
__rustc_usize _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx7in_size(void) {
  __rustc_usize _t483;

bb_0_start:
  _t483 = ZSTD_DStreamInSize();
  return _t483;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx8out_size
__rustc_usize _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx8out_size(void) {
  __rustc_usize _t484;

bb_0_start:
  _t484 = ZSTD_DStreamOutSize();
  return _t484;
}

#pragma weak _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx9ref_ddict
struct _S2 _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx9ref_ddict(void * _arg0, void * _arg1) {
  void * _t485;
  _Bool _t486;
  void * _t487;
  void * _t488;
  _Bool _t489;
  void * _t490;
  __rustc_usize _t491;
  struct _S2 _t492;
  uint64_t _t493;
  uint64_t _t494;
  struct _S2 _t495;
  struct _S2 _t496;

bb_0_start:
  _t485 = *(void * *)_arg0;
  _t486 = (int64_t)_t485 != (int64_t)0;
  _t487 = (void *)_t485;
  _t488 = *(void * *)_arg1;
  _t489 = (int64_t)_t488 != (int64_t)0;
  _t490 = (void *)_t488;
  _t491 = ZSTD_DCtx_refDDict(_t487, _t490);
  _t492 = _RNvCskQUcIKPqzjg_9zstd_safe10parse_code(_t491);
  _t493 = _t492.f0;
  _t494 = _t492.f1;
  memset(&_t495, 0, sizeof(_t495));
  _t495.f0 = _t493;
  _t496 = _t495;
  _t496.f1 = _t494;
  return _t496;
}

#pragma weak _RNvMs9_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict10try_create
void * _RNvMs9_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict10try_create(void * _arg0, __rustc_usize _arg1, int32_t _arg2) {
  _Alignas(8) uint8_t _t497_storage[8];
  void *_t497 = (void *)_t497_storage;
  _Alignas(8) uint8_t _t498_storage[8];
  void *_t498 = (void *)_t498_storage;
  _Alignas(8) uint8_t _t499_storage[8];
  void *_t499 = (void *)_t499_storage;
  void * _t500;
  int64_t _t501;
  _Bool _t502;
  void * _t503;
  void * _t504;
  _Bool _t505;
  void * _t506;
  void * _t507;
  void * _t508;

bb_0_start:
  _t500 = ZSTD_createCDict(_arg0, _arg1, _arg2);
  _t501 = (int64_t)_t500;
  _t502 = (__rustc_isize)_t501 == (__rustc_isize)0ULL;
  if (_t502) goto bb_1_bb3; else goto bb_2_bb4;
bb_1_bb3:
  *(void * *)_t497 = (void *)(__rustc_usize)0ULL;
  goto bb_3_bb2;
bb_2_bb4:
  _t503 = (void *)_t500;
  _t504 = (void *)_t503;
  _t505 = (int64_t)_t504 != (int64_t)0;
  *(void * *)_t499 = _t504;
  _t506 = *(void * *)_t499;
  *(void * *)_t498 = _t506;
  _t507 = *(void * *)_t498;
  *(void * *)_t497 = _t507;
  goto bb_3_bb2;
bb_3_bb2:
  _t508 = *(void * *)_t497;
  return _t508;
}

#pragma weak _RNvMs9_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict6create
void * _RNvMs9_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict6create(void * _arg0, __rustc_usize _arg1, int32_t _arg2) {
  _Alignas(8) uint8_t _t509_storage[8];
  void *_t509 = (void *)_t509_storage;
  void * _t510;
  void * _t511;
  int64_t _t512;
  _Bool _t513;
  __rustc_isize _t514;
  _Bool _t515;
  void * _t516;

bb_0_start:
  _t510 = _RNvMs9_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict10try_create(_arg0, _arg1, _arg2);
  *(void * *)_t509 = _t510;
  _t511 = *(void * *)_t509;
  _t512 = (int64_t)_t511;
  _t513 = (int64_t)_t512 == (int64_t)0LL;
  _t514 = (_t513) ? (0LL) : (1LL);
  _t515 = (_Bool)_t514;
  if (_t515) goto bb_1_bb4; else goto bb_2_bb3;
bb_1_bb4:
  _t516 = *(void * *)_t509;
  return _t516;
bb_2_bb3:
  _RNvNtCs41fFVwHnQdq_4core6option13expect_failed(_bytes12, 45ULL, &_bytes13);
  abort();
bb_3_bb2:
  abort();
}

#pragma weak _RNvMsa_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict11get_dict_id
uint32_t _RNvMsa_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict11get_dict_id(void * _arg0) {
  void * _t517;
  _Bool _t518;
  void * _t519;
  uint32_t _t520;
  int32_t _t521;

bb_0_start:
  _t517 = *(void * *)_arg0;
  _t518 = (int64_t)_t517 != (int64_t)0;
  _t519 = (void *)_t517;
  _t520 = ZSTD_getDictID_fromCDict(_t519);
  _t521 = (int32_t)_t520;
  return _t521;
}

#pragma weak _RNvMsa_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict6sizeof
__rustc_usize _RNvMsa_CskQUcIKPqzjg_9zstd_safeNtB5_5CDict6sizeof(void * _arg0) {
  void * _t522;
  _Bool _t523;
  void * _t524;
  __rustc_usize _t525;

bb_0_start:
  _t522 = *(void * *)_arg0;
  _t523 = (int64_t)_t522 != (int64_t)0;
  _t524 = (void *)_t522;
  _t525 = ZSTD_sizeof_CDict(_t524);
  return _t525;
}

#pragma weak _RNvMse_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict10try_create
void * _RNvMse_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict10try_create(void * _arg0, __rustc_usize _arg1) {
  _Alignas(8) uint8_t _t526_storage[8];
  void *_t526 = (void *)_t526_storage;
  _Alignas(8) uint8_t _t527_storage[8];
  void *_t527 = (void *)_t527_storage;
  _Alignas(8) uint8_t _t528_storage[8];
  void *_t528 = (void *)_t528_storage;
  void * _t529;
  int64_t _t530;
  _Bool _t531;
  void * _t532;
  void * _t533;
  _Bool _t534;
  void * _t535;
  void * _t536;
  void * _t537;

bb_0_start:
  _t529 = ZSTD_createDDict(_arg0, _arg1);
  _t530 = (int64_t)_t529;
  _t531 = (__rustc_isize)_t530 == (__rustc_isize)0ULL;
  if (_t531) goto bb_1_bb3; else goto bb_2_bb4;
bb_1_bb3:
  *(void * *)_t526 = (void *)(__rustc_usize)0ULL;
  goto bb_3_bb2;
bb_2_bb4:
  _t532 = (void *)_t529;
  _t533 = (void *)_t532;
  _t534 = (int64_t)_t533 != (int64_t)0;
  *(void * *)_t528 = _t533;
  _t535 = *(void * *)_t528;
  *(void * *)_t527 = _t535;
  _t536 = *(void * *)_t527;
  *(void * *)_t526 = _t536;
  goto bb_3_bb2;
bb_3_bb2:
  _t537 = *(void * *)_t526;
  return _t537;
}

#pragma weak _RNvMse_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict6create
void * _RNvMse_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict6create(void * _arg0, __rustc_usize _arg1) {
  _Alignas(8) uint8_t _t538_storage[8];
  void *_t538 = (void *)_t538_storage;
  void * _t539;
  void * _t540;
  int64_t _t541;
  _Bool _t542;
  __rustc_isize _t543;
  _Bool _t544;
  void * _t545;

bb_0_start:
  _t539 = _RNvMse_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict10try_create(_arg0, _arg1);
  *(void * *)_t538 = _t539;
  _t540 = *(void * *)_t538;
  _t541 = (int64_t)_t540;
  _t542 = (int64_t)_t541 == (int64_t)0LL;
  _t543 = (_t542) ? (0LL) : (1LL);
  _t544 = (_Bool)_t543;
  if (_t544) goto bb_1_bb4; else goto bb_2_bb3;
bb_1_bb4:
  _t545 = *(void * *)_t538;
  return _t545;
bb_2_bb3:
  _RNvNtCs41fFVwHnQdq_4core6option13expect_failed(_bytes15, 45ULL, &_bytes16);
  abort();
bb_3_bb2:
  abort();
}

#pragma weak _RNvMsf_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict11get_dict_id
uint32_t _RNvMsf_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict11get_dict_id(void * _arg0) {
  void * _t546;
  _Bool _t547;
  void * _t548;
  uint32_t _t549;
  int32_t _t550;

bb_0_start:
  _t546 = *(void * *)_arg0;
  _t547 = (int64_t)_t546 != (int64_t)0;
  _t548 = (void *)_t546;
  _t549 = ZSTD_getDictID_fromDDict(_t548);
  _t550 = (int32_t)_t549;
  return _t550;
}

#pragma weak _RNvMsf_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict6sizeof
__rustc_usize _RNvMsf_CskQUcIKPqzjg_9zstd_safeNtB5_5DDict6sizeof(void * _arg0) {
  void * _t551;
  _Bool _t552;
  void * _t553;
  __rustc_usize _t554;

bb_0_start:
  _t551 = *(void * *)_arg0;
  _t552 = (int64_t)_t551 != (int64_t)0;
  _t553 = (void *)_t551;
  _t554 = ZSTD_sizeof_DDict(_t553);
  return _t554;
}

#pragma weak _RNvMsu_CskQUcIKPqzjg_9zstd_safeNtB5_8InBuffer7set_pos
void _RNvMsu_CskQUcIKPqzjg_9zstd_safeNtB5_8InBuffer7set_pos(void * _arg0, __rustc_usize _arg1) {
  void * _t555;
  void * _t556;
  __rustc_usize _t557;
  _Bool _t558;
  void * _t559;

bb_0_start:
  _t555 = *(void * *)_arg0;
  _t556 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t557 = *(__rustc_usize *)_t556;
  _t558 = (__rustc_usize)_arg1 > (__rustc_usize)_t557;
  if (_t558) goto bb_2_bb1; else goto bb_1_bb2;
bb_1_bb2:
  _t559 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  *(__rustc_usize *)_t559 = _arg1;
  return;
bb_2_bb1:
  _RNvNtCs41fFVwHnQdq_4core9panicking5panic(_bytes18, 44ULL, &_bytes19);
  abort();
}

#pragma weak _RNvXCskQUcIKPqzjg_9zstd_safeNtB2_16ContentSizeErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt
_Bool _RNvXCskQUcIKPqzjg_9zstd_safeNtB2_16ContentSizeErrorNtNtCs41fFVwHnQdq_4core3fmt7Display3fmt(void * _arg0, void * _arg1) {
  _Bool _t560;
  _Bool _t561;

bb_0_start:
  _t560 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(_arg1, _bytes21, 26ULL);
  _t561 = (_Bool)(_t560);
  return _t561;
}

#pragma weak _RNvXs1_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtxNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop
void _RNvXs1_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtxNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void * _arg0) {
  void * _t562;
  _Bool _t563;
  void * _t564;
  __rustc_usize _t565;

bb_0_start:
  _t562 = *(void * *)_arg0;
  _t563 = (int64_t)_t562 != (int64_t)0;
  _t564 = (void *)_t562;
  _t565 = ZSTD_freeCCtx(_t564);
  return;
}

static _Bool _RNvXs1g_NtCs41fFVwHnQdq_4core3fmtRINtNtB8_6option6OptionhENtB6_5Debug3fmtCskQUcIKPqzjg_9zstd_safe(void * _arg0, void * _arg1) {
  void * _t566;
  _Bool _t567;
  _Bool _t568;

bb_0_start:
  _t566 = *(void * *)_arg0;
  _t567 = _RNvXsR_NtCs41fFVwHnQdq_4core6optionINtB5_6OptionhENtNtB7_3fmt5Debug3fmtCskQUcIKPqzjg_9zstd_safe(_t566, _arg1);
  _t568 = (_Bool)(_t567);
  return _t568;
}

static _Bool _RNvXs1g_NtCs41fFVwHnQdq_4core3fmtRhNtB6_5Debug3fmtCskQUcIKPqzjg_9zstd_safe(void * _arg0, void * _arg1) {
  void * _t569;
  _Bool _t570;
  _Bool _t571;

bb_0_start:
  _t569 = *(void * *)_arg0;
  _t570 = _RNvXsU_NtNtCs41fFVwHnQdq_4core3fmt3numhNtB7_5Debug3fmt(_t569, _arg1);
  _t571 = (_Bool)(_t570);
  return _t571;
}

#pragma weak _RNvXs4_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtxNtNtCs41fFVwHnQdq_4core7default7Default7default
void * _RNvXs4_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtxNtNtCs41fFVwHnQdq_4core7default7Default7default(void) {
  void * _t572;

bb_0_start:
  _t572 = _RNvMs5_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtx6create();
  return _t572;
}

#pragma weak _RNvXs6_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtxNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop
void _RNvXs6_CskQUcIKPqzjg_9zstd_safeNtB5_4DCtxNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void * _arg0) {
  void * _t573;
  _Bool _t574;
  void * _t575;
  __rustc_usize _t576;

bb_0_start:
  _t573 = *(void * *)_arg0;
  _t574 = (int64_t)_t573 != (int64_t)0;
  _t575 = (void *)_t573;
  _t576 = ZSTD_freeDCtx(_t575);
  return;
}

static _Bool _RNvXs9_NtNtCs41fFVwHnQdq_4core3str5errorNtB5_9Utf8ErrorNtNtB9_3fmt5Debug3fmt(void * _arg0, void * _arg1) {
  _Alignas(8) uint8_t _t577_storage[8];
  void *_t577 = (void *)_t577_storage;
  void * _t578;
  _Bool _t579;
  _Bool _t580;

bb_0_start:
  _t578 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t577 = _t578;
  _t579 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter26debug_struct_field2_finish(_arg1, _bytes24, 9ULL, _bytes25, 11ULL, _arg0, &_bytes22, _bytes26, 9ULL, _t577, &_bytes23);
  _t580 = (_Bool)(_t579);
  return _t580;
}

static _Bool _RNvXsR_NtCs41fFVwHnQdq_4core6optionINtB5_6OptionhENtNtB7_3fmt5Debug3fmtCskQUcIKPqzjg_9zstd_safe(void * _arg0, void * _arg1) {
  _Alignas(1) uint8_t _t581_storage[1];
  void *_t581 = (void *)_t581_storage;
  _Alignas(8) uint8_t _t582_storage[8];
  void *_t582 = (void *)_t582_storage;
  _Bool _t583;
  void * _t584;
  uint8_t _t585;
  __rustc_isize _t586;
  _Bool _t587;
  _Bool _t588;
  _Bool _t589;
  void * _t590;
  _Bool _t591;
  _Bool _t592;
  _Bool _t593;

bb_0_start:
  _t583 = *(_Bool *)_arg0;
  _t584 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(int8_t));
  _t585 = *(uint8_t *)_t584;
  _t586 = (__rustc_isize)_t583;
  _t587 = (_Bool)_t586;
  if (_t587) goto bb_1_bb2; else goto bb_2_bb3;
bb_1_bb2:
  _t590 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(1ULL) * (__rustc_isize)sizeof(int8_t));
  *(void * *)_t582 = _t590;
  _t591 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter25debug_tuple_field1_finish(_arg1, _bytes29, 4ULL, _t582, &_bytes28);
  _t592 = (_Bool)(_t591);
  *(_Bool *)_t581 = _t592;
  goto bb_3_bb5;
bb_2_bb3:
  _t588 = _RNvMsa_NtCs41fFVwHnQdq_4core3fmtNtB5_9Formatter9write_str(_arg1, _bytes27, 4ULL);
  _t589 = (_Bool)(_t588);
  *(_Bool *)_t581 = _t589;
  goto bb_3_bb5;
bb_3_bb5:
  _t593 = *(_Bool *)_t581;
  return _t593;
bb_4_bb1:
  abort();
}

static _Bool _RNvXsU_NtNtCs41fFVwHnQdq_4core3fmt3numhNtB7_5Debug3fmt(void * _arg0, void * _arg1) {
  _Alignas(1) uint8_t _t594_storage[1];
  void *_t594 = (void *)_t594_storage;
  void * _t595;
  uint32_t _t596;
  uint32_t _t597;
  _Bool _t598;
  void * _t599;
  uint32_t _t600;
  uint32_t _t601;
  _Bool _t602;
  _Bool _t603;
  _Bool _t604;
  _Bool _t605;
  _Bool _t606;
  _Bool _t607;
  _Bool _t608;
  _Bool _t609;

bb_0_start:
  _t595 = (void *)((__rustc_usize)_arg1 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t596 = *(uint32_t *)_t595;
  _t597 = _t596 & 33554432ULL;
  _t598 = (int32_t)_t597 == (int32_t)0ULL;
  if (_t598) goto bb_1_bb2; else goto bb_2_bb1;
bb_1_bb2:
  _t599 = (void *)((__rustc_usize)_arg1 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t600 = *(uint32_t *)_t599;
  _t601 = _t600 & 67108864ULL;
  _t602 = (int32_t)_t601 == (int32_t)0ULL;
  if (_t602) goto bb_3_bb4; else goto bb_4_bb3;
bb_2_bb1:
  _t607 = _RNvXse_NtNtCs41fFVwHnQdq_4core3fmt3numhNtB7_8LowerHex3fmt(_arg0, _arg1);
  _t608 = (_Bool)(_t607);
  *(_Bool *)_t594 = _t608;
  goto bb_6_bb6;
bb_3_bb4:
  _t603 = _RNvXNtNtNtCs41fFVwHnQdq_4core3fmt3num3imphNtB6_7Display3fmt(_arg0, _arg1);
  _t604 = (_Bool)(_t603);
  *(_Bool *)_t594 = _t604;
  goto bb_5_bb5;
bb_4_bb3:
  _t605 = _RNvXsg_NtNtCs41fFVwHnQdq_4core3fmt3numhNtB7_8UpperHex3fmt(_arg0, _arg1);
  _t606 = (_Bool)(_t605);
  *(_Bool *)_t594 = _t606;
  goto bb_5_bb5;
bb_5_bb5:
  goto bb_6_bb6;
bb_6_bb6:
  _t609 = *(_Bool *)_t594;
  return _t609;
}

static _Bool _RNvXsZ_NtNtCs41fFVwHnQdq_4core3fmt3numjNtB7_5Debug3fmt(void * _arg0, void * _arg1) {
  _Alignas(1) uint8_t _t610_storage[1];
  void *_t610 = (void *)_t610_storage;
  void * _t611;
  uint32_t _t612;
  uint32_t _t613;
  _Bool _t614;
  void * _t615;
  uint32_t _t616;
  uint32_t _t617;
  _Bool _t618;
  _Bool _t619;
  _Bool _t620;
  _Bool _t621;
  _Bool _t622;
  _Bool _t623;
  _Bool _t624;
  _Bool _t625;

bb_0_start:
  _t611 = (void *)((__rustc_usize)_arg1 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t612 = *(uint32_t *)_t611;
  _t613 = _t612 & 33554432ULL;
  _t614 = (int32_t)_t613 == (int32_t)0ULL;
  if (_t614) goto bb_1_bb2; else goto bb_2_bb1;
bb_1_bb2:
  _t615 = (void *)((__rustc_usize)_arg1 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t616 = *(uint32_t *)_t615;
  _t617 = _t616 & 67108864ULL;
  _t618 = (int32_t)_t617 == (int32_t)0ULL;
  if (_t618) goto bb_3_bb4; else goto bb_4_bb3;
bb_2_bb1:
  _t623 = _RNvXs6_NtNtCs41fFVwHnQdq_4core3fmt3numjNtB7_8LowerHex3fmt(_arg0, _arg1);
  _t624 = (_Bool)(_t623);
  *(_Bool *)_t610 = _t624;
  goto bb_6_bb6;
bb_3_bb4:
  _t619 = _RNvXsi_NtNtNtCs41fFVwHnQdq_4core3fmt3num3impjNtB9_7Display3fmt(_arg0, _arg1);
  _t620 = (_Bool)(_t619);
  *(_Bool *)_t610 = _t620;
  goto bb_5_bb5;
bb_4_bb3:
  _t621 = _RNvXs8_NtNtCs41fFVwHnQdq_4core3fmt3numjNtB7_8UpperHex3fmt(_arg0, _arg1);
  _t622 = (_Bool)(_t621);
  *(_Bool *)_t610 = _t622;
  goto bb_5_bb5;
bb_5_bb5:
  goto bb_6_bb6;
bb_6_bb6:
  _t625 = *(_Bool *)_t610;
  return _t625;
}

#pragma weak _RNvXs_CskQUcIKPqzjg_9zstd_safeNtB4_4CCtxNtNtCs41fFVwHnQdq_4core7default7Default7default
void * _RNvXs_CskQUcIKPqzjg_9zstd_safeNtB4_4CCtxNtNtCs41fFVwHnQdq_4core7default7Default7default(void) {
  void * _t626;

bb_0_start:
  _t626 = _RNvMs0_CskQUcIKPqzjg_9zstd_safeNtB5_4CCtx6create();
  return _t626;
}

#pragma weak _RNvXsb_CskQUcIKPqzjg_9zstd_safeNtB5_5CDictNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop
void _RNvXsb_CskQUcIKPqzjg_9zstd_safeNtB5_5CDictNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void * _arg0) {
  void * _t627;
  _Bool _t628;
  void * _t629;
  __rustc_usize _t630;

bb_0_start:
  _t627 = *(void * *)_arg0;
  _t628 = (int64_t)_t627 != (int64_t)0;
  _t629 = (void *)_t627;
  _t630 = ZSTD_freeCDict(_t629);
  return;
}

#pragma weak _RNvXsg_CskQUcIKPqzjg_9zstd_safeNtB5_5DDictNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop
void _RNvXsg_CskQUcIKPqzjg_9zstd_safeNtB5_5DDictNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void * _arg0) {
  void * _t631;
  _Bool _t632;
  void * _t633;
  __rustc_usize _t634;

bb_0_start:
  _t631 = *(void * *)_arg0;
  _t632 = (int64_t)_t631 != (int64_t)0;
  _t633 = (void *)_t631;
  _t634 = ZSTD_freeDDict(_t633);
  return;
}

static void * _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf10as_mut_ptr(void * _arg0, __rustc_usize _arg1) {
bb_0_start:
  return _arg0;
}

static void _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf12filled_until(void * _arg0, __rustc_usize _arg1, __rustc_usize _arg2) {
bb_0_start:
  return;
}

static __rustc_usize _RNvXsn_CskQUcIKPqzjg_9zstd_safeShNtB5_8WriteBuf8capacity(void * _arg0, __rustc_usize _arg1) {
bb_0_start:
  return _arg1;
}

#pragma weak _RNvXsv_CskQUcIKPqzjg_9zstd_safeNtB5_15InBufferWrapperNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop
void _RNvXsv_CskQUcIKPqzjg_9zstd_safeNtB5_15InBufferWrapperNtNtNtCs41fFVwHnQdq_4core3ops4drop4Drop4drop(void * _arg0) {
  void * _t635;
  void * _t636;
  void * _t637;
  __rustc_usize _t638;

bb_0_start:
  _t635 = *(void * *)_arg0;
  _t636 = (void *)((__rustc_usize)_arg0 + (__rustc_isize)(8ULL) * (__rustc_isize)sizeof(int8_t));
  _t637 = (void *)((__rustc_usize)_t636 + (__rustc_isize)(16ULL) * (__rustc_isize)sizeof(int8_t));
  _t638 = *(__rustc_usize *)_t637;
  _RNvMsu_CskQUcIKPqzjg_9zstd_safeNtB5_8InBuffer7set_pos(_t635, _t638);
  return;
}

