@ stdcall D3D12CreateDevice(ptr long ptr ptr)
@ stdcall D3D12GetDebugInterface(ptr ptr)
@ stdcall D3D12CoreCreateLayeredDevice()
@ stdcall D3D12CoreGetLayeredDeviceSize()
@ stdcall D3D12CoreRegisterLayers()
@ stdcall D3D12CreateRootSignatureDeserializer(ptr int64 ptr ptr)
@ stdcall D3D12CreateVersionedRootSignatureDeserializer(ptr int64 ptr ptr)
@ stdcall D3D12EnableExperimentalFeatures(long ptr ptr ptr)
@ stdcall D3D12SerializeRootSignature(ptr long ptr ptr)
@ stdcall D3D12SerializeVersionedRootSignature(ptr ptr ptr)
@ stdcall GetBehaviorValue()
