#!/usr/bin/env bash
set -euo pipefail

SDK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_ROOT="${SDK_ROOT}/runtime"
DXMT_RUNTIME="${RUNTIME_ROOT}/dxmt"
WINE_RUNTIME="${RUNTIME_ROOT}/wine"
DEFAULT_PREFIX="${SDK_ROOT}/.prefix"

export METALSHARP_D3D12_SDK_ROOT="${SDK_ROOT}"
export METALSHARP_DXMT_RUNTIME="${METALSHARP_DXMT_RUNTIME:-$DXMT_RUNTIME}"
export WINEPREFIX="${WINEPREFIX:-$DEFAULT_PREFIX}"

if [ -x "$WINE_RUNTIME/bin/wine" ]; then
  export WINE="${WINE:-$WINE_RUNTIME/bin/wine}"
  export PATH="$WINE_RUNTIME/bin:$PATH"
fi

if [ -d "$METALSHARP_DXMT_RUNTIME/x86_64-windows" ]; then
  export WINEDLLPATH="$METALSHARP_DXMT_RUNTIME/x86_64-windows${WINEDLLPATH:+:$WINEDLLPATH}"
fi

if [ -d "$METALSHARP_DXMT_RUNTIME/x86_64-unix" ]; then
  export WINEDLLPATH="$METALSHARP_DXMT_RUNTIME/x86_64-unix${WINEDLLPATH:+:$WINEDLLPATH}"
fi

cat <<EOF
METALSHARP_D3D12_SDK_ROOT=$METALSHARP_D3D12_SDK_ROOT
METALSHARP_DXMT_RUNTIME=$METALSHARP_DXMT_RUNTIME
WINEPREFIX=$WINEPREFIX
WINE=${WINE:-wine}

Run probes with:
  "\$METALSHARP_D3D12_SDK_ROOT/scripts/run-probes.sh" \\
    --wine "\${WINE:-wine}" \\
    --prefix "\$WINEPREFIX" \\
    --dxmt-runtime "\$METALSHARP_DXMT_RUNTIME"
EOF
